#!/usr/bin/env python3
"""
Adds monuments 25-60 for Asia and writes src/data/monuments/asianMonuments.ts
"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_asia_monuments_60 import all_asia, item
import json

asia_part2 = [
  # 25. Prambanan Temple, Indonesia
  item("prambanan", "Prambanan Temple Compounds", "ꦕꦤ꧀ꦝꦶꦥꦿꦩ꧀ꦧꦤꦤ꧀ (Candi Prambanan / Roro Jonggrang)", "Sacred Temple / Cathedral", "Sleman, Yogyakarta", "Indonesia",
    "Sanjaya Dynasty, Mataram Kingdom (c. 850 CE)", "c. 850 CE", 850, "Rakai Pikatan & Dyah Balitung",
    "Classical Hindu Javanese Architecture (Tall pointed spires)", "Shiva temple height: 47 m (154 ft); Width: 34 m; Complex contains 240 original temples",
    "Volcanic andesite stone masonry, relief carvings",
    "Prambanan is the largest Hindu temple site in Indonesia and the second-largest in Southeast Asia. Built around 850 CE by Rakai Pikatan of the Mataram Kingdom, likely as a Hindu royal answer to the nearby Buddhist monument of Borobudur. Dedicated to the Trimurti: Brahma (the Creator), Vishnu (the Preserver), and Shiva (the Destroyer). Abandoned following volcanic eruptions from Mount Merapi and a devastating earthquake in the 16th century, it was restored starting in the 1930s.",
    "Characterized by its towering, pointed Dravidian-influenced spires. The central Shiva temple soars 47 meters and houses a 3-meter statue of Shiva Mahadeva alongside the legendary statue of Durga Mahisasuramardini, locally known as Rara Jonggrang (the 'Slender Maiden'). The inner balustrades are adorned with bas-reliefs illustrating the complete narrative of the Ramayana and Bhagavata Purana.",
    "Declared a UNESCO World Heritage Site in 1991. Stages the world-renowned Ramayana Ballet on an open-air stage against the illuminated temple backdrop.",
    "https://images.unsplash.com/photo-1596402184320-417e7178b2cd?auto=format&fit=crop&q=80&w=1200",
    ["Prambanan", "Indonesia", "Java", "Hindu", "Trimurti", "UNESCO", "Temple"],
    ["The largest Hindu temple complex in Indonesia, originally comprising 240 temples", "The central temple dedicated to Shiva soars 47 meters (154 feet) into the sky", "Balustrades feature continuous carved stone reliefs of the Ramayana epic", "Restored after being abandoned for centuries following Mount Merapi volcanic eruptions"],
    "Inscribed 1991 (Criteria i, iv)"),

  # 26. Red Fort, Delhi, India
  item("red-fort-delhi", "Red Fort (Lal Qila)", "लाल क़िला (Lāl Qil\'a) / قلعہ معلی", "Palace & Fortress", "Old Delhi", "India",
    "Mughal Empire (1638–1648 CE)", "1638–1648 CE", 1648, "Ustad Ahmad Lahori, commissioned by Emperor Shah Jahan",
    "Mughal Imperial Palace Architecture", "Fort perimeter: 2.41 km; Wall height: 18–33 m; Area: 254 acres",
    "Red sandstone ramparts, Makrana white marble pavilions, floral pietra dura inlay",
    "The Red Fort served as the main residence of the Mughal Emperors for nearly 200 years. Emperor Shah Jahan commissioned the fort in 1638 when he decided to shift the imperial capital from Agra to his newly planned city of Shahjahanabad (Delhi). Construction took nearly ten years under architect Ustad Ahmad Lahori. It housed the imperial court, the royal harem, and the legendary jewel-encrusted Peacock Throne until Persian invader Nader Shah plundered Delhi in 1739.",
    "Named for its massive enclosing walls of red sandstone. Inside lie exquisite white marble pavilions including the Diwan-i-Aam (Hall of Public Audience) and Diwan-i-Khas (Hall of Private Audience), inscribed with the famous Persian couplet: 'If there be a paradise on earth, it is this, it is this, it is this!' Water from the Yamuna River flowed through the pavilions in artificial channels known as the Nahr-i-Bihisht ('Stream of Paradise').",
    "Designated a UNESCO World Heritage Site in 2007. Every year on August 15, India's Prime Minister hoists the national tricolor from the ramparts on Independence Day.",
    "https://images.unsplash.com/photo-1585135497273-1a86b09fe70e?auto=format&fit=crop&q=80&w=1200",
    ["Red Fort", "Delhi", "India", "Mughal", "Shah Jahan", "UNESCO", "Lal Qila"],
    ["Constructed by Emperor Shah Jahan when shifting the Mughal capital from Agra to Delhi in 1638", "The Diwan-i-Khas bore the legendary inscription: 'If there is a paradise on earth, it is this'", "Original site of the diamond-encrusted Peacock Throne looted by Nader Shah in 1739", "The Indian Prime Minister hoists the national flag from its ramparts every Independence Day"],
    "Inscribed 2007 (Criteria ii, iii, vi)"),

  # 27. Qutb Minar, Delhi, India
  item("qutb-minar", "Qutb Minar & Complex", "क़ुतुब मीनार (Qutb Minār) / قطب منار", "Monument & Tower", "Mehrauli, New Delhi", "India",
    "Delhi Sultanate (1192–1368 CE)", "1199–1368 CE", 1199, "Qutb ud-Din Aibak, Shams ud-Din Iltutmish, Firuz Shah Tughlaq",
    "Indo-Islamic Afghan Victory Tower Architecture", "Height: 72.5 m (238 ft); Base diameter: 14.3 m; Top diameter: 2.7 m; 379 steps",
    "Fluted red sandstone, white marble upper storeys, carved Quranic calligraphy and geometric arabesques",
    "The Qutb Minar is a towering minaret and victory tower that forms part of the Qutb complex in Delhi. Founded by Qutb ud-Din Aibak, the first Sultan of Delhi, in 1199 to commemorate his victory over the Rajput Chauhan dynasty and serve as a minaret for the Quwwat-ul-Islam mosque. His successor Iltutmish added three more storeys, and Firuz Shah Tughlaq repaired damage from a 1368 lightning strike by adding the top two storeys in white marble.",
    "It is the tallest brick minaret in the world. The tower tapers from 14.3 meters at the base to 2.7 meters at the peak across five distinct storeys, each marked by a projecting balcony supported by delicate stone brackets. The complex also contains the famous rust-resistant 4th-century Iron Pillar of Chandragupta II, which has withstood tropical weathering for 1,600 years without corroding due to a high phosphorus slag layer.",
    "Inscribed as a UNESCO World Heritage Site in 1993. A monumental milestone in the architectural transition to Indo-Islamic design in South Asia.",
    "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&q=80&w=1200",
    ["Qutb Minar", "Delhi", "India", "Delhi Sultanate", "UNESCO", "Minaret", "Architecture"],
    ["The tallest brick minaret in the world at 72.5 meters (238 feet) tall", "Complex houses an ancient 1,600-year-old iron pillar that has mysteriously never rusted", "Features 379 spiral stone steps ascending through five distinct fluted storeys", "Built using red sandstone carved with intricate Arabic calligraphy and geometric patterns"],
    "Inscribed 1993 (Criterion iv)"),

  # 28. Khajuraho Temples, India
  item("khajuraho-temples", "Khajuraho Group of Monuments", "खजुराहो स्मारक समूह (Khajuraho Group of Monuments)", "Sacred Temple / Cathedral", "Chhatarpur District, Madhya Pradesh", "India",
    "Chandela Dynasty (950–1050 CE)", "950–1050 CE", 1000, "Kings of the Chandela Rajput Dynasty",
    "Nagara-style North Indian Hindu & Jain Temple Architecture", "Kandariya Mahadeva height: 31 m (101 ft); Original 85 temples, 25 survive today",
    "Buff and pink sandstone fitted with mortise-and-tenon joints without mortar, granite foundations",
    "The Khajuraho Group of Monuments is a complex of Hindu and Jain temples built by the Chandela dynasty between 950 and 1050 CE. Located in central India, the temples celebrate the cosmic harmony between the spiritual and physical realms. Sacked by the Delhi Sultanate in the 13th century, the temples were swallowed by dense teak forests and remained hidden until British officer T.S. Burt was led to them by local guides in 1838.",
    "The temples are renowned for their breathtaking Nagara-style soaring spires (shikharas) simulating the sacred peaks of Mount Kailash. The exterior and interior walls feature over 800 exquisitely carved stone sculptures depicting gods, goddesses, celestial dancers (apsaras), warriors, musicians, and famous erotic scenes illustrating the Kama Sutra, representing the sanctification of earthly life and human passion as an integral step toward spiritual liberation.",
    "Declared a UNESCO World Heritage Site in 1986. Celebrated as one of the apex achievements of Indian medieval sculptural art.",
    "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=1200",
    ["Khajuraho", "India", "Madhya Pradesh", "UNESCO", "Chandela", "Hindu", "Sculpture"],
    ["Built by the Chandela Rajput dynasty between 950 and 1050 CE", "Temples celebrate both Hindu and Jain religious traditions with 25 surviving structures", "World-famous for over 800 intricate stone carvings depicting everyday life, gods, and erotic art", "Preserved for centuries hidden inside dense teak forests before rediscovery in 1838"],
    "Inscribed 1986 (Criteria i, iii)"),

  # 29. Ajanta Caves, India
  item("ajanta-caves", "Ajanta Rock-Cut Caves", "अजिंठा लेणी (Ajanta Caves)", "Ancient Wonder", "Aurangabad District, Maharashtra", "India",
    "Satavahana & Vakataka Dynasties (2nd Century BCE – 5th Century CE)", "c. 200 BCE – 480 CE", 200, "Buddhist monks under royal patronage of Emperor Harishena",
    "Ancient Indian Buddhist Rock-Cut Cave & Mural Architecture", "30 rock-cut caves carved into a 75-meter curved horseshoe-shaped basalt gorge",
    "Deccan Traps solid volcanic basalt rock, tempera mud plaster, mineral pigments (lapis lazuli, malachite, cinnabar)",
    "The Ajanta Caves are approximately 30 rock-cut Buddhist cave monuments dating from the 2nd century BCE to about 480 CE. Carved into the sheer volcanic cliffs of the Waghora River horseshoe gorge in Maharashtra. The caves served as residential viharas (monasteries) and chaitya-grihas (prayer sanctuaries) for Buddhist monks during the monsoon seasons. Abandoned around 480 CE when Emperor Harishena died and the court shifted, the gorge was swallowed by jungle until British officer John Smith stumbled upon Cave 10 while hunting tigers in April 1819.",
    "Ajanta contains the finest surviving masterpieces of ancient Indian classical painting. The cave walls and ceilings are covered in luminous Buddhist frescoes depicting the Jataka tales (previous lives of the Buddha) and courtly life with expressive emotional realism, dynamic perspective, and rich shading. The painting of Bodhisattva Padmapani holding a blue lotus in Cave 1 is regarded as one of the greatest treasures of world art.",
    "Inscribed as a UNESCO World Heritage Site in 1983. Considered the fountainhead from which Buddhist visual art spread across Central Asia, China, and Japan.",
    "https://images.unsplash.com/photo-1590559899731-a3f30bc42588?auto=format&fit=crop&q=80&w=1200",
    ["Ajanta", "India", "Maharashtra", "Buddhist", "UNESCO", "Rock-Cut", "Ancient Caves"],
    ["Comprises 30 rock-cut cave temples chiseled into a sheer 75-meter volcanic cliff face", "Contains the finest surviving ancient classical Buddhist mural paintings on Earth", "Rediscovered accidentally by British officer John Smith while hunting a tiger in 1819", "Includes the famous Bodhisattva Padmapani fresco holding a sacred blue lotus flower"],
    "Inscribed 1983 (Criteria i, ii, iii, vi)"),

  # 30. Ellora Caves & Kailasa Temple, India
  item("ellora-kailasa", "Kailasa Temple (Cave 16) & Ellora", "कैलास मंदिर, एलोरा (Kailasa Rock Temple)", "Ancient Wonder", "Verul, Chhatrapati Sambhajinagar, Maharashtra", "India",
    "Rashtrakuta Dynasty (c. 756–773 CE)", "c. 756–773 CE", 760, "King Krishna I (Rashtrakuta dynasty)",
    "Dravidian Monolithic Rock-Cut Architecture", "Temple length: 45 m; Width: 30 m; Height: 32 m (105 ft); Excavated trench: 85 × 46 m",
    "Single living basalt volcanic cliff outcrop, carved top-down without scaffolding",
    "The Kailasa Temple (Cave 16 at Ellora) is the largest monolithic rock-cut structure in the world. Commissioned by King Krishna I of the Rashtrakuta dynasty in the 8th century CE to represent Mount Kailash, the sacred Himalayan abode of Shiva. What makes Kailasa an unprecedented engineering miracle is that the entire temple—including multi-story sanctuaries, grand courtyards, life-sized carved elephants, monumental victory pillars, and intricate stone friezes—was carved top-to-bottom out of a single solid basalt cliff face without adding a single block of stone.",
    "Master masons removed an estimated 200,000 to 400,000 tonnes of volcanic rock over several decades, working from the mountain peak downward with only chisels and hammers. No scaffolding was needed as the rock itself provided the footing. The temple is covered with dynamic bas-reliefs, including the famous panel of Ravana attempting to shake Mount Kailash while Shiva calms the mountain with the touch of his toe. Mughal Emperor Aurangzeb reportedly assigned 1,000 soldiers to demolish the temple in 1682, but after three years of labor they could only cause minor superficial damage.",
    "Designated a UNESCO World Heritage Site in 1983. Universally recognized as one of the absolute supreme engineering feats in human history.",
    "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&q=80&w=1200",
    ["Kailasa Temple", "Ellora", "India", "Rashtrakuta", "UNESCO", "Monolithic", "Ancient Wonder"],
    ["The largest single monolithic rock excavation in the world, carved from the top downward", "Over 200,000 tonnes of solid volcanic basalt were excavated using hand chisels alone", "Entire multi-story temple, courtyard, and life-size elephants are carved from one mountain cliff", "Commissioned by King Krishna I of the Rashtrakuta dynasty in the 8th century CE"],
    "Inscribed 1983 (Criteria i, iii, vi)"),

  # 31. Brihadisvara Temple, Thanjavur, India
  item("brihadisvara-temple", "Brihadisvara Temple (Peruvudaiyar Kovil)", "பெருவுடையார் கோயில் (Peruvudaiyar Kovil / Big Temple)", "Sacred Temple / Cathedral", "Thanjavur, Tamil Nadu", "India",
    "Chola Empire Golden Age (1003–1010 CE)", "1003–1010 CE", 1010, "Emperor Raja Raja Chola I (Architect: Kunjara Mallan Raja Raja Perunthachan)",
    "Classical Chola Dravidian Granite Temple Architecture", "Vimana height: 66 m (216 ft); 16 stories; Base: 29 × 29 m; Granite capstone weight: 80 metric tonnes",
    "130,000 tonnes of dressed charnockite granite blocks interlocking without mortar",
    "The Brihadisvara Temple, known locally as the 'Big Temple', is a Hindu temple dedicated to Shiva built by Emperor Raja Raja Chola I between 1003 and 1010 CE. It was built to celebrate the Chola Empire's naval supremacy and political dominance across the Indian Ocean from South India to Sri Lanka and the Srivijaya Empire in Southeast Asia. Completely built of granite in a region with no natural granite outcrops within a 60-kilometer radius.",
    "The central vimana tower soars 66 meters (216 feet) into the sky, making it one of the tallest temple towers in antiquity. The summit is crowned by a monolithic octagonal granite dome (Kumbam) carved from a single piece of stone weighing approximately 80 tonnes. Chola engineers constructed a gentle 6-kilometer-long inclined ramp made of earth and timber to roll the 80-tonne capstone to the summit using elephants and rollers. The sanctum encloses one of the largest monolithic Shiva Lingams in India, carved from black granite standing 3.7 meters high.",
    "Inscribed as a UNESCO World Heritage Site in 1987 as the Great Living Chola Temples. An undisputed engineering pinnacle of South Indian classical architecture.",
    "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&q=80&w=1200",
    ["Brihadisvara", "Thanjavur", "India", "Chola", "UNESCO", "Dravidian", "Granite Temple"],
    ["Built entirely of 130,000 tonnes of granite transported from over 60 km away without nearby hills", "The central tower soars 66 meters and was the tallest structure in South Asia when completed in 1010 CE", "The 80-tonne granite summit dome was hauled to the top along a 6-kilometer-long inclined ramp", "Contains one of the largest monolithic stone Shiva lingams in India at 3.7 meters tall"],
    "Inscribed 1987 (Criteria ii, iii)"),

  # 32. Konark Sun Temple, India
  item("konark-sun-temple", "Konark Sun Temple (Black Pagoda)", "कोणार्क सूर्य मंदिर (Konark Surya Mandir)", "Sacred Temple / Cathedral", "Konark, Puri District, Odisha", "India",
    "Eastern Ganga Dynasty (c. 1250 CE)", "c. 1250 CE", 1250, "King Narasimhadeva I (Master architect: Bisu Maharana)",
    "Kalinga Architecture (Deula style)", "Original sanctuary height: 68 m (225 ft); Jagamohana hall height: 39 m; 24 colossal stone wheels",
    "Chlorite stone, khondalite stone, iron tie-beams and magnetic ballast",
    "The Sun Temple of Konark was built around 1250 CE by King Narasimhadeva I of the Eastern Ganga Dynasty on the shores of the Bay of Bengal. Conceived as a colossal celestial chariot of the Hindu Sun God Surya, drawn by seven galloping stone horses representing the seven days of the week and the seven colors of the light spectrum. European sailors in the 17th century used its dark silhouette for navigation, calling it the 'Black Pagoda' in contrast to the whitewashed Jagannath Temple in Puri.",
    "The chariot is mounted on 24 colossal intricately carved stone wheels (nearly 3 meters in diameter) that function as accurate sundials: the shadows cast by the spokes and central hub tell the precise time of day to within a few minutes. Master builders placed heavy iron beams between stone courses and, according to maritime legends, a massive lodestone (magnet) at the apex that allowed the deity idol to float in midair and disrupted the compasses of passing European merchant ships.",
    "Designated a UNESCO World Heritage Site in 1984. One of the greatest monuments of Indian architectural imagination.",
    "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=1200",
    ["Konark", "Sun Temple", "India", "Odisha", "UNESCO", "Surya", "Black Pagoda"],
    ["Designed as a colossal stone chariot of the Sun God Surya with 24 wheels and 7 galloping horses", "The 3-meter stone wheels function as precision sundials indicating time by sun shadow", "Known by 17th-century European sailors as the 'Black Pagoda' due to its dark silhouette", "Legend states a massive magnetic lodestone at the peak once held the central sun idol suspended in midair"],
    "Inscribed 1984 (Criteria i, iii, vi)"),

  # 33. Golden Temple (Harmandir Sahib), Amritsar, India
  item("golden-temple-amritsar", "Golden Temple (Sri Harmandir Sahib)", "ਹਰਿਮੰਦਰ ਸਾਹਿਬ (Sri Harmandir Sahib - Abode of God) / ਦਰਬਾਰ ਸਾਹਿਬ", "Sacred Temple / Cathedral", "Amritsar, Punjab", "India",
    "Sikh Empire & Guru Period (1581–1604 CE; gold cladding 1830 CE)", "1581–1604 CE", 1604, "Guru Arjan Dev (5th Sikh Guru) & Maharaja Ranjit Singh",
    "Sikh Architecture (Fusion of Islamic Mughal and Hindu Rajput styles)", "Sanctuary: 12.25 × 12.25 m; Amrit Sarovar tank: 150 × 150 m; Gold leaf weight: 500 kg",
    "White marble lower walls with floral pietra dura inlays, copper plates clad in pure 24-karat gold leaf",
    "Sri Harmandir Sahib, known worldwide as the Golden Temple, is the preeminent spiritual and cultural sanctuary of Sikhism. Conceived by Guru Amar Das, the fourth Guru, who excavated the holy pool (Amrit Sarovar - 'Pool of Nectar'). The temple foundation was laid in December 1588 when Guru Arjan invited the revered Sufi Muslim saint Hazrat Mian Mir of Lahore to lay the cornerstone, symbolizing universal spiritual brotherhood. Guru Arjan compiled the Adi Granth (the Sikh holy scripture) and installed it here in 1604. In 1830, Maharaja Ranjit Singh, founder of the Sikh Empire, sheathed the upper storeys in 500 kilograms of pure gold leaf.",
    "Unlike traditional Hindu temples built on elevated platforms, the Golden Temple is built at a level lower than the surrounding city streets, requiring visitors to walk downward, symbolizing spiritual humility. It features four entrance doors on all four cardinal directions, welcoming all humans regardless of caste, creed, religion, or nationality. It operates the world's largest community kitchen (Guru ka Langar), serving free, hot, nutritious vegetarian meals to over 100,000 people every single day.",
    "The spiritual heart of over 30 million Sikhs worldwide. Celebrated as an international beacon of human equality, selfless service (Seva), and architectural splendor.",
    "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&q=80&w=1200",
    ["Golden Temple", "Amritsar", "India", "Sikh", "Harmandir Sahib", "Punjab", "Gold"],
    ["Upper storeys are clad in over 500 kilograms of pure 24-karat gold leaf", "Operates the world's largest free community kitchen (Langar), feeding 100,000 people daily", "The foundation stone was laid in 1588 by Muslim Sufi saint Hazrat Mian Mir", "Has four entrances open in all directions symbolizing universal welcome to all humanity"],
    "Global Spiritual Beacon"),

  # 34. Hawa Mahal, Jaipur, India
  item("hawa-mahal", "Hawa Mahal (Palace of Winds)", "हवा महल (Hawa Mahal - Palace of Winds)", "Palace & Fortress", "Jaipur, Rajasthan", "India",
    "Kachwaha Rajput Dynasty (1799 CE)", "1799 CE", 1799, "Lal Chand Ustad, commissioned by Maharaja Sawai Pratap Singh",
    "Rajput Architecture with Mughal Influences", "Height: 15 m (50 ft); 5 stories; Width: 15 m; 953 jharokha latticed windows",
    "Red and pink sandstone, quicklime plaster (chunam)",
    "Hawa Mahal, or the 'Palace of the Winds', is a landmark palace in the heart of the Pink City of Jaipur. Built in 1799 by Maharaja Sawai Pratap Singh, a grandson of Maharaja Sawai Jai Singh (the founder of Jaipur). An ardent devotee of Lord Krishna, the Maharaja commissioned Lal Chand Ustad to design the facade in the shape of Krishna's sacred feather crown (Mukut).",
    "The five-story facade resembles an intricate honeycomb of a beehive, featuring 953 exquisitely carved pink sandstone casements (jharokhas) with fine latticework screens. These allowed the royal women of the purdah system to observe vibrant street festivals, royal processions, and daily bazaars below without being seen by the public. The honeycomb design channeled breezes using the Venturi cooling effect, keeping interior chambers pleasantly cool even during scorching desert summers.",
    "A protected national monument under the Archaeological Survey of India. One of the most photographed and beloved icons of Rajasthan.",
    "https://images.unsplash.com/photo-1599839575945-a9e5af0c3fa5?auto=format&fit=crop&q=80&w=1200",
    ["Hawa Mahal", "Jaipur", "India", "Rajasthan", "Palace of Winds", "Rajput", "Pink City"],
    ["Features 953 delicately carved latticework casements (jharokhas) across five storeys", "Built in 1799 in the distinctive shape of Lord Krishna's sacred crowned headdress", "The natural air currents through the facade produce a Venturi cooling effect like air conditioning", "Has no stairs to the upper floors—rooms are accessed via gentle sloping ramps"],
    "State Architectural Monument"),

  # 35. Amber Fort (Amer Fort), Jaipur, India
  item("amber-fort", "Amber Fort (Amer Palace)", "आमेर क़िला (Amer Fort)", "Palace & Fortress", "Amer, Jaipur, Rajasthan", "India",
    "Kachwaha Rajput Clan (1592–1727 CE)", "1592 CE", 1592, "Raja Man Singh I, expanded by Mirza Raja Jai Singh",
    "Rajput-Mughal Fusion Palace Fortress Architecture", "Fort perimeter: 4 km; Elevation: 400 m; Courtyards: 4 major courtyards; Area: 4 km²",
    "Yellow and pink sandstone, white marble, Belgian mirror inlays, brass doors",
    "Amber Fort is an imposing fortress and palace perched high on the rugged Cheel ka Teela (Hill of Eagles) overlooking Maota Lake in Amer, the ancient capital of the Kachwaha Rajputs before Jaipur was founded in 1727. Begun in 1592 by Raja Man Singh I, one of the nine gems (Navaratnas) of Mughal Emperor Akbar's court, and expanded by his successors. Connected to Jaigarh Fort above via fortified underground subterranean escape tunnels.",
    "The palace is celebrated for the Sheesh Mahal (Mirror Palace), whose walls and ceilings are covered in thousands of convex imported Belgian glass mirrors that glitter like a star-filled galaxy when illuminated by a single candle flame. The Ganesh Pol (Ganesh Gate) is an artistic marvel decorated with frescoes and intricate jali screens. Above the fort lies the Jaivana cannon at Jaigarh, the world's largest wheeled cannon of the early modern era.",
    "Inscribed as a UNESCO World Heritage Site in 2013 as part of the Hill Forts of Rajasthan. Welcomes over 1.5 million visitors annually.",
    "https://images.unsplash.com/photo-1590559899731-a3f30bc42588?auto=format&fit=crop&q=80&w=1200",
    ["Amber Fort", "Jaipur", "India", "Rajasthan", "UNESCO", "Sheesh Mahal", "Fortress"],
    ["Home to the famous Sheesh Mahal (Mirror Palace), which glitters like stars with a single candle", "Connected to the hilltop Jaigarh Fort by a series of fortified underground tunnels", "Raja Man Singh I began construction in 1592 overlooking the waters of Maota Lake", "Part of the UNESCO Hill Forts of Rajasthan inscribed in 2013"],
    "Inscribed 2013 (Hill Forts of Rajasthan)"),

  # 36. Fatehpur Sikri, India
  item("fatehpur-sikri", "Fatehpur Sikri (City of Victory)", "फ़तेहपुर सीकरी (Fatehpur Sikri)", "Palace & Fortress", "Agra District, Uttar Pradesh", "India",
    "Mughal Empire (1571–1585 CE)", "1571–1585 CE", 1571, "Emperor Akbar the Great",
    "Mughal Classical Imperial City Architecture", "City wall length: 8 km; Buland Darwaza height: 54 m (177 ft); Complex area: 2.5 km²",
    "Quarried red Sikri sandstone, white marble tomb of Salim Chishti",
    "Fatehpur Sikri was founded in 1571 by Mughal Emperor Akbar to serve as the capital of the Mughal Empire. Akbar built the city near the cave hermitage of Sufi saint Sheikh Salim Chishti, who had correctly prophesied that Akbar would father three sons (the first being Jahangir). Akbar established his experimental hall of religious dialogues, the Ibadat Khana, where scholars of Islam, Hinduism, Jainism, Christianity, and Zoroastrianism debated spiritual truths, leading Akbar to formulate the syncretic philosophy of Din-i Ilahi. The city was abandoned in 1585 due to acute water scarcity.",
    "The city is entered through the Buland Darwaza ('Gate of Magnificence'), a 54-meter red sandstone gate built to commemorate Akbar's conquest of Gujarat—the highest gateway on Earth. Inside lies the Diwan-i-Khas featuring a central carved stone lotus pillar supporting a floating circular platform where Akbar sat. The complex also houses the pure white marble tomb of Salim Chishti, where thousands still tie sacred red threads for answered prayers.",
    "Declared a UNESCO World Heritage Site in 1986. Preserved almost intact as a ghost city of Mughal imperial grandeur.",
    "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&q=80&w=1200",
    ["Fatehpur Sikri", "India", "Mughal", "Akbar", "UNESCO", "Buland Darwaza", "City of Victory"],
    ["Served as Akbar the Great's imperial capital for 14 years before being abandoned due to water shortages", "The Buland Darwaza is the highest monumental gateway in the world at 54 meters tall", "Houses the Diwan-i-Khas with a single central carved lotus pillar where the Emperor held counsel", "The white marble tomb of Sufi saint Salim Chishti is renowned for its delicate jali lattice screens"],
    "Inscribed 1986 (Criteria ii, iii, iv)"),

  # 37. Lotus Temple, New Delhi, India
  item("lotus-temple", "Lotus Temple (Bahá'í House of Worship)", "कमल मंदिर (Lotus Temple) / مشرق‌الاذکار", "Sacred Temple / Cathedral", "Kalkaji, New Delhi", "India",
    "Contemporary Expressionist Architecture (1980–1986 CE)", "1980–1986 CE", 1986, "Fariborz Sahba (Iranian-Canadian Architect)",
    "Expressionist Biomimetic Architecture (Lotus Blossom form)", "Height: 34.27 m (112 ft); Diameter: 70 m; Capacity: 2,500 people; 9 ponds",
    "Greek Pentelikon white marble claddings, white silica concrete, dolomite aggregate, structural steel",
    "The Lotus Temple in New Delhi is a Bahá'í House of Worship dedicated to the oneness of God, the oneness of religion, and the oneness of humanity. Designed by Iranian-Canadian architect Fariborz Sahba, who chose the lotus flower—a universal symbol of purity, beauty, and spiritual rebirth sacred to Hinduism, Buddhism, Jainism, and Islam. Opened to the public in December 1986, it welcomes visitors of all religions to pray and meditate without sermons, rituals, or sectarian images.",
    "The building is composed of 27 freestanding petal-like shells arranged in clusters of three to form nine petals and nine entry doors. The nine entrance doors open onto a central hall capable of seating 2,500 people. The structure is enveloped by nine crystal-clear ponds that resemble floating green leaves around a blooming white lotus, naturally cooling the air through convective airflow before entering the prayer hall.",
    "One of the most visited buildings in the world, having received over 100 million visitors since its opening, surpassing the Eiffel Tower and the Taj Mahal in annual footfall.",
    "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&q=80&w=1200",
    ["Lotus Temple", "Delhi", "India", "Bahai", "Lotus", "Architecture", "Modern Wonder"],
    ["Shaped like a blooming lotus flower with 27 freestanding petals made of Greek white marble", "Open to people of all faiths, with no idols, religious icons, or sectarian sermons permitted", "Surrounded by nine reflective ponds that naturally cool the indoor prayer hall", "Has welcomed over 100 million visitors, making it one of the most visited buildings on Earth"],
    "National Landmark of Faith"),

  # 38. Victoria Memorial, Kolkata, India
  item("victoria-memorial", "Victoria Memorial Hall", "ভিক্টোরিয়া মেমোরিয়াল (Victoria Memorial)", "Monument & Tower", "Maidan, Kolkata, West Bengal", "India",
    "British Raj Indo-Saracenic Era (1906–1921 CE)", "1906–1921 CE", 1921, "William Emerson & Vincent Esch",
    "Indo-Saracenic Revival Architecture (British Imperial, Venetian, Mughal fusion)", "Height: 56 m (184 ft); Dimensions: 103 × 69 m; Park area: 64 acres",
    "Translucent Makrana white marble, structural brick core, bronze angel of victory statue",
    "The Victoria Memorial is a colossal white marble monument in Kolkata, West Bengal, built in memory of Queen Victoria, Empress of India, following her death in January 1901. Conceived by Lord Curzon, then Viceroy of India, as a grand state monument and historical museum. Funded by voluntary donations from Indian princes, merchants, and the British administration. Built between 1906 and 1921 using the same Makrana marble quarries in Rajasthan that provided stone for the Taj Mahal.",
    "Designed by William Emerson, President of the Royal Institute of British Architects, combining classical Renaissance styling with Mughal domes and Rajasthani chattris. The 56-meter central dome is surmounted by a 5-meter-tall black bronze figure of the Angel of Victory, which rotates with the wind like a giant weathercock on ball bearings. The museum holds over 28,000 artifacts, including royal oil paintings, illuminated manuscripts, and personal belongings of Queen Victoria.",
    "The premier heritage landmark of Kolkata, surrounded by 64 acres of landscaped gardens, pools, and fountains.",
    "https://images.unsplash.com/photo-1558431382-27e303142255?auto=format&fit=crop&q=80&w=1200",
    ["Victoria Memorial", "Kolkata", "India", "British Raj", "Marble", "Indo-Saracenic", "Museum"],
    ["Built between 1906 and 1921 using the exact same Makrana white marble as the Taj Mahal", "The 5-meter bronze Angel of Victory at the dome's peak rotates on ball bearings with the wind", "Conceived by Lord Curzon as a grand museum and imperial memorial to Queen Victoria", "Surrounded by 64 acres of lush gardens in Kolkata's central Maidan park"],
    "National Monument of India"),

  # 39. Gateway of India, Mumbai, India
  item("gateway-of-india", "Gateway of India", "गेटवे ऑफ़ इंडिया (Gateway of India)", "Monument & Tower", "Apollo Bunder, Colaba, Mumbai", "India",
    "British Raj Edwardian Era (1911–1924 CE)", "1911–1924 CE", 1924, "George Wittet",
    "Indo-Saracenic Revival Architecture (16th-century Gujarati Muslim motifs)", "Height: 26 m (85 ft); Central arch width: 15 m; Diameter of dome: 15 m",
    "Yellow basalt stone quarried locally from Kharodi, reinforced concrete foundations",
    "The Gateway of India is an arch-monument erected on the waterfront of the Arabian Sea at Apollo Bunder in Mumbai. Built to commemorate the historic landing of King George V and Queen Mary in December 1911—the first British monarch to visit India. Designed by Scottish architect George Wittet and completed in 1924. Historically, the gateway served as the ceremonial entry point for viceroys and governors entering British India.",
    "Designed in the Indo-Saracenic style, incorporating Muslim architectural elements of 16th-century Gujarat with classical Roman triumphal arches. The yellow basalt arch is flanked by four turrets and features intricate pierced jali tracery screens. Symbolically, on February 28, 1948, the final British military battalion (the First Battalion of the Somerset Light Infantry) marched through the Gateway of India to board troopships home, marking the final end of British imperial rule in independent India.",
    "Mumbai's most famous landmark and tourist meeting point, serving as the embarkation dock for ferries to the UNESCO Elephanta Caves.",
    "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&q=80&w=1200",
    ["Gateway of India", "Mumbai", "India", "Colaba", "Indo-Saracenic", "British Raj", "Arch"],
    ["Built to commemorate the 1911 royal visit of King George V and Queen Mary to India", "The last British troops ceremonially marched through the gateway on February 28, 1948, ending the Raj", "Designed by architect George Wittet fusing Gujarati 16th-century Islamic and Roman arch forms", "Constructed using yellow basalt stone quarried from nearby Kharodi"],
    "Heritage Landmark of Mumbai"),

  # 40. Todai-ji, Nara, Japan
  item("todai-ji", "Tōdai-ji (Eastern Great Temple)", "東大寺 (Tōdai-ji - Great Eastern Temple)", "Sacred Temple / Cathedral", "Nara, Nara Prefecture", "Japan",
    "Nara Period (738–752 CE; rebuilt 1709 CE)", "738–752 CE", 752, "Emperor Shōmu (Master sculptors: Kuninaka no Muraji Kimimaro)",
    "Classical Japanese Buddhist Timber Architecture", "Daibutsuden height: 49 m (161 ft); Width: 57 m; Daibutsu statue height: 15 m (49 ft), weight: 500 tonnes",
    "Japanese cedar and cypress wood beams, cast bronze, gilded copper",
    "Tōdai-ji is a monumental Buddhist temple complex in Nara, Japan. Commissioned in 743 CE by Emperor Shōmu, who decreed that a nationwide network of provincial temples be established to protect the nation from disease, crop failure, and political rebellion. The consecration ceremony in 752 was attended by Buddhist dignitaries from India, China, and Persia. The Great Buddha Hall (Daibutsuden) burned down twice during samurai conflicts and was rebuilt in 1709 at two-thirds of its original size.",
    "The Daibutsuden is one of the largest wooden buildings in the world. It houses the Daibutsu (Great Buddha), a colossal 15-meter-tall cast-bronze statue of Vairocana Buddha weighing 500 tonnes, cast from over 400 tonnes of bronze and 130 kilograms of pure gold. One of the massive wooden rear pillars has a hole at its base the same dimensions as the Buddha's nostril; Japanese tradition holds that anyone who squeezes through the opening is guaranteed enlightenment in their next rebirth.",
    "Declared a UNESCO World Heritage Site in 1998 as part of the Historic Monuments of Ancient Nara. Surrounded by Nara Park, where hundreds of sacred free-roaming Sika deer greet pilgrims.",
    "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&q=80&w=1200",
    ["Todai-ji", "Nara", "Japan", "Great Buddha", "Daibutsu", "UNESCO", "Wooden Temple"],
    ["The Great Buddha Hall is one of the largest wooden buildings on the planet", "Houses the 500-ton cast bronze Daibutsu (Great Buddha) sitting 15 meters tall", "Commissioned by Emperor Shōmu in 743 CE to protect Japan from famine and plagues", "Visitors squeeze through a hole in a wooden pillar said to grant enlightenment in the next life"],
    "Inscribed 1998 (Historic Monuments of Ancient Nara)"),

  # 41. Itsukushima Floating Torii, Miyajima, Japan
  item("itsukushima-shrine", "Itsukushima Shrine & Floating Torii", "嚴島神社 (Itsukushima Jinja) / 宮島 (Miyajima)", "Sacred Temple / Cathedral", "Hatsukaichi, Hiroshima Prefecture", "Japan",
    "Heian Period (593 CE foundation; current shrine 1168 CE)", "1168 CE", 1168, "Taira no Kiyomori (Chancellor of the Realm)",
    "Shinden-zukuri Pier-Supported Shinto Shrine Architecture", "Torii height: 16.6 m (54 ft); Weight: 60 tonnes; Shrine boardwalk length: 275 m",
    "Centuries-old natural camphor wood (kusunoki) trunks, vermilion cinnabar paint, cedar",
    "Itsukushima Shrine is a Shinto shrine located on the sacred island of Itsukushima (popularly known as Miyajima) in the Seto Inland Sea. Established in 593 CE and grandly rebuilt in 1168 by the powerful warlord Taira no Kiyomori. Because the entire island was considered sacred, commoners were forbidden from stepping foot on the soil; consequently, the entire shrine was built on wooden stilts over the tidal flats, appearing to float gracefully on the sea at high tide.",
    "The world-famous 'Floating Torii Gate' stands 16.6 meters tall in the bay, constructed of four rot-resistant camphor tree pillars. The gate is not sunk into the seabed; it rests on the ocean floor under its own 60-tonne weight, with wooden roof boxes filled with seven tonnes of river stones for balance. At high tide, the gate appears to float on the blue sea; at low tide, the sea recedes, allowing visitors to walk right up to its monumental timber base.",
    "Designated a UNESCO World Heritage Site in 1996 and recognized as one of the 'Three Views of Japan' (Nihon Sankei).",
    "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&q=80&w=1200",
    ["Itsukushima", "Miyajima", "Japan", "Floating Torii", "Shinto", "UNESCO", "Hiroshima"],
    ["The famous 16.6-meter vermilion torii gate appears to float on the sea during high tide", "Not anchored into the seabed—stands purely under its own 60-tonne weight stabilized with stones", "Rebuilt in 1168 by warlord Taira no Kiyomori on wooden stilts over the tidal flat", "Ranked as one of the Three Views of Japan (Nihon Sankei) since the 17th century"],
    "Inscribed 1996 (Criteria i, ii, iv, vi)"),

  # 42. Kiyomizu-dera, Kyoto, Japan
  item("kiyomizu-dera", "Kiyomizu-dera (Pure Water Temple)", "音羽山清水寺 (Otowasan Kiyomizu-dera)", "Sacred Temple / Cathedral", "Higashiyama-ku, Kyoto", "Japan",
    "Heian Period (778 CE foundation; current main hall 1633 CE)", "1633 CE", 1633, "Tokugawa Iemitsu (3rd Tokugawa Shōgun) & Enchin",
    "Classical Japanese Mountain Temple Architecture (Kake-zukuri cantilever)", "Main hall height: 13 m (43 ft); Stage width: 12 m; Supported by 139 zelkova pillars",
    "Japanese zelkova (keyaki) pillars, cypress bark roof (hiwada-buki), interlocking wood joints without nails",
    "Kiyomizu-dera is an independent Buddhist temple founded in 778 CE by Enchin, an ascetic monk who discovered the sacred Otowa waterfall in the hills east of Kyoto. The temple takes its name ('Clear Water Temple') from the pure mountain spring waters that still tumble below the main hall. Sacked and burned numerous times during feudal wars, the current buildings were reconstructed in 1633 by Shogun Tokugawa Iemitsu without using a single nail.",
    "The Main Hall features an audacious wooden observation stage (Kiyomizu-no-butai) projecting over the hillside, supported by a 13-meter-tall scaffold of 139 massive zelkova pillars interlocking via complex traditional wood joinery. The Japanese expression 'to jump off the stage at Kiyomizu' is the equivalent of the English idiom 'to take the plunge'. Below the hall, visitors drink from the Otowa Waterfall using long-handled cups; three streams are said to grant health, longevity, or success in studies.",
    "Inscribed as a UNESCO World Heritage Site in 1994 as part of the Historic Monuments of Ancient Kyoto. Renowned for its spectacular spring cherry blossoms and autumn maples.",
    "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&q=80&w=1200",
    ["Kiyomizu-dera", "Kyoto", "Japan", "UNESCO", "Pure Water", "Wooden Temple", "Higashiyama"],
    ["Built on the edge of a cliff without a single nail, supported by 139 massive wooden pillars", "The Otowa Waterfall flows into three streams believed to bestow health, longevity, or study success", "The Japanese phrase 'to jump off the stage at Kiyomizu' means to take a bold leap of faith", "Reconstructed in 1633 by Shogun Tokugawa Iemitsu in the peaceful early Edo period"],
    "Inscribed 1994 (Historic Monuments of Ancient Kyoto)"),

  # 43. Osaka Castle, Japan
  item("osaka-castle", "Osaka Castle", "大坂城 (Ōsaka-jō)", "Palace & Fortress", "Chuo-ku, Osaka", "Japan",
    "Azuchi–Momoyama to Modern Period (1583 CE; reconstructed 1931 CE)", "1583–1931 CE", 1583, "Toyotomi Hideyoshi, reconstructed by Tokugawa Hidetada & citizen donations",
    "Japanese Azuchi-Momoyama Hilltop Fortress Architecture", "Keep height: 58 m (190 ft); 8 stories; Castle park area: 105 hectares; Moat width: 70–90 m",
    "Massive granite megaliths (ishigaki), gold leaf tiger and shachihoko reliefs, reinforced concrete core",
    "Osaka Castle was built in 1583 by Toyotomi Hideyoshi, the great unifier of feudal Japan, as the intended capital fortress of a unified realm. Modeled after Oda Nobunaga's Azuchi Castle but on a vastly more monumental scale. Following Hideyoshi's death, Tokugawa Ieyasu besieged the castle in the epic Winter and Summer Sieges of Osaka (1614–1615), destroying the Toyotomi clan and burying their ruins beneath meters of earth to build a new Tokugawa fortress. The castle keep was destroyed by lightning in 1665 and reconstructed in 1931 through public citizen donations.",
    "Surrounded by monumental dry-stone ramparts and wide moats. Inside the Ote-mon Gate lies the Takoishi ('Octopus Stone'), a single giant granite slab weighing an estimated 108 metric tonnes, transported across the sea from Shodoshima. The keep is crowned with golden shachihoko (mythical tiger-carp protectors against fire) and gold-leaf bas-relief tigers.",
    "The definitive historical symbol of Osaka, housing an eight-floor museum of samurai history and weapons surrounded by over 600 cherry trees.",
    "https://images.unsplash.com/photo-1590559899731-a3f30bc42588?auto=format&fit=crop&q=80&w=1200",
    ["Osaka Castle", "Osaka", "Japan", "Samurai", "Toyotomi Hideyoshi", "Fortress", "Tokugawa"],
    ["Constructed in 1583 by Toyotomi Hideyoshi to serve as the supreme capital fortress of Japan", "Features the 'Octopus Stone' (Takoishi), a single granite wall megalith weighing 108 metric tonnes", "The epic Siege of Osaka in 1615 ended the Toyotomi dynasty and solidified Tokugawa rule", "The keep's exterior is adorned with golden carp-tigers (shachihoko) to ward off fires"],
    "Special Historic Site of Japan"),

  # 44. Mount Fuji Fujisan Hongū Sengen Taisha, Japan
  item("fujisan-sengen-taisha", "Fujisan Hongū Sengen Taisha & Mount Fuji", "富士山本宮浅間大社 (Fujisan Hongū Sengen Taisha)", "Sacred Temple / Cathedral", "Fujinomiya, Shizuoka Prefecture", "Japan",
    "Classical Antiquity to Edo Period (27 BCE traditional; current shrine 1604 CE)", "1604 CE", 1604, "Tokugawa Ieyasu & Emperor Sujin",
    "Sengen-zukuri Double-Storey Shinto Architecture", "Mount Fuji height: 3,776.24 m (12,389 ft); Wakutama-ike spring discharge: 3.6 tonnes/second",
    "Japanese cypress, vermilion lacquer, volcanic basalt stones, pure spring water pond",
    "Fujisan Hongū Sengen Taisha is the head shrine of all 1,300 Asama (Sengen) shrines throughout Japan, dedicated to Konohanasakuya-hime, the Shinto goddess of Mount Fuji and cherry blossoms. Built to appease the volcanic spirits of Mount Fuji following devastating eruptions in antiquity. In 1604, Shogun Tokugawa Ieyasu funded the complete reconstruction of the shrine to celebrate his victory at the Battle of Sekigahara, donating the entire upper mountain above the eighth station (3,360 m) to the shrine as private sacred grounds.",
    "Features the rare Sengen-zukuri architectural style, characterized by a two-story inner sanctuary (honden) with a gabled hip roof. The shrine precinct contains Wakutama-ike, a sacred pond fed by melted snow from Mount Fuji filtered through underground volcanic basalt layers for over a century, bubbling forth crystal-clear spring water at a constant 13°C. Historic pilgrims traditionally performed misogi (cold-water purification rituals) here before ascending the mountain.",
    "Inscribed as a UNESCO World Heritage Site in 2013 as part of 'Fujisan, sacred place and source of artistic inspiration'.",
    "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&q=80&w=1200",
    ["Mount Fuji", "Sengen Taisha", "Japan", "Shinto", "UNESCO", "Tokugawa Ieyasu", "Volcano"],
    ["The head shrine of all 1,300 Mount Fuji shrines in Japan, dedicated to the goddess of volcanoes", "Shogun Tokugawa Ieyasu donated the entire peak of Mount Fuji above 3,360 meters to this shrine", "Contains Wakutama Pond, fed by Mount Fuji snowmelt filtered through basalt rock for 100 years", "Historically, pilgrims purified themselves in its spring waters before climbing the sacred volcano"],
    "Inscribed 2013 (Fujisan World Heritage)"),

  # 45. Tokyo Tower, Japan
  item("tokyo-tower", "Tokyo Tower", "日本電波塔 (Nippon Denpatō - Tokyo Tower)", "Monument & Tower", "Shiba-koen, Minato, Tokyo", "Japan",
    "Postwar Showa Era (1957–1958 CE)", "1957–1958 CE", 1958, "Tachū Naitō & Nikken Sekkei",
    "Lattice Steel Communications Tower (Mid-century Modernism)", "Height: 332.9 m (1,092 ft); Weight: 4,000 metric tonnes; Base width: 80 m",
    "Prefabricated structural steel (including scrap metal from US Army Korean War tanks), white and international orange paint",
    "Tokyo Tower is a communications and observation tower in the Shiba-koen district of Minato, Tokyo. Erected in 1958 during Japan's postwar economic miracle to serve as a consolidated television broadcasting antenna for the Kanto region, preventing a forest of private antennas from cluttering Tokyo's rooftops. Designed by structural engineer Tachū Naitō, known as the 'Father of Earthquake-Proof Design' in Japan.",
    "Inspired by the Eiffel Tower in Paris, Tokyo Tower was built 13 meters taller (332.9 m) while weighing only 4,000 tonnes—roughly half the weight of the Eiffel Tower—thanks to advanced high-tensile steel engineering. In a poignant symbol of postwar peace, approximately one-third of the steel used in the upper tower came from 90 decommissioned US military tanks damaged in the Korean War. Painted in white and international orange to comply with aviation safety regulations, requiring 28,000 liters of paint every five years.",
    "A cherished national landmark, featured in countless anime, manga, and films. Has welcomed over 190 million visitors since its inauguration.",
    "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&q=80&w=1200",
    ["Tokyo Tower", "Tokyo", "Japan", "Showa", "Architecture", "Tower", "Eiffel"],
    ["Built in 1958 at 332.9 meters tall, surpassing the Eiffel Tower by 13 meters", "One-third of the steel used was recycled from US Army tanks damaged in the Korean War", "Weighs only 4,000 tonnes, nearly half the weight of the Eiffel Tower due to advanced engineering", "Painted in alternating international orange and white requiring 28,000 liters of paint"],
    "Registered Tangible Cultural Property of Japan"),

  # 46. Tokyo Skytree, Japan
  item("tokyo-skytree", "Tokyo Skytree", "東京スカイツリー (Tōkyō Sukaitsurī)", "Monument & Tower", "Sumida, Tokyo", "Japan",
    "21st Century High-Tech Neo-Futurism (2008–2012 CE)", "2008–2012 CE", 2012, "Nikken Sekkei (Design team led by Tadao Ando and Kiwamu Kiuchi)",
    "Neo-Futurist Lattice Tower Architecture (Fusion of traditional pagoda and modern cybernetics)", "Height: 634 m (2,080 ft); Observatories at 350 m and 450 m; Weight: 41,000 tonnes",
    "High-strength steel pipes, reinforced concrete central column (shinbashira), damping oil dampers",
    "Tokyo Skytree is a broadcasting and observation tower in Sumida, Tokyo. Completed in February 2012, it became the tallest freestanding tower in the world and the second-tallest structure on Earth after the Burj Khalifa. Built because Tokyo's proliferating cluster of high-rise skyscrapers began blocking digital terrestrial television signals from the older Tokyo Tower.",
    "Its height of exactly 634 meters was chosen for its wordplay on 'Musashi' (6=mu, 3=sa, 4=shi), the historic province name of the Tokyo region. The tower's cross-section transitions smoothly from an equilateral triangle at the base to a cylinder at 320 meters, incorporating traditional Japanese architectural curves: 'sori' (concave curves) and 'mukuri' (convex curves). Incorporates ancient anti-seismic pagoda engineering: a massive central concrete cylinder (shinbashira) stands mechanically isolated from the outer steel frame, swinging out-of-phase during earthquakes to cancel out 50% of seismic shaking.",
    "The modern technological beacon of Japan, attracting millions to its two observation decks and digital planetarium.",
    "https://images.unsplash.com/photo-1542051841857-5f90071e7989?auto=format&fit=crop&q=80&w=1200",
    ["Tokyo Skytree", "Tokyo", "Japan", "Skytree", "Tower", "Tallest Tower", "Earthquake Engineering"],
    ["The tallest freestanding communications tower in the world at 634 meters (2,080 feet)", "The height '634' is a pun on 'Musashi', the ancient samurai province of the Tokyo region", "Uses traditional pagoda center-pillar (shinbashira) engineering to dampen earthquake sway by 50%", "Features a spiraling glass skywalk 450 meters above the streets of Tokyo"],
    "Modern Engineering Wonder"),

  # 47. Shanghai Tower, China
  item("shanghai-tower", "Shanghai Tower", "上海中心大厦 (Shànghǎi Zhōngxīn Dàshà)", "Famous Building", "Lujiazui, Pudong, Shanghai", "China",
    "21st Century Sustainable Supertall Skyscraper (2008–2015 CE)", "2008–2015 CE", 2015, "Gensler (Design led by Jun Xia)",
    "Contemporary Sustainable High-Tech Architecture (Twisting Double-Skin Facade)", "Height: 632 m (2,073 ft); 128 floors; Floor area: 380,000 m²; Twist angle: 120 degrees",
    "Reinforced concrete core, steel mega-columns, double-layered glass curtain wall (20,000 glass panels)",
    "The Shanghai Tower is a 128-story, 632-meter-tall megatall skyscraper in Pudong, Shanghai. The tallest building in China and the third-tallest building in the world by height to architectural top. Anchors the Lujiazui financial district alongside the Jin Mao Tower and Shanghai World Financial Center, forming the world's first contiguous cluster of three supertall buildings.",
    "The tower twists approximately 120 degrees as it rises, reducing wind loads on the building by 24% during typhoons, which saved an estimated $58 million in structural steel costs during construction. Constructed as nine cylindrical vertical zones stacked on top of each other, enclosed by a double-glass curtain wall. The space between the inner and outer glass walls creates nine transparent public atrium sky-gardens. Features wind turbines at the apex that generate 350,000 kWh of renewable electricity annually and an elevator that travels at 73.8 km/h (20.5 m/s).",
    "Awarded LEED Platinum certification. A triumphant exemplar of 21st-century green engineering and sustainable urban vertical design.",
    "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&q=80&w=1200",
    ["Shanghai Tower", "Shanghai", "China", "Skyscraper", "Gensler", "Supertall", "Green Building"],
    ["Tallest building in China and third-tallest on Earth at 632 meters (2,073 feet) tall", "The exterior twists 120 degrees as it climbs, reducing typhoon wind vortex loads by 24%", "Features a double-glass facade creating nine indoor public sky-gardens between the walls", "Contains high-speed elevators traveling at 73.8 km/h, reaching the 119th floor in 55 seconds"],
    "World Megatall Skyscraper"),

  # 48. Mogao Caves (Caves of the Thousand Buddhas), Dunhuang, China
  item("mogao-caves", "Mogao Caves (Caves of the Thousand Buddhas)", "莫高窟 (Mògāo Kū - Peerless Caves) / 千佛洞", "Ancient Wonder", "Dunhuang, Gansu Province", "China",
    "Six Dynasties to Yuan Dynasty (366–1368 CE)", "366–1368 CE", 366, "Buddhist monk Le Zun & generations of Silk Road patrons",
    "Ancient Chinese Buddhist Cave Temple & Fresco Art", "492 decorated caves; 45,000 m² of wall paintings; 2,415 painted clay sculptures; Cliff length: 1.6 km",
    "Sandstone conglomerate cliff face, clay and straw plaster, mineral pigments (malachite, cinnabar, lapis lazuli), gold leaf",
    "The Mogao Caves, also known as the Thousand Buddha Grottoes, are a system of 492 sanctuaries carved into the cliffs above the Dachuan River southeast of the oasis town of Dunhuang in Gansu province. Dunhuang sat at the vital geographic crossroads of the northern and southern branches of the ancient Silk Road. According to tradition, in 366 CE, a Buddhist monk named Le Zun had a vision of a thousand Buddhas bathed in golden light on Mount Sanwei and excavated the first cave. For a thousand years, merchants, kings, and pilgrims commissioned caves filled with statues and frescoes to pray for safe journeys across the treacherous Taklamakan Desert.",
    "In 1900, Daoist monk Wang Yuanlu discovered Cave 17 ('The Library Cave'), which had been sealed in the early 11th century. Inside lay over 50,000 ancient manuscripts, silk paintings, and textiles written in Chinese, Tibetan, Sanskrit, Sogdian, and Khotanese—including the world's earliest dated printed book, the Diamond Sutra (868 CE). The caves contain 45,000 square meters of colorful murals showing scenes from Buddhist sutras, commercial caravans, musical instruments, and royal banquets.",
    "Inscribed as a UNESCO World Heritage Site in 1987. Recognized as the world's most comprehensive repository of Silk Road history and Buddhist visual culture.",
    "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?auto=format&fit=crop&q=80&w=1200",
    ["Mogao Caves", "Dunhuang", "China", "Silk Road", "UNESCO", "Buddhism", "Library Cave"],
    ["Contains 492 rock-cut cave temples filled with 45,000 square meters of Silk Road murals", "The sealed 'Library Cave' yielded 50,000 ancient manuscripts, including the 868 CE Diamond Sutra", "Carved over a 1,000-year span by merchants and monks seeking spiritual protection in the desert", "Houses the world's largest collection of Buddhist cliff paintings and painted clay sculptures"],
    "Inscribed 1987 (Criteria i, ii, iii, iv, v, vi)"),

  # 49. Leshan Giant Buddha, China
  item("leshan-giant-buddha", "Leshan Giant Buddha", "乐山大佛 (Lèshān Dàfó)", "Ancient Wonder", "Leshan, Sichuan Province", "China",
    "Tang Dynasty (713–803 CE)", "713–803 CE", 803, "Buddhist monk Hai Tong",
    "Tang Dynasty Monolithic Rock-Cut Cliff Sculpture", "Height: 71 m (233 ft); Shoulder width: 28 m; Head length: 14.7 m; Ear length: 7 m",
    "Cretaceous red sandstone cliff, wood and plaster ears, concealed drainage network",
    "The Leshan Giant Buddha is a colossal 71-meter-tall stone statue carved out of a cliff face of Cretaceous red sandstone at the confluence of the Min, Dadu, and Qingyi rivers in southern Sichuan province. Construction was initiated in 713 CE by the Buddhist monk Hai Tong. Hai Tong observed that the turbulent waters at the river junction frequently wrecked shipping boats and drowned boatmen; he believed that carving a massive statue of Maitreya Buddha would calm the spirits of the river. Legend holds that when local officials tried to extort funding from him, Hai Tong gouged out his own eye to prove his piety.",
    "It is the largest carved stone Buddha in the world and the tallest pre-modern statue on Earth. Hai Tong's engineering plan had a physical effect: the massive quantities of rock rubble chiseled from the cliff were swept into the river bed below, altering water currents and genuinely making the river safer for passing ships! The statue contains an ingenious concealed drainage system composed of hidden drainage gutters behind the ears, shoulders, and chest that channel rainwater away, preventing structural erosion.",
    "Inscribed as a UNESCO World Heritage Site in 1996 in conjunction with Mount Emei. A crowning achievement of Tang Dynasty rock sculpture.",
    "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&q=80&w=1200",
    ["Leshan Buddha", "Sichuan", "China", "Tang Dynasty", "UNESCO", "Giant Buddha", "Rock-Cut"],
    ["The largest and tallest carved stone Buddha in the world at 71 meters (233 feet) tall", "Initiated in 713 CE by monk Hai Tong to calm the deadly river rapids below the cliff", "The rubble carved from the mountain altered the riverbed currents, genuinely reducing boat wrecks", "Features an ingenious hidden drainage system inside the head and arms that prevents stone erosion"],
    "Inscribed 1996 (Criteria iv, vi)"),

  # 50. Longmen Grottoes, China
  item("longmen-grottoes", "Longmen Grottoes (Dragon Gate)", "龙门石窟 (Lóngmén Shíkū)", "Ancient Wonder", "Luoyang, Henan Province", "China",
    "Northern Wei to Tang Dynasty (493–1127 CE)", "493–1127 CE", 493, "Emperor Xiaowen of Northern Wei & Empress Wu Zetian",
    "Classical Chinese Rock-Cut Cave Art & Imperial Relief Sculpture", "2,345 caves; 100,000 statues; 2,800 inscriptions; Cliff span: 1 km",
    "Hard dense Yi River limestone cliff outcrops, mineral pigments",
    "The Longmen Grottoes are located 12 kilometers south of historic Luoyang in Henan province. The grottoes line both banks of the Yi River between Mount Xiang and Mount Longmen (the 'Dragon Gate'). Excavation began in 493 CE when Emperor Xiaowen of the Northern Wei dynasty moved the capital to Luoyang, and reached its zenith under Tang Dynasty Empress Wu Zetian in the late 7th century.",
    "The centerpiece of Longmen is the Fengxian Temple (Ancestor Worshipping Cave), commissioned by Empress Wu Zetian in 672 CE. It is dominated by the colossal 17-meter-tall statue of Vairocana Buddha, carved with serene, graceful feminine facial contours that, according to historical accounts, were modeled after the Empress herself. Surrounding the central Buddha are statues of disciples, Bodhisattvas, heavenly kings (Tianwang), and Vajrapani guardians carrying thunderbolts. The caves contain over 2,800 engraved stone stelae, providing historians with vital inscriptions on ancient medicine, politics, and linguistics.",
    "Inscribed as a UNESCO World Heritage Site in 2000, lauded as 'an outstanding manifestation of human artistic creativity'.",
    "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?auto=format&fit=crop&q=80&w=1200",
    ["Longmen Grottoes", "Luoyang", "China", "Tang Dynasty", "UNESCO", "Wu Zetian", "Cave Temples"],
    ["Contains over 100,000 Buddhist statues carved into limestone cliffs along the Yi River", "The 17-meter Vairocana Buddha was commissioned by China's only female emperor, Wu Zetian", "Features over 2,800 stone inscriptions detailing ancient medicine, culture, and dynasties", "Excavated continuously across four centuries by Northern Wei and Tang dynasty monarchs"],
    "Inscribed 2000 (Criteria i, ii, iii)"),

  # 51. Norbulingka (Jeweled Park), Tibet
  item("norbulingka", "Norbulingka (The Jewel Park)", "ནོར་བུ་གླིང་ཀ (Norbulingka - Treasure Garden)", "Palace & Fortress", "Lhasa, Tibet Autonomous Region", "China",
    "Ganden Phodrang Era (1755–1956 CE)", "1755 CE", 1755, "7th Dalai Lama (Kelzang Gyatso) & 14th Dalai Lama",
    "Tibetan Horticultural & Palace Architecture", "Park area: 36 hectares (89 acres); 374 rooms; 5 palaces",
    "Tibetan granite, cedar timber, gold foil, painted thangka murals",
    "Norbulingka, meaning 'Treasure Park' or 'Jewel Park' in Tibetan, was the traditional summer palace of the Dalai Lamas from the 1780s until 1959. Founded in 1755 by the 7th Dalai Lama, Kelzang Gyatso. Every summer, a grand ceremonial procession known as the 'Serbang' was held to accompany the Dalai Lama from his winter residence at Potala Palace to Norbulingka, where he conducted state affairs and held religious assemblies in the open air.",
    "The park covers 36 hectares and is considered the largest human-made horticultural garden in Tibet, featuring rare Himalayan flowers, willow trees, and tranquil ponds. The New Summer Palace (Takten Migyur Potrang) was completed in 1956 for the 14th Dalai Lama, featuring modern amenities blended with traditional Tibetan thangkas, including a 301-panel continuous mural chronicling the entire history of Tibet from mythical ape ancestors to the 20th century. It was from Norbulingka that the 14th Dalai Lama escaped disguised as a soldier into exile in India in March 1959.",
    "Inscribed as a UNESCO World Heritage Site in 2001 as an extension of the Potala Palace complex.",
    "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&q=80&w=1200",
    ["Norbulingka", "Lhasa", "Tibet", "Dalai Lama", "UNESCO", "Summer Palace", "Himalayas"],
    ["Served as the official summer residence of the Dalai Lamas from 1780 to 1959", "The largest human-engineered garden in Tibet, spanning 36 hectares with rare alpine flora", "Contains the New Summer Palace with a 301-panel mural recording complete Tibetan history", "The 14th Dalai Lama departed from Norbulingka on his historic escape to India in March 1959"],
    "Inscribed 2001 (Potala Palace Historic Ensemble)"),

  # 52. Sheikh Zayed Grand Mosque, Abu Dhabi, UAE
  item("sheikh-zayed-mosque", "Sheikh Zayed Grand Mosque", "جامع الشيخ زايد الكبير (Jāmiʿ ash-Shaykh Zāyid al-Kabīr)", "Sacred Temple / Cathedral", "Abu Dhabi", "United Arab Emirates",
    "Contemporary Islamic Renaissance (1996–2007 CE)", "1996–2007 CE", 2007, "Yousef Abdelke & Halcrow Group (commissioned by Sheikh Zayed bin Sultan Al Nahyan)",
    "Contemporary Neo-Classical Islamic Architecture (Mamluk, Ottoman, Fatimid fusion)", "Length: 420 m; Width: 290 m; 82 domes; 4 minarets height: 107 m; Capacity: 41,000 worshippers",
    "Sivec white marble from North Macedonia, Italian Carrara marble, 24-karat gold-plated brass chandeliers, mother-of-pearl, semi-precious lapis lazuli and amethyst inlays",
    "The Sheikh Zayed Grand Mosque is the largest mosque in the United Arab Emirates and the key site of national worship. Commissioned by Sheikh Zayed bin Sultan Al Nahyan, the founding father and first President of the UAE, whose final resting place is located in the grounds beside the mosque. Designed to unite the cultural diversity of the Islamic world with modern artistic values. Constructed between 1996 and 2007 by more than 3,000 workers and 38 contracting companies from across the world.",
    "The mosque features 82 domes clad in pure white Sivec marble, with the main dome soaring 85 meters. The grand courtyard (Sahan) is paved in 17,000 square meters of floral marble mosaic, making it the largest marble mosaic floor on Earth. The main prayer hall houses the world's largest hand-knotted carpet: hand-crafted by 1,200 Iranian artisans over two years, measuring 5,627 square meters and weighing 35 metric tonnes. Above hangs a 12-tonne Swarovski crystal chandelier plated in 24-karat gold. The exterior pools reflect the columns and feature an innovative lunar lighting system that shifts intensity according to the phases of the moon.",
    "Welcomes millions of visitors and worshippers annually. A world-class symbol of architectural luxury, interfaith openness, and peaceful coexistence.",
    "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&q=80&w=1200",
    ["Sheikh Zayed Mosque", "Abu Dhabi", "UAE", "Islamic", "Marble", "Grand Mosque", "Modern Wonder"],
    ["Clad in brilliant white Sivec marble from North Macedonia across 82 domes and 1,000 columns", "Houses the world's largest hand-knotted wool carpet, covering 5,627 square meters", "Features a 12-tonne Swarovski crystal chandelier plated in pure 24-karat gold", "The unique exterior lighting system shifts color and intensity with the phases of the moon"],
    "National Landmark of the UAE"),

  # 53. Burj Al Arab, Dubai, UAE
  item("burj-al-arab", "Burj Al Arab (Tower of the Arabs)", "برج العرب (Burj al-ʿArab - Tower of the Arabs)", "Famous Building", "Jumeirah Beach, Dubai", "United Arab Emirates",
    "Contemporary Postmodern High-Tech (1994–1999 CE)", "1994–1999 CE", 1999, "Tom Wright (WKK Architects) & Khuan Chew (Interiors)",
    "Neo-Futurist High-Tech (Sail-shaped superstructure)", "Height: 321 m (1,053 ft); 56 floors; Artificial island distance: 280 m offshore; Helipad: 210 m high",
    "Steel truss exoskeleton, Teflon-coated double-curved fiberglass fabric, 24-karat gold leaf interiors (1,790 m²), statuario marble",
    "The Burj Al Arab is an iconic luxury hotel standing on an artificial island 280 meters off Jumeirah Beach in Dubai. Commissioned by Sheikh Mohammed bin Rashid Al Maktoum to serve as an unmistakable global symbol for Dubai, comparable to the Sydney Opera House for Australia or the Eiffel Tower for France. Construction of the artificial island alone took three years of reclaiming land from the sea using a protective layer of concrete honeycombs designed to absorb wave energy without splashing.",
    "Designed in the shape of the billowing spinnaker sail of a traditional Arabian dhow yacht. The hotel features an open central atrium that soars 182 meters high, making it the tallest hotel atrium in the world. The interior is lavishly decorated with 1,790 square meters of 24-karat gold leaf, Italian Statuario marble, and dancing water geysers. Features a cantilevered helipad suspended 210 meters above the sea, made famous worldwide by Roger Federer and Andre Agassi playing tennis atop it in 2005.",
    "Regularly described as the world's only 'Seven-Star Hotel'. An undisputed icon of modern luxury, high-tech civil engineering, and Arabian ambition.",
    "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&q=80&w=1200",
    ["Burj Al Arab", "Dubai", "UAE", "Hotel", "Luxury", "Architecture", "Sail"],
    ["Built on an artificial island 280 meters out to sea, supported by 230 concrete foundation piles", "Shaped like the billowing spinnaker sail of an Arabian dhow yacht, standing 321 meters tall", "The interior is decorated with nearly 1,800 square meters of pure 24-karat gold leaf", "Features a suspended helipad 210 meters in the sky, famously used for a tennis match in 2005"],
    "Global Luxury Icon"),

  # 54. Western Wall (Kotel), Jerusalem
  item("western-wall", "Western Wall (Kotel / Wailing Wall)", "הַכֹּתֶל הַמַּעֲרָבִי (HaKotel HaMa'aravi) / حائط البراق (Buraq Wall)", "Sacred Temple / Cathedral", "Old City of Jerusalem", "Palestine / Jerusalem",
    "Herodian Second Temple Era (c. 19 BCE)", "c. 19 BCE", -19, "King Herod the Great",
    "Ancient Herodian Monolithic Dry-Stone Ashlar Masonry", "Exposed prayer plaza length: 57 m; Total wall length: 488 m; Height above plaza: 19 m (total height 32 m); Largest stone: 570 tonnes",
    "Massive Meleke limestone megalithic ashlar blocks, dry-stone fitted without mortar",
    "The Western Wall, located in the Old City of Jerusalem, is the most sacred place where Jews are permitted to pray. Originally built by King Herod the Great around 19 BCE as part of the massive expansion and retaining wall system for the elevated Second Temple plateau. Following the Roman siege and destruction of Jerusalem and the Second Temple by Titus in 70 CE, this western retaining wall was the sole substantial structure left standing. In Islamic tradition, the wall is also known as the Buraq Wall, where the Prophet Muhammad tethered his winged steed Buraq during the Night Journey.",
    "Built using gigantic limestone ashlar blocks known as 'Herodian stones', characterized by precision chisel margins around the borders. The blocks fit together with microscopic precision without any mortar or cement. Deep inside the Western Wall Tunnels lies the 'Western Stone', one of the heaviest building blocks ever moved by humans in antiquity: measuring 13.6 meters long, 3 meters high, and weighing an astounding 570 metric tonnes. Millions of pilgrims of all backgrounds place folded paper notes containing personal prayers into the cracks between the stones.",
    "Part of the UNESCO World Heritage Old City of Jerusalem (1981). The ultimate emotional touchstone of Jewish memory, yearning, and spiritual heritage.",
    "https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&q=80&w=1200",
    ["Western Wall", "Jerusalem", "Kotel", "Herodian", "Second Temple", "UNESCO", "Sacred Site"],
    ["The most sacred prayer site in Judaism, surviving from Herod's Second Temple retaining wall", "Contains the 'Western Stone', a single colossal megalith weighing 570 metric tonnes", "Millions of visitors annually insert written prayer notes into the crevices of the stones", "Fitted together in antiquity with microscopic precision completely without the use of mortar"],
    "Inscribed 1981 (Old City of Jerusalem)"),

  # 55. Church of the Holy Sepulchre, Jerusalem
  item("holy-sepulchre", "Church of the Holy Sepulchre", "كنيسة القيامة (Church of the Resurrection) / כנסיית הקבר", "Sacred Temple / Cathedral", "Christian Quarter, Old City of Jerusalem", "Palestine / Jerusalem",
    "Constantinian to Crusader Era (326–1149 CE)", "326–1149 CE", 335, "Saint Helena, Emperor Constantine the Great, Crusader architects",
    "Early Christian Roman, Byzantine & Crusader Romanesque Architecture", "Rotunda diameter: 20.4 m; Anastasis dome height: 35 m; Complex area: 5,000 m²",
    "Jerusalem limestone, marble columns, Crusader relief carvings, Byzantine gold mosaics",
    "The Church of the Holy Sepulchre is the holiest site in Christianity. According to traditions dating back to the early 4th century, the church encompasses the two most sacred sites in the New Testament: the hill of Calvary (Golgotha), where Jesus of Nazareth was crucified, and the empty rock-cut tomb (Sepulchre) where he was buried and subsequently resurrected. In 326 CE, Saint Helena, mother of Emperor Constantine the Great, traveled to Jerusalem and identified the sites, leading Constantine to commission the first basilica.",
    "The church is dominated by the grand Rotunda (Anastasis), beneath whose dome stands the Aedicula ('Little House'), a 19th-century marble pavilion enclosing the Holy Sepulchre itself. Inside the entrance lies the Stone of Anointing, where Jesus's body was prepared for burial. Custody of the church is shared among six ancient Christian denominations (Greek Orthodox, Roman Catholic, Armenian Apostolic, Coptic, Syriac, and Ethiopian) governed by the 1852 Ottoman 'Status Quo' decree; to maintain neutrality, the physical iron keys to the front door have been held by the Muslim Nuseibeh and Joudeh families since the 12th century.",
    "Part of the UNESCO World Heritage Old City of Jerusalem (1981). The spiritual epicenter of Christian pilgrimage for nearly seventeen centuries.",
    "https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&q=80&w=1200",
    ["Holy Sepulchre", "Jerusalem", "Constantine", "Crusader", "Christianity", "UNESCO", "Golgotha"],
    ["Encloses Golgotha (Calvary), the site of the Crucifixion, and the empty tomb of Jesus Christ", "The first basilica was commissioned by Emperor Constantine after his mother Helena found the site in 326 CE", "To keep peace between rival Christian orders, the keys have been kept by a Muslim family since 1192", "Features the famous 'Immovable Ladder' on a window ledge, untouched since at least 1757"],
    "Inscribed 1981 (Old City of Jerusalem)"),

  # 56. Great Mosque of Isfahan (Jameh Mosque), Iran
  item("jameh-mosque-isfahan", "Jameh Mosque of Isfahan", "مسجد جامع اصفهان (Masjid-e Jāmeh-e Eṣfahān - Friday Mosque)", "Sacred Temple / Cathedral", "Isfahan", "Iran",
    "Abbasid to Safavid Dynasties (771–1700 CE)", "771–1700 CE", 1088, "Nizam al-Mulk & Taj al-Mulk (Seljuk viziers), Safavid shahs",
    "Four-Iwan Islamic Persian Architecture", "Area: 20,000 m² (largest mosque complex in Iran); South dome height: 30 m; North dome height: 19.5 m",
    "Kiln-fired unglazed baked brick, turquoise glazed faience mosaic tiles, carved stucco inscriptions",
    "The Jameh Mosque of Isfahan is the grand, congregational Friday mosque of Isfahan, Iran. It is a stunning living museum of over a millennium of Islamic architectural evolution, showcasing uninterrupted building campaigns from the Umayyad and Abbasid caliphates through the Seljuk, Ilkhanid, Timurid, and Safavid dynasties. Founded in 771 CE, it became the architectural prototype for the classic 'four-iwan' mosque plan that subsequently spread across the entire Islamic world from Central Asia to India.",
    "Features four vaulted open monumental gateways (iwans) facing each other across a vast central courtyard. The northern Taj al-Mulk dome, built in 1088 CE, is widely celebrated by mathematicians and architectural historians as one of the most structurally perfect brick domes ever built: constructed without mortar using mathematical pentagonal proportions and ribbed squinches that have stood without a single crack for over 900 years despite repeated regional earthquakes. The mosque features the famous 1310 stucco prayer niche (Mihrab of Oljaytu), an astonishingly deep, three-dimensional filigree of carved Quranic arabesques.",
    "Designated a UNESCO World Heritage Site in 2012. Revered as the definitive architectural encyclopedia of Persian Islamic design.",
    "https://images.unsplash.com/photo-1568084680786-a84f91d1153c?auto=format&fit=crop&q=80&w=1200",
    ["Jameh Mosque", "Isfahan", "Iran", "Seljuk", "Safavid", "UNESCO", "Persian Architecture"],
    ["The architectural prototype for the four-iwan mosque design across the entire Islamic world", "Features the 1088 Taj al-Mulk brick dome, surviving 900 years of earthquakes without a single crack", "Displays an unbroken 1,000-year timeline of Persian Islamic architectural evolution", "Contains the famous 1310 Mihrab of Oljaytu, a masterpiece of three-dimensional stucco carving"],
    "Inscribed 2012 (Criteria ii)"),

  # 57. Naqsh-e Jahan Square & Shah Mosque, Isfahan, Iran
  item("naqsh-e-jahan", "Naqsh-e Jahan Square & Shah Mosque", "میدان نقش جهان (Image of the World Square) / مسجد شاه", "Sacred Temple / Cathedral", "Isfahan", "Iran",
    "Safavid Empire Golden Age (1598–1629 CE)", "1598–1629 CE", 1611, "Ali Akbar Isfahani, commissioned by Shah Abbas I the Great",
    "Classical Safavid Persian Islamic Architecture", "Square dimensions: 560 × 160 m (89,600 m²); Dome height: 52 m; Minarets: 42 m; Area: 22 acres",
    "Seven-colored glazed haft-rangi ceramic tiles, marble base courses, turquoise tiles, acoustic brick vaults",
    "Naqsh-e Jahan Square, meaning 'Image of the World', is an immense public square in central Isfahan, built between 1598 and 1629 by Safavid ruler Shah Abbas I the Great when he relocated the Persian imperial capital to Isfahan. The square was designed as the grand civic stage of the Safavid Empire, uniting the four pillars of Persian power: religion (the royal Shah Mosque), aristocracy and court (Ali Qapu Palace), spirituality and science (Sheikh Lotfollah Mosque), and commerce (the Grand Qeysarie Bazaar).",
    "The centerpiece Shah Mosque (now Abbasi Mosque) is a triumph of Islamic tilework, its soaring 52-meter double-shelled turquoise dome and minarets completely sheathed in seven-colored glazed mosaic tiles (haft-rangi) depicting intricate floral arabesques and calligraphy. Because the square was aligned north-south while Mecca lies southwest, architect Ali Akbar Isfahani ingeniously rotated the mosque 45 degrees through a curved entrance portal without disrupting the symmetrical unity of the square. Beneath the central dome, a specific stone on the floor produces twelve distinct acoustic echoes when stamped upon.",
    "Inscribed as a UNESCO World Heritage Site in 1979. One of the largest historic city squares in the world, celebrated in Persian literature with the proverb: 'Isfahan is half the world' (Esfahān nesf-e jahān ast).",
    "https://images.unsplash.com/photo-1568084680786-a84f91d1153c?auto=format&fit=crop&q=80&w=1200",
    ["Naqsh-e Jahan", "Isfahan", "Iran", "Safavid", "Shah Abbas", "UNESCO", "Persian Square"],
    ["One of the largest historic public city squares in the world, spanning over 22 acres", "Ingeniously angled 45 degrees via an invisible curved portal to face Mecca while aligning with the square", "Beneath the central dome of the Shah Mosque, stamping your foot produces 12 distinct echoes", "Shah Abbas played royal horseback polo matches across the square, whose marble goalposts still stand"],
    "Inscribed 1979 (Criteria i, v, vi)"),

  # 58. Golestan Palace, Tehran, Iran
  item("golestan-palace", "Golestan Palace (Rose Garden Palace)", "کاخ گلستان (Kākh-e Golestān - Palace of Flowers)", "Palace & Fortress", "Tehran", "Iran",
    "Safavid to Qajar Dynasty (1524–1896 CE; current halls 1865 CE)", "1865 CE", 1865, "Haji Abol-hasan Mimar Navai, commissioned by Naser al-Din Shah Qajar",
    "Qajar Architecture (Persian motifs fused with 19th-century European neoclassical elements)", "Complex area: 53,000 m²; 8 palace structures; Mirror Hall area: 240 m²",
    "Mirrored glass mosaics (Aina-kari), painted ceramic tiles depicting hunting and courtly scenes, marble, crystal chandeliers",
    "Golestan Palace, the 'Palace of Flowers', is the historic royal residence of the Qajar dynasty in Tehran. Originally founded during the Safavid era within Tehran's historic mud-brick citadel, it was transformed into the ceremonial heart of the nation when Agha Mohammad Khan chose Tehran as the Qajar capital in 1789. Under Naser al-Din Shah Qajar (reigned 1848–1896), who traveled extensively to Paris, London, and Vienna, the palace was extensively remodeled, blending traditional Persian palace design with European Victorian architecture.",
    "Famous for its sensational Talar-e Ayeneh (Hall of Mirrors), whose ceilings and walls are entirely covered with thousands of microscopic cut-glass mirror facets (Aina-kari) that reflect candlelight like diamond facets, immortalized in the famous 1891 painting by master artist Kamal-ol-Molk. The Marble Throne (Takht-e Marmar) terrace features a magnificent throne supported by 65 carved yellow marble figures of demons, angels, and lions. It was at Golestan that the Pahlavi shahs Reza Shah and Mohammad Reza Pahlavi were coronated.",
    "Inscribed as a UNESCO World Heritage Site in 2013 as a masterpiece of Qajar architectural synthesis.",
    "https://images.unsplash.com/photo-1568084680786-a84f91d1153c?auto=format&fit=crop&q=80&w=1200",
    ["Golestan Palace", "Tehran", "Iran", "Qajar", "UNESCO", "Hall of Mirrors", "Persian Palace"],
    ["Royal ceremonial palace of the Qajar dynasty blending Persian art with European neoclassical design", "The Hall of Mirrors took artist Kamal-ol-Molk five years to capture in his famous 1891 painting", "Features the Marble Throne carved from 65 pieces of yellow Yazd marble supported by stone demons", "Site of the royal coronations of the Pahlavi dynasty shahs in 1925 and 1967"],
    "Inscribed 2013 (Criteria ii, iii, iv)"),

  # 59. Hegra (Mada'in Salih), Saudi Arabia
  item("hegra-saudi", "Hegra (Mada'in Salih / Al-Hijr)", "الحِجر (Al-Hijr) / مدائن صالح", "Archaeological City", "Al-'Ula Governorate, Medina Province", "Saudi Arabia",
    "Nabataean Kingdom (1st Century BCE – 1st Century CE)", "c. 1 BCE – 70 CE", 1, "Nabataean master masons under King Aretas IV and King Malichus II",
    "Nabataean Rock-Cut Monumental Tomb Architecture", "111 monumental rock-cut tombs across 13.4 km²; Qasr al-Farid height: 21.5 m (70 ft)",
    "Living golden-red sandstone desert inselberg rock monoliths",
    "Hegra (Al-Hijr), also known as Mada'in Salih, was the major southern regional capital of the Nabataean Kingdom, second only to Petra in Jordan. Located in the desert valley of Al-'Ula in northwestern Saudi Arabia along the lucrative frankincense and myrrh caravan route. The site features 111 monumental rock-cut tombs carved directly into freestanding golden sandstone inselbergs between the 1st century BCE and the 1st century CE. Mentioned in the Quran as the ancient home of the Thamud people and the prophet Salih.",
    "The undisputed icon of Hegra is Qasr al-Farid ('The Lonely Castle'), an enormous four-story monolithic tomb carved entirely out of an isolated sandstone boulder standing alone in the desert sand. Because it was left unfinished, the bottom portion clearly shows the chisel marks of the ancient Nabataean masons, revealing that they carved their monuments from the top down. The facades feature decorative Hellenistic triangular pediments, Roman columns, Egyptian stepped crow-step crenellations, and protective statues of eagles and gorgons.",
    "Inscribed as Saudi Arabia's first UNESCO World Heritage Site in 2008. Because the dry desert air prevented weathering, Hegra's tomb inscriptions and carvings are far better preserved than those at Petra.",
    "https://images.unsplash.com/photo-1579606032834-deffd1b4260f?auto=format&fit=crop&q=80&w=1200",
    ["Hegra", "Saudi Arabia", "Al Ula", "Nabataean", "UNESCO", "Madain Salih", "Ancient Wonder"],
    ["Saudi Arabia's first UNESCO World Heritage Site, serving as the southern capital of the Nabataeans", "Features 111 monumental rock-cut tombs chiseled directly out of desert sandstone boulders", "Home to Qasr al-Farid ('The Lonely Castle'), a magnificent 21-meter tomb carved from an isolated rock", "Tombs are far better preserved than Petra due to the arid desert climate protecting inscriptions"],
    "Inscribed 2008 (Criteria ii, iii)"),

  # 60. The Kaaba & Masjid al-Haram, Mecca, Saudi Arabia
  item("the-kaaba-mecca", "The Kaaba & Masjid al-Haram", "الكعبة المشرفة (The Holy Kaaba) / المسجد الحرام (The Sacred Mosque)", "Sacred Temple / Cathedral", "Mecca, Hejaz", "Saudi Arabia",
    "Ancient Antiquity to Modern Era (Traditionally Abrahamic; rebuilt 608 CE and expanded 20th–21st Century)", "Tradition antiquity; rebuilt 608 CE", 608, "Traditionally Prophet Abraham (Ibrahim) and Ishmael; major expansions by Ottoman and Saudi kings",
    "Sacred Islamic Cubic Monolithic & Grand Expansion Architecture", "Kaaba height: 13.1 m (43 ft); Base: 11.03 × 12.86 m; Masjid al-Haram area: 356,000 m² (expanding to 1.5 million m²); Capacity: 4 million worshippers",
    "Local Mecca granite ashlar blocks, black silk Kiswah embroidered with 120 kg of pure gold and silver wire, marble, green marble floor slabs",
    "The Kaaba, meaning 'The Cube' in Arabic, is the most sacred building in Islam and the physical focal point toward which all Muslims worldwide turn during their daily prayers (the Qibla). Located at the center of the Masjid al-Haram (The Sacred Mosque) in Mecca, Saudi Arabia. In Islamic belief, the original Kaaba was established by Adam and later rebuilt by Abraham (Ibrahim) and his son Ishmael (Ismail) as the first house of monotheistic worship on Earth. In 608 CE, the Quraysh rebuilt the structure, during which a young Prophet Muhammad placed the sacred Black Stone (al-Hajar al-Aswad) in its eastern corner.",
    "The building is draped annually during the Hajj pilgrimage in the Kiswah, a ceremonial black silk shroud woven with 670 kilograms of dyed silk and embroidered with 120 kilograms of pure gold and silver threads reciting Quranic verses, crafted in a specialized state atelier in Mecca. The eastern corner houses the Black Stone, set in a polished sterling silver frame, believed to date to the time of Adam and Abraham. The surrounding courtyard accommodates over 4 million pilgrims simultaneously performing the Tawaf (seven counterclockwise circumambulations).",
    "The holiest sanctuary in Islam, drawing millions of pilgrims from every corner of the Earth annually for the Hajj and Umrah.",
    "https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&q=80&w=1200",
    ["The Kaaba", "Mecca", "Saudi Arabia", "Hajj", "Islamic", "Masjid al-Haram", "Sacred Site"],
    ["The holiest site in Islam and the direction (Qibla) toward which 1.9 billion Muslims pray daily", "The Kaaba is draped in the Kiswah, a black silk shroud embroidered with 120 kg of pure gold and silver", "The eastern corner encloses the sacred ancient Black Stone in a sterling silver casing", "The surrounding Masjid al-Haram can accommodate up to 4 million worshippers during the Hajj"],
    "Holiest Sanctuary in Islam")
]

full_60_asia = all_asia + asia_part2

with open("src/data/monuments/asianMonuments.ts", "w", encoding="utf-8") as f:
    f.write("import { WorldMonumentOrArtifact } from '../../types';\n\n")
    f.write("export const ASIAN_MONUMENTS: WorldMonumentOrArtifact[] = ")
    f.write(json.dumps(full_60_asia, ensure_ascii=False, indent=2))
    f.write(";\n")

print(f"Successfully generated all {len(full_60_asia)} Asian monuments in src/data/monuments/asianMonuments.ts!")
