#!/usr/bin/env python3
import json

def m(id, name, native, cat, loc, country, region, era, yr_str, yr_num, arch, style, dim, mat, hist, marv, mod, img, tags, facts, unesco="World Heritage Landmark"):
    return {
        "id": id,
        "name": name,
        "nativeOrAlternateName": native,
        "category": cat,
        "location": loc,
        "country": country,
        "region": region,
        "era": era,
        "yearBuilt": yr_str,
        "numericYear": yr_num,
        "architectOrCreator": arch,
        "architecturalStyle": style,
        "dimensionsAndHeight": dim,
        "materialsUsed": mat,
        "historyAndBackground": hist,
        "architecturalMarvels": marv,
        "modernStatusAndSignificance": mod,
        "imageUrl": img,
        "fallbackImageUrl": "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&q=80&w=1200",
        "tags": tags,
        "keyFacts": facts,
        "unescoStatus": unesco
    }

asian_data = [
  m("taj-mahal", "Taj Mahal", "क्राउन ऑफ़ द पैलेस (Crown of the Palace)", "Famous Building", "Agra, Uttar Pradesh", "India", "Asia",
    "Mughal Empire Golden Age (1632–1653 CE)", "1632–1653 CE", 1648, "Ustad Ahmad Lahori, commissioned by Emperor Shah Jahan",
    "Mughal Architecture (Persian, Islamic, and Indian fusion)", "Height: 73 m (240 ft); Dome diameter: 17.7 m; Complex area: 42 acres",
    "Translucent Makrana white marble, red sandstone, inlaid with 28 types of precious gemstones",
    "The Taj Mahal is widely acknowledged as the crown jewel of Indo-Islamic art in India. It was commissioned in 1631 by Emperor Shah Jahan to house the tomb of his beloved favorite wife, Mumtaz Mahal, who died giving birth to their fourteenth child. Construction began in 1632 and enlisted over 20,000 artisans, masons, calligraphers, and stone carvers from India, Persia, the Ottoman Empire, and Europe, alongside 1,000 elephants used to haul marble from Rajasthan. The central mausoleum was completed in 1648, while surrounding courtyards, minarets, and mosque were completed by 1653.",
    "Celebrated for its absolute bilateral symmetry along a central axis, with the sole exception being Shah Jahan’s tomb itself, which was added later beside Mumtaz Mahal. The four 40-meter corner minarets are tilted outward by approximately 3 degrees so that during an earthquake, they would fall outward away from the delicate marble dome. The translucent white marble shifts hue across the day—rosy pink at dawn, bright milky white at noon, and shimmering silver under the moon.",
    "Inscribed as a UNESCO World Heritage Site in 1983 and voted one of the New 7 Wonders of the World in 2007. Protected by the Taj Trapezium Zone (TTZ) restricting industrial emissions.",
    "https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&q=80&w=1200",
    ["Taj Mahal", "India", "Mughal", "UNESCO", "Wonder of the World", "Marble", "Agra", "Shah Jahan"],
    ["Built by Emperor Shah Jahan in memory of his favorite empress Mumtaz Mahal", "Minarets lean outward at a 3-degree angle as an earthquake defense mechanism", "Took 22 years and over 20,000 master artisans to construct", "Shifts color throughout the day from pink at sunrise to golden under moonlight"],
    "Inscribed 1983 (Criterion i)"),

  m("great-wall-of-china", "Great Wall of China", "万里长城 (Wànlǐ Chángchéng - 10,000-Li Long Wall)", "Ancient Wonder", "Northern Frontier across 15 provinces", "China", "Asia",
    "Qin Dynasty to Ming Dynasty (7th Century BCE – 1644 CE)", "c. 221 BCE – 1644 CE", -221, "First unified under Emperor Qin Shi Huang; fortified by Ming Dynasty emperors",
    "Ancient Chinese Military Defensive Rampart Engineering", "Total length: 21,196 km (13,171 miles); Average wall height: 6–8 m; Width: 5–8 m",
    "Rammed earth, dressed granite blocks, kiln-fired gray bricks, sticky rice mortar lime binder",
    "The Great Wall is the longest defensive fortification in human history. Earliest sections were built by rival feudal states during the Warring States period. In 221 BCE, Qin Shi Huang unified China and ordered existing walls joined along the northern ridges to repel raids by Xiongnu nomadic confederations. Hundreds of thousands of soldiers and peasants labored under General Meng Tian. Later dynasties maintained sections, but the iconic stone and brick watchtowers seen today were built during the Ming Dynasty (1368–1644 CE) following the Battle of Tumu.",
    "Ming builders mixed sticky rice soup with slaked lime, producing a mortar with amylopectin that created an extraordinarily resilient seal against weather and vegetation. Traces razor-thin mountain ridges across steep terrain and was supported by over 25,000 watchtowers and beacon towers that transmitted emergency tactical warnings thousands of miles within hours using coded smoke by day and beacon fires by night.",
    "Designated a UNESCO World Heritage Site in 1987 and voted one of the New 7 Wonders of the World in 2007. Serves as the ultimate symbol of Chinese civilizational perseverance.",
    "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?auto=format&fit=crop&q=80&w=1200",
    ["Great Wall", "China", "UNESCO", "Fortress", "Ming Dynasty", "Qin Shi Huang", "Wonder of the World"],
    ["Total recognized length exceeds 21,196 kilometers across northern China", "Mortar used in Ming sections contained sticky rice starch for phenomenal durability", "Beacon towers used coded smoke signals by day and fire torches by night", "Contrary to myth, it is not visible from low Earth orbit without camera zoom lenses"],
    "Inscribed 1987 (Criteria i, ii, iii, iv, vi)"),

  m("angkor-wat", "Angkor Wat", "អង្គរវត្ត (City Temple)", "Sacred Temple / Cathedral", "Siem Reap Province", "Cambodia", "Asia",
    "Khmer Empire (12th Century CE)", "c. 1113–1150 CE", 1130, "King Suryavarman II",
    "Classical Khmer Architecture (Temple-Mountain & Concentric Galleries)", "Central tower height: 65 m (213 ft); Outer moat perimeter: 5 km; Area: 162.6 hectares (402 acres)",
    "Over 5 million tonnes of quarried sandstone blocks, volcanic laterite foundation sub-blocks",
    "Angkor Wat is the largest religious monument in the world. Built during the peak of the Khmer Empire under King Suryavarman II in the early 12th century, it was dedicated to the Hindu deity Vishnu as the royal state temple and funerary mausoleum. Sandstone blocks were quarried 40 km away at Mount Kulen and floated on bamboo rafts down the Siem Reap River. By the late 12th century, under King Jayavarman VII, the temple gradually transformed into an active Theravada Buddhist sanctuary, remaining in continuous worship even when neighboring jungle reclaimed the city of Angkor.",
    "A terrestrial representation of Hindu cosmology: five central lotus-bud towers represent the five sacred peaks of Mount Meru, while the 190-meter-wide moat symbolizes the cosmic ocean. Uniquely faces westward toward the setting sun, consistent with funerary symbolism. Gallery walls feature over 1,200 square meters of bas-reliefs, depicting the Churning of the Ocean of Milk, the Mahabharata battle, and Suryavarman II’s war elephant procession. On the spring equinox, the sun rises precisely over the central spire.",
    "Core of the UNESCO Angkor World Heritage Site (1992). Prominently depicted on Cambodia's national flag, making it one of the only buildings on Earth featured on a national banner.",
    "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=1200",
    ["Angkor Wat", "Cambodia", "Khmer", "Hindu", "Buddhist", "UNESCO", "Temple Mountain"],
    ["Largest religious complex in the world, covering over 400 acres", "Faces westward toward the setting sun, unique among major classical Khmer temples", "The sun rises precisely over the central tower on the equinoxes", "Decorated with over 3,000 uniquely individual celestial Apsara carvings"],
    "Inscribed 1992 (Criteria i, ii, iii, iv)"),

  m("burj-khalifa", "Burj Khalifa", "برج خليفة (Khalifa Tower)", "Monument & Tower", "Downtown Dubai", "United Arab Emirates", "Middle East",
    "Contemporary Global Engineering (2004–2010 CE)", "2004–2010 CE", 2010, "Adrian Smith & William F. Baker (Skidmore, Owings & Merrill)",
    "Neo-futurist High-Tech Skyscraper (Y-shaped Buttressed Core)", "Height: 828 m (2,717 ft); 163 floors; Floor area: 309,473 m²",
    "Reinforced concrete core, structural steel spire, 103,000 m² of reflective glass and aluminum panels",
    "The Burj Khalifa is the tallest building and tallest freestanding structure in human history. Initiated by Dubai's ruler Sheikh Mohammed bin Rashid Al Maktoum to shift Dubai's economic center toward international tourism and commerce. Construction began in 2004 with over 12,000 workers on site daily. Designed by Adrian Smith and engineered by Bill Baker, it opened on January 4, 2010, named in honor of UAE President Sheikh Khalifa bin Zayed Al Nahyan.",
    "Features a revolutionary buttressed core design—a hexagonal central concrete core braced by three wings in a Y-shape inspired by the desert flower Hymenocallis. This aerodynamic profile deflects high-altitude desert wind vortices as the tower steps back in 26 helical terraces. Set the world record for vertical concrete pumping at 606 meters. The sun sets three to four minutes later on the top floors than on the ground.",
    "The defining icon of 21st-century architectural engineering, holding world records for tallest structure, highest occupied floor, and elevator with the longest travel distance.",
    "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&q=80&w=1200",
    ["Burj Khalifa", "Dubai", "UAE", "Skyscraper", "Tallest Building", "Architecture"],
    ["Tallest structure ever built by human hands at 828 meters (2,717 feet)", "Exterior is wrapped in over 26,000 hand-cut reflective glass panels", "Takes three to four months for professional abseilers to clean the entire facade", "The temperature at the tip of the spire is about 6°C cooler than at ground level"],
    "Modern Architectural Wonder"),

  m("petra-treasury", "Al-Khazneh (The Treasury) & Petra", "الخزنة (The Treasury) / الرقيم (Raqmu)", "Ancient Wonder", "Ma'an Governorate", "Jordan", "Middle East",
    "Nabataean Kingdom (1st Century BCE – 1st Century CE)", "c. 9 BCE – 40 CE", 9, "Nabataean master stonemasons under King Aretas IV",
    "Hellenistic-Nabataean Rock-Cut Architecture", "Facade height: 39.5 m (130 ft); Width: 25 m; City area: 264 km²",
    "Living rose-red and ochre iron-banded sandstone cliff faces",
    "Al-Khazneh is the most famous facade in the ancient rock-cut city of Petra, capital of the Nabataean Arab kingdom. Dominating the crossroads of ancient silk and incense routes linking Arabia, Egypt, and Rome. Carved into the cliffs of Jabal al-Madhbah under King Aretas IV. Bedouins called it 'The Treasury' believing an Egyptian pharaoh hid gold in the upper stone urn, though it was in fact an elaborate royal tomb. Petra thrived until trade routes shifted to sea voyages and earthquakes in 363 and 551 CE damaged its water system. Rediscovered by Swiss explorer Johann Burckhardt in 1812.",
    "Carved directly into the cliff-face from the top down without scaffolding; masons cut footholds, chiseled upper pediments, and worked downward. The city thrived in an arid desert thanks to a sophisticated network of terracotta pipes, cisterns, and dams that distributed 45 million liters of spring water daily.",
    "UNESCO World Heritage Site (1985) and one of the New 7 Wonders of the World (2007). Jordan’s most iconic cultural destination.",
    "https://images.unsplash.com/photo-1579606032834-deffd1b4260f?auto=format&fit=crop&q=80&w=1200",
    ["Petra", "Jordan", "Nabataean", "Al-Khazneh", "Treasury", "UNESCO", "Wonder of the World"],
    ["Carved directly out of sandstone mountain cliffs from the top downward", "The decorative top urn bears bullet marks from treasure hunters seeking gold", "Reached through the Siq, a dramatic 1.2 km narrow canyon between 80-meter cliffs", "Supported a thriving desert population of 30,000 using advanced water engineering"],
    "Inscribed 1985 (Criteria i, iii, iv)"),

  m("forbidden-city", "The Forbidden City", "故宫 (Gùgōng) / 紫禁城 (Purple Forbidden City)", "Palace & Fortress", "Beijing", "China", "Asia",
    "Ming & Qing Dynasties (1406–1912 CE)", "1406–1420 CE", 1420, "Yongle Emperor (Zhu Di); Master Architect Kuai Xiang",
    "Traditional Imperial Chinese Palace Architecture (Feng Shui, Dougang)", "Complex area: 72 hectares (178 acres); 980 surviving buildings; 8,886 room bays; Wall height: 10 m",
    "Phoebe zhennan logs, 'golden bricks', yellow glazed ceramic tiles, white marble terraces",
    "The Forbidden City was the imperial palace of China from 1420 to 1912, housing 24 successive emperors of the Ming and Qing dynasties. Built over 14 years by one million workers on the orders of the Yongle Emperor, who moved the capital from Nanjing to Beijing. Commoners were strictly forbidden from entering under penalty of execution. It was the stage for five centuries of dynastic politics, the fall of the Ming, the Manchu conquest, and the abdication of Puyi in 1912.",
    "Arranged along a precise north-south meridian axis aligning with the North Star. Constructed entirely without iron nails using interlocking timber dougong brackets that flex to withstand major earthquakes. Roofs are covered in imperial yellow tiles, reserved exclusively for the sovereign. The Hall of Supreme Harmony features a marble terrace with 1,142 dragon heads that spout rainwater during summer storms.",
    "Inscribed as a UNESCO World Heritage Site in 1987 as the world's largest collection of preserved wooden structures. Today it houses the Palace Museum, displaying over 1.8 million imperial artifacts.",
    "https://images.unsplash.com/photo-1584646098378-0874589d76b1?auto=format&fit=crop&q=80&w=1200",
    ["Forbidden City", "Beijing", "China", "Imperial Palace", "Ming", "Qing", "UNESCO"],
    ["Home of 24 Chinese emperors across the Ming and Qing dynasties for 492 years", "Built with interlocking wooden mortise-and-tenon joints without a single iron nail", "Floor 'golden bricks' were fired for months in clay kilns to ring like chimes when stepped on", "Contains 980 preserved wooden buildings and exactly 8,886 rooms"],
    "Inscribed 1987 (Criteria i, ii, iii, iv)"),

  m("himeji-castle", "Himeji Castle (White Heron Castle)", "姫路城 (Himeji-jō - Shirasagijō)", "Palace & Fortress", "Himeji, Hyōgo Prefecture", "Japan", "Asia",
    "Sengoku to Edo Period (1333–1609 CE)", "1601–1609 CE", 1609, "Ikeda Terumasa, son-in-law of Shogun Tokugawa Ieyasu",
    "Japanese Feudal Hilltop (Hirayama) Castle Architecture", "Main keep height: 46.4 m (152 ft); Altitude: 92 m; Grounds: 107 hectares",
    "Giant cypress timber pillars, cyclopean granite stone walls, fireproof white plaster",
    "Himeji Castle is Japan's finest surviving feudal fortress. Expanded after the Battle of Sekigahara (1600) by Ikeda Terumasa into a massive defensive stronghold. Nicknamed 'White Heron Castle' because its graceful curving white eaves resemble a heron in flight. Survived the Meiji samurai disarmament, WWII bombing that leveled the surrounding city, and the 1995 Kobe earthquake completely unscathed.",
    "Features a lethal defensive labyrinth of gates and dead-ends designed to trap attackers in firing zones under 997 shooting embrasures (sama). Foundation walls curve outward to prevent climbing. Supported by two massive 25-meter cypress columns extending from the ground to the top floor.",
    "Japan's first UNESCO World Heritage Site (1993) and a designated National Treasure of Japan.",
    "https://images.unsplash.com/photo-1578637387939-43c525550085?auto=format&fit=crop&q=80&w=1200",
    ["Himeji Castle", "Japan", "Samurai", "White Heron", "UNESCO", "Castle"],
    ["Japan's most pristine feudal castle, surviving WWII bombing and the 1995 Kobe earthquake", "Outer plaster is infused with crushed seashell to provide fire resistance", "Incorporates 997 shooting embrasures engineered for matchlock guns and arrows", "Concentric spiral paths lead attackers away from the central keep into kill zones"],
    "Inscribed 1993 (Criteria i, iv)"),

  m("borobudur-temple", "Borobudur Temple Compounds", "Candi Borobudur", "Sacred Temple / Cathedral", "Central Java", "Indonesia", "Asia",
    "Sailendra Dynasty (c. 750–825 CE)", "c. 778–850 CE", 825, "Master Architect Gunadharma under Sailendra Kings",
    "Javanese Buddhist Stupa Mandala", "Base: 123 × 123 m (403 ft); Height: 35 m (115 ft); Volume: 55,000 m³ stone",
    "Over 2 million volcanic andesite stone blocks carved without mortar",
    "Borobudur is the largest Buddhist monument in the world. Constructed around 800 CE in Java during the Sailendra Dynasty. Following volcanic eruptions from Mount Merapi and political shifts, it was abandoned in the 14th century and swallowed by jungle and volcanic ash. Rediscovered in 1814 by British governor Thomas Stamford Raffles and excavated over decades.",
    "Built as a giant three-dimensional stone mandala representing Buddhist cosmology: Kamadhatu (desire), Rupadhatu (forms), and Arupadhatu (formlessness). Contains 2,672 carved relief panels and 72 perforated bell-shaped stupas, each housing a seated Buddha statue on the circular upper terraces.",
    "UNESCO World Heritage Site (1991). The sacred epicenter for global celebrations of Vesak Day in Southeast Asia.",
    "https://images.unsplash.com/photo-1596402184320-417e7178b2cd?auto=format&fit=crop&q=80&w=1200",
    ["Borobudur", "Indonesia", "Buddhist", "Java", "UNESCO", "Mandala"],
    ["World's largest Buddhist temple monument, built from 2 million volcanic stones", "Constructed entirely without mortar using interlocking tongue-and-groove joints", "Features 2,672 narrative stone relief panels and 504 Buddha statues", "Lay buried under volcanic ash for centuries until its rediscovery in 1814"],
    "Inscribed 1991 (Criteria i, ii, vi)"),

  m("fushimi-inari-taisha", "Fushimi Inari-Taisha Shrine", "伏見稲荷大社 (Grand Shinto Shrine of Inari)", "Sacred Temple / Cathedral", "Fushimi-ku, Kyoto", "Japan", "Asia",
    "Nara to Edo Period (711 CE – Present)", "Founded 711 CE; Main Hall rebuilt 1499 CE", 711, "Hata clan chieftain Hata no Irogu",
    "Traditional Japanese Shinto Shrine Architecture (Nagare-zukuri)", "Mount Inari trail: 4 km (2.5 miles); Over 10,000 vermilion torii gates",
    "Japanese cypress timber (hinoki), vermilion and black cinnabar lacquer, carved stone fox statues (kitsune)",
    "Fushimi Inari-Taisha is the head shrine for 32,000 Inari shrines throughout Japan. Founded in 711 CE by the aristocratic Hata clan to honor Inari, the Shinto kami of rice, fertility, and harvests. As Japan modernized, Inari became revered as the patron kami of business prosperity and commerce. The Main Hall was rebuilt in 1499 following destruction in the Onin War.",
    "The iconic Senbon Torii features thousands of vivid vermilion torii gates creating tunnels through sacred Mount Inari. The vermilion color, derived from cinnabar, repels evil forces and wood decay in Shinto belief. Each gate is inscribed with the donor company or family and date of dedication. Stone foxes hold symbolic granary keys or sacred jewels in their mouths.",
    "Regularly voted the top cultural destination in Japan by global travelers. Part of Ancient Kyoto's heritage fabric.",
    "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?auto=format&fit=crop&q=80&w=1200",
    ["Fushimi Inari", "Kyoto", "Japan", "Shinto", "Torii Gates", "Shrine"],
    ["Features over 10,000 vermilion torii gates winding up sacred Mount Inari", "Dedicated to Inari, kami of agriculture, rice harvest, and business fortune", "Fox statues (kitsune) serve as messengers holding keys to harvest granaries", "Every single torii gate is funded and donated by Japanese businesses or families"],
    "Important Cultural Property of Japan"),

  m("kinkaku-ji", "Kinkaku-ji (The Golden Pavilion)", "金閣寺 (Rokuon-ji)", "Sacred Temple / Cathedral", "Kita-ku, Kyoto", "Japan", "Asia",
    "Muromachi Period (1397 CE)", "1397 CE (Rebuilt 1955)", 1397, "Shogun Ashikaga Yoshimitsu",
    "Kitayama Culture Zen Buddhist & Shinden-zukuri Fusion", "Height: 12.5 m (41 ft); 3-story pavilion; Mirror Pond: 6,600 m²",
    "Japanese cypress frame, pure gold leaf gilding, Japanese urushi lacquer, bronze phoenix",
    "Built in 1397 as a retirement villa for third Ashikaga Shogun Yoshimitsu, who converted it to a Rinzai Zen temple upon his death. The pavilion miraculously survived the Onin War when most of Kyoto was burned. In 1950, a novice monk burned the 550-year-old pavilion to the ground, an event immortalized in Yukio Mishima's novel. Meticulously reconstructed in 1955 using 20 kg of gold leaf.",
    "Synthesizes three architectural styles across three floors: Heian aristocratic palace style on the ground, samurai warrior hall style on the middle, and Chinese Zen temple style on the top. The top two stories are gilded in pure gold leaf. Perched beside the Mirror Pond, casting a shimmering golden reflection amidst pine trees.",
    "UNESCO World Heritage Site (1994, Historic Monuments of Ancient Kyoto). One of Japan's most celebrated aesthetic landmarks.",
    "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?auto=format&fit=crop&q=80&w=1200",
    ["Kinkaku-ji", "Golden Pavilion", "Kyoto", "Japan", "Zen", "Ashikaga", "UNESCO"],
    ["Top two floors are completely gilded in pure gold leaf over natural lacquer", "Combines three distinct historical architectural styles on each of its three stories", "The roof is crowned with a solid bronze Chinese phoenix (Fenghuang)", "Designed specifically to project a pristine unbroken reflection across Mirror Pond"],
    "Inscribed 1994 (Historic Monuments of Ancient Kyoto)"),

  m("shwedagon-pagoda", "Shwedagon Pagoda (Great Dagon Pagoda)", "ရွှေတိဂုံဘုရား (Golden Dagon Pagoda)", "Sacred Temple / Cathedral", "Yangon", "Myanmar", "Asia",
    "Mon & Burmese Dynasties (c. 6th–15th Century CE)", "c. 6th–10th Century CE (Expanded 1453–1472)", 1453, "Mon founders; Expanded by Queen Shin Sawbu",
    "Burmese Buddhist Zedi (Stupa) Architecture", "Height: 112 m (367 ft); Plinth perimeter: 433 m; Perched on Singuttara Hill",
    "Solid brick core plated in real gold sheets, crowned with 5,448 diamonds, 2,317 rubies, and a 76-carat diamond at the apex",
    "The Shwedagon Pagoda is the most sacred Buddhist pagoda in Myanmar. Tradition records that it was founded over 2,500 years ago when two merchant brothers met Gautama Buddha in India and received eight sacred hair strands, enshrining them on Singuttara Hill alongside relics of three previous Buddhas. In the 15th century, Queen Shin Sawbu of the Mon kingdom expanded the stupa and donated her body weight in pure gold.",
    "The exterior is covered in thousands of pure gold plates. The umbrella finial (Hti) weighs over a ton of gold filigree, encrusted with 5,448 diamonds, 2,317 rubies, and thousands of bells that chime in the wind. The summit holds a flawless 76-carat diamond that catches the last rays of the setting sun.",
    "The spiritual heart of Myanmar and the historical site of pivotal independence and democracy rallies.",
    "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&q=80&w=1200",
    ["Shwedagon Pagoda", "Myanmar", "Burma", "Yangon", "Buddhist", "Gold", "Stupa"],
    ["The only Buddhist stupa holding relics of all four Buddhas of our current era", "Plated with thousands of pure gold bars and foil sheets", "The umbrella finial contains 5,448 diamonds and 2,317 rubies and emeralds", "The apex is crowned with a single flawless 76-carat diamond"],
    "Sacred National Buddhist Shrine"),

  m("potala-palace", "Potala Palace", "པོ་ཏ་ལ (Potala) / 布达拉宫", "Palace & Fortress", "Lhasa, Tibet", "China", "Asia",
    "Tibetan Empire to Ganden Phodrang (1645–1694 CE)", "1645–1694 CE", 1648, "5th Dalai Lama (Ngawang Lobsang Gyatso) & Regent Desi Sangye Gyatso",
    "Traditional Tibetan Dzong Fortress Architecture", "Altitude: 3,700 m (12,100 ft); Height: 117 m (384 ft); 13 stories; Over 1,000 rooms",
    "Rammed earth, granite blocks, sweet-smelling cedar timber beams, copper-gilded golden roofs",
    "Perched atop Marpo Ri (the Red Mountain) in Lhasa Valley, the Potala Palace was the winter residence and administrative seat of the Dalai Lamas until 1959. Originating in the 7th century when King Songtsen Gampo built a meditation pavilion. The 5th Dalai Lama commenced the present monumental palace in 1645. The White Palace was completed in 1648, and the Red Palace in 1694 under Regent Desi Sangye Gyatso, who concealed the Dalai Lama’s death for 15 years so construction would not halt.",
    "A Himalayan engineering marvel rising 13 stories with walls up to 5 meters thick at the base, poured with molten copper to resist earthquakes. The Red Palace houses the opulent funerary stupas of eight Dalai Lamas; the 5th Dalai Lama’s tomb alone is covered in 3,721 kilograms of solid gold and studded with 18,680 gems.",
    "Designated a UNESCO World Heritage Site in 1994. The definitive architectural symbol of Tibetan culture and Buddhism.",
    "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&q=80&w=1200",
    ["Potala Palace", "Tibet", "Lhasa", "Dalai Lama", "Buddhism", "UNESCO", "Himalayas"],
    ["Highest ancient palace in the world at 3,700 meters (12,100 ft) elevation", "Funerary stupa of the 5th Dalai Lama contains over 3,700 kg of solid gold", "Base walls are 5 meters thick and fortified with poured molten copper", "Death of the 5th Dalai Lama was kept secret for 15 years to finish construction"],
    "Inscribed 1994 (Criteria i, iv, vi)"),

  m("meenakshi-temple", "Meenakshi Amman Temple", "மீனாட்சி அம்மன் கோவில் (Arulmigu Meenakshi Temple)", "Sacred Temple / Cathedral", "Madurai, Tamil Nadu", "India", "Asia",
    "Pandyan & Nayak Dynasties (6th Century BCE – 1655 CE)", "Current layout 1623–1655 CE", 1623, "King Thirumalai Nayak & Vishwanatha Nayakar",
    "Dravidian Architecture (Monumental Gopurams, Mandapams)", "Area: 14 acres (58,000 m²); Tallest Southern Gopuram height: 52 m (170 ft); 14 gopurams",
    "Granite bedrock foundations, carved limestone, terracotta stucco, polychrome pigments",
    "The Meenakshi Amman Temple is one of India's oldest and grandest Hindu temple complexes. Dedicated to Meenakshi (a form of Parvati) and Sundareswarar (Shiva). Mentioned in Tamil Sangam literature over 2,500 years ago. Rebuilt and expanded between the 16th and 17th centuries by the Madurai Nayak Dynasty into a massive temple city following earlier medieval invasions.",
    "Enclosed by granite walls pierced by 14 monumental gopurams (gateway towers), the tallest reaching 52 meters. Gopurams are covered in thousands of colorful stucco sculptures of deities, demons, and celestial beings. The Hall of a Thousand Pillars contains 985 carved granite columns. Includes 'Musical Pillars' carved from solid granite that produce different musical notes when struck.",
    "Attracts over 15,000 visitors daily, swelling to over 1 million during the annual Chithirai Festival in April/May.",
    "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&q=80&w=1200",
    ["Meenakshi Temple", "Madurai", "India", "Hindu", "Dravidian", "Gopuram", "Tamil Nadu"],
    ["Features 14 towering gateway gopurams adorned with over 33,000 colorful statues", "The Hall of Thousand Pillars contains 985 hand-carved solid granite columns", "Includes famous 'Musical Pillars' that emit acoustic musical tones when tapped", "One of few ancient Indian temples where the goddess is worshiped before the male god"],
    "Historic Dravidian Monument"),

  m("dome-of-the-rock", "Dome of the Rock", "قبة الصخرة (Qubbat al-Sakhrah)", "Sacred Temple / Cathedral", "Old City of Jerusalem", "Palestine / Jerusalem", "Middle East",
    "Umayyad Caliphate (688–691 CE)", "688–691 CE", 691, "Umayyad Caliph Abd al-Malik ibn Marwan; Architects Yazid ibn Salam & Raja ibn Haywah",
    "Early Islamic Architecture (Octagonal Central-Plan, Byzantine Mosaics)", "Dome height: 35 m (115 ft); Dome diameter: 20 m; Octagon diameter: 55 m",
    "Jerusalem limestone, marble columns, Byzantine glass and gold tesserae mosaics, 24K gold-plated dome",
    "The Dome of the Rock is the oldest existing Islamic monument in the world. Commissioned by Umayyad Caliph Abd al-Malik and completed in 691 CE on Mount Moriah (Haram al-Sharif / Temple Mount). In Islamic tradition, the central Foundation Stone is where the Prophet Muhammad ascended to heaven (Mi'raj) during his Night Journey. In Jewish tradition, it is the Holy of Holies where Abraham prepared to sacrifice Isaac and the site of Solomon’s Temple.",
    "The octagonal structure encloses the sacred Foundation Stone. Features over 1,200 square meters of 7th-century glass and gold mosaic tesserae. Includes a 240-meter-long continuous Kufic Arabic inscription from the Quran, representing the earliest dated Quranic architectural text in existence. Crowned by a 20-meter golden dome plated with 80 kg of pure gold.",
    "Core of the UNESCO World Heritage Site 'Old City of Jerusalem and its Walls' (1981). Administered by the Jerusalem Islamic Waqf.",
    "https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?auto=format&fit=crop&q=80&w=1200",
    ["Dome of the Rock", "Jerusalem", "Umayyad", "Islamic", "UNESCO", "Golden Dome"],
    ["Oldest surviving Islamic monument in the world, completed in 691 CE", "Encloses the Foundation Stone, sacred in Judaism, Christianity, and Islam", "Interior inscription contains the earliest dated Quranic verses on stone", "Dome was electroplated in 80 kg of 24K gold in 1993 by King Hussein of Jordan"],
    "Inscribed 1981 (Old City of Jerusalem)"),

  m("persepolis", "Persepolis (Takht-e Jamshid)", "تخت جمشید (Throne of Jamshid) / Pārsa", "Archaeological City", "Marvdasht, Fars Province", "Iran", "Middle East",
    "Achaemenid Persian Empire (c. 518–330 BCE)", "c. 518 BCE", -518, "King Darius I the Great; King Xerxes I",
    "Achaemenid Persian Imperial Architecture (Hypostyle Apadana)", "Terrace area: 125,000 m² (30 acres); Height: 12 m; Column height: 20 m",
    "Dark grey limestone from Mount Rahmat, cedar wood roof beams, gold foil cladding",
    "Persepolis was the ceremonial capital of the Achaemenid Persian Empire under Darius the Great and Xerxes I. Built on a grand stone terrace to host Nowruz (the Persian New Year and spring equinox), where delegations from 23 subject nations presented tribute to the King of Kings. In 330 BCE, Alexander the Great captured Persepolis, looted its treasuries, and burned the cedar palaces.",
    "Built atop an immense 12-meter-high stone terrace. The Gate of All Nations is guarded by colossal winged human-headed bull statues (Lamassu). The Apadana hall was supported by 72 soaring 20-meter columns. Bas-relief staircases depict delegates from Ethiopia to Greece in authentic national dress with tribute gifts.",
    "Designated a UNESCO World Heritage Site in 1979. The premier archaeological treasure of ancient Iran.",
    "https://images.unsplash.com/photo-1568084680786-a84f91d1153c?auto=format&fit=crop&q=80&w=1200",
    ["Persepolis", "Iran", "Persia", "Achaemenid", "Darius the Great", "Xerxes", "UNESCO"],
    ["The ceremonial capital where 23 subject nations presented New Year tribute", "The Apadana audience hall was supported by 72 colossal 20-meter columns", "Burned by Alexander the Great in 330 BCE, which baked and preserved clay tablets", "Dry-stone blocks were locked together with molten lead and iron butterfly clamps"],
    "Inscribed 1979 (Criteria i, iii, vi)")
]

print(f"Loaded {len(asian_data)} Asian monuments in build_asia.py")
