#!/usr/bin/env python3
import json
import os

items = [
  {
    "id": "eiffel-tower",
    "name": "Eiffel Tower",
    "nativeOrAlternateName": "Tour Eiffel (La Dame de Fer - The Iron Lady)",
    "category": "Monument & Tower",
    "location": "Champ de Mars, 7th Arrondissement, Paris",
    "country": "France",
    "region": "Europe",
    "era": "Belle Époque & Industrial Revolution (1887–1889 CE)",
    "yearBuilt": "1887–1889 CE",
    "numericYear": 1889,
    "architectOrCreator": "Gustave Eiffel (Engineer & Builder); Maurice Koechlin & Émile Nouguier (Designers); Stephen Sauvestre (Architect)",
    "architecturalStyle": "19th-Century Structural Wrought-Iron Puddled Lattice Tower",
    "dimensionsAndHeight": "Height: 330 m (1,083 ft) including radio tip; Base square: 125 m (410 ft) on each side; Total weight: 10,100 tonnes",
    "materialsUsed": "7,300 tonnes of high-grade puddled wrought iron from Pompey, Lorraine; 2.5 million hot-riveted iron rivets; protective lead-free paint",
    "historyAndBackground": "The Eiffel Tower was erected as the monumental entrance arch for the 1889 Exposition Universelle (World's Fair), organized to celebrate the centennial of the French Revolution. Selected out of 107 competing proposals, the project was directed by engineer Gustave Eiffel alongside chief engineers Maurice Koechlin and Émile Nouguier. Construction began on January 28, 1887, and took precisely two years, two months, and five days to complete with zero fatalities during construction hours. Initially, the tower sparked fierce outrage among Parisian intellectual and artistic elites; prominent cultural figures including Guy de Maupassant, Alexandre Dumas fils, and Charles Garnier signed a fiery manifesto in 'Le Temps' condemning the tower as a 'ridiculous, dizzying chimney... a black gigantic industrial monstrosity.' The original contract granted Eiffel a 20-year concession, after which the tower was slated to be demolished in 1909. Eiffel saved the monument by championing its invaluable utility as a military telecommunications antenna and meteorological observatory. During the First World War, the tower's radio transmitters intercepted coded German military telegrams that halted the Battle of the Marne.",
    "architecturalMarvels": "The tower's distinctive curved flared profile is mathematically calculated to counteract aerodynamic wind resistance: under the fiercest gales, the tower sways by only 6 to 7 centimeters (2.5 to 3 inches). Thermal expansion causes the sun-facing iron side to expand more than the shaded side, causing the summit to tilt away from the sun by up to 15 centimeters. The iron framework relies on 18,038 individual metal components joined by 2.5 million rivets heated red-hot and hammered into place by four-man teams. It is repainted every seven years by hand using 60 tonnes of paint in three gradated shades of 'Eiffel Tower Brown'—darkest at the bottom and lightest at the top—to maintain an optical illusion of uniform tone against the Parisian sky.",
    "modernStatusAndSignificance": "Inscribed as a core part of the UNESCO World Heritage Site 'Paris, Banks of the Seine' in 1991. It is the most visited paid monument on Earth, welcoming approximately 7 million visitors every year. Globally recognized as the ultimate romantic symbol of Paris, French cultural pride, and industrial prowess.",
    "imageUrl": "https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?auto=format&fit=crop&q=80&w=1200",
    "fallbackImageUrl": "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&q=80&w=1200",
    "tags": ["Eiffel Tower", "Paris", "France", "Iron Lady", "Industrial Revolution", "UNESCO", "World Fair", "Gustave Eiffel"],
    "keyFacts": [
      "Built for the 1889 World's Fair and was originally scheduled to be torn down after 20 years",
      "Held the title of tallest man-made structure in the world for 41 years until the Chrysler Building",
      "Shrinks in freezing winter weather and expands by up to 15 cm in hot summer sun",
      "Held together by 2.5 million individually hand-hammered red-hot iron rivets"
    ],
    "unescoStatus": "Inscribed 1991 (Banks of the Seine)"
  },
  {
    "id": "colosseum",
    "name": "The Colosseum (Flavian Amphitheatre)",
    "nativeOrAlternateName": "Amphitheatrum Flavium / Il Colosseo",
    "category": "Ancient Wonder",
    "location": "Piazza del Colosseo, Rome",
    "country": "Italy",
    "region": "Europe",
    "era": "Roman Empire (Flavian Dynasty, 70–80 CE)",
    "yearBuilt": "70–80 CE",
    "numericYear": 80,
    "architectOrCreator": "Commissioned by Emperor Vespasian; inaugurated by Emperor Titus; modified by Domitian",
    "architecturalStyle": "Ancient Roman Monumental Amphitheatre (Arcade & Vault Concrete Engineering)",
    "dimensionsAndHeight": "Outer height: 48 m (157 ft); Ellipse axes: 189 × 156 m (620 × 512 ft); Arena floor: 87 × 55 m; Capacity: 50,000–80,000 spectators",
    "materialsUsed": "100,000 m³ of travertine limestone, volcanic tuff, Roman pozzolanic concrete (opus caementicium), 300 tonnes of iron clamps",
    "historyAndBackground": "The Colosseum is the largest ancient amphitheatre ever built and the monumental emblem of Imperial Roman engineering. Commissioned by Emperor Vespasian around 70–72 CE on the site of Nero’s reviled Golden House (Domus Aurea) lake, deliberately returning land to the Roman public after the civil wars of the Year of the Four Emperors. Funded by spoils looted from the siege of Jerusalem and built by thousands of Jewish captives and Roman artisans. Inaugurated in 80 CE by Emperor Titus with 100 consecutive days of lavish inaugural games, in which over 9,000 wild animals were slaughtered. For four centuries it hosted gladiatorial combats (munera), public executions, mock naval battles (naumachiae), and animal hunts (venationes). Following the fall of Rome, earthquakes damaged its outer walls, and during the Middle Ages and Renaissance, it was quarried as a stone supply for St. Peter’s Basilica and Roman palaces until Pope Benedict XIV consecrated it in 1749 in honor of Christian martyrs.",
    "architecturalMarvels": "Showcases Roman mastery of the arch and concrete. Features four tiers with superimposed classical orders: Doric columns on the ground level, Ionic on the second, Corinthian on the third, and Corinthian pilasters on the attic. Spectators entered through 80 numbered arched vomitoria gates, allowing 50,000 people to fill or evacuate the stadium within 15 minutes. Beneath the wooden sand-covered arena floor lay the Hypogeum: a two-level subterranean labyrinth of tunnels, cages, and 28 counterweight wooden elevators that hoisted gladiators and wild tigers directly through trapdoors into the arena. On scorching days, a gigantic retractable canvas awning (velarium) was rigged across the top by imperial sailors to shade the crowd.",
    "modernStatusAndSignificance": "Designated a UNESCO World Heritage Site in 1980 and voted one of the New 7 Wonders of the World in 2007. Attracts over 7.6 million visitors annually and serves as the backdrop for the Pope’s annual Good Friday Way of the Cross procession.",
    "imageUrl": "https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&q=80&w=1200",
    "fallbackImageUrl": "https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?auto=format&fit=crop&q=80&w=1200",
    "tags": ["Colosseum", "Rome", "Italy", "Flavian", "Amphitheatre", "Gladiators", "UNESCO", "Wonder of the World"],
    "keyFacts": [
      "Largest ancient amphitheatre in the world, holding up to 80,000 Roman spectators",
      "Subterranean hypogeum contained 28 manual elevators that launched wild beasts through trapdoors",
      "Could be evacuated completely in under 15 minutes through 80 arched vomitoria exits",
      "Supplied with a massive canvas awning (velarium) operated by trained imperial Roman sailors"
    ],
    "unescoStatus": "Inscribed 1980 (Historic Centre of Rome)"
  },
  {
    "id": "parthenon-acropolis",
    "name": "The Parthenon & Acropolis",
    "nativeOrAlternateName": "Παρθενών (Temple of Athena Parthenos) / Ακρόπολη Αθηνών",
    "category": "Ancient Wonder",
    "location": "Acropolis Rock, Athens",
    "country": "Greece",
    "region": "Europe",
    "era": "Classical Greece Golden Age (447–432 BCE)",
    "yearBuilt": "447–432 BCE",
    "numericYear": -438,
    "architectOrCreator": "Architects Iktinos and Kallikrates; Sculptor and General Overseer Phidias; Commissioned by Pericles",
    "architecturalStyle": "Classical Greek Peripteral Doric Order (with Ionic Frieze Elements)",
    "dimensionsAndHeight": "Base: 69.5 × 30.9 m (228 × 101 ft); Column height: 10.4 m (34 ft); 46 outer Doric columns",
    "materialsUsed": "Over 20,000 tonnes of flawless Pentelic white marble, timber roof beams, chryselephantine gold and ivory",
    "historyAndBackground": "The Parthenon is the supreme pinnacle of Classical Greek architecture and Western civilization’s most influential building. Commissioned by the democratic statesman Pericles in 447 BCE following the Persian Wars, when Athens stood at the zenith of its maritime empire. Built to replace the Older Parthenon destroyed by Xerxes I in 480 BCE, it served as both a treasury and a temple honoring Athena Parthenos, the patron goddess of Athens. The master sculptor Phidias supervised the sculptural decoration and crafted the 12-meter chryselephantine (gold and ivory) statue of Athena housed within. Throughout its 2,500-year history, the temple was converted into a Christian cathedral under the Byzantines, a Catholic church under the Franks, and an Ottoman mosque with an added minaret. In 1687, during the Morean War, a Venetian mortar shell struck an Ottoman gunpowder magazine stored inside, blowing out the temple’s central cella and toppling 28 columns. In 1801–1805, Lord Elgin removed half the surviving sculptural friezes (the 'Elgin Marbles'), now in the British Museum.",
    "architecturalMarvels": "The Parthenon contains almost no straight lines: every structural member is gently curved to correct for human optical illusions. The horizontal stylobate (floor) bows upward in the center by 60 mm on the facades and 110 mm along the sides so it does not appear to sag under perspective viewing. The Doric columns feature entasis—a subtle swelling around one-third of the way up—and lean inward by about 6 cm toward the center; if projected upward, the columns would meet at a single focal point approximately 2.4 kilometers in the sky. Corner columns are 2.5% thicker than interior columns and positioned closer together because bright sunlight behind them would otherwise make them appear thinner. The continuous 160-meter-long interior Ionic frieze depicted the Panathenaic procession with breathtaking anatomical fidelity.",
    "modernStatusAndSignificance": "Designated a UNESCO World Heritage Site in 1987 as the universal symbol of democracy, classical harmony, and philosophical reason. Undergoing one of the world's most meticulous architectural restoration projects using original Pentelic marble from Mount Pentelicus.",
    "imageUrl": "https://images.unsplash.com/photo-1603565816030-6b389eeb23cb?auto=format&fit=crop&q=80&w=1200",
    "fallbackImageUrl": "https://images.unsplash.com/photo-1555993539-1732b0258235?auto=format&fit=crop&q=80&w=1200",
    "tags": ["Parthenon", "Acropolis", "Athens", "Greece", "Classical", "Athena", "Pericles", "UNESCO"],
    "keyFacts": [
      "Contains virtually no straight lines; every surface is curved to correct optical illusions",
      "Columns lean inward so that if projected 2.4 km into the sky, they would meet at a single apex",
      "Housed Phidias’s 12-meter chryselephantine statue of Athena made of gold and ivory",
      "Survived intact for over 2,000 years until a Venetian artillery shell ignited gunpowder in 1687"
    ],
    "unescoStatus": "Inscribed 1987 (Criteria i, ii, iii, iv, vi)"
  },
  {
    "id": "sagrada-familia",
    "name": "Basílica de la Sagrada Família",
    "nativeOrAlternateName": "Basílica i Temple Expiatori de la Sagrada Família",
    "category": "Sacred Temple / Cathedral",
    "location": "Eixample, Barcelona, Catalonia",
    "country": "Spain",
    "region": "Europe",
    "era": "Modernisme & Contemporary Sacred Architecture (1882–Present)",
    "yearBuilt": "1882–Present (Targeted completion 2026)",
    "numericYear": 1882,
    "architectOrCreator": "Antoni Gaudí (Chief Architect 1883–1926); Francisco de Paula del Villar (Original planner)",
    "architecturalStyle": "Catalan Modernisme (Organic Gothic & Art Nouveau Fusion)",
    "dimensionsAndHeight": "Jesus Christ Tower height: 172.5 m (566 ft); Basilica footprint: 4,500 m²; Planned 18 towers",
    "materialsUsed": "Montjuïc sandstone, porphyry, basalt, granite, reinforced concrete, Venetian glass mosaics, trencadís ceramics",
    "historyAndBackground": "The Sagrada Família is the most famous unfinished monumental church on planet Earth. Construction began in March 1882 under architect Francisco de Paula del Villar. In 1883, 31-year-old visionary Catalan architect Antoni Gaudí took over the project, radically transforming the conventional neo-Gothic design into an organic forest of stone inspired by nature, geometry, and Christian scripture. Gaudí devoted the final 43 years of his life exclusively to the basilica, even moving his bed into the workshop. When asked about the slow pace of work, Gaudí famously replied, 'My client is not in a hurry.' In June 1926, Gaudí was struck by a streetcar in Barcelona and died days later; only one tower and the Nativity Facade were complete. During the Spanish Civil War in 1936, anarchists vandalized Gaudí's workshop, destroying his plaster architectural models and plans. Architects reconstructed his mathematical parametric designs from charred fragments. Funded entirely by private donations and ticket sales, construction has accelerated using 3D aeronautical CAD software, with the central Jesus Christ spire scheduled for completion around 2026, the centenary of Gaudí's death.",
    "architecturalMarvels": "Gaudí designed the interior nave to emulate a living sacred forest: branching inclined columns made of varying hard stones (porphyry, basalt, and granite) split like tree limbs to carry vaulted ceilings without flying buttresses. Double-twisted helicoidal columns and catenary arches distribute weight with astonishing organic efficiency. Stained-glass windows by Joan Vila-Grau flood the nave with glowing dawn cool blues and greens on the east and fiery twilight oranges and reds on the west. The exterior features three theological facades: the joyful, organic Nativity Facade (completed during Gaudí's life); the angular, stark Passion Facade (sculpted by Josep Maria Subirachs); and the monumental Glory Facade. Upon completion of the central Tower of Jesus Christ (172.5 m), it will become the tallest church building in the world—intentionally kept 1 meter shorter than Barcelona’s Montjuïc hill because Gaudí insisted 'man's work should never exceed God's work.'",
    "modernStatusAndSignificance": "The Nativity facade and crypt were inscribed as a UNESCO World Heritage Site in 1984 under 'Works of Antoni Gaudí'. Consecrated by Pope Benedict XVI as a minor basilica in November 2010. Welcomes over 4.7 million visitors annually as Barcelona's most recognizable cultural landmark.",
    "imageUrl": "https://images.unsplash.com/photo-1583422409516-2895a77efded?auto=format&fit=crop&q=80&w=1200",
    "fallbackImageUrl": "https://images.unsplash.com/photo-1523531294919-4bcd7c65e216?auto=format&fit=crop&q=80&w=1200",
    "tags": ["Sagrada Familia", "Barcelona", "Spain", "Gaudi", "Modernisme", "Cathedral", "UNESCO", "Architecture"],
    "keyFacts": [
      "Under continuous construction since 1882—longer than the Great Pyramid of Giza took to build",
      "Interior columns branch outward like trees to distribute weight without exterior flying buttresses",
      "Will become the tallest church in the world at 172.5 m, kept 1 meter shorter than Montjuïc hill",
      "Gaudí is buried in the crypt of the basilica he spent 43 years creating"
    ],
    "unescoStatus": "Inscribed 1984 (Works of Antoni Gaudí)"
  },
  {
    "id": "big-ben-westminster",
    "name": "Big Ben & Palace of Westminster",
    "nativeOrAlternateName": "Elizabeth Tower & Houses of Parliament",
    "category": "Famous Building",
    "location": "City of Westminster, London",
    "country": "United Kingdom",
    "region": "Europe",
    "era": "Victorian Era (1840–1859 CE)",
    "yearBuilt": "1840–1859 CE",
    "numericYear": 1859,
    "architectOrCreator": "Charles Barry & Augustus Pugin; Horologist Edmund Beckett Denison",
    "architecturalStyle": "Gothic Revival (Perpendicular Gothic Architecture)",
    "dimensionsAndHeight": "Elizabeth Tower height: 96 m (316 ft); 334 stone steps; Clock dial diameter: 7 m (23 ft); Bell weight: 13.7 tonnes",
    "materialsUsed": "Anston magnesium limestone, cast-iron framework, 312 pieces of pot opal glass in each clock face, bronze hands",
    "historyAndBackground": "The Palace of Westminster and its world-famous clock tower, officially named the Elizabeth Tower in 2012 for Queen Elizabeth II's Diamond Jubilee, is the seat of the Parliament of the United Kingdom. Following a catastrophic fire in October 1834 that destroyed the medieval royal palace, a public competition was held to design a replacement in the Gothic or Elizabethan style. Architect Charles Barry and Gothic prodigy Augustus Welby Pugin won the commission. While 'Big Ben' strictly refers to the 13.7-tonne Great Bell inside the belfry (likely named after Sir Benjamin Hall, First Commissioner of Works), the name is universally applied to the entire clock tower. Completed in 1859, the clock first ticked on May 31, 1859, and the Great Bell first chimed on July 11, 1859. The bells rang throughout the Blitz during World War II, broadcasting the sound of British defiance across the globe via the BBC World Service.",
    "architecturalMarvels": "Engineered by lawyer and amateur horologist Edmund Beckett Denison and crafted by clockmaker Edward John Dent, the Great Clock features the revolutionary 'Double Three-legged Gravity Escapement', which isolates the pendulum from external wind buffeting and snow load on the giant exterior hands, maintaining an incredible accuracy within one second per week. The clock's speed is calibrated using pre-decimal British copper pennies placed atop the pendulum: adding a single penny speeds the clock up by two-fifths of a second in 24 hours. The four clock dials contain 312 pieces of opalescent glass resembling stained-glass rose windows, inscribed in Latin at the base: 'DOMINE SALVAM FAC REGINAM NOSTRAM VICTORIAM PRIMAM' ('O Lord, keep safe our Queen Victoria the First').",
    "modernStatusAndSignificance": "Inscribed as a UNESCO World Heritage Site in 1987 alongside Westminster Abbey and Saint Margaret's Church. Following an extensive £80 million conservation project between 2017 and 2022 that restored the Prussian blue hands and limestone masonry, Big Ben remains the definitive global emblem of parliamentary democracy and British identity.",
    "imageUrl": "https://images.unsplash.com/photo-1529655683826-aba9b3e77383?auto=format&fit=crop&q=80&w=1200",
    "fallbackImageUrl": "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&q=80&w=1200",
    "tags": ["Big Ben", "London", "UK", "Westminster", "Elizabeth Tower", "Parliament", "Gothic Revival", "UNESCO"],
    "keyFacts": [
      "The name 'Big Ben' strictly belongs to the massive 13.7-tonne Great Bell hanging inside",
      "The speed of the clock pendulum is adjusted by placing old British penny coins on top",
      "The clock faces are cleaned by abseiling window washers suspended 60 meters in the air",
      "Broadcast live across the globe as the radio heartbeat of Britain throughout the WWII Blitz"
    ],
    "unescoStatus": "Inscribed 1987 (Criteria i, ii, iv)"
  },
  {
    "id": "notre-dame-paris",
    "name": "Cathédrale Notre-Dame de Paris",
    "nativeOrAlternateName": "Notre-Dame de Paris (Our Lady of Paris)",
    "category": "Sacred Temple / Cathedral",
    "location": "Île de la Cité, Paris",
    "country": "France",
    "region": "Europe",
    "era": "High Medieval Gothic Architecture (1163–1260 CE)",
    "yearBuilt": "1163–1260 CE (Restored by Viollet-le-Duc 1844–1864; Rebuilt 2019–2024)",
    "numericYear": 1250,
    "architectOrCreator": "Maurice de Sully (Bishop of Paris); Jean de Chelles & Pierre de Montreuil; Eugène Viollet-le-Duc",
    "architecturalStyle": "French Rayonnant High Gothic Architecture",
    "dimensionsAndHeight": "Spire height: 96 m (315 ft); Twin towers: 69 m (226 ft); Length: 128 m; Width: 48 m",
    "materialsUsed": "Lutetian limestone quarried beneath Paris, oak timber roof frame ('the forest'), lead roof sheathing, stained glass",
    "historyAndBackground": "Notre-Dame de Paris is the quintessential masterpiece of French Gothic architecture. Initiated in 1163 by Bishop Maurice de Sully on the historic Île de la Cité, the cathedral took nearly a century to construct. Over its 850-year history, it was the site of the coronation of Henry VI of England in 1431, the coronation of Napoleon Bonaparte as Emperor of the French in 1804, and the Te Deum celebrating the liberation of Paris in 1944. During the French Revolution, anti-clerical mobs decapitated the 28 statues of the Kings of Judah on the facade, mistaking them for French royalty. The cathedral fell into decrepitude until Victor Hugo's 1831 masterpiece 'The Hunchback of Notre-Dame' ignited public fervor, prompting architect Eugène Viollet-le-Duc's legendary 19th-century restoration that added the iconic lead spire and chimeras. On April 15, 2019, a catastrophic fire broke out in the timber roof, destroying the spire and wooden vault frame. An unprecedented international mobilization raised nearly €1 billion, enabling a triumphant restoration that reopened the cathedral in late 2024.",
    "architecturalMarvels": "Notre-Dame was among the earliest medieval buildings to employ external flying buttresses, engineered to support exceptionally high thin stone walls pierced by vast stained-glass windows. The western facade is a masterpiece of geometric proportion based on the Golden Ratio, featuring the 28 Kings of Judah, the Portal of the Last Judgment, and twin 69-meter bell towers. The cathedral houses three colossal stained-glass Rose Windows from the 13th century; the South Rose, measuring 12.9 meters across with 84 panes of glass depicting Christ and the Apostles, miraculously survived the 2019 inferno undamaged. It preserves the Holy Crown of Thorns, traditionally believed to have been placed on Jesus Christ's head.",
    "modernStatusAndSignificance": "Core of the UNESCO World Heritage Site 'Paris, Banks of the Seine' (1991). Symbol of French cultural tenacity, inspiring worldwide solidarity following the 2019 fire and its monumental rebuilding.",
    "imageUrl": "https://images.unsplash.com/photo-1549144511-f099e773c147?auto=format&fit=crop&q=80&w=1200",
    "fallbackImageUrl": "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&q=80&w=1200",
    "tags": ["Notre Dame", "Paris", "France", "Gothic", "Cathedral", "Rose Window", "UNESCO", "Architecture"],
    "keyFacts": [
      "Pioneered the structural use of exterior flying buttresses to support high Gothic stone walls",
      "The three magnificent 13th-century stained-glass Rose Windows survived the 2019 fire intact",
      "Housed 'The Forest', an 800-year-old timber roof frame built from 1,300 ancient oak trees",
      "Point Zero of French roads is embedded in the stone plaza outside the main entrance"
    ],
    "unescoStatus": "Inscribed 1991 (Banks of the Seine)"
  },
  {
    "id": "leaning-tower-pisa",
    "name": "Leaning Tower of Pisa",
    "nativeOrAlternateName": "Torre pendente di Pisa / Campanile del Duomo di Pisa",
    "category": "Monument & Tower",
    "location": "Piazza dei Miracoli, Pisa, Tuscany",
    "country": "Italy",
    "region": "Europe",
    "era": "Medieval Romanesque Architecture (1173–1372 CE)",
    "yearBuilt": "1173–1372 CE (Built over 199 years in 3 stages)",
    "numericYear": 1372,
    "architectOrCreator": "Bonanno Pisano & Gherardo di Gherardo; Giovanni di Simone; Completed by Tommaso di Andrea Pisano",
    "architecturalStyle": "Pisan Romanesque Architecture (Arcaded Bell Tower)",
    "dimensionsAndHeight": "Height: 56.67 m (185.9 ft) on high side, 55.86 m on low side; Tilt: 3.97 degrees (3.9 m off vertical); Weight: 14,500 tonnes",
    "materialsUsed": "White and grey Carrara marble, San Giuliano limestone, mortar rubble core",
    "historyAndBackground": "The Leaning Tower of Pisa is the freestanding bell tower (campanile) of the Pisa Cathedral on the Piazza dei Miracoli (Field of Miracles). Construction began in August 1173 during a period of naval and military triumphs for the Republic of Pisa. When workers reached the third tier in 1178, the tower began to sink and tilt visibly to the south due to a deficient three-meter foundation set into weak, unstable alluvial silt, clay, and sand. Construction halted for nearly a century due to wars with Genoa and Florence, which inadvertently saved the tower: the century-long delay allowed the underlying soil to consolidate and compress under the immense weight. In 1272, Giovanni di Simone resumed construction, building subsequent floors taller on one side to compensate for the tilt, resulting in the tower’s subtle banana-like curve. The bell chamber was finally completed in 1372. Galileo Galilei, native to Pisa, is traditionally said to have dropped two cannonballs of different masses from the top of the tower to disprove Aristotle's theory of gravity.",
    "architecturalMarvels": "The tower consists of eight stories of Romanesque open marble arcades. By 1990, the tilt had reached a critical 5.5 degrees, putting the structure on the verge of catastrophic collapse. In a landmark 11-year stabilization effort led by structural engineer Michele Jamiolkowski, engineers removed 38 cubic meters of soil from beneath the northern high side using angled drill tubes and anchored the base with 800 tonnes of lead counterweights. This safely reduced the tilt to 3.97 degrees (straightening the summit by 45 cm) and stabilized the foundation for at least the next 300 years.",
    "modernStatusAndSignificance": "Inscribed as a UNESCO World Heritage Site in 1987 as part of the Piazza del Duomo, praised for its extraordinary artistic unity. Welcomes millions of tourists eager to take perspective photos appearing to hold up the leaning marble column.",
    "imageUrl": "https://images.unsplash.com/photo-1543429776-2782fc8e1acd?auto=format&fit=crop&q=80&w=1200",
    "fallbackImageUrl": "https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?auto=format&fit=crop&q=80&w=1200",
    "tags": ["Tower of Pisa", "Pisa", "Italy", "Leaning Tower", "Piazza dei Miracoli", "Romanesque", "UNESCO"],
    "keyFacts": [
      "Began leaning during construction of the third floor due to unstable, clay-rich alluvial soil",
      "Took nearly 200 years to build because wars delayed construction, allowing the soil to settle",
      "The tower is curved like a banana because later builders made columns taller on one side to fix the lean",
      "Galileo Galilei dropped two cannonballs of different weights from its top to test gravity"
    ],
    "unescoStatus": "Inscribed 1987 (Criteria i, ii, iv, vi)"
  },
  {
    "id": "saint-basils-cathedral",
    "name": "Saint Basil's Cathedral",
    "nativeOrAlternateName": "Покровский собор (Cathedral of the Intercession of the Virgin by the Moat)",
    "category": "Sacred Temple / Cathedral",
    "location": "Red Square, Moscow",
    "country": "Russia",
    "region": "Europe",
    "era": "Tsardom of Russia (1555–1561 CE)",
    "yearBuilt": "1555–1561 CE",
    "numericYear": 1561,
    "architectOrCreator": "Master Architects Barma and Postnik Yakovlev; Commissioned by Tsar Ivan IV 'the Terrible'",
    "architecturalStyle": "Traditional Russian Tent-Roof & Onion Dome Eclectic Architecture",
    "dimensionsAndHeight": "Height: 47.5 m (156 ft); Composed of 9 distinct interconnecting chapels; Brick construction",
    "materialsUsed": "Red brick, white limestone foundation blocks, patterned copper roof sheets, polychrome mineral enamels",
    "historyAndBackground": "Saint Basil's Cathedral, standing at the geometric heart of Moscow on Red Square, was commissioned by Tsar Ivan IV ('Ivan the Terrible') in 1555 to celebrate the capture of the Tatar stronghold of Kazan on the feast of the Intercession of the Virgin. Formally consecrated on July 12, 1561. Officially dedicated to the Intercession of the Theotokos, it became universally known as Saint Basil’s after the beloved Moscow 'holy fool' Basil the Blessed, who was buried in a tenth chapel added to the complex in 1588. A dark Russian legend claims that Ivan the Terrible was so dazzled by the cathedral's fairy-tale beauty that he ordered architects Barma and Postnik blinded so they could never build anything comparable, though historical records disprove this as Postnik later worked on the Kremlin walls in Kazan. The cathedral survived Napoleon’s 1812 retreat from Moscow (when French sappers were ordered to blow it up, but torrential rain extinguished the fuses) and escaped demolition under Joseph Stalin, who considered tearing it down to widen Red Square for military parades until architect Pyotr Baranovsky heroically threatened suicide to protect it.",
    "architecturalMarvels": "The cathedral has no precedent in Russian medieval architecture. It is designed as a central tent-roofed church surrounded by eight independently dedicated chapels arranged symmetrically around the center to form an eight-pointed star—a symbol of the Virgin Mary and the New Jerusalem. Each of the eight surrounding chapels is capped with a wildly distinct, vividly colored onion dome featuring unique embossed patterns: spiraling flame ridges, diamond facets, pineapple scales, and zigzags in cobalt blue, emerald green, saffron yellow, and crimson red. These dazzling polychrome colors and tin onion domes were added in the late 17th and 18th centuries, replacing original white and gilded finishes.",
    "modernStatusAndSignificance": "Inscribed as a UNESCO World Heritage Site in 1990 as part of the 'Kremlin and Red Square'. It stands as the quintessential visual symbol of Russia and its spiritual heritage.",
    "imageUrl": "https://images.unsplash.com/photo-1513326738677-b964603b136d?auto=format&fit=crop&q=80&w=1200",
    "fallbackImageUrl": "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&q=80&w=1200",
    "tags": ["Saint Basils", "Moscow", "Russia", "Red Square", "Onion Domes", "Ivan the Terrible", "UNESCO"],
    "keyFacts": [
      "Composed of nine individual churches grouped harmoniously on a single foundation",
      "Every onion dome features completely unique geometric patterns, textures, and color spirals",
      "Saved from demolition in 1930s Moscow when architect Pyotr Baranovsky defied Stalin",
      "Napoleon ordered the cathedral blown up in 1812, but sudden rain extinguished the gunpowder fuses"
    ],
    "unescoStatus": "Inscribed 1990 (Kremlin and Red Square)"
  },
  {
    "id": "st-peters-basilica",
    "name": "St. Peter's Basilica",
    "nativeOrAlternateName": "Basilica Papale di San Pietro in Vaticano",
    "category": "Sacred Temple / Cathedral",
    "location": "Vatican City, Rome",
    "country": "Vatican City",
    "region": "Europe",
    "era": "Renaissance to Baroque Era (1506–1626 CE)",
    "yearBuilt": "1506–1626 CE",
    "numericYear": 1626,
    "architectOrCreator": "Donato Bramante, Michelangelo Buonarroti, Carlo Maderno, Gian Lorenzo Bernini",
    "architecturalStyle": "High Renaissance & Roman Baroque Architecture",
    "dimensionsAndHeight": "Dome height: 136.6 m (448 ft); Interior length: 220 m (720 ft); Floor area: 23,000 m²; Capacity: 60,000 people",
    "materialsUsed": "Travertine marble quarried from Tivoli, white Carrara marble, gilded bronze, antique Roman columns",
    "historyAndBackground": "St. Peter's Basilica is the grandest church in Christendom and the principal shrine of the Roman Catholic Church. Constructed atop Vatican Hill above the traditional tomb of Saint Peter, one of the Twelve Apostles and first Bishop of Rome, who was crucified upside-down nearby in Nero's Circus around 64 CE. In the 4th century, Emperor Constantine built Old St. Peter’s Basilica, which stood for over a millennium. By 1505, Pope Julius II decided to demolish the crumbling ancient basilica and build the greatest temple in the Christian world. Over 120 years, the greatest artistic geniuses of the Italian Renaissance and Baroque served as chief architects: Bramante designed the original Greek-cross plan; Raphael contributed redesigns; Michelangelo took over in 1547 at age 71 and engineered the soaring dome; Carlo Maderno elongated the nave into a Latin cross and built the grand facade; and Gian Lorenzo Bernini designed the four-tiered bronze Baldacchino and the monumental St. Peter’s Square with its welcoming colonnades.",
    "architecturalMarvels": "The dome of St. Peter's is the tallest dome in the world, rising 136.6 meters from the marble floor. Its internal diameter of 41.5 meters is slightly smaller than the Pantheon, but Michelangelo designed a double-shell dome reinforced with five iron tension chains to prevent cracking. Inside, every seemingly painted artwork is actually a microscopic glass mosaic tessera, crafted by the Vatican Mosaic Studio so moisture would never degrade the colors. Beneath the dome stands Bernini's 29-meter-tall bronze Baldacchino, cast from bronze stripped from the Pantheon's portico. Near the entrance sits Michelangelo's peerless 'Pietà', sculpted from a single block of Carrara marble when the master was only 24 years old—the only work he ever signed.",
    "modernStatusAndSignificance": "Core of the UNESCO World Heritage Site 'Vatican City' (1984). It is the ceremonial epicenter of the global Catholic Church, hosting papal liturgies, canonizations, and the Urbi et Orbi blessings.",
    "imageUrl": "https://images.unsplash.com/photo-1542820229-081e0c12af0b?auto=format&fit=crop&q=80&w=1200",
    "fallbackImageUrl": "https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&q=80&w=1200",
    "tags": ["St Peters", "Vatican", "Rome", "Michelangelo", "Bernini", "Renaissance", "Baroque", "UNESCO"],
    "keyFacts": [
      "The tallest dome on Earth, engineered by Michelangelo when he was 71 years old",
      "Almost all interior paintings are actually microscopic, moisture-proof glass mosaics",
      "Houses Michelangelo's 'Pietà', the only sculpture the master artist ever signed",
      "Built directly above the historic 1st-century tomb of Saint Peter the Apostle"
    ],
    "unescoStatus": "Inscribed 1984 (Vatican City)"
  },
  {
    "id": "alhambra-palace",
    "name": "The Alhambra & Generalife",
    "nativeOrAlternateName": "قصر الحمراء (The Red Castle) / Al-Qal'a al-Hamra",
    "category": "Palace & Fortress",
    "location": "Granada, Andalusia",
    "country": "Spain",
    "region": "Europe",
    "era": "Nasrid Dynasty of Al-Andalus (1238–1492 CE)",
    "yearBuilt": "1238–1358 CE",
    "numericYear": 1358,
    "architectOrCreator": "Muhammad I ibn Nasr (Founder); Yusuf I and Muhammad V (Palace builders)",
    "architecturalStyle": "Moorish Islamic Nasrid Architecture (Arabesque Stucco, Sebka Lattice)",
    "dimensionsAndHeight": "Complex length: 740 m (2,430 ft); Area: 142,000 m² (35 acres); 30 towers",
    "materialsUsed": "Rammed red clay earth (tapia), carved plaster stucco, cedar wood ceiling joinery, glazed ceramic zillij tiles",
    "historyAndBackground": "The Alhambra is the finest surviving palace-citadel of Islamic Spain (Al-Andalus) and one of the crowning achievements of medieval architecture. Perched on Sabika Hill against the snow-capped Sierra Nevada mountains, it was begun in 1238 by Muhammad I ibn Nasr, founder of the Nasrid Emirate of Granada. Over the 14th century, Sultans Yusuf I and Muhammad V transformed the military fortress into an earthly paradise of palatial courtyards, reflecting pools, and fragrant gardens. The Alhambra was the last bastion of Islamic rule in Western Europe until January 2, 1492, when the last Nasrid Sultan, Muhammad XII (Boabdil), surrendered the keys of Granada to the Catholic Monarchs, Ferdinand and Isabella, bringing an end to the 780-year Reconquista. It was in the Alhambra that Christopher Columbus received royal authorization and funding from Queen Isabella for his historic 1492 voyage to the Americas.",
    "architecturalMarvels": "The palace is famed for its sublime integration of water, light, and geometry. The Court of the Lions (Patio de los Leones) centers upon a marble fountain supported by twelve sculpted lions, surrounded by an arcade of 124 slender white marble columns with filigree capitals. The ceilings feature breathtaking 'muqarnas' (honeycomb or stalactite vaulting); the Hall of the Two Sisters contains a dome of 5,416 individual plaster cells that evoke the celestial sphere of heaven. Wall bases are lined with colorful zillij ceramic tile mosaics displaying complex mathematical symmetry groups (all 17 two-dimensional wallpaper symmetry groups are present in Alhambra tiles). Arabic poetic calligraphy is carved into almost every wall, repeating the famous Nasrid motto: 'Wa la ghaliba illa Allah' ('There is no conqueror but God').",
    "modernStatusAndSignificance": "Designated a UNESCO World Heritage Site in 1984 along with the Generalife summer palace and the Albayzín quarter. Welcomes over 2.7 million visitors annually as Spain’s most visited historical monument.",
    "imageUrl": "https://images.unsplash.com/photo-1568084680786-a84f91d1153c?auto=format&fit=crop&q=80&w=1200",
    "fallbackImageUrl": "https://images.unsplash.com/photo-1523531294919-4bcd7c65e216?auto=format&fit=crop&q=80&w=1200",
    "tags": ["Alhambra", "Granada", "Spain", "Moorish", "Andalusia", "Nasrid", "UNESCO", "Palace"],
    "keyFacts": [
      "The last sovereign Islamic palace of Al-Andalus, surrendered in 1492",
      "Christopher Columbus received royal backing from Queen Isabella inside its halls in 1492",
      "The Court of the Lions features a central fountain resting on 12 carved marble lions",
      "Its tile work contains all 17 mathematical wallpaper symmetry groups discovered by science"
    ],
    "unescoStatus": "Inscribed 1984 (Criteria i, iii, iv)"
  }
]

print(f"Europe base items count: {len(items)}")
