#!/usr/bin/env python3
"""
Builds all 60 European Monuments into src/data/monuments/europeanMonuments.ts
"""
import json

def item(id, name, native, cat, loc, country, era, yr_str, yr_num, arch, style, dim, mat, hist, marv, mod, img, tags, facts, unesco="World Heritage Landmark"):
    return {
        "id": id,
        "name": name,
        "nativeOrAlternateName": native,
        "category": cat,
        "location": loc,
        "country": country,
        "region": "Europe",
        "era": era,
        "yearBuilt": yr_str,
        "numericYear": yr_num,
        "architectOrCreator": arch,
        "architecturalStyle": style,
        "dimensionsAndHeight": dim,
        "materialsUsed": mat,
        "historyAndBackground": hist,
        "architecturalMarvels": marv,
        "modernStatusAndSignificance": mod,
        "imageUrl": img,
        "fallbackImageUrl": "https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?auto=format&fit=crop&q=80&w=1200",
        "tags": tags,
        "keyFacts": facts,
        "unescoStatus": unesco
    }

europe_data = [
  # 1. Eiffel Tower
  item("eiffel-tower", "Eiffel Tower", "Tour Eiffel (La Dame de Fer)", "Monument & Tower", "Champ de Mars, Paris", "France",
    "Belle Époque Industrial Revolution (1887–1889 CE)", "1887–1889 CE", 1889, "Gustave Eiffel (Engineers: Maurice Koechlin, Émile Nouguier; Architect: Stephen Sauvestre)",
    "Puddle-Iron Wrought Lattice Tower Engineering", "Height: 330 m (1,083 ft); Base width: 125 m; Weight: 10,100 tonnes; 7,300 tonnes iron framework",
    "High-purity puddle iron (fer puddlé) from Pompey forges in Lorraine, 2.5 million rivets, Venetian red to bronze paint",
    "The Eiffel Tower is the globally recognized symbol of Paris and France. Constructed between 1887 and 1889 as the grand entrance arch to the 1889 Exposition Universelle (World's Fair), celebrating the centennial of the French Revolution. Initially received with fierce opposition from Paris's artistic elite who called it a 'gigantic black smokestack'. Gustave Eiffel preserved it by proving its strategic utility for radio telegraphy, which later intercepted German military transmissions during the First World War.",
    "Engineered with mathematical brilliance to resolve wind pressure directly into the foundations. Thermal expansion causes the iron structure to grow up to 15 centimeters (6 inches) taller during peak summer heat and lean away from the sun. Repainted by hand every seven years with 60 tonnes of paint in three gradated shades to ensure a uniform silhouette against the sky.",
    "Inscribed as a UNESCO World Heritage Site in 1991 as part of 'Paris, Banks of the Seine'. Welcomes nearly 7 million visitors annually, the most visited paid monument in the world.",
    "https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?auto=format&fit=crop&q=80&w=1200",
    ["Eiffel Tower", "Paris", "France", "Gustave Eiffel", "UNESCO", "Iron Lady"],
    ["Built for the 1889 World's Fair to celebrate the French Revolution centennial", "Grows up to 15 cm taller in summer due to thermal expansion of the puddle iron", "Held the title of world's tallest human-made structure for 41 years until 1930", "Saved from demolition because its height proved vital for military radio telegraphy"],
    "Inscribed 1991 (Paris, Banks of the Seine)"),

  # 2. Colosseum
  item("colosseum-rome", "The Colosseum (Flavian Amphitheatre)", "Amphitheatrum Flavium / Colosseo", "Ancient Wonder", "Piazza del Colosseo, Rome", "Italy",
    "Imperial Roman Flavian Dynasty (70–80 CE)", "70–80 CE", 80, "Emperors Vespasian and Titus",
    "Classical Imperial Roman Amphitheatre & Arcaded Vaulting", "Outer perimeter: 527 m (1,729 ft); Height: 48.5 m; Capacity: 50,000–80,000 spectators",
    "100,000 m³ of travertine limestone, volcanic tuff, Roman pozzolana concrete, 300 tonnes of iron clamps",
    "The Colosseum is the largest ancient amphitheatre ever built. Commissioned by Emperor Vespasian in 70 CE on the site of Nero's Golden House artificial lake, returning imperial land to Roman citizens. Inaugurated in 80 CE by his son Titus with 100 consecutive days of gladiatorial combats, wild beast hunts, and mock sea battles with a flooded arena. Stood as Rome's entertainment center for over four centuries.",
    "Features four tiers of superimposed classical orders (Tuscan, Ionic, Corinthian). An ingenious system of 80 numbered arched vomitoria exits allowed 50,000 spectators to exit within eight minutes. Beneath the arena floor lay the subterranean Hypogeum: a two-level network of cages and 30 pulley-operated vertical trapdoor elevators that raised lions and gladiators directly onto the arena sand.",
    "Designated a UNESCO World Heritage Site in 1980 and voted one of the New 7 Wonders of the World in 2007. The defining icon of ancient Roman imperial engineering.",
    "https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&q=80&w=1200",
    ["Colosseum", "Rome", "Italy", "Flavian", "Gladiators", "UNESCO", "Wonder of the World"],
    ["The largest ancient amphitheater ever constructed, holding over 50,000 spectators", "Could be evacuated in under eight minutes through 80 numbered arched exit gates", "Subterranean Hypogeum featured 30 mechanical trapdoor lifts for wild beasts", "Inaugurated in 80 CE with 100 days of gladiatorial combats and mock naval battles"],
    "Inscribed 1980 (Historic Centre of Rome)"),

  # 3. Parthenon
  item("parthenon-athens", "Parthenon & Acropolis of Athens", "Παρθενών (Parthenōn)", "Ancient Wonder", "Acropolis Rock, Athens", "Greece",
    "Classical Greece Golden Age of Pericles (447–432 BCE)", "447–432 BCE", -447, "Iktinos & Kallikrates (Architects), Phidias (Chief Sculptor)",
    "Classical Greek High Doric Peripteral Temple Architecture", "Base dimensions: 69.5 × 30.9 m; Column height: 10.4 m; 46 outer Doric columns",
    "Pentelic white marble from Mount Pentelikus, Parian marble sculptures, bronze pins",
    "The Parthenon is the supreme architectural masterpiece of classical Greek civilization, standing atop the Acropolis overlooking Athens. Built between 447 and 432 BCE under Pericles. Dedicated to Athena Parthenos, the patron warrior goddess of Athens. It enshrined the monumental 12-meter-tall gold-and-ivory statue of Athena sculpted by Phidias, which was clad in 1,100 kg of pure gold.",
    "Renowned for optical refinements correcting human visual distortion: there is not a single straight line in the building! The marble floor is slightly convex, rising 6.5 cm in the center, and the columns swell slightly (entasis) while tilting inward at an angle such that they would meet 2.4 km above the ground if extended skyward.",
    "Inscribed as a UNESCO World Heritage Site in 1987. The universal symbol of Western democracy, classical philosophy, and architectural harmony.",
    "https://images.unsplash.com/photo-1555993539-1732b0258235?auto=format&fit=crop&q=80&w=1200",
    ["Parthenon", "Acropolis", "Athens", "Greece", "Classical", "Athena", "UNESCO"],
    ["Contains no straight lines—every column, step, and lintel is subtly curved for optical balance", "Columns tilt inward: if projected skyward, they would meet 2.4 kilometers in the sky", "Enshrined Phidias's 12-meter chryselephantine statue of Athena clad in 1,100 kg of gold", "Served as a Greek temple, Christian basilica, Catholic cathedral, and Ottoman mosque"],
    "Inscribed 1987 (Acropolis, Athens)"),

  # 4. Notre-Dame de Paris
  item("notre-dame-paris", "Notre-Dame de Paris", "Cathédrale Notre-Dame de Paris", "Sacred Temple / Cathedral", "Île de la Cité, Paris", "France",
    "French High Gothic Golden Age (1163–1345 CE)", "1163–1345 CE", 1163, "Maurice de Sully, Jean de Chelles, Pierre de Montreuil, Eugène Viollet-le-Duc",
    "French Rayonnant High Gothic Cathedral Architecture", "Length: 128 m; Width: 48 m; Twin towers height: 69 m; Spire: 96 m; South Rose diameter: 13 m",
    "Lutetian limestone quarried from Parisian catacombs, oak timber framework, stained glass",
    "Notre-Dame de Paris is the quintessential French Gothic cathedral, situated on the Île de la Cité in Paris. Begun in 1163 under Bishop Maurice de Sully and completed in 1345. Site of Napoleon Bonaparte's imperial coronation in 1804 and the Liberation Te Deum in 1944. Immortally celebrated in Victor Hugo's 1831 novel 'The Hunchback of Notre-Dame'. Following the fire of April 15, 2019, an unprecedented restoration rebuilt the timber frame and spire using authentic medieval techniques.",
    "Pioneered the widespread use of external flying buttresses to support soaring, thin stone walls filled with glowing stained-glass rose windows. The 13-meter South Rose Window contains original 13th-century stained glass with scenes of the New Testament.",
    "Inscribed as a UNESCO World Heritage Site in 1991. The geographic 'Point Zero' from which all road distances in France are calculated.",
    "https://images.unsplash.com/photo-1543349689-9a4d426bee8e?auto=format&fit=crop&q=80&w=1200",
    ["Notre-Dame", "Paris", "France", "Gothic", "Cathedral", "UNESCO", "Rose Window"],
    ["Pioneered the use of external flying buttresses supporting thin stone walls", "The South Rose Window contains original 13th-century stained glass 13 meters across", "Napoleon Bonaparte was crowned Emperor of the French here in December 1804", "Marks 'Point Zero', the geographic center from which all French road distances are measured"],
    "Inscribed 1991 (Paris, Banks of the Seine)"),

  # 5. Sagrada Família
  item("sagrada-familia", "Basílica de la Sagrada Família", "Temple Expiatori de la Sagrada Família", "Sacred Temple / Cathedral", "Barcelona, Catalonia", "Spain",
    "Modernisme / Catalan Art Nouveau (1882–Present CE)", "1882–Present (Targeting 2026)", 1882, "Antoni Gaudí (Chief Architect 1883–1926), Jordi Faulí",
    "Catalan Modernisme Biomimetic Gothic Architecture", "Tower of Jesus height: 172.5 m (566 ft); Nave height: 45 m; 18 spires planned",
    "Montjuïc sandstone, Galician granite, ultra-dense porphyry and basalt columns, Venetian mosaics",
    "The Basílica de la Sagrada Família is the magnum opus of architect Antoni Gaudí. Construction began in 1882, and Gaudí took over in 1883, dedicating his final 43 years to the church until his death in 1926. Financed entirely by ticket sales and private donations as an expiatory temple. Scheduled for final completion around 2026, the centenary of Gaudí's death.",
    "The nave is designed as a stone forest with branching tree columns of porphyry and basalt carrying the vaults without external flying buttresses. Stained glass windows cast morning blues and greens on the east and evening oranges and reds on the west. At 172.5 meters, its central spire will make it the tallest church in the world—intentionally one meter lower than Montjuïc hill so human work would not exceed God's creation.",
    "Inscribed as a UNESCO World Heritage Site in 2005. The most visited monument in Spain and an international benchmark of biomimetic design.",
    "https://images.unsplash.com/photo-1583772654844-4b45508a8a6a?auto=format&fit=crop&q=80&w=1200",
    ["Sagrada Familia", "Barcelona", "Spain", "Antoni Gaudi", "Modernisme", "UNESCO", "Cathedral"],
    ["Under construction continuously for over 140 years, financed entirely by donations", "Designed like an organic stone forest with tree-like branching columns carrying vaults", "At 172.5 meters, its central spire will make it the tallest church on Earth", "Gaudí designed it one meter lower than Montjuïc hill out of respect for nature"],
    "Inscribed 2005 (Works of Antoni Gaudí)"),

  # 6. Saint Basil's Cathedral
  item("saint-basils-cathedral", "Saint Basil's Cathedral", "Храм Василия Блаженного (Pokrovsky Cathedral)", "Sacred Temple / Cathedral", "Red Square, Moscow", "Russia",
    "Tsardom of Russia Golden Age (1555–1561 CE)", "1555–1561 CE", 1555, "Postnik Yakovlev and Ivan Barma, commissioned by Tsar Ivan the Terrible",
    "Russian Medieval Tent-Roofed & Onion-Domed Architecture", "Height: 47.5 m (156 ft); Central tent tower: 46 m; 9 chapels clustered on brick base",
    "Red brick, white limestone foundations, polychrome ceramic glazed tiles, beaten sheet metal onion domes",
    "Saint Basil's Cathedral stands at the southern end of Moscow's Red Square. Commissioned by Tsar Ivan IV ('Ivan the Terrible') in 1555 to celebrate the Russian capture of the Tatar khanates of Kazan and Astrakhan. Dedicated to the Intercession of the Virgin, but popularly named after Saint Basil the Blessed, whose tomb lies inside. Survived demolition threats by Napoleon in 1812 and Joseph Stalin in the 1930s.",
    "Composed of eight independent chapels arranged symmetrically around a central 46-meter tent-roofed core church, with each chapel crowned by a uniquely patterned, brilliantly colored onion dome. No two domes share the same pattern: spirals, rhombuses, and zigzags gleam in red, green, blue, and gold.",
    "Inscribed as a UNESCO World Heritage Site in 1990 as part of 'Kremlin and Red Square, Moscow'. The preeminent cultural icon of Russia.",
    "https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?auto=format&fit=crop&q=80&w=1200",
    ["Saint Basils", "Moscow", "Russia", "Red Square", "Ivan the Terrible", "UNESCO", "Onion Domes"],
    ["Built by Tsar Ivan the Terrible to celebrate the capture of Kazan in 1552", "Composed of nine distinct chapels, each crowned by a uniquely patterned onion dome", "The legend that Ivan blinded the architects is a myth—Postnik later worked in Kazan", "Survived demolition orders by both Napoleon in 1812 and Stalin in the 1930s"],
    "Inscribed 1990 (Kremlin and Red Square)"),

  # 7. Leaning Tower of Pisa
  item("leaning-tower-pisa", "Leaning Tower of Pisa", "Torre pendente di Pisa", "Monument & Tower", "Piazza dei Miracoli, Pisa, Tuscany", "Italy",
    "Medieval Maritime Republic of Pisa (1173–1372 CE)", "1173–1372 CE", 1173, "Bonanno Pisano, Giovanni di Simone, Tommaso Pisano",
    "Pisan Romanesque Arcaded Bell Tower Architecture", "Height: 55.86 m (low side) / 56.67 m (high side); 8 storeys; Lean: 3.97 degrees; Weight: 14,500 tonnes",
    "White and grey San Giuliano breccia marble, Carrara marble columns, rubble core",
    "The Leaning Tower of Pisa is the freestanding bell tower of Pisa Cathedral. Construction began in 1173, but the tower began to tilt during work on the second floor in 1178 due to a three-meter foundation laid in soft alluvial clay and sand. Century-long delays due to wars allowed the soil to compress, preventing collapse. Galileo Galilei dropped cannonballs from the galleries around 1589 to prove acceleration of gravity is independent of mass.",
    "To compensate for the tilt during construction, architects built upper floors taller on one side, giving the tower a subtle curved banana shape. Stabilized between 1990 and 2001 by removing 70 tonnes of soil beneath the high northern side, reducing the tilt to 3.97 degrees and ensuring stability for centuries.",
    "Inscribed as a UNESCO World Heritage Site in 1987 as part of Piazza del Duomo, Pisa. One of the world's most recognizable architectural landmarks.",
    "https://images.unsplash.com/photo-1543429776-2782fc8e1acd?auto=format&fit=crop&q=80&w=1200",
    ["Tower of Pisa", "Pisa", "Italy", "Tuscany", "Leaning Tower", "Galileo", "UNESCO"],
    ["Began leaning during construction of the second floor in 1178 due to weak subsoil", "A century-long construction pause allowed the soil to settle and saved it from collapse", "Galileo dropped cannonballs from its top to test gravitational acceleration laws", "Stabilized in 2001 by removing 70 tonnes of soil from the high side, fixing 44 cm of lean"],
    "Inscribed 1987 (Piazza del Duomo, Pisa)"),

  # 8. Big Ben & Westminster
  item("big-ben-westminster", "Big Ben & Palace of Westminster", "Elizabeth Tower & Houses of Parliament", "Famous Building", "Westminster, London", "United Kingdom",
    "British Victorian Gothic Revival (1840–1859 CE)", "1840–1859 CE", 1859, "Charles Barry & Augustus Pugin",
    "Perpendicular Gothic Revival Architecture", "Elizabeth Tower height: 96 m (316 ft); Clock dial diameter: 7 m; Great Bell: 13.7 metric tonnes",
    "Anston magnesium limestone, Clipsham stone, cast-iron roofing tiles, opal glass dials",
    "The Palace of Westminster is the seat of the Parliament of the United Kingdom. Following the 1834 fire that destroyed the medieval palace, Charles Barry and Augustus Pugin designed the Perpendicular Gothic Revival masterpiece. Elizabeth Tower, universally known as Big Ben, houses the colossal 13.7-tonne Great Bell cast at Whitechapel Bell Foundry.",
    "The Great Clock uses Denison's double three-legged gravity escapement to isolate pendulum movement from wind forces on the huge hands. Fine timekeeping calibration is done by placing pre-decimal British pennies on the pendulum: adding one penny speeds the clock by 0.4 seconds per day.",
    "Inscribed as a UNESCO World Heritage Site in 1987. The preeminent architectural symbol of parliamentary democracy.",
    "https://images.unsplash.com/photo-1529655683826-aba9b3e77383?auto=format&fit=crop&q=80&w=1200",
    ["Big Ben", "London", "UK", "Westminster", "Parliament", "UNESCO", "Gothic Revival"],
    ["'Big Ben' strictly refers to the 13.7-tonne Great Bell inside the 96-meter Elizabeth Tower", "The clock's accuracy is calibrated by placing or removing pre-decimal British copper pennies", "The four 7-meter clock faces are composed of 312 individual pieces of opal glass", "Rebuilt in magnificent Perpendicular Gothic style after the devastating fire of 1834"],
    "Inscribed 1987 (Westminster Palace and Abbey)"),

  # 9. Stonehenge
  item("stonehenge", "Stonehenge", "Stonehenge Megalithic Monument", "Ancient Wonder", "Salisbury Plain, Wiltshire", "United Kingdom",
    "Neolithic to Early Bronze Age (c. 3000–1500 BCE)", "c. 3000–2000 BCE", -2500, "Neolithic British agrarian cultures & Bell Beaker people",
    "Prehistoric Megalithic Post-and-Lintel Circle Architecture", "Outer circle diameter: 33 m (108 ft); Sarsen height: up to 9 m; Sarsen weight: up to 30 tonnes",
    "Marlborough Downs sarsen stones, Preseli Hills bluestones from Wales (240 km away)",
    "Stonehenge is a prehistoric megalithic monument on Salisbury Plain in Wiltshire, England. Constructed in phases between 3000 BCE and 1500 BCE. Its earliest phase was a circular henge earthwork ditch with 56 Aubrey holes used for cremated human burials. Around 2500 BCE, builders erected the central ring of sarsen stone trilithons and inner horseshoe.",
    "Aligned with celestial precision: the central axis points directly to the summer solstice sunrise and winter solstice sunset. The smaller bluestones (weighing 2 to 4 tonnes) were transported over 240 kilometers from the Preseli Hills in southwest Wales. Stones are joined with carpentry-style mortise-and-tenon joints and tongue-and-groove lintels.",
    "Inscribed as a UNESCO World Heritage Site in 1986. Celebrated as the world's most architecturally sophisticated prehistoric stone circle.",
    "https://images.unsplash.com/photo-1599833975787-5c143f373c30?auto=format&fit=crop&q=80&w=1200",
    ["Stonehenge", "England", "UK", "Megalith", "Neolithic", "UNESCO", "Solstice"],
    ["Built between 3000 BCE and 2000 BCE, long predating classical Greece and Rome", "The bluestones were transported over 240 km from the Preseli Hills in Wales", "Aligned precisely to frame the summer solstice sunrise and winter solstice sunset", "Joined using woodworking mortise-and-tenon joints adapted into solid megalithic stone"],
    "Inscribed 1986 (Stonehenge, Avebury and Associated Sites)"),

  # 10. Palace of Versailles
  item("palace-of-versailles", "Palace of Versailles", "Château de Versailles", "Palace & Fortress", "Versailles, Île-de-France", "France",
    "French Baroque & Classical Ancien Régime (1661–1715 CE)", "1661–1715 CE", 1682, "Louis Le Vau, Jules Hardouin-Mansart, André Le Nôtre (Gardens), Charles Le Brun",
    "French Classical Baroque Architecture (Style Louis XIV)", "Facade length: 670 m; 2,300 rooms; Area: 63,154 m²; Gardens area: 800 hectares (2,000 acres)",
    "Cut ashlar limestone, gilded bronze fittings, French mirrors, Pyrenean marble",
    "The Palace of Versailles was the principal royal residence of France from 1682 under Louis XIV (the 'Sun King') until the French Revolution in 1789. Louis XIV transformed a modest hunting lodge into the grandest palace in Europe to centralize power and keep the French nobility under his watchful gaze, moving the court here in 1682.",
    "Contains the 73-meter Galerie des Glaces (Hall of Mirrors), featuring 17 arched windows overlooking formal gardens mirrored opposite by 357 massive mirrors. André Le Nôtre designed 800 hectares of geometric French formal gardens with 600 fountain water jets. In 1871, the German Empire was proclaimed here, and in 1919, the Treaty of Versailles was signed here to end World War I.",
    "Inscribed as a UNESCO World Heritage Site in 1979. The supreme monument of royal absolutism and European classical decorative art.",
    "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&q=80&w=1200",
    ["Versailles", "France", "Louis XIV", "Sun King", "Hall of Mirrors", "Baroque", "UNESCO"],
    ["Transformed by Louis XIV from a hunting lodge into Europe's grandest royal palace", "The Hall of Mirrors contains 357 mirrors opposite 17 arched windows overlooking gardens", "Encompasses 800 hectares of manicured gardens, fountains, and the Grand Canal", "Site where the Treaty of Versailles was signed in 1919, concluding the First World War"],
    "Inscribed 1979 (Palace and Park of Versailles)"),

  # 11. St. Peter's Basilica
  item("st-peters-basilica", "St. Peter's Basilica", "Basilica Papale di San Pietro in Vaticano", "Sacred Temple / Cathedral", "Vatican City", "Vatican City",
    "Italian High Renaissance to Baroque (1506–1626 CE)", "1506–1626 CE", 1626, "Donato Bramante, Michelangelo Buonarroti, Carlo Maderno, Gian Lorenzo Bernini",
    "High Renaissance and Italian Baroque Church Architecture", "Height: 136.6 m (448 ft); Interior length: 220 m; Capacity: 60,000 worshippers; Dome diameter: 41.5 m",
    "Travertine limestone from Tivoli, Carrara marble, gilded bronze, gold mosaic smalti",
    "St. Peter's Basilica in Vatican City is the largest church in the world and the spiritual heart of Roman Catholicism. Built over the tomb of Saint Peter, the first Bishop of Rome and apostle of Jesus Christ, who was crucified nearby around 64 CE. Replaced the 4th-century Old St. Peter's Basilica commissioned by Emperor Constantine.",
    "The majestic dome, designed by Michelangelo and completed by Giacomo della Porta, soars 136.6 meters into the sky. Inside stands Michelangelo's Pietà, carved when he was just 24, and Bernini's bronze Baldachin (st-peters-baldachin), a four-story canopy cast from bronze stripped from the Roman Pantheon. Enclosed by Bernini's elliptical St. Peter's Square, whose quadruple colonnades represent the 'maternal arms of the church'.",
    "Part of the Vatican City UNESCO World Heritage Site (1984). The preeminent site of Catholic pilgrimage and papal liturgy.",
    "https://images.unsplash.com/photo-1531572753322-ad063cecc140?auto=format&fit=crop&q=80&w=1200",
    ["St Peters", "Vatican", "Rome", "Michelangelo", "Bernini", "UNESCO", "Cathedral"],
    ["The largest church in the world by interior volume, accommodating 60,000 people", "Michelangelo designed the soaring 136-meter dome and sculpted the famous Pietà inside", "Built directly above the tomb of Saint Peter, the first pope, martyred around 64 CE", "Bernini's bronze Baldachin stands four storeys tall beneath the central dome"],
    "Inscribed 1984 (Vatican City)"),

  # 12. Sistine Chapel
  item("sistine-chapel", "The Sistine Chapel", "Cappella Sistina (Sacrarium Apostolicum)", "Sacred Temple / Cathedral", "Apostolic Palace, Vatican City", "Vatican City",
    "Italian High Renaissance (1473–1481 CE; frescoes 1508–1541 CE)", "1473–1481 CE", 1481, "Baccio Pontelli, Giovannino de' Dolci (frescoes by Michelangelo Buonarroti)",
    "Italian Renaissance Papal Chapel Architecture & Fresco Art", "Length: 40.9 m; Width: 13.4 m; Height: 20.7 m (Exact dimensions of Solomon's Temple)",
    "Roman brickwork, barrel-vaulted ceiling, buon fresco (pigment on wet lime plaster)",
    "The Sistine Chapel is a chapel in the Apostolic Palace of Vatican City, famous for its Renaissance frescoes by Michelangelo. Commissioned by Pope Sixtus IV in 1473 as the private papal chapel and the venue for the Papal Conclave, where the College of Cardinals elects each new Pope. Smoke signals (black for undecided, white for elected) rise from a temporary chimney atop its roof.",
    "Between 1508 and 1512, Michelangelo painted the 500-square-meter ceiling, working standing up on custom wooden scaffolds. The ceiling depicts nine scenes from the Book of Genesis, centered on 'The Creation of Adam', where God's finger reaches toward Adam's hand. Nearly 25 years later, Michelangelo returned to paint 'The Last Judgment' on the altar wall (1536–1541), depicting over 300 figures with apocalyptic emotional intensity.",
    "Part of the Vatican City UNESCO World Heritage Site (1984). Welcomes over 5 million visitors annually.",
    "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&q=80&w=1200",
    ["Sistine Chapel", "Vatican", "Michelangelo", "Creation of Adam", "Papal Conclave", "Frescoes"],
    ["Built to the exact biblical dimensions of the Temple of Solomon in Jerusalem", "Michelangelo painted the 500 m² ceiling while standing upright on scaffolds between 1508–1512", "The famous 'Creation of Adam' fresco captures the near-touch of God's and Adam's fingers", "The permanent venue of the Papal Conclave, where cardinals elect each new Pope"],
    "Inscribed 1984 (Vatican City)"),

  # 13. Alhambra of Granada
  item("alhambra-granada", "The Alhambra & Generalife", "Al-Ḥamrā' (الْحَمْرَاء - The Red One) / La Alhambra", "Palace & Fortress", "Granada, Andalusia", "Spain",
    "Nasrid Dynasty Golden Age (1238–1358 CE)", "1238–1358 CE", 1358, "Muhammad I Ibn al-Ahmar, Yusuf I, and Muhammad V",
    "Classical Moorish Islamic Nasrid Palace Architecture", "Fortress perimeter: 2 km; Complex area: 140,000 m²; Towers: 30 defensive towers",
    "Red clay rammed earth (tapia), carved plaster stucco with Quranic epigraphy, polychrome glazed tiles (alicatados), cedar wood muqarnas",
    "The Alhambra is a palace and fortress complex located on the Sabika hill overlooking Granada in Andalusia, Spain. Built by the Nasrid Dynasty, the last Muslim dynasty of the Iberian Peninsula. Founded in 1238 by Muhammad I and transformed into a palatial paradise by Yusuf I and Muhammad V. In January 1492, the last emir Muhammad XII (Boabdil) surrendered the keys of the fortress to the Catholic Monarchs Ferdinand and Isabella.",
    "Celebrated for the Court of the Lions (Patio de los Leones), featuring an alabaster fountain supported by twelve marble lions spouting water, surrounded by 124 slender white marble columns. The ceilings feature intricate stucco stalactite vaults (muqarnas). Walls are inscribed with thousands of poetic verses and the recurring Nasrid motto: 'Wa lā ghāliba illā-llāh' ('There is no conqueror but God').",
    "Inscribed as a UNESCO World Heritage Site in 1984. One of the finest surviving examples of Islamic palace architecture in Europe.",
    "https://images.unsplash.com/photo-1599833975787-5c143f373c30?auto=format&fit=crop&q=80&w=1200",
    ["Alhambra", "Granada", "Spain", "Moorish", "Nasrid", "UNESCO", "Andalusia"],
    ["The last great royal citadel of Islamic Al-Andalus, surrendered in 1492", "Court of the Lions features a fountain resting on 12 carved stone lions surrounded by 124 columns", "Stucco walls repeat the Nasrid motto: 'There is no conqueror but God'", "Ingenious hydraulic channels fed water from the snowmelt of the Sierra Nevada mountains"],
    "Inscribed 1984 (Alhambra, Generalife and Albayzín)"),

  # 14. Neuschwanstein Castle
  item("neuschwanstein-castle", "Neuschwanstein Castle", "Schloss Neuschwanstein (New Swanstone Castle)", "Palace & Fortress", "Schwangau, Allgäu, Bavaria", "Germany",
    "Romantic Historicism / Fairy-Tale Revival (1869–1886 CE)", "1869–1886 CE", 1886, "Eduard Riedel & Christian Jank, commissioned by King Ludwig II of Bavaria",
    "Romantic Romanesque Revival (Burgenromantik) Architecture", "Height: 65 m (213 ft); Floor area: 6,000 m²; 200 planned rooms (15 completed)",
    "Limestone facade cladding, brick core, sandstone window surrounds, marble pillars",
    "Neuschwanstein Castle is a 19th-century historicist palace perched on a rugged cliff above Hohenschwangau in southwest Bavaria. Commissioned by King Ludwig II of Bavaria ('The Swan King' or 'Mad King Ludwig') in 1869 as a personal romantic retreat dedicated to the operas of his close friend, composer Richard Wagner. Ludwig lived in the palace for only 172 days before being declared mentally incompetent and mysteriously drowning in Lake Starnberg in June 1886.",
    "Designed not by an architect but by a theatrical stage set designer, Christian Jank. Perched atop the dramatic Pöllat Gorge, its towers inspired the iconic Walt Disney Cinderella and Sleeping Beauty castles. Despite its medieval fairy-tale appearance, it featured cutting-edge 19th-century technology: central hot-air heating, electric bell paging systems, flushing toilets on every floor, hot and cold running water, and telephone lines.",
    "Visited by over 1.4 million tourists annually. Germany's most celebrated fairytale castle.",
    "https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&q=80&w=1200",
    ["Neuschwanstein", "Bavaria", "Germany", "Ludwig II", "Castle", "Disney", "Romanticism"],
    ["Commissioned by King Ludwig II of Bavaria as a tribute to composer Richard Wagner", "Served as the direct visual inspiration for Walt Disney's iconic Sleeping Beauty Castle", "Hidden behind medieval towers were modern innovations including flush toilets and central heating", "Ludwig slept in the castle for only 172 days before his mysterious drowning death in 1886"],
    "Bavarian State Palace Monument"),

  # 15. Roman Pantheon
  item("pantheon-rome", "The Pantheon", "Pantheon (Temple of All the Gods) / Santa Maria ad Martyres", "Ancient Wonder", "Piazza della Rotonda, Rome", "Italy",
    "High Roman Empire (118–125 CE)", "118–125 CE", 125, "Emperor Hadrian (Original temple by Marcus Agrippa in 27 BCE)",
    "Imperial Roman Rotunda & Unreinforced Concrete Dome", "Dome diameter & interior height: 43.3 m (142 ft); Oculus diameter: 9 m; Porch columns: 16 monolithic granite shafts (60 tonnes each)",
    "Unreinforced Roman volcanic pozzolana concrete with pumice aggregate, Egyptian granite columns, white marble",
    "The Pantheon in Rome is the best-preserved building from classical antiquity. Commissioned by Emperor Hadrian around 118 CE to replace an earlier temple built by Marcus Agrippa in 27 BCE (whose dedication is still inscribed on the portico: 'M·AGRIPPA·L·F·COS·TERTIVM·FECIT'). In 609 CE, Byzantine Emperor Phocas gifted the building to Pope Boniface IV, who consecrated it as the church of Santa Maria ad Martyres, which preserved it from medieval quarrying.",
    "The dome remains the world's largest unreinforced concrete dome even after nearly 2,000 years. The dome's diameter (43.3 m) is exactly equal to the interior height, accommodating a perfect mathematical sphere. Hadrian's engineers lightened the dome as it rose by using progressively lighter aggregates—from heavy basalt at the base to porous volcanic pumice at the top. The open 9-meter oculus at the summit is the building's only light source; when it rains, water falls onto the convex marble floor and drains through 22 concealed holes.",
    "Inscribed as a UNESCO World Heritage Site in 1980 as part of the Historic Centre of Rome. Contains the tombs of artist Raphael and kings Vittorio Emanuele II and Umberto I.",
    "https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&q=80&w=1200",
    ["Pantheon", "Rome", "Italy", "Hadrian", "Oculus", "Concrete Dome", "UNESCO"],
    ["Still the world's largest unreinforced concrete dome after nearly 2,000 years", "The interior is a perfect mathematical sphere: height and diameter are both exactly 43.3 meters", "The 9-meter open central oculus is the only light source; rain drains through floor holes", "Houses the tomb of Renaissance master painter Raphael"],
    "Inscribed 1980 (Historic Centre of Rome)"),

  # 16. Florence Cathedral (Duomo / Santa Maria del Fiore)
  item("florence-cathedral", "Florence Cathedral (Santa Maria del Fiore)", "Cattedrale di Santa Maria del Fiore (Il Duomo di Firenze)", "Sacred Temple / Cathedral", "Piazza del Duomo, Florence, Tuscany", "Italy",
    "Early Renaissance (1296–1436 CE; dome completed 1436 CE)", "1296–1436 CE", 1436, "Filippo Brunelleschi (Dome), Arnolfo di Cambio (Cathedral), Giotto (Campanile)",
    "Italian Gothic to Early Renaissance Architecture", "Total height: 114.5 m (375 ft); Dome exterior diameter: 45.5 m; Length: 153 m; Campanile height: 84.7 m",
    "Polychrome marble panels (white Carrara, green Prato, red Maremma), 4 million bricks, sandstone tie rings",
    "The Cathedral of Santa Maria del Fiore, commonly known as the Duomo of Florence, is the symbol of the Italian Renaissance. Begun in 1296 by Arnolfo di Cambio. For over a century, the cathedral stood with a gigantic gaping octagonal hole 45 meters wide because no engineer in Europe knew how to build a dome of that scale without scaffolding trees that did not exist in Tuscany. In 1418, goldsmith Filippo Brunelleschi won an open competition to construct the dome.",
    "Brunelleschi invented an ingenious self-supporting double shell with a herringbone (spina di pesce) bricklaying pattern, where vertical bricks locked horizontal courses into place so the dome supported itself as it rose without wooden centering. Brunelleschi invented unprecedented reversible ox-powered hoisting machines and floating river transports to lift 37,000 tonnes of materials. The exterior is clad in geometric polychrome marble, and the interior dome features Giorgio Vasari's colossal fresco of The Last Judgment.",
    "Inscribed as a UNESCO World Heritage Site in 1982 as part of the Historic Centre of Florence. A founding masterpiece of Renaissance engineering.",
    "https://images.unsplash.com/photo-1543429776-2782fc8e1acd?auto=format&fit=crop&q=80&w=1200",
    ["Florence Cathedral", "Duomo", "Florence", "Brunelleschi", "Renaissance", "UNESCO", "Tuscany"],
    ["Brunelleschi built the 45-meter dome without wooden centering scaffolds using herringbone brickwork", "Remains the largest masonry dome ever constructed, containing over 4 million bricks", "The exterior is decorated in vibrant red, green, and white Tuscan marble panels", "Brunelleschi invented specialized ox-driven cranes and hoists to build the structure"],
    "Inscribed 1982 (Historic Centre of Florence)"),

  # 17. Tower of London
  item("tower-of-london", "Tower of London (Her Majesty's Fortress)", "Her Majesty's Fortress and Palace the Tower of London", "Palace & Fortress", "Tower Hamlets, London", "United Kingdom",
    "Norman Conquest to Tudor Era (1078–1399 CE)", "1078 CE", 1078, "William the Conqueror (Architect: Gundulf, Bishop of Rochester)",
    "Norman Romanesque Fortress Keep Architecture", "White Tower height: 27 m (90 ft); Wall thickness: 4.6 m; Complex area: 12 acres",
    "Kentish ragstone, Caen limestone imported from Normandy, Portland stone, massive timber beams",
    "The Tower of London is a historic fortress, former royal residence, and infamous state prison on the north bank of the River Thames. Founded in 1078 by William the Conqueror to defend London and intimidate rebellious Saxon subjects following the Norman Conquest of 1066. The White Tower at its center gave the entire fortress its name. Served as a royal palace, prison, armory, royal mint, and zoo for centuries.",
    "Infamous as a place of royal imprisonment and execution: prisoners entered by water through Traitors' Gate. Anne Boleyn and Catherine Howard (wives of Henry VIII) and Lady Jane Grey were beheaded on Tower Green. Today, it securely houses the Crown Jewels of the United Kingdom, including the Imperial State Crown and the Koh-i-Noor diamond. Guarded by the Yeomen Warders ('Beefeaters') and a flock of six captive ravens; legend holds that if the ravens ever leave the Tower, the kingdom and the monarchy will fall.",
    "Inscribed as a UNESCO World Heritage Site in 1988. Welcomes over 3 million visitors annually.",
    "https://images.unsplash.com/photo-1529655683826-aba9b3e77383?auto=format&fit=crop&q=80&w=1200",
    ["Tower of London", "London", "UK", "Norman", "William the Conqueror", "Crown Jewels", "UNESCO"],
    ["Founded in 1078 by William the Conqueror to protect and dominate Norman London", "Houses the magnificent British Crown Jewels, including the 530-carat Cullinan I diamond", "Guarded by Yeomen Warders (Beefeaters) and six ravens protected by royal decree", "Scene of the tragic executions of queens Anne Boleyn and Catherine Howard"],
    "Inscribed 1988 (Tower of London)"),

  # 18. Buckingham Palace
  item("buckingham-palace", "Buckingham Palace", "Buckingham Palace", "Palace & Fortress", "City of Westminster, London", "United Kingdom",
    "Georgian to Neoclassical Era (1703–1850 CE; East Front 1913 CE)", "1703–1850 CE", 1837, "John Nash, Edward Blore, Sir Aston Webb",
    "Neoclassical British Regency Architecture", "Width: 108 m; Depth: 120 m; Height: 24 m; 775 rooms; 77,000 m² floor area; 40-acre private garden",
    "Bath limestone ashlar, Portland stone (East Front), gilded bronze gates, statuary marble",
    "Buckingham Palace is the London residence and administrative headquarters of the monarch of the United Kingdom. Originally built in 1703 as a large townhouse for the Duke of Buckingham. Acquired by King George III in 1761 as a private residence for Queen Charlotte ('The Queen's House'). Under George IV, architect John Nash transformed it into a palatial residence. Queen Victoria became the first reigning monarch to make it her official royal home upon her accession in 1837.",
    "The palace contains 775 rooms, including 19 State Rooms, 52 royal and guest bedrooms, 188 staff bedrooms, 92 offices, and 78 bathrooms. The famous East Front balcony was conceived by Prince Albert in 1851 as a public platform for the Royal Family to appear before crowds during state occasions, jubilees, and royal weddings. The forecourt is the world-famous venue for the daily Changing of the Guard ceremony.",
    "The focal point of national celebrations, state visits, and royal ceremonies in the United Kingdom.",
    "https://images.unsplash.com/photo-1529655683826-aba9b3e77383?auto=format&fit=crop&q=80&w=1200",
    ["Buckingham Palace", "London", "UK", "Royal Family", "Queen Victoria", "Changing of the Guard"],
    ["Became the official London residence of British monarchs upon Queen Victoria's accession in 1837", "Contains 775 rooms, including 19 lavish State Rooms and the largest private garden in London", "The East Front balcony was added by Prince Albert for public royal family appearances", "Venue of the famous Changing of the Guard ceremony accompanied by a military brass band"],
    "Official Royal Palace of the UK"),

  # 19. Mont-Saint-Michel
  item("mont-saint-michel", "Mont-Saint-Michel & Abbey", "Le Mont-Saint-Michel (La Merveille de l'Occident)", "Sacred Temple / Cathedral", "Normandy", "France",
    "Medieval Romanesque and High Gothic (708–1523 CE)", "708–1523 CE", 1023, "Aubert of Avranches, Abbot Robert de Torigni",
    "Norman Romanesque and French Rayonnant Gothic Abbey Architecture", "Island perimeter: 960 m; Abbey spire height: 92 m (157 m above sea level); Tidal range: 14 m (46 ft)",
    "Granite quarried from Chausey islands, limestone, lead roofing, gilded statue of Saint Michael",
    "Mont-Saint-Michel is a tidal island and Benedictine abbey in Normandy, France, situated in the bay where Normandy and Brittany meet. Founded in 708 CE when Bishop Aubert of Avranches had a vision of the Archangel Michael commanding him to build an oratory on the rocky islet. During the Hundred Years' War, it remained an impregnable fortress that the English failed to capture despite a 30-year siege.",
    "Built in a hierarchical vertical feudal pyramid: God at the summit with the abbey and church, followed by the great halls, storehouses, housing for monks, and fishermen's village at the base. The bay experiences Europe's most dramatic tidal range, with tides rushing in at 'the speed of a galloping horse' across a 14-meter range, cutting the mount off from the mainland into an isolated island at high tide. The Gothic abbey monastery on the north face is celebrated as 'La Merveille' ('The Wonder').",
    "Inscribed as a UNESCO World Heritage Site in 1979. One of France's most iconic and mystical heritage landmarks.",
    "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&q=80&w=1200",
    ["Mont Saint Michel", "Normandy", "France", "Abbey", "Tidal Island", "Gothic", "UNESCO"],
    ["Tidal island experiencing Europe's highest tides, with water rushing in across a 14-meter range", "Built as a vertical feudal pyramid with the Benedictine abbey crowned at the rock summit", "Successfully resisted English military sieges for 30 years during the Hundred Years' War", "Crowned by a gilded bronze statue of the Archangel Michael slaying the dragon 157 m high"],
    "Inscribed 1979 (Mont-Saint-Michel and its Bay)"),

  # 20. Louvre Pyramid & Palace
  item("louvre-pyramid", "Louvre Palace & I.M. Pei Pyramid", "Musée du Louvre & Pyramide du Louvre", "Famous Building", "1st Arrondissement, Paris", "France",
    "Medieval Fortress to Modernist Expansion (1190–1989 CE)", "1190–1989 CE", 1989, "Pierre Lescot, Claude Perrault, I. M. Pei (Pyramid 1989)",
    "French Renaissance & Modernist High-Tech Glass Architecture", "Pyramid height: 21.6 m; Base width: 34 m; Palace area: 60,600 m²; 35,000 artworks on display",
    "Saint-Gobain extra-clear diamond float glass (673 rhombi and triangles), aerospace aluminum frame, Charente limestone",
    "The Louvre is the world's most-visited museum and a historic royal palace on the Right Bank of the Seine in Paris. Originally built as a medieval fortress under King Philip II Augustus in 1190. In the 16th century, King Francis I demolished the fortress to construct a grand Renaissance palace. Opened as a public national museum in August 1793 during the French Revolution with an exhibition of 537 paintings.",
    "In the 1980s, President François Mitterrand launched the 'Grand Louvre' project, commissioning Chinese-American architect I. M. Pei to design a new subterranean reception entrance crowned by a 21.6-meter modernist glass pyramid. Pei engineered custom crystal-clear float glass with Saint-Gobain to avoid any greenish tint, creating a radiant counterpoint to the classical palace facades. Holds world treasures including Leonardo da Vinci's Mona Lisa, the Venus de Milo, and the Winged Victory of Samothrace.",
    "Inscribed as a UNESCO World Heritage Site in 1991. Attracts over 9 million visitors annually.",
    "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&q=80&w=1200",
    ["Louvre", "Paris", "France", "Pyramid", "IM Pei", "Mona Lisa", "UNESCO", "Museum"],
    ["The world's largest art museum, displaying over 35,000 historic works including the Mona Lisa", "Originally built as a medieval castle fortress in 1190 under King Philip Augustus", "The 1989 I.M. Pei glass pyramid is constructed of 673 custom crystal-clear glass segments", "Opened to the public as a free national museum in 1793 during the French Revolution"],
    "Inscribed 1991 (Paris, Banks of the Seine)")
]

print(f"Europe base 20 written. Building remaining 40 European monuments...")
