// Generator for Batch 1: Ancient Near East, Egypt, Mesopotamia, Levant, Anatolia & Persia (155 entries)
import * as fs from 'fs';
import * as path from 'path';

interface SpeechDef {
  id: string;
  title: string;
  origTitle?: string;
  ruler: string;
  titleRole: string;
  year: number;
  yearDisplay: string;
  era: 'Antiquity' | 'Classical' | 'Medieval' | 'Early Modern' | '19th Century' | '20th Century' | 'Modern';
  cat: 'Treaties & Accords' | 'Legal Codes & Edicts' | 'Monumental Speeches' | 'Charters & Constitutions' | 'Religious & Philosophical Texts' | 'Human Rights & Declarations';
  civ: string;
  loc: string;
  lang: string;
  format: string;
  pres: string;
  quote: string;
  summary: string;
  context: string;
  excerpt: string;
  clauseTitle: string;
  clauseExcerpt: string;
  clauseMeaning: string;
  clauseSig: string;
  impact: string;
  audio: string;
}

const rawList: SpeechDef[] = [
  // EGYPT OLD, MIDDLE & NEW KINGDOM
  {
    id: 'anc_egypt_narmer_unification',
    title: 'The Unification Proclamation of Upper and Lower Egypt',
    origTitle: 'The Narmer Palette Iconographic Inscriptions',
    ruler: 'Narmer (Menes)',
    titleRole: 'First Pharaoh of the First Dynasty of Unified Egypt',
    year: -3100,
    yearDisplay: 'c. 3100 BC',
    era: 'Antiquity',
    cat: 'Monumental Speeches',
    civ: 'Ancient Egypt (Protodynastic / 1st Dynasty)',
    loc: 'Hierakonpolis (Nekhen), Upper Egypt',
    lang: 'Archaic Egyptian Hieroglyphs',
    format: 'Carved Siltstone Ceremonial Palette',
    pres: 'Egyptian Museum, Cairo, Egypt',
    quote: 'Horus brings forward the conquered marshlands of the Delta; the Two Lands are united beneath the White and Red Crowns.',
    summary: 'Narmer proclaims the unification of Upper and Lower Egypt into a single kingdom, founding the Egyptian dynastic state.',
    context: 'At the dawn of written history, King Narmer led Upper Egyptian forces north, conquering the Delta and binding Egypt under a divine monarch.',
    excerpt: 'Horus, divine patron of Nekhen, delivers ten thousand captives from the Delta marshes into the hand of Narmer. Wearing the High White Crown of the South and the Red Deshret of the North, the King stands victorious before the gods, establishing order over chaos throughout the river.',
    clauseTitle: 'Sovereignty of the Two Lands',
    clauseExcerpt: 'Narmer wears the Pschent double crown: let both banks of the Nile bow in obedience to the throne of Horus.',
    clauseMeaning: 'Establishes the ideological foundation of pharaonic dual kingship.',
    clauseSig: 'First recorded political unification of a regional nation-state in world history.',
    impact: 'Created the 3,000-year institution of the Egyptian Pharaoh and defined imperial iconography.',
    audio: 'Behold the unification of the Two Lands! By the favor of Horus, the marshes and the valley are forged into one throne. Chaos is repelled, and Maat shall reign from the cataracts unto the Great Green Sea.'
  },
  {
    id: 'anc_egypt_djoser_famine_stela',
    title: 'The Famine Stela: Decree of Relief and Endowments for Khnum',
    origTitle: 'The Sehel Island Inscription of Netjerikhet',
    ruler: 'Djoser (Netjerikhet)',
    titleRole: 'Pharaoh of the Third Dynasty & Builder of the Step Pyramid',
    year: -2670,
    yearDisplay: 'c. 2670 BC',
    era: 'Antiquity',
    cat: 'Legal Codes & Edicts',
    civ: 'Ancient Egypt (Old Kingdom)',
    loc: 'Sehel Island, Elephantine (Aswan), Egypt',
    lang: 'Middle Egyptian (Hieroglyphic text)',
    format: 'Granite Rock Stela Inscription',
    pres: 'Sehel Island rock face, Aswan, Egypt',
    quote: 'My heart was in great sorrow because the Nile had failed to flood for seven full years. Grain was scarce, the elderly wept, and children collapsed.',
    summary: 'Pharaoh Djoser consults his vizier Imhotep during a catastrophic seven-year famine and decrees permanent grain and land endowments to the temple of Khnum.',
    context: 'Consecutive failures of the annual Nile inundation brought Egypt to near collapse. Djoser sought spiritual reconciliation with Khnum, god of the cataract waters.',
    excerpt: 'Pharaoh questioned Imhotep, son of Ptah: What is the birthplace of the inundation? Imhotep answered: Khnum guards the caverns of the flood. Therefore did Pharaoh decree: all fisheries, quarry lands, and ten cubits of harvest from the First Cataract shall forever be endowed unto Khnum so that the waters may surge anew.',
    clauseTitle: 'Perpetual Endowments for Cataract Priests',
    clauseExcerpt: 'Every fisherman, fowler, and extractor of gold in Elephantine shall surrender one-tenth of their yield to the temple of the Nile flood.',
    clauseMeaning: 'A tax concession and administrative decentralization to ensure religious and social stability during resource crises.',
    clauseSig: 'Preserves the earliest known detailed narrative of state-managed famine crisis relief.',
    impact: 'Served as an administrative and religious precedent cited across two millennia of Egyptian history.',
    audio: 'For seven bitter years the Nile did not rise. The granaries stood empty, and my people grieved. Thus I turned to wise Imhotep, and together we restored honor to Khnum. Now let the cataracts burst forth, and let plenty cover the land!'
  },
  {
    id: 'anc_egypt_sneferu_cedar_decree',
    title: 'Decree of the High Fleet and Cedar Importation',
    origTitle: 'The Palermo Stone Inscription of Sneferu',
    ruler: 'Sneferu',
    titleRole: 'Pharaoh of the Fourth Dynasty and Founder of True Pyramid Architecture',
    year: -2613,
    yearDisplay: 'c. 2613 BC',
    era: 'Antiquity',
    cat: 'Charters & Constitutions',
    civ: 'Ancient Egypt (Old Kingdom)',
    loc: 'Memphis / Dahshur, Egypt',
    lang: 'Old Egyptian',
    format: 'Inscribed Basalt Royal Annals',
    pres: 'Palermo Regional Archeological Museum, Italy / Cairo Museum',
    quote: 'Bringing forty ships laden with cedar logs from Byblos, and building a fleet of one hundred cubits of royal pine.',
    summary: 'Sneferu organizes the earliest recorded state-sponsored naval merchant convoy across the Mediterranean to secure Lebanese timber for monument building.',
    context: 'Pyramid construction required immense timber scaffolding, sledges, and royal barques that native Nile palm trees could not provide.',
    excerpt: 'The Majesty of the King of Upper and Lower Egypt, Sneferu, commanded the dispatch of forty vessels into the Great Green Sea unto the Lebanon mountains. The fleet returned laden with fragrant cedar, whereof the King constructed two great ships of one hundred cubits length and doors for the Royal Palaces.',
    clauseTitle: 'State Monopoly on Strategic Timber Trade',
    clauseExcerpt: 'All cedar wood brought from the Syrian coast shall be consigned to the Royal Treasury for sacred temples and warships.',
    clauseMeaning: 'Centralized royal control over international importations of strategic materials.',
    clauseSig: 'Oldest direct documentary evidence of organized international maritime commerce in human history.',
    impact: 'Established maritime trade routes between Egypt and Phoenicia that lasted over 2,500 years.',
    audio: 'Forty great ships we sent across the sea, and forty ships returned laden with the tall cedars of Lebanon. No land stands isolated from Egypt; our barques navigate the outer ocean to gather the riches of the earth for eternity.'
  },
  {
    id: 'anc_egypt_khufu_quarry_edict',
    title: 'The Giza Horizon Royal Charter and Quarry Mobilization Edict',
    origTitle: 'The Wadi al-Jarf Papyrus and Giza Inscriptions',
    ruler: 'Khufu (Cheops)',
    titleRole: 'Pharaoh of the Fourth Dynasty & Builder of the Great Pyramid',
    year: -2580,
    yearDisplay: 'c. 2580 BC',
    era: 'Antiquity',
    cat: 'Legal Codes & Edicts',
    civ: 'Ancient Egypt (Old Kingdom)',
    loc: 'Giza Necropolis / Wadi al-Jarf, Red Sea Coast',
    lang: 'Old Egyptian',
    format: 'Papyrus Logbooks & Mason Mark Inscriptions',
    pres: 'Egyptian Museum, Cairo, Egypt',
    quote: 'The team "Friends of Khufu" carries the white limestone blocks across the water of the canal unto Akhet-Khufu.',
    summary: 'Administrative and ideological decree governing the mobilization, rations, and spiritual elevation of the thousands of free workers constructing the Great Pyramid.',
    context: 'Excavations at Wadi al-Jarf (the Diary of Merer) proved that the Great Pyramid was built by organized national corvée teams provided with generous rations of bread, meat, and beer.',
    excerpt: 'Let the phyles of builders and navigators transport the finest Tura stone across the high Nile flood unto the Horizon of Khufu. Each team shall be registered by name, receiving daily rations of grain, dried fish, garlic, and fresh garments from the King’s storehouses.',
    clauseTitle: 'Worker Sustenance and Protection',
    clauseExcerpt: 'No laborer upon the sacred Horizon shall suffer abuse or deprivation; bread and ale shall be provided without failure.',
    clauseMeaning: 'Guaranteed nutritional welfare and institutional honor for royal craftsmen and laborers.',
    clauseSig: 'Debunks ancient Greek fables of slave labor, proving sophisticated bureaucratic state-welfare logistics.',
    impact: 'Constructed the only surviving wonder of the ancient world through voluntary collective national labor.',
    audio: 'Akhet-Khufu rises toward the heavens! Not through misery, but through the united will of Egypt. Every craftsman who places a stone upon my horizon shall be fed from my granaries and remembered in the book of life.'
  },
  {
    id: 'anc_egypt_pepi_ii_harkhuf',
    title: 'Royal Letter to Harkhuf on the African Pygmy of Yam',
    origTitle: 'Autobiography of Harkhuf at Qubbet el-Hawa',
    ruler: 'Pepi II Neferkare',
    titleRole: 'Boy Pharaoh of the Sixth Dynasty',
    year: -2270,
    yearDisplay: 'c. 2270 BC',
    era: 'Antiquity',
    cat: 'Monumental Speeches',
    civ: 'Ancient Egypt (Old Kingdom)',
    loc: 'Aswan / Memphis, Egypt',
    lang: 'Old Egyptian (Hieroglyphic tomb inscription)',
    format: 'Carved Limestone Tomb Wall Inscription',
    pres: 'Qubbet el-Hawa, Aswan, Egypt',
    quote: 'Come north to the court immediately! Bring this dwarf with you alive, sound and well, to dance the dances of the god, and to gladden the heart of the King!',
    summary: 'An eight-year-old Pharaoh writes a letter of childlike excitement to governor Harkhuf, ordering extraordinary safety precautions for a sacred dancer from central Africa.',
    context: 'Governor Harkhuf had led an expedition deep into inner Africa (Sudan/Congo border) and returned with gold, ivory, and a pygmy dancer skilled in sacred rituals.',
    excerpt: 'When he goes down with you into the vessel, appoint trustworthy men to remain about him on each side of the boat: take care lest he fall into the water! When he sleeps at night, appoint trustworthy men to sleep beside him in his tent. Inspect ten times a night! For My Majesty desires to see this dancing dwarf more than all the tributes of Sinai and Punt!',
    clauseTitle: 'Royal Order of Protection',
    clauseExcerpt: 'Guard him by day and by night; if he arrives safe, thou shalt receive higher honors than any servant of the King.',
    clauseMeaning: 'Absolute priority placed on the welfare of foreign envoys and sacred performers.',
    clauseSig: 'One of the most human and emotionally vivid royal documents preserved from the Old Kingdom.',
    impact: 'Pioneered documented ethnographic fascination and trade connectivity between Egypt and sub-Saharan Africa.',
    audio: 'Hasten north to Memphis, Harkhuf! Bring this wondrous dancer alive and unharmed! Appoint guards to watch over him while he sleeps, for my royal heart longs to witness the sacred dances of the god more than all the gold of the deserts!'
  },
  {
    id: 'anc_egypt_senusret_iii_semna',
    title: 'The Semna Border Inscription: Guarding the Southern Frontier',
    origTitle: 'The Semna Stela of Year 16',
    ruler: 'Senusret III',
    titleRole: 'Pharaoh of the Twelfth Dynasty and Military Conqueror of Nubia',
    year: -1862,
    yearDisplay: '1862 BC',
    era: 'Antiquity',
    cat: 'Legal Codes & Edicts',
    civ: 'Ancient Egypt (Middle Kingdom)',
    loc: 'Semna Fortress, Second Cataract, Nubia (Sudan)',
    lang: 'Middle Egyptian',
    format: 'Red Granite Boundary Stela',
    pres: 'Egyptian Museum of Berlin, Germany',
    quote: 'He who preserves this boundary which My Majesty has established, he is my son, he is born to My Majesty. But he who abandons it, he is no son of mine!',
    summary: 'Senusret III establishes a fortified military boundary at the Second Cataract of the Nile, commanding future kings never to surrender an inch of territory.',
    context: 'Senusret III transformed Egypt into a superpower by building a network of massive mudbrick fortresses along the Nile in Nubia to control gold and trade routes.',
    excerpt: 'I made my boundary south of my fathers. I added to what was bequeathed to me. I am a king who speaks and acts; what my heart plans is done by my arm. Now as for any son of mine who shall maintain this boundary which My Majesty has made, he is my son; but as for him who shall fail to defend it, he is not my son, he was not born to me!',
    clauseTitle: 'Eternal Maintenance of the Frontier',
    clauseExcerpt: 'My statue is set up at this frontier, not that ye should worship it, but that ye should fight for it.',
    clauseMeaning: 'Binding imperative on royal descendants to uphold territorial integrity through active military readiness.',
    clauseSig: 'The earliest known explicit definition of defined geopolitical national borders in military history.',
    impact: 'Established the southern frontier of Egypt that endured throughout the Middle and New Kingdoms.',
    audio: 'I pushed the boundary of Egypt farther south than any of my fathers! What I speak, my right arm executes without retreat. If my son preserves this border, he is truly my son; but if he gives way, let him be stripped of my lineage!'
  },
  {
    id: 'anc_egypt_hatshepsut_speos_artemidos',
    title: 'The Speos Artemidos Restoration Inscription',
    origTitle: 'Speos Artemidos Rock Temple Inscription',
    ruler: 'Hatshepsut',
    titleRole: 'Female Pharaoh of the Eighteenth Dynasty',
    year: -1470,
    yearDisplay: 'c. 1470 BC',
    era: 'Antiquity',
    cat: 'Monumental Speeches',
    civ: 'Ancient Egypt (New Kingdom)',
    loc: 'Beni Hasan, Middle Egypt',
    lang: 'Middle Egyptian',
    format: 'Carved Cliffside Temple Inscription',
    pres: 'Rock Temple of Pakhet, Beni Hasan, Egypt',
    quote: 'I have restored that which was in ruins; I have raised up that which was unfinished since the Asiatics were in the midst of the Delta, ruling in ignorance of Re.',
    summary: 'Queen Hatshepsut proclaims the complete restoration of Egyptian temples destroyed generations earlier by the Hyksos invaders, asserting divine right.',
    context: 'Hatshepsut reigned as female Pharaoh for two decades of peace, economic prosperity, architectural brilliance, and temple reconstruction.',
    excerpt: 'Hear ye, all people and common folk, as many as ye may be! I have done these things by the design of my heart. I have restored what was destroyed. I have rebuilt the sanctuaries that lay in dust. For Amun himself commanded me to rule, and my authority is established like the mountains.',
    clauseTitle: 'Sacred Rebuilding Mandate',
    clauseExcerpt: 'Every altar that was neglected shall flow with wine and incense, and the names of the gods shall shine anew.',
    clauseMeaning: 'Religious justification for political authority through nationwide infrastructural and sacred reconstruction.',
    clauseSig: 'A monumental declaration of female political sovereignty and architectural revitalization.',
    impact: 'Marked the golden age of 18th Dynasty art, temple architecture, and commercial expansion to Punt.',
    audio: 'Listen, all ye people of Egypt! What was ruined, I have rebuilt with my own hands. The shrines that lay neglected since foreign invaders trod upon our Delta now gleam with pure gold. Amun has chosen me, and Maat walks again among us.'
  },
  {
    id: 'anc_egypt_thutmose_iii_megiddo',
    title: 'The Megiddo War Council Oration: Marching through the Aruna Pass',
    origTitle: 'Annals of Thutmose III at Karnak Temple',
    ruler: 'Thutmose III',
    titleRole: 'Pharaoh of the Eighteenth Dynasty ("The Napoleon of Egypt")',
    year: -1457,
    yearDisplay: '1457 BC',
    era: 'Antiquity',
    cat: 'Monumental Speeches',
    civ: 'Ancient Egypt (New Kingdom)',
    loc: 'Aruna / Megiddo Plain, Canaan (Israel)',
    lang: 'Middle Egyptian',
    format: 'Carved Sandstone Temple Annals',
    pres: 'Temple of Amun-Re, Karnak, Luxor, Egypt',
    quote: 'As Re loves me, as my father Amun praises me, My Majesty will proceed along this narrow Aruna road! Let him who will go upon these other roads, and let him who will follow My Majesty!',
    summary: 'Thutmose III overrides his timid generals in a war council, choosing the treacherous narrow mountain pass of Aruna to surprise the Canaanite coalition at Megiddo.',
    context: 'A coalition of 330 Canaanite and Syrian princes gathered at Megiddo to rebel against Egyptian hegemony. Egyptian generals urged the Pharaoh to take wide, safe detour roads.',
    excerpt: 'The generals said: How can man walk behind man and horse behind horse through this ravine? Will not our vanguard fight while our rearguard stands trapped in Aruna? But Pharaoh swore an oath: I will not allow the cowardly enemy to say, Does His Majesty go another way because he is afraid of us? I will lead the vanguard myself!',
    clauseTitle: 'Leadership by Personal Example',
    clauseExcerpt: 'Pharaoh himself leads the front rank, showing the path of his feet unto his soldiers.',
    clauseMeaning: 'Supreme command achieved through direct personal exposure to mortal danger.',
    clauseSig: 'The first battle in human history recorded with tactical details, troop movements, and strategic speeches.',
    impact: 'Secured total victory at Megiddo and established the Egyptian Empire across Canaan and Syria for four centuries.',
    audio: 'By the life of Amun, I swear! Shall the wretched prince of Kadesh say that Pharaoh fled through the detour out of fear? No! I will march through the narrow pass of Aruna at the head of my legions! Follow me who dares, for victory belongs to the brave!'
  },
  {
    id: 'anc_egypt_akhenaten_amarna_boundary',
    title: 'The Great Amarna Boundary Stela: Dedication of Akhetaten to the Sun Disc',
    origTitle: 'Boundary Stela K of Amarna',
    ruler: 'Akhenaten (Amenhotep IV)',
    titleRole: 'Pharaoh of the Eighteenth Dynasty and Monotheistic Visionary',
    year: -1353,
    yearDisplay: '1353 BC',
    era: 'Antiquity',
    cat: 'Religious & Philosophical Texts',
    civ: 'Ancient Egypt (New Kingdom / Amarna Period)',
    loc: 'Akhetaten (Tell el-Amarna), Middle Egypt',
    lang: 'Late Egyptian',
    format: 'Limestone Cliff Boundary Stela',
    pres: 'Rock cliffs surrounding Amarna, Egypt',
    quote: 'Behold, it is the Aten who pointed out this virgin ground to me! It belongs not to a god, it belongs not to a goddess; it belongs to the living Aten my father alone.',
    summary: 'Akhenaten founds a brand-new imperial capital dedicated solely to the Aten (the solar disc), renouncing the traditional pantheon of Thebes.',
    context: 'Breaking with the wealthy priesthood of Amun, Akhenaten established the world’s earliest state-enforced monolatry in a desert plain untouched by previous cults.',
    excerpt: 'The living Sun Disc, who illuminates the two horizons, revealed this place unto me. I shall make Akhetaten for the Aten in this place. I shall not make it south of it, nor north of it, nor west of it, nor east of it. Here shall be built the Great Temple of the Sun, with unroofed altars welcoming the morning rays.',
    clauseTitle: 'Inviolability of the Sacred City Boundaries',
    clauseExcerpt: 'I shall never step beyond these boundary markers to move my city elsewhere, even if my queen or nobles should plead with me.',
    clauseMeaning: 'An immutable theological boundary covenant binding the king permanently to his sacred city.',
    clauseSig: 'World history’s first documented religious revolution and foundation of a monotheistic holy city.',
    impact: 'Pioneered pure solar theology, revolutionized ancient Egyptian art and literature before being dismantled by Tutankhamun.',
    audio: 'Behold this clean desert plain, revealed to me by the light of the living Aten! Here shall rise Akhetaten, the horizon of the sun. No old gods shall pollute its air; only truth, light, and love shall dwell within its walls for ever and ever.'
  },
  {
    id: 'anc_egypt_tutankhamun_restoration',
    title: 'The Restoration Stela: Reviving the Temples of the Ancient Gods',
    origTitle: 'The Great Restoration Stela of Tutankhamun at Karnak',
    ruler: 'Tutankhamun',
    titleRole: 'Pharaoh of the Eighteenth Dynasty ("The Boy King")',
    year: -1334,
    yearDisplay: '1334 BC',
    era: 'Antiquity',
    cat: 'Religious & Philosophical Texts',
    civ: 'Ancient Egypt (New Kingdom)',
    loc: 'Karnak Temple, Thebes (Luxor), Egypt',
    lang: 'Middle Egyptian',
    format: 'Red Granite Monumental Stela',
    pres: 'Egyptian Museum, Cairo, Egypt',
    quote: 'The temples of the gods were in ruins; their shrines were overgrown with weeds as if they had never been. If an army was sent to Syria to expand the borders, it met with no success, for the gods turned their backs on this land.',
    summary: 'Tutankhamun officially ends the Amarna heresy, restoring Amun, Osiris, and Ptah, reopening the ancestral temples, and doubling the priestly endowments.',
    context: 'Following Akhenaten\'s death, young Tutankhamun relocated the court back to Thebes and Memphis, reversing his predecessor\'s radical religious experiments.',
    excerpt: 'When His Majesty arose as King, the sanctuaries of the gods were neglected and fallen into decay. The gods had forsaken Egypt. If one prayed to a god for guidance, he heard no reply. Therefore His Majesty took counsel with his heart, crafting new divine statues of electrum and lapis lazuli, doubling the offerings of silver, gold, and cattle, that the gods might return and smile upon Egypt once more.',
    clauseTitle: 'Restoration of Traditional Temple Estates',
    clauseExcerpt: 'All property, slaves, and fields stripped from the gods of old are restored tenfold to their hereditary priesthoods.',
    clauseMeaning: 'A complete institutional and economic counter-reformation restoring social balance.',
    clauseSig: 'The definitive state decree ending the Amarna Period and preserving Egypt’s classical religious heritage.',
    impact: 'Re-stabilized the New Kingdom and reconnected Egypt with its traditional theological stability.',
    audio: 'The land was sick; the gods had abandoned our shrines because of neglect. Today, I, Tutankhamun, have restored their altars with pure gold and electrum. The priests sing again in the courtyards, and peace has returned to the hearts of the people.'
  },
  {
    id: 'anc_egypt_ramesses_ii_kadesh_poem',
    title: 'The Battle of Kadesh Oration: The Divine Solo Charge Against the Hittite Chariots',
    origTitle: 'The Poem of Pentaur / Bulletin of Kadesh',
    ruler: 'Ramesses II (The Great)',
    titleRole: 'Pharaoh of the Nineteenth Dynasty ("Usermaatre Setepenre")',
    year: -1274,
    yearDisplay: '1274 BC',
    era: 'Antiquity',
    cat: 'Monumental Speeches',
    civ: 'Ancient Egypt (New Kingdom)',
    loc: 'Orontes River, Kadesh, Syria',
    lang: 'Late Egyptian Hieroglyphic & Hieratic',
    format: 'Temple Relief Inscriptions at Abu Simbel, Karnak, and Ramesseum',
    pres: 'Abu Simbel Great Temple & Ramesseum, Luxor, Egypt',
    quote: 'I found 2,500 chariots surrounding me, all the elite warriors of Hatti and their allies. Not one of my princes was beside me, not one of my charioteers stood with me. I called upon Amun: My father Amun, has a father forgotten his son?',
    summary: 'Ramesses II rallies his desperate courage after being ambushed at Kadesh, charging single-handedly into thousands of Hittite chariots while invoking Amun.',
    context: 'Deceived by Bedouin spies, Ramesses advanced with only the Division of Amun and was caught by King Muwatalli’s massive chariot ambush outside Kadesh.',
    excerpt: 'I cried out: What is it, Amun? Does a father ignore his son? Have I not built thee monuments of sandstone and endowed thy altars with thousands of cattle? Behold, Amun is more to me than millions of foot soldiers and hundreds of thousands of chariots! Amun heard my cry; he gave me his hand from the heavens, saying: Forward, Ramesses! I am with thee! Then I struck them like Monthu; I hurled them into the waters of the Orontes like crocodiles, and not one looked back behind him!',
    clauseTitle: 'Divine Invocation of Amun',
    clauseExcerpt: 'The hand of Amun is with the Pharaoh; one royal arrow strikes down twenty enemies.',
    clauseMeaning: 'Theological legitimation of royal military invulnerability and personal valor.',
    clauseSig: 'The most famously publicized personal combat narrative in the ancient world, carved on five major temples.',
    impact: 'Led directly to the world\'s first recorded international peace treaty sixteen years later.',
    audio: 'I stood alone, surrounded by two thousand five hundred chariots of Hatti! My army had fled in terror, but I cried unto Amun: Father, are you not with me? Amun gave me his strength! I charged into their ranks like a raging lion, scattering their princes into the river!'
  },
  {
    id: 'anc_egypt_kadesh_peace_treaty',
    title: 'The Silver Peace Treaty of Kadesh: The World’s First Bilateral Non-Aggression Pact',
    origTitle: 'The Treaty of Ramesses II and Hattusili III',
    ruler: 'Ramesses II & Hattusili III',
    titleRole: 'Pharaoh of Egypt & Great King of the Hittites',
    year: -1258,
    yearDisplay: '1258 BC',
    era: 'Antiquity',
    cat: 'Treaties & Accords',
    civ: 'Ancient Egypt & Hittite Empire',
    loc: 'Pi-Ramesses, Egypt & Hattusa, Anatolia (Turkey)',
    lang: 'Akkadian Cuneiform (Diplomatic language) & Egyptian Hieroglyphs',
    format: 'Engraved Silver Tablet & Temple Walls',
    pres: 'Istanbul Archaeology Museum, Turkey (Replica at UN Headquarters, New York)',
    quote: 'Behold, Ramesses, Beloved of Amun, the Great King of Egypt, has made peace and brotherhood with Hattusili, the Great King of Hatti. There shall be no enmity between them forever.',
    summary: 'The earliest surviving formal diplomatic peace treaty in world history, establishing mutual non-aggression, defensive alliance, and prisoner extradition.',
    context: 'After decades of warfare over Syrian borderlands, Egypt and Hatti recognized the rising threat of the Assyrian Empire and chose diplomatic alliance.',
    excerpt: 'There shall be good peace and brotherhood between the children of Ramesses and the children of Hattusili forever. The Great King of Egypt shall not invade the land of Hatti to take anything therefrom, and the Great King of Hatti shall not invade the land of Egypt. If another enemy come against the land of Hatti, Ramesses shall send his troops and his chariots to assist his brother; and if an enemy attack Egypt, Hattusili shall likewise hasten to the defense of his brother.',
    clauseTitle: 'Mutual Defense and Extradition of Political Refugees',
    clauseExcerpt: 'If any noble or citizen flee from Egypt to Hatti, Hattusili shall return him to Egypt without mutilating his eyes, ears, or children.',
    clauseMeaning: 'Humanitarian extradition clause prohibiting torture or collective punishment of repatriated individuals.',
    clauseSig: 'A foundational milestone of international law and bilateral diplomacy.',
    impact: 'Secured fifty years of unbroken peace across the ancient Near East and hangs today at the United Nations building.',
    audio: 'Let the thousands of gods of Egypt and Hatti witness this oath! There shall be brotherhood between Ramesses and Hattusili forever. We shall never raise the sword against each other; if an enemy attacks either brother, both shall unite to crush them in peace and honor.'
  },
  {
    id: 'anc_egypt_merneptah_victory_stela',
    title: 'The Victory Stela of Merneptah (The Israel Stela)',
    origTitle: 'The Great Triumphal Inscription of Merneptah',
    ruler: 'Merneptah',
    titleRole: 'Pharaoh of the Nineteenth Dynasty',
    year: -1208,
    yearDisplay: '1208 BC',
    era: 'Antiquity',
    cat: 'Monumental Speeches',
    civ: 'Ancient Egypt (New Kingdom)',
    loc: 'Thebes (Luxor), Egypt',
    lang: 'Late Egyptian',
    format: 'Carved Black Granite Stela (Over 3 meters tall)',
    pres: 'Egyptian Museum, Cairo, Egypt',
    quote: 'Canaan is plundered with every evil; Ashkelon is taken; Gezer is seized; Yanoam is made non-existent; Israel is laid waste, his seed is not.',
    summary: 'Pharaoh Merneptah celebrates his victories over the Libyan confederation and the Sea Peoples, containing the earliest historical mention of "Israel".',
    context: 'Massive migrations of Sea Peoples and Libyan tribes threatened the western Delta, while Canaanite city-states attempted rebellion.',
    excerpt: 'The princes are prostrate, saying: Peace! Not one raises his head among the Nine Bows. Tehenu-land is devastated; Hatti is quieted; Canaan is conquered. Ashkelon is carried off; Gezer is captured; Israel is laid waste, his seed is no more! Egypt has become like a tranquil mother, and all lands are bound in peace under the sandals of the Pharaoh.',
    clauseTitle: 'Triumph over the Northern Tribes',
    clauseExcerpt: 'Those who dared set foot upon the borders of Egypt have seen their breath cut off forever.',
    clauseMeaning: 'Imperial deterrence asserting divine sovereignty over both western invaders and Levantine tribes.',
    clauseSig: 'Contains the only direct mention of "Israel" in Egyptian pharaonic records.',
    impact: 'A key chronological benchmark for biblical archaeology, Near Eastern history, and the Bronze Age collapse.',
    audio: 'The princes of the nations bow low, pleading for peace! The invaders who sought to burn our towns have perished beneath our blades. Canaan is pacified, and all who challenged Egypt lie broken beneath our sandals.'
  },
  {
    id: 'anc_egypt_ramesses_iii_sea_peoples',
    title: 'The Medinet Habu Inscription: Crushing the Sea Peoples Invasion',
    origTitle: 'The Naval War Reliefs of Medinet Habu',
    ruler: 'Ramesses III',
    titleRole: 'Pharaoh of the Twentieth Dynasty',
    year: -1177,
    yearDisplay: '1177 BC',
    era: 'Antiquity',
    cat: 'Monumental Speeches',
    civ: 'Ancient Egypt (New Kingdom)',
    loc: 'Medinet Habu Temple, Western Thebes, Egypt',
    lang: 'Late Egyptian',
    format: 'Carved Sandstone Mortuary Temple Reliefs',
    pres: 'Medinet Habu, Luxor, Egypt',
    quote: 'The foreign countries made a conspiracy in their islands. All at once the lands were on the move, scattered in war. No land could stand before their arms. But as for Egypt, they were trapped in the mouth of the Nile like birds in a net!',
    summary: 'Ramesses III describes the catastrophic Bronze Age migration of the Sea Peoples that destroyed the Hittites and Mycenaeans, and his epic land and naval victories defending Egypt.',
    context: 'The Sea Peoples (Philistines, Shardana, Tjeker, Weshesh) obliterated the empires of the eastern Mediterranean before assaulting Egypt by land and sea.',
    excerpt: 'No land could withstand their arms: from Hatti, Kode, Carchemish, Arzawa, and Alashiya, they were cut off at one time. A camp was set up in one place in Amurru. But I, Pharaoh, prepared my boundary in Djahi, marshaling my infantry and charioteers. In the river-mouths, I stationed warships manned by archers. Those who came by sea were met by a wall of fire; their ships were overturned, their warriors dragged ashore and slaughtered like fish on the sand!',
    clauseTitle: 'Total Defense of the River Mouths',
    clauseExcerpt: 'Let the ships of the northern barbarians be encircled and grappled; let not one invader return home to tell the tale.',
    clauseMeaning: 'Tactical order combining riverine ambush, archer volleys, and grappling boarding tactics.',
    clauseSig: 'The definitive contemporary account of the Late Bronze Age collapse that reshaped civilization.',
    impact: 'Saved Egyptian civilization from destruction when all other contemporary empires collapsed.',
    audio: 'From their distant islands the northern hordes swept across the world, burning cities and toppling mighty kings! No empire could resist them until they dared set foot in Egypt. In the river-mouths we ambushed their armada; we pierced them with arrows and cast their bodies into the sea!'
  },
  {
    id: 'anc_egypt_piye_conquest_stela',
    title: 'The Triumphal Stela of King Piye: The Nubian Conquest and Chivalric War Code',
    origTitle: 'The Piye Victory Stela at Gebel Barkal',
    ruler: 'Piye (Piankhi)',
    titleRole: 'King of Kush & First Pharaoh of the Twenty-Fifth Dynasty of Egypt',
    year: -728,
    yearDisplay: '728 BC',
    era: 'Antiquity',
    cat: 'Monumental Speeches',
    civ: 'Kingdom of Kush / Nubian 25th Dynasty',
    loc: 'Temple of Amun, Gebel Barkal, Napata (Sudan)',
    lang: 'Classical Middle Egyptian (Masterful archaic style)',
    format: 'Grey Granite Monumental Stela (Over 500 lines)',
    pres: 'Egyptian Museum, Cairo, Egypt',
    quote: 'Do not attack by night in the manner of games; fight only when the enemy is in readiness! Call out to them: The battle is joined! Choose your ground!',
    summary: 'The Black Pharaoh Piye orders his Nubian army to invade Egypt to purify the temples, instituting an astonishing code of chivalric warfare and mercy.',
    context: 'Egypt had fragmented into squabbling, corrupt petty kingdoms. Piye, devout worshipper of Amun at Napata, marched north to reunite Egypt under traditional righteousness.',
    excerpt: 'His Majesty commanded: Delay not, day or night, as if you were playing a game. Fight in the open! Say to the foe: Gird your armor, harness your best horses, that it may be known that Amun sent us! And when Nimlot surrendered Hermopolis, Piye entered his stables and wept, saying: By my life, it pains my heart more that my horses were starved than any other crime thou hast committed!',
    clauseTitle: 'Code of Honor and Sanctity of Horses',
    clauseExcerpt: 'Spare the vanquished who surrender without deceit; plunder not the shrines of Amun.',
    clauseMeaning: 'Prohibition of wanton looting and insistence on animal welfare and battlefield transparency.',
    clauseSig: 'Regarded as one of the finest literary and moral inscriptions in ancient Egyptian history.',
    impact: 'Founded the 25th "Black Pharaohs" Dynasty, reuniting Egypt and Nubia into an empire that rivaled Assyria.',
    audio: 'Fight not like cowards in the darkness! Challenge your enemies openly, face-to-face, that they may know the righteousness of Amun. And when you enter their cities, show mercy to the helpless and feed the starving horses in their stalls.'
  },
  {
    id: 'anc_egypt_psamtik_i_unification',
    title: 'The Saite Renaissance Proclamation of Sovereign Re-unification',
    origTitle: 'The Adoption Stela of Nitocris',
    ruler: 'Psamtik I (Wahibre)',
    titleRole: 'Pharaoh of the Twenty-Sixth Dynasty (Saite Period)',
    year: -656,
    yearDisplay: '656 BC',
    era: 'Antiquity',
    cat: 'Charters & Constitutions',
    civ: 'Ancient Egypt (Saite 26th Dynasty)',
    loc: 'Sais / Karnak, Egypt',
    lang: 'Late Egyptian / Demotic transitional',
    format: 'Carved Red Granite Stela',
    pres: 'Egyptian Museum, Cairo, Egypt',
    quote: 'I have given my daughter to be the Divine Adoratrice of Amun; I have endowed her with estates in the North and the South, that Egypt may know one law and one throne.',
    summary: 'Psamtik I uses Greek mercenaries and political diplomacy to expel the Assyrians, reunite Lower and Upper Egypt, and launch the Saite cultural renaissance.',
    context: 'Following devastating Assyrian sacks of Memphis and Thebes, Psamtik I united Egypt through hiring Ionian and Carian bronze-armored hoplites and securing the high priesthood.',
    excerpt: 'The King speaks: I have not done what was done in times of chaos, when brother fought brother. I have established my daughter Nitocris in Thebes as the God’s Wife of Amun, providing her with rich lands in every nome. Now let the Greek bronze men guard our borders, and let the scribes copy the ancient scrolls of the Old Kingdom, that wisdom may flourish again.',
    clauseTitle: 'Integration of Mediterranean Allies and Traditional Law',
    clauseExcerpt: 'The foreign bronze warriors shall dwell in camps along the Pelusiac branch, defending the realm without molesting the temples.',
    clauseMeaning: 'Institutional integration of foreign military specialists balanced with traditional temple preservation.',
    clauseSig: 'Launched the Saite Renaissance, the last great flourishing of native Egyptian art, commerce, and culture.',
    impact: 'Re-established Egypt as a Mediterranean maritime trading power and preserved thousands of classical texts.',
    audio: 'Egypt is made whole once more! The invaders are driven back, and the divided kingdoms are knit together. We look back to the greatness of our ancestors who built the pyramids, restoring their wisdom and their laws for all generations.'
  },
  {
    id: 'anc_egypt_ptolemy_canopus_reform',
    title: 'The Decree of Canopus: The Leap Year Calendar and Trilingual Synodal Proclamation',
    origTitle: 'The Canopus Inscription of the Priests of Egypt',
    ruler: 'Ptolemy III Euergetes',
    titleRole: 'Ptolemaic Pharaoh of Egypt',
    year: -238,
    yearDisplay: '238 BC',
    era: 'Classical',
    cat: 'Legal Codes & Edicts',
    civ: 'Ptolemaic Egypt & Hellenistic World',
    loc: 'Canopus (near Alexandria), Egypt',
    lang: 'Ancient Greek, Egyptian Hieroglyphic, Egyptian Demotic (Trilingual)',
    format: 'Carved Limestone Stelae',
    pres: 'Egyptian Museum, Cairo & Louvre Museum, Paris',
    quote: 'That the seasons may always correspond with the sun according to the order of the cosmos, one additional day shall be celebrated every four years.',
    summary: 'The synod of Egyptian priests and King Ptolemy III decree the introduction of the leap year (an extra day every 4 years), 200 years before Julius Caesar.',
    context: 'The ancient Egyptian 365-day calendar drifted by 1 day every 4 years, causing festivals like the rising of Sirius to drift through all seasons.',
    excerpt: 'Because the star of Isis wanders according to the old calendar, so that festivals celebrated in winter come to fall in summer; it is decreed: that after the five intercalary days at the end of the year, a sixth day shall be added every four years as a sacred festival of the Benefactor Gods, so that the calendar shall forever agree with the celestial heavens.',
    clauseTitle: 'Establishment of the Quadrennial Leap Day',
    clauseExcerpt: 'Every fourth year, a sixth Epagomenal day shall be inserted before the first day of Thoth.',
    clauseMeaning: 'Correction of solar drift through systematic leap-year intercalation.',
    clauseSig: 'The direct astronomical precursor to the Julian and Gregorian calendar systems used worldwide today.',
    impact: 'Demonstrated the advanced scientific synthesis between native Egyptian astronomy and Hellenistic royal governance.',
    audio: 'To ensure that the sacred festivals do not wander through winter and summer, let the calendar be fixed by the stars! Every four years, an additional day of celebration shall be added to the year, bringing human time into harmony with the cosmos.'
  },
  {
    id: 'anc_egypt_ptolemy_rosetta_decree',
    title: 'The Memphis Decree: The Rosetta Stone of Religious Privileges and Tax Remissions',
    origTitle: 'The Rosetta Stone Inscription (Ptolemaic Decree of Memphis)',
    ruler: 'Ptolemy V Epiphanes',
    titleRole: 'Pharaoh of the Ptolemaic Dynasty of Egypt',
    year: -196,
    yearDisplay: '196 BC',
    era: 'Classical',
    cat: 'Legal Codes & Edicts',
    civ: 'Ptolemaic Egypt',
    loc: 'Memphis / Rosetta (Rashid), Nile Delta, Egypt',
    lang: 'Hieroglyphic (Sacred), Demotic (Civil), Ancient Greek (Administrative)',
    format: 'Granodiorite Stela',
    pres: 'British Museum, London, United Kingdom',
    quote: 'King Ptolemy, living forever, beloved of Ptah, has remitted debts, reduced taxes on cotton and grain, and bestowed great benefactions upon the temples.',
    summary: 'Ptolemy V grants massive tax cuts, debt amnesties, and military pardons to reconcile with native Egyptian priests and citizens following severe rebellions.',
    context: 'Native Egyptian rebellions led by Pharaohs Horwennefer and Ankhwennefer in the south had crippled the Ptolemaic state. Ptolemy V issued this sweeping conciliation decree.',
    excerpt: 'The King has remitted entirely the debts owed to the royal treasury by the people of Egypt. He has commanded that those who were imprisoned and accused shall be freed. He has decreed that the temples shall receive their customary allowances of wine and wheat, and that the tax on sailing the Nile shall be abolished. In return, let this decree be inscribed on hard stone in sacred, native, and Greek letters in every temple of the first rank.',
    clauseTitle: 'Trilingual Publication Mandate',
    clauseExcerpt: 'This decree shall be inscribed upon a stela of hard stone in sacred characters, in popular script, and in the speech of the Greeks.',
    clauseMeaning: 'Legal requirement to publish state edicts across all major linguistic communities for universal access.',
    clauseSig: 'The key that allowed Jean-François Champollion to decipher Egyptian hieroglyphs in 1822, unlocking Egyptian history.',
    impact: 'Became the most famous archaeological artifact in the world and the master key to ancient linguistics.',
    audio: 'In the ninth year of the reign of young Ptolemy, peace is offered unto all citizens. Debts are forgiven, prisoners are released, and the ancient temples are endowed anew. Let this decree be engraved in hieroglyphs, in the native script, and in Greek, that all may read and understand.'
  },
  {
    id: 'anc_egypt_cleopatra_tax_exemption',
    title: 'Royal Ordinance of Tax Immunity for Alexandria Grain Shipping',
    origTitle: 'The Cleopatra Papyrus (BGU VIII 1730)',
    ruler: 'Cleopatra VII Thea Philopator',
    titleRole: 'Last Sovereign Pharaoh of Ptolemaic Egypt',
    year: -33,
    yearDisplay: '33 BC',
    era: 'Classical',
    cat: 'Legal Codes & Edicts',
    civ: 'Ptolemaic Egypt & Late Roman Republic',
    loc: 'Alexandria, Egypt',
    lang: 'Koine Greek with Royal Demotic Approval ("Ginestho" - "Make it so!")',
    format: 'Papyrus Official Decree',
    pres: 'Egyptian Museum of Berlin, Germany',
    quote: 'Ginestho! Let it be done! Exemption from all export duties and personal taxes for the transport of wheat throughout the realm.',
    summary: 'Cleopatra VII issues an emergency tax incentive to Roman general Publius Canidius Crassus to ensure unhindered grain supplies for her allied fleets.',
    context: 'As war with Octavian loomed, Cleopatra personally managed the economic logistics of the joint Egyptian-Roman army and fleet supporting Mark Antony.',
    excerpt: 'We have granted unto Publius Canidius and his heirs the duty-free export of ten thousand artabas of wheat annually, and that neither he nor his tenant farmers shall pay taxes on land or cattle. No official shall exact corvée labor from his estates. And at the bottom of the roll, in the Queen’s own handwriting: Ginestho ("Let it be done!").',
    clauseTitle: 'Royal Autograph of Executive Approval',
    clauseExcerpt: 'Ginestho — written in the royal hand of the Queen of Kings.',
    clauseMeaning: 'Direct personal authorization by the monarch executing sovereign economic policy.',
    clauseSig: 'Contains the only known surviving handwriting of Cleopatra VII herself.',
    impact: 'Illuminates Cleopatra\'s brilliant, hands-on administrative competence as an economist and statesman.',
    audio: 'Let it be done! Exemption from every toll and duty is hereby granted for the shipping of our harvest. No tax collector shall hinder the barges upon the river; Egypt’s wealth shall sustain our allies in the defense of our sovereign throne!'
  },

  // MESOPOTAMIA, SUMER, AKKAD, BABYLON, ASSYRIA
  {
    id: 'anc_meso_urukagina_reforms',
    title: 'The Liberty and Anti-Corruption Edict of Urukagina',
    origTitle: 'The Reform Cones of Urukagina at Girsu',
    ruler: 'Urukagina',
    titleRole: 'Ensi (King) of Lagash ("First Reformer in Human History")',
    year: -2350,
    yearDisplay: 'c. 2350 BC',
    era: 'Antiquity',
    cat: 'Human Rights & Declarations',
    civ: 'Sumer (Ancient Lagash)',
    loc: 'Girsu (Tello), Sumer (Southern Iraq)',
    lang: 'Sumerian Cuneiform',
    format: 'Inscribed Clay Foundation Cones',
    pres: 'Louvre Museum, Paris, France',
    quote: 'Urukagina established the liberty (Amargi) of the citizens of Lagash. He cleared the tax collectors from the orchards and riverbanks; he protected the widow and the orphan from the powerful.',
    summary: 'The earliest known legal and social reform document in history, curbing extortion by the aristocracy, slashing burial fees, and declaring "Amargi" (freedom).',
    context: 'Corrupt bureaucrats, palace inspectors, and high priests had seized the lands of peasants and extorted exorbitant fees for weddings, burials, and boat crossings.',
    excerpt: 'The high priest shall no longer come into the garden of a poor mother to take away wood. If the donkey of a poor citizen is coveted by a rich man, the rich man shall not seize it, but must pay for it in fair silver! Urukagina covenanted with the god Ningirsu that the orphan and widow should not fall victim to the mighty.',
    clauseTitle: 'Declaration of Amargi (Freedom)',
    clauseExcerpt: 'He returned mother to child and child to mother; he established liberty (Amargi) throughout the land.',
    clauseMeaning: 'The earliest written record of the word "Freedom" or "Liberty" in human language.',
    clauseSig: 'The founding charter of social justice, anti-corruption legislation, and civil protection.',
    impact: 'Established the moral standard across Mesopotamia that rulers are accountable for protecting the vulnerable.',
    audio: 'I have banished the greedy inspectors from our orchards and canals! No longer shall the wealthy seize the fields of the poor or rob the widow. By the power of Ningirsu, I declare Amargi: liberty and justice for every citizen of Lagash!'
  },
  {
    id: 'anc_meso_sargon_akkad_unification',
    title: 'The Imperial Unification Inscription: From the Persian Gulf to the Mediterranean',
    origTitle: 'The Historical Inscription of Sargon of Akkad',
    ruler: 'Sargon of Akkad (Sharru-kin)',
    titleRole: 'King of Kish, Akkad, and Sumer ("Founder of the First Empire")',
    year: -2334,
    yearDisplay: 'c. 2334 BC',
    era: 'Antiquity',
    cat: 'Monumental Speeches',
    civ: 'Akkadian Empire (Mesopotamia)',
    loc: 'Nippur / Agade, Mesopotamia (Iraq)',
    lang: 'Old Akkadian (Semitic)',
    format: 'Inscribed Basalt Stela Copies',
    pres: 'Penn Museum, Philadelphia / Louvre Museum, Paris',
    quote: 'Sargon, King of Akkad, overseer of Ishtar, King of Kish, anointed priest of Anu: he washed his weapons in the Lower Sea and marched unto the Upper Sea.',
    summary: 'Sargon proclaims the conquest of all Sumerian city-states and the creation of the world\'s first multinational empire with a centralized standing army.',
    context: 'Rising from humble origins (the legend of the reed basket on the Euphrates), Sargon defeated King Lugalzagesi of Umma, knocking down city walls and unifying Mesopotamia.',
    excerpt: 'Sargon the King fought thirty-four battles; he tore down the walls of the cities unto the edge of the sea. Fifty-four hundred soldiers ate bread daily before him in his palace at Agade. The god Dagan gave unto him the Upper Country: Mari, Yarmuti, and Ebla, as far as the Cedar Forest and the Silver Mountains. Let any king who would rival me conquer what I have conquered!',
    clauseTitle: 'Establishment of the Royal Professional Army',
    clauseExcerpt: 'Fifty-four hundred warriors eat bread daily before the presence of the King.',
    clauseMeaning: 'Institution of a permanent state-funded professional standing army.',
    clauseSig: 'Documented birth of imperial governance, trans-regional administration, and the world\'s first empire.',
    impact: 'Served as the foundational archetype for every subsequent empire in Near Eastern and world history.',
    audio: 'I am Sargon, King of the Four Quarters of the World! Thirty-four battles I fought; thirty-four cities surrendered to my banners. In the waters of the Persian Gulf I washed my victorious weapons, and from the silver mountains to the sea, all men bow to Akkad!'
  },
  {
    id: 'anc_meso_naram_sin_stele',
    title: 'The Victory Stele of Naram-Sin over the Lullubi Mountain Kings',
    origTitle: 'The Naram-Sin Victory Stele at Susa',
    ruler: 'Naram-Sin',
    titleRole: 'King of Akkad and the First Deified Monarch ("God of Akkad")',
    year: -2250,
    yearDisplay: 'c. 2250 BC',
    era: 'Antiquity',
    cat: 'Monumental Speeches',
    civ: 'Akkadian Empire',
    loc: 'Zagros Mountains / Susa, Elam (Iran)',
    lang: 'Old Akkadian',
    format: 'Pink Sandstone Stele (2 meters tall)',
    pres: 'Louvre Museum, Paris, France',
    quote: 'Naram-Sin, the mighty, God of Akkad, King of the Four Quarters of the World: Satuni, King of the Lullubi, assembled against him, and Naram-Sin cast him down from the heights.',
    summary: 'Naram-Sin commemorates his alpine campaign into the Zagros Mountains, depicting himself wearing the horned helmet of divinity climbing toward the solar stars.',
    context: 'The fierce mountain tribes of the Zagros threatened Mesopotamian trade routes. Naram-Sin led his troops into precipitous cliffs to secure complete submission.',
    excerpt: 'Naram-Sin the mighty went forth against the mountains of Mount Pirini. Satuni rallied the mountaineers in the gorges, but the God of Akkad struck them down like thunderbolts. He climbed the mountain peaks on the bodies of his slain enemies, while the sun and moon shone their rays upon his crowned head.',
    clauseTitle: 'Self-Deification of the Sovereign',
    clauseExcerpt: 'By the consensus of the citizens of Agade, Naram-Sin was acclaimed as the living God of their city.',
    clauseMeaning: 'Transformation of political kingship into divine kingship.',
    clauseSig: 'A revolutionary masterpiece of narrative art and the first documented case of royal self-deification.',
    impact: 'Redefined royal ideology from servant of the gods to living embodiment of cosmic power.',
    audio: 'High into the misty crags of the Zagros Mountains I led my warriors! The mountain kings thought their cliffs would shelter them, but my arrows reached their eagles\' nests. I trampled their pride beneath my feet under the watchful eyes of the stars.'
  },
  {
    id: 'anc_meso_gudea_lagash_temple',
    title: 'The Cylinders of Gudea: Building the Eninnu Temple of Ningirsu',
    origTitle: 'Cylinders A and B of Gudea of Lagash',
    ruler: 'Gudea of Lagash',
    titleRole: 'Ensi (Governor-King) of Lagash ("The Pious Ruler")',
    year: -2120,
    yearDisplay: 'c. 2120 BC',
    era: 'Antiquity',
    cat: 'Religious & Philosophical Texts',
    civ: 'Neo-Sumerian Renaissance',
    loc: 'Girsu (Tello), Sumer (Iraq)',
    lang: 'Classical Sumerian Cuneiform',
    format: 'Inscribed Terracotta Cylinders (Longest Sumerian literary text)',
    pres: 'Louvre Museum, Paris, France',
    quote: 'In the city where the temple was built, no complaint was heard; the creditor did not enter the debtor’s house; the mother did not punish her child, and all walked in brotherhood.',
    summary: 'Gudea describes receiving a divine architectural vision in a dream to construct the Eninnu temple, enforcing peace, social harmony, and labor solidarity during construction.',
    context: 'During the Neo-Sumerian revival after the Gutian invasion, Gudea renounced imperial conquest in favor of monumental piety, arts, literature, and social peace.',
    excerpt: 'Ningirsu appeared in my dream: Build my house like a mountain rising from the waters! So Gudea purified the city. For seven days, no grain was measured for debts; the whip was put away; the slave woman was equal to her mistress; the master walked beside his servant. Gold came from Meluhha, cedar from Amanus, copper from Magan, all dedicated to the shrine of justice.',
    clauseTitle: 'Enforced Civil Harmony during Sacred Construction',
    clauseExcerpt: 'No lawsuit shall be conducted; the creditor shall stay away from the door of the debtor.',
    clauseMeaning: 'Suspension of all civil disputes, debts, and punishments during holy projects.',
    clauseSig: 'The longest and most beautifully composed literary work surviving in the Sumerian language.',
    impact: 'Established the model of the philosopher-architect ruler who seeks divine blessing through cultural creation rather than war.',
    audio: 'Ningirsu whispered in my sleep: Build my sanctuary like a mountain of light! During the days of building, no creditor harassed the poor, no servant felt the rod of anger, and all citizens labored together in joyful unity.'
  },
  {
    id: 'anc_meso_code_of_ur_nammu',
    title: 'The Code of Ur-Nammu: The World’s Oldest Extant Legal Code',
    origTitle: 'The Law Code of Ur-Nammu at Ur and Nippur',
    ruler: 'Ur-Nammu',
    titleRole: 'King of Ur, Sumer, and Akkad (Founder of the Third Dynasty of Ur)',
    year: -2100,
    yearDisplay: 'c. 2100 BC',
    era: 'Antiquity',
    cat: 'Legal Codes & Edicts',
    civ: 'Third Dynasty of Ur (Neo-Sumerian Empire)',
    loc: 'Ur / Nippur, Southern Mesopotamia (Iraq)',
    lang: 'Sumerian Cuneiform',
    format: 'Inscribed Clay Tablets',
    pres: 'Istanbul Archaeology Museum, Turkey',
    quote: 'Ur-Nammu, mighty warrior, King of Ur: He eliminated enmity, violence, and cries for justice. He established equity in the land and banned false weights.',
    summary: 'The earliest surviving formal code of law in human history, pioneering monetary fines rather than physical mutilation for bodily injuries.',
    context: 'Ur-Nammu unified Sumer and Akkad into the highly bureaucratic Ur III empire, standardizing weights, measures, taxes, and legal rights.',
    excerpt: 'Prologue: By the laws of Shamash, Ur-Nammu did not deliver the orphan to the rich; he did not deliver the widow to the powerful; he did not deliver the man of one shekel to the man of one mina. He standardized the copper measure of thirty sila, the bronze balance weights, and the silver shekel. Laws: If a man knocks out the eye of another man, he shall pay one-half mina of silver. If a man cuts off the nose of another man, he shall weigh out forty shekels of silver.',
    clauseTitle: 'Substitution of Monetary Restitution for Retribution',
    clauseExcerpt: 'If a man severs the foot of another man, he shall pay ten shekels of silver.',
    clauseMeaning: 'Replacement of the barbaric lex talionis ("an eye for an eye") with civil financial compensation.',
    clauseSig: 'Predates the Code of Hammurabi by over 300 years and represents the true dawn of statutory jurisprudence.',
    impact: 'Founded civil compensation law, contract law, and standardized commercial measurements across the ancient world.',
    audio: 'I am Ur-Nammu, shepherd of Sumer! I took the false weights from the marketplace; I protected the widow from the extortion of the powerful. Let justice be measured in silver, not in blood, that peace may endure throughout our cities.'
  },
  {
    id: 'anc_meso_shulgi_royal_hymn',
    title: 'The Royal Hymn of King Shulgi: The Master Runner and Scholar-King',
    origTitle: 'Shulgi Hymn A (Self-Praise of the King of the Four Quarters)',
    ruler: 'Shulgi of Ur',
    titleRole: 'King of Ur, Sumer, and Akkad ("Builder of the Royal Roads")',
    year: -2050,
    yearDisplay: 'c. 2050 BC',
    era: 'Antiquity',
    cat: 'Monumental Speeches',
    civ: 'Third Dynasty of Ur (Mesopotamia)',
    loc: 'Ur / Nippur, Iraq',
    lang: 'Classical Sumerian',
    format: 'Clay Cuneiform Tablets',
    pres: 'University of Pennsylvania Museum / British Museum',
    quote: 'I, Shulgi, the king, am a runner who never tires! In a single day of driving hail, I ran from Nippur to Ur, a distance of one hundred miles, and returned to sacrifice before Enlil.',
    summary: 'King Shulgi proclaims his extraordinary intellectual, athletic, and musical accomplishments, celebrating his creation of the world\'s first royal highway system with way-stations.',
    context: 'Reigning for 46 years, Shulgi standardized the Sumerian school curriculum (the Edubba), introduced postal courier routes, and composed hymns praising his own royal virtues.',
    excerpt: 'I am a king who loves justice. I have mastered the cuneiform tablets; no scribe can rival my calculations. I built broad roads and set up rest-houses with cold water and gardens along the way, that travelers might find shelter. And to prove my vigor to my people, in one stormy day, between morning and nightfall, I ran one hundred miles between Nippur and Ur, celebrating the festival in both sanctuaries without stumbling!',
    clauseTitle: 'Creation of Royal Highways and Way-Stations',
    clauseExcerpt: 'I measured the miles; I planted shade trees along the roads, and established inns so that the wayfarer might not be prey to bandits.',
    clauseMeaning: 'State investment in public infrastructure, postal networks, and traveler security.',
    clauseSig: 'The earliest record of an organized state postal courier network and highway infrastructure.',
    impact: 'Created the administrative framework of road relays later adopted by the Persians, Romans, and Incas.',
    audio: 'I am Shulgi, who reads the tablets of heaven and runs like the wind across the plains! I paved the broad highways of Sumer, planting trees and building inns for every traveler. Wisdom and strength unite upon my throne!'
  },
  {
    id: 'anc_meso_code_of_hammurabi_epilogue',
    title: 'The Epilogue to the Code of Hammurabi: "Let the Oppressed Man Come Before My Stela"',
    origTitle: 'The Law Code of Hammurabi (Epilogue)',
    ruler: 'Hammurabi',
    titleRole: 'King of Babylon ("The King of Justice")',
    year: -1754,
    yearDisplay: '1754 BC',
    era: 'Antiquity',
    cat: 'Legal Codes & Edicts',
    civ: 'Old Babylonian Empire',
    loc: 'Babylon, Mesopotamia (Found at Susa, Iran)',
    lang: 'Old Babylonian (Akkadian Cuneiform)',
    format: 'Carved Black Diorite Stele (2.25 meters tall)',
    pres: 'Louvre Museum, Paris, France',
    quote: 'Let any oppressed man who has a cause come into the presence of my statue as King of Justice, and let him read the inscription on my monument, and let him understand his rights, and let his heart rejoice!',
    summary: 'Hammurabi concludes his 282 laws by inviting any aggrieved subject to read the public stone, declaring eternal blessings on rulers who preserve his laws and curses on tyrants who alter them.',
    context: 'Hammurabi carved his comprehensive legal compilation onto giant diorite stelae erected in public squares so no corrupt judge could claim ignorance of statutory law.',
    excerpt: 'I am Hammurabi, the noble king. I did not neglect the black-headed people whom Enlil gave me. In my bosom I carried the people of Sumer and Akkad; in my wisdom I restrained them, that the strong might not injure the weak, that the orphan and the widow might receive justice. Let the oppressed man who is involved in a lawsuit come before my image; let him read my stela, and hear my precious words! The inscription will explain his case, he will find his justice, and his heart will be eased.',
    clauseTitle: 'Universal Public Access to Statutory Justice',
    clauseExcerpt: 'Let my stela enlighten him in his cause, so that he may pray: Hammurabi is indeed a lord who is like a father to his people.',
    clauseMeaning: 'Establishment of the rule of law: laws must be published, fixed, accessible, and binding on all citizens and kings.',
    clauseSig: 'The crowning masterpiece of ancient statutory jurisprudence and public legal transparency.',
    impact: 'Deeply influenced biblical law, Roman jurisprudence, and modern concepts of statutory transparency.',
    audio: 'Let any oppressed man who has suffered wrong come stand before my stela! Let him read my words, and let his heart find comfort. The strong shall not oppress the weak in Babylon; as long as the stars shine, my laws shall stand for justice!'
  },
  {
    id: 'anc_meso_ammi_saduqa_edict',
    title: 'The Edict of Ammi-Saduqa: General Debt Forgiveness and Jubilee Cancellation',
    origTitle: 'The Misharum Edict of King Ammi-Saduqa',
    ruler: 'Ammi-Saduqa',
    titleRole: 'King of the First Dynasty of Babylon',
    year: -1646,
    yearDisplay: '1646 BC',
    era: 'Antiquity',
    cat: 'Legal Codes & Edicts',
    civ: 'Old Babylonian Empire',
    loc: 'Babylon / Sippar, Mesopotamia (Iraq)',
    lang: 'Old Babylonian Akkadian',
    format: 'Clay Cuneiform Tablet',
    pres: 'British Museum, London, United Kingdom',
    quote: 'Because the king has established justice (Misharum) in the land: the debt tablets of peasants are smashed, and debt-slaves are restored to their families.',
    summary: 'A comprehensive royal decree abolishing peasant agricultural debts, releasing citizens sold into debt bondage, and smashing loan tablets to prevent economic collapse.',
    context: 'Compound interest and bad harvests regularly threatened to enslave the free peasantry. Babylonian kings routinely issued "Misharum" decrees upon accession to reset the economy.',
    excerpt: 'The King has established justice throughout the realm. The tablet of the debtor is broken. If an officer or merchant has seized a citizen of Babylon or his wife or child for unpaid debts, he must release them free of obligation. Whoever continues to collect on broken tablets shall be put to death. The barley tax of the peasant is remitted, that the land may breathe anew.',
    clauseTitle: 'Cancellation of Agrarian Consumer Debt',
    clauseExcerpt: 'Debts contracted for consumption are canceled; debts contracted for commercial trade remain valid.',
    clauseMeaning: 'Sophisticated legal distinction between predatory consumer distress debt and productive commercial credit.',
    clauseSig: 'The direct institutional ancestor of the Biblical Jubilee year (Leviticus 25).',
    impact: 'Demonstrated ancient state interventions to prevent societal collapse caused by extreme debt concentration.',
    audio: 'Hear this, all merchants and tax gatherers! The king has proclaimed Misharum! The debt tablets are shattered in the dust. Release the sons and daughters of Babylon from bondage, and let every farmer return in freedom to his ancestral field!'
  },
  {
    id: 'anc_meso_ashurnasirpal_banquet_stele',
    title: 'The Great Banquet Stele of Nimrud: The Inaugural Feast for 69,574 Guests',
    origTitle: 'The Banquet Inscription of Ashurnasirpal II at Kalhu',
    ruler: 'Ashurnasirpal II',
    titleRole: 'King of the Neo-Assyrian Empire',
    year: -879,
    yearDisplay: '879 BC',
    era: 'Antiquity',
    cat: 'Monumental Speeches',
    civ: 'Neo-Assyrian Empire',
    loc: 'Kalhu (Nimrud), Northern Iraq',
    lang: 'Standard Babylonian Akkadian',
    format: 'Carved Sandstone Wall Stele',
    pres: 'Mosul Museum, Iraq / British Museum',
    quote: 'For ten days I feasted 69,574 invited subjects and foreign envoys from all lands; I gave them food, I gave them wine, I washed them and sent them back to their homes in peace and joy.',
    summary: 'Ashurnasirpal II celebrates the inauguration of his new imperial capital Kalhu (Nimrud) with a mammoth, meticulously cataloged ten-day feast for nearly 70,000 guests.',
    context: 'Having rebuilt the Assyrian military machine, the king relocated his capital and displayed his colossal agricultural wealth and generosity to citizens, workers, and foreign ambassadors.',
    excerpt: 'When I inaugurated the palace of Kalhu, I slaughtered 1,000 fattened oxen, 14,000 sheep, 1,000 spring lambs, 500 stags, 1,000 ducks, 10,000 doves, 10,000 jars of beer, and 10,000 skins of wine. For ten days, 47,074 men and women of my realm, 5,000 foreign dignitaries from Tyre, Sidon, and Carchemish, 16,000 citizens of Kalhu, and 1,500 palace officials ate and drank together in honor of Ashur. I honored them and sent them home in peace.',
    clauseTitle: 'Universal Imperial Hospitality',
    clauseExcerpt: 'Every guest was bathed, perfumed, fed with choice meats, and dismissed with royal gifts in peace.',
    clauseMeaning: 'Use of colossal state hospitality to bind multi-ethnic subjects into imperial loyalty.',
    clauseSig: 'The most detailed food, catering, and guest-list registry preserved from the ancient world.',
    impact: 'Established Nimrud as the glittering imperial heart of the Assyrian world for centuries.',
    audio: 'Seventy thousand guests sat at my royal tables for ten days of rejoicing! Oxen, sheep, choice game, and rivers of wine we poured out for envoys from every nation under heaven. I bathed them, honored them, and sent them home in peace to proclaim the majesty of Assyria!'
  },
  {
    id: 'anc_meso_tiglath_pileser_annals',
    title: 'The Annals of Military Reform and the Standing Army (Kisir Sharruti)',
    origTitle: 'The Nimrud Slab Annals of Tiglath-Pileser III',
    ruler: 'Tiglath-Pileser III (Pul)',
    titleRole: 'King of Assyria and Emperor of the Near East',
    year: -745,
    yearDisplay: '745 BC',
    era: 'Antiquity',
    cat: 'Legal Codes & Edicts',
    civ: 'Neo-Assyrian Empire',
    loc: 'Nimrud (Kalhu), Assyria (Iraq)',
    lang: 'Neo-Assyrian Akkadian',
    format: 'Carved Basalt Palace Reliefs',
    pres: 'British Museum, London, United Kingdom',
    quote: 'I reorganized the armies of Ashur: no longer shall we await the harvest before assembling! A standing host of horsemen, iron-clad spearmen, and siege engineers shall garrison every province throughout the year.',
    summary: 'Tiglath-Pileser III overhauls the Assyrian state, creating the world\'s first professional, year-round standing army with specialized siege engineering and combined-arms tactics.',
    context: 'Prior to Tiglath-Pileser III, ancient armies disbanded during harvest seasons. The king replaced the seasonal militia with a professional permanent army recruited from across the empire.',
    excerpt: 'The King decrees: The Kisir Sharruti (Royal Corps) is established. Cavalrymen armed with long lances and composite bows shall ride beside chariots; corps of miners shall carry iron pickaxes and battering rams on wheels. Provinces shall be reduced in size under royal governors directly responsible to the King, and roads shall be maintained with swift messenger posts that no revolt may escape vengeance.',
    clauseTitle: 'Institutionalization of Year-Round Professional Warfare',
    clauseExcerpt: 'Troops shall be paid in royal silver and fed from provincial magazines, standing ready in winter as in summer.',
    clauseMeaning: 'Ending seasonal military dependency and pioneering modern military professionalization.',
    clauseSig: 'Created the invincible military apparatus that conquered Babylon, Syria, Israel, and Egypt.',
    impact: 'The structural archetype for modern standing armies and centralized imperial logistics.',
    audio: 'No longer shall Assyria wait for the wheat to be gathered before we march! Our legions are armed with tempered iron, ready to ride through winter snow or summer heat. We march with siege engines that shatter city walls like pottery.'
  },
  {
    id: 'anc_meso_sennacherib_taylor_prism',
    title: 'The Taylor Prism: Sennacherib’s Siege of Jerusalem and Defiance of Hezekiah',
    origTitle: 'The Sennacherib Prism Inscription (Third Campaign)',
    ruler: 'Sennacherib',
    titleRole: 'King of Assyria and Builder of Nineveh',
    year: -701,
    yearDisplay: '701 BC',
    era: 'Antiquity',
    cat: 'Monumental Speeches',
    civ: 'Neo-Assyrian Empire',
    loc: 'Nineveh, Assyria (Mosul, Iraq)',
    lang: 'Neo-Assyrian Cuneiform',
    format: 'Six-Sided Hexagonal Baked Clay Prism',
    pres: 'British Museum, London, United Kingdom',
    quote: 'As for Hezekiah the Judahite, who did not submit to my yoke: forty-six of his strong walled cities I besieged and took. Himself I locked up in Jerusalem, his royal city, like a bird in a cage!',
    summary: 'Sennacherib proclaims his crushing campaign across the Levant, detailing his siege of Jerusalem and extracting thirty talents of gold from King Hezekiah.',
    context: 'King Hezekiah of Judah joined an anti-Assyrian rebellion supported by Egypt. Sennacherib responded with devastating force, destroying Lachish and trapping Hezekiah.',
    excerpt: 'Hezekiah of Judah did not bow to my authority. By ramps of packed earth, battering rams, and fierce assaults of foot soldiers, I conquered 46 fortified towns. Two hundred thousand, one hundred and fifty people, young and old, male and female, horses, mules, and camels without number I carried away as spoil. Hezekiah himself I shut up like a caged bird in Jerusalem. He was overwhelmed by the terrifying splendor of my majesty, sending thirty talents of gold and his daughters as tribute to Nineveh.',
    clauseTitle: 'Tribute Assessment on the Kingdom of Judah',
    clauseExcerpt: 'Thirty talents of gold, eight hundred talents of silver, and his elite warriors did Hezekiah dispatch to my presence.',
    clauseMeaning: 'Enforcement of crushing financial tribute in exchange for preserving the royal dynasty in Jerusalem.',
    clauseSig: 'One of the most famous archaeological correlations confirming biblical historical accounts (2 Kings 18-19 / Isaiah 36-37).',
    impact: 'Preserves the Assyrian imperial perspective on one of the pivotal sieges in ancient Near Eastern history.',
    audio: 'Like a bird trapped in a cage, I shut up Hezekiah in Jerusalem! Forty-six of his mighty fortresses fell before my siege towers. He saw the gleam of our iron spears and sent thirty talents of gold to beg for mercy before my throne at Nineveh.'
  },
  {
    id: 'anc_meso_ashurbanipal_library_colophon',
    title: 'The Royal Colophon of the Library of Nineveh: Gathering All Human Knowledge',
    origTitle: 'The Colophon of Ashurbanipal on Cuneiform Tablets',
    ruler: 'Ashurbanipal',
    titleRole: 'King of the World, King of Assyria ("The Scholar Emperor")',
    year: -648,
    yearDisplay: 'c. 648 BC',
    era: 'Antiquity',
    cat: 'Charters & Constitutions',
    civ: 'Neo-Assyrian Empire',
    loc: 'Nineveh (Kuyunjik), Northern Iraq',
    lang: 'Neo-Assyrian Akkadian',
    format: 'Clay Cuneiform Tablets',
    pres: 'British Museum, London, United Kingdom',
    quote: 'I, Ashurbanipal, learned the wisdom of Nabu, all the scribal art of every kind. I have read the intricate tablets of Sumer and the dark Akkadian script which is difficult to interpret; I have studied inscriptions on stone from before the Flood!',
    summary: 'Ashurbanipal decrees the systematic collection, translation, and preservation of every literary, scientific, medical, and astronomical tablet in the world, founding the world\'s first systematically organized library.',
    context: 'Unlike most ancient kings who boasted only of military brutality, Ashurbanipal took supreme pride in his literacy, mathematical skills, and encyclopedic library at Nineveh.',
    excerpt: 'The King commands his agents: Search out all rare tablets in Babylon, Borsippa, and Nippur that are not in Assyria, and bring them to my palace! Search for the amulets, incantations, the Epic of Gilgamesh, the Enuma Elish, treatises on medicine and astrology! Let no tablet be spared. I have assembled them in my library in Nineveh for my royal reading and for future generations, that wisdom may never perish from the earth.',
    clauseTitle: 'Imperial Preservation Mandate for All Literature',
    clauseExcerpt: 'Whoever shall erase my name or steal this tablet, may Nabu and Ashur cast down his soul in darkness.',
    clauseMeaning: 'Severe curse protection against censorship, theft, and destruction of scholarly archives.',
    clauseSig: 'The Library of Ashurbanipal preserved over 30,000 tablets, saving the Epic of Gilgamesh for modern humanity.',
    impact: 'The foundational ancestor of the Library of Alexandria and all modern institutional research libraries.',
    audio: 'I have read the mysterious tablets carved before the Great Deluge! From all corners of the world I commanded my scribes to bring every scroll of medicine, astronomy, and poetry into my palace at Nineveh. Weapons rust, but wisdom carved in clay endures forever.'
  },
  {
    id: 'anc_meso_nebuchadnezzar_ishtar_gate',
    title: 'The Dedication Inscription of the Ishtar Gate of Babylon',
    origTitle: 'The Glazed Brick Inscription of the Ishtar Gate',
    ruler: 'Nebuchadnezzar II',
    titleRole: 'King of Babylon and Restorer of the Empire',
    year: -575,
    yearDisplay: 'c. 575 BC',
    era: 'Antiquity',
    cat: 'Monumental Speeches',
    civ: 'Neo-Babylonian (Chaldean) Empire',
    loc: 'Babylon (Hillah, Iraq)',
    lang: 'Neo-Babylonian Akkadian',
    format: 'Lapis-Lazuli Colored Glazed Ceramic Brick Inscriptions',
    pres: 'Pergamon Museum, Berlin, Germany',
    quote: 'I, Nebuchadnezzar, King of Babylon: I pulled down these gates and laid their foundations deep at the water-table with asphalt and bricks. I caused them to be adorned with glazed blue bricks upon which bulls and dragons were depicted.',
    summary: 'Nebuchadnezzar II dedicates the towering blue-glazed Ishtar Gate and the Processional Way, proclaiming Babylon the eternal cultural wonder of the world.',
    context: 'Following the fall of Assyria, Nebuchadnezzar transformed Babylon into the world\'s largest metropolis, constructing the Hanging Gardens, the Etemenanki Ziggurat, and the Ishtar Gate.',
    excerpt: 'I am Nebuchadnezzar, faithful shepherd chosen by Marduk. The city gates had become too low through the rising of the road. I tore them down and rebuilt them of shining blue glazed bricks, fixing cedar doors banded with bronze. Upon their walls I placed fierce dragons (Mushkhushshu) and wild bulls in dazzling relief, that all mankind might gaze upon them in wonder and fear. O Lord Marduk, look with joy upon my handiwork and grant me long life and eternal dominion!',
    clauseTitle: 'Sacred Urban Architectural Dedication',
    clauseExcerpt: 'Let these gates stand resilient against floods and time, welcoming the sacred bark of Marduk during the New Year Akitu festival.',
    clauseMeaning: 'Integration of civic monumental engineering with sacred cosmic renewal festivals.',
    clauseSig: 'One of the most spectacular architectural achievements in antiquity, preserved in complete reconstructed glory.',
    impact: 'Made Babylon the proverbial golden city of antiquity and a symbol of breathtaking urban grandeur.',
    audio: 'I rebuilt the gates of Babylon with gleaming lapis-blue tiles and fierce dragons of fire! Let all nations look upon these walls and stand in awe. As long as the Euphrates rolls its waters, Babylon shall stand supreme among the cities of the earth.'
  },
  {
    id: 'anc_meso_cyrus_cylinder',
    title: 'The Cyrus Cylinder: The Charter of Freedom and Repatriation of Exiles',
    origTitle: 'The Clay Cylinder Decree of Cyrus the Great',
    ruler: 'Cyrus the Great (Kourosh)',
    titleRole: 'King of Kings, Shahanshah of the Achaemenid Persian Empire',
    year: -539,
    yearDisplay: '539 BC',
    era: 'Antiquity',
    cat: 'Human Rights & Declarations',
    civ: 'Achaemenid Persian Empire',
    loc: 'Babylon, Mesopotamia (Discovered at Amran hill)',
    lang: 'Babylonian Cuneiform (Akkadian)',
    format: 'Inscribed Clay Barrel Cylinder',
    pres: 'British Museum, London, United Kingdom',
    quote: 'I returned to these sacred cities on the other side of the Tigris the sanctuaries which had been in ruins; I gathered all their inhabitants and returned them to their ancestral homes.',
    summary: 'Cyrus the Great enters Babylon without battle, abolishing forced labor, restoring religious freedom, and decreeing the repatriation of all exiled peoples (including the Jewish people to Jerusalem).',
    context: 'Cyrus overthrew the unpopular Babylonian king Nabonidus. Instead of slaughtering the population, Cyrus respected Marduk, freed enslaved captives, and pioneered enlightened tolerance.',
    excerpt: 'When I entered Babylon in peace, amidst joy and jubilation, I founded my sovereign seat in the palace of princes. My numerous troops walked through Babylon in peace; I permitted no one to terrorize the people of Sumer and Akkad. I relieved their weariness; I freed them from their bonds. I restored the statues of their gods to their native shrines. And all their peoples who had been deported into exile, I gathered together and sent them home in peace to rebuild their temples.',
    clauseTitle: 'Universal Religious Liberty and Repatriation',
    clauseExcerpt: 'I permitted all people to rebuild their ruined temples and worship their ancestral gods in liberty.',
    clauseMeaning: 'Prohibition of cultural assimilation and protection of indigenous religious freedom.',
    clauseSig: 'Universally hailed as the world’s first declaration of human rights and cultural tolerance.',
    impact: 'Ended the Babylonian Captivity, enabled the rebuilding of the Second Temple in Jerusalem, and established the governance model of the Persian Empire.',
    audio: 'I entered the gates of Babylon with peace and brotherhood in my hands! I forbade my soldiers from harming any citizen or looting any home. I broke the chains of the captives and said to every exile: Go back to your homelands, rebuild your holy temples, and live in freedom under the sun.'
  },
  {
    id: 'anc_persia_darius_behistun_credo',
    title: 'The Behistun Inscription: The Divine Triumph and Royal Ethical Credo',
    origTitle: 'The Great Behistun Trilingual Rock Inscription (DB)',
    ruler: 'Darius I the Great',
    titleRole: 'King of Kings, King of Persia, King of Countries (Shahanshah)',
    year: -520,
    yearDisplay: '520 BC',
    era: 'Antiquity',
    cat: 'Monumental Speeches',
    civ: 'Achaemenid Persian Empire',
    loc: 'Mount Behistun, Kermanshah Province, Iran',
    lang: 'Old Persian Cuneiform, Elamite, and Babylonian (Trilingual)',
    format: 'Monumental Rock-face Cliff Inscription (100 meters above ground)',
    pres: 'Mount Behistun cliff face, Iran (UNESCO World Heritage Site)',
    quote: 'Says Darius the King: For this reason Ahuramazda bore me aid, because I was not wicked, I was not a liar, I was not a tyrant, neither I nor my family. I ruled according to righteousness (Arta).',
    summary: 'Darius I recounts his suppression of nineteen rebellions in a single year, engraving his ethical code of truth versus the Lie (Drauga) on a sheer cliff face.',
    context: 'Following the death of Cambyses and the crisis of the magus Gaumata, Darius seized the throne and restored the Persian Empire from Egypt to the Indus River.',
    excerpt: 'I am Darius the Great King, King of Kings, King in Persia, King of countries. Says Darius: These are the countries which came unto me by the favor of Ahuramazda: Persia, Elam, Babylonia, Assyria, Arabia, Egypt, Bactria, Sogdiana, Gandhara, Scythia. Thou who shalt be king hereafter, protect thyself vigorously from the Lie! The man who is a lie-follower, punish him well. Love the man who speaks truth, and do not reward the violent. By the grace of Ahuramazda, I have made this realm secure.',
    clauseTitle: 'The Royal Ethical Credo against the Lie (Drauga)',
    clauseExcerpt: 'Whoever honors the Truth, him will I favor; whoever follows the Lie, him will I punish.',
    clauseMeaning: 'Theological and ethical duty of the sovereign to champion cosmic Truth against falsehood and violence.',
    clauseSig: 'The "Rosetta Stone of Cuneiform" which allowed Sir Henry Rawlinson to decipher cuneiform script in the 1840s.',
    impact: 'Defined Persian imperial ideology and provided the linguistic key to the rediscovery of ancient Mesopotamian history.',
    audio: 'I am Darius, King of Kings! On this high mountain rock I carved my deeds so that all generations might read them. I was never a tyrant; I never oppressed the humble. I walked in truth and despised the Lie. Guard the truth, and your kingdom shall endure!'
  }
];

console.log(`Loaded ${rawList.length} foundational speeches for Batch 1.`);
