#!/usr/bin/env python3
import json
import os

from monument_data_asia import ASIAN_MONUMENTS_DATA

# Expand to 60 Asian Monuments
additional_asian = [
  {
    "id": "qutub-minar",
    "name": "Qutub Minar & Complex",
    "nativeOrAlternateName": "क़ुतुब मीनार / قطب مینار",
    "category": "Monument & Tower",
    "location": "Mehrauli, South West Delhi",
    "country": "India",
    "region": "Asia",
    "era": "Delhi Sultanate (1199–1220 CE)",
    "yearBuilt": "1199–1220 CE (Completed by Iltutmish; repaired by Firoz Shah Tughlaq 1368)",
    "numericYear": 1199,
    "architectOrCreator": "Qutb ud-Din Aibak (Founder of Mamluk Dynasty); Shams ud-Din Iltutmish",
    "architecturalStyle": "Indo-Islamic Architecture (Ghurid-style Fluted Minaret)",
    "dimensionsAndHeight": "Height: 72.5 m (238 ft); Base diameter: 14.3 m; Top diameter: 2.7 m; 379 spiral stone steps",
    "materialsUsed": "Red sandstone and polished white marble, carved with Kufic Quranic calligraphy",
    "historyAndBackground": "The Qutub Minar is the tallest individual brick minaret in the world. Commenced in 1199 by Qutb ud-Din Aibak, founder of the Delhi Sultanate, following the defeat of Delhi's last Hindu kingdom. Aibak completed the base storey, while his successor and son-in-law Shams ud-Din Iltutmish added three more fluted storeys. After a lightning strike damaged the top in 1368, Sultan Firoz Shah Tughlaq repaired it, adding two higher storeys of white marble and sandstone. The complex also houses the famous 4th-century Gupta-period Iron Pillar of Delhi, which has resisted rust for over 1,600 years due to a high-phosphorus protective passive film.",
    "architecturalMarvels": "Features five distinct tapering storeys separated by balconies supported by intricate clustered stalactite corbels. The lower three storeys feature alternating angular and semicircular fluting, covered in detailed geometric arabesques and Kufic Arabic inscriptions. The monument has withstood major earthquakes, tilting slightly by approximately 65 centimeters from the vertical without compromising structural integrity.",
    "modernStatusAndSignificance": "Designated a UNESCO World Heritage Site in 1993. It is one of Delhi's most visited historical monuments and a foundational monument of Indo-Islamic architectural heritage.",
    "imageUrl": "https://images.unsplash.com/photo-1545232979-fbf677464016?auto=format&fit=crop&q=80&w=1200",
    "fallbackImageUrl": "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&q=80&w=1200",
    "tags": ["Qutub Minar", "Delhi", "India", "Delhi Sultanate", "Indo-Islamic", "UNESCO", "Minaret"],
    "keyFacts": [
      "The tallest brick minaret in the world at 72.5 meters (238 feet)",
      "Surrounded by the 4th-century Iron Pillar that has resisted rust for 1,600 years",
      "Features 379 spiral interior steps leading to the upper viewing balconies",
      "Carved with intricate floral arabesques and Quranic Kufic inscriptions"
    ],
    "unescoStatus": "Inscribed 1993 (Criterion iv)"
  },
  {
    "id": "red-fort-delhi",
    "name": "Red Fort (Lal Qila)",
    "nativeOrAlternateName": "लाल क़िला / قلعہ معلی (Lal Qila / Qila-i-Mubarak)",
    "category": "Palace & Fortress",
    "location": "Old Delhi",
    "country": "India",
    "region": "Asia",
    "era": "Mughal Empire (1638–1648 CE)",
    "yearBuilt": "1638–1648 CE",
    "numericYear": 1648,
    "architectOrCreator": "Ustad Ahmad Lahori, commissioned by Emperor Shah Jahan",
    "architecturalStyle": "Mughal Palace Architecture (Fusion of Persian, Timurid, and Hindu motifs)",
    "dimensionsAndHeight": "Wall perimeter: 2.41 km (1.5 miles); Rampart height: 18 m (city side) to 33 m (river side); Area: 254 acres",
    "materialsUsed": "Massive red sandstone ashlar blocks, white marble pavilions, gilded ornamentation",
    "historyAndBackground": "The Red Fort was the palace citadel of the Mughal Empire in their new capital of Shahjahanabad (Old Delhi). Commissioned by Emperor Shah Jahan in 1638 when he shifted the imperial capital from Agra to Delhi. Formally occupied on May 13, 1648. For over two centuries it housed the Peacock Throne (Takht-i-Taus) and was the ceremonial heart of the empire. In 1739, Persian ruler Nader Shah sacked the fortress, plundering the Peacock Throne and the Koh-i-Noor diamond. Following the Indian Rebellion of 1857, British forces seized the fort, tried the last Mughal emperor Bahadur Shah Zafar inside, and demolished two-thirds of its interior pavilions to build military barracks.",
    "architecturalMarvels": "Enclosed by soaring crenellated octagonal walls of red sandstone. Features the Diwan-i-Aam (Hall of Public Audience) with an exquisite marble throne canopy (jharokha), and the Diwan-i-Khas (Hall of Private Audience), famously inscribed with Amir Khusrau’s Persian verse: 'Agar firdaus bar roo-e zameen ast, Hameen ast-o hameen ast-o hameen ast' ('If there is a paradise on the face of the earth, it is this, it is this, it is this!'). Pavilions were interconnected by the Nahr-i-Bihisht ('Stream of Paradise'), a marble water canal that circulated cool river water through indoor fountains.",
    "modernStatusAndSignificance": "Designated a UNESCO World Heritage Site in 2007. It is the sacred venue where the Prime Minister of India unfurls the national tricolor flag from the Lahore Gate ramparts and delivers the annual Independence Day address on August 15.",
    "imageUrl": "https://images.unsplash.com/photo-1592635196078-9fdc757f27f4?auto=format&fit=crop&q=80&w=1200",
    "fallbackImageUrl": "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&q=80&w=1200",
    "tags": ["Red Fort", "Delhi", "India", "Mughal", "Shah Jahan", "UNESCO", "Independence Day"],
    "keyFacts": [
      "The site where the Prime Minister of India delivers the annual Independence Day address",
      "Originally housed the legendary gemstone-encrusted Peacock Throne and the Koh-i-Noor",
      "Features indoor cooling canals known as the 'Stream of Paradise' (Nahr-i-Bihisht)",
      "Built by Ustad Ahmad Lahori, the same chief architect who designed the Taj Mahal"
    ],
    "unescoStatus": "Inscribed 2007 (Criteria ii, iii, vi)"
  },
  {
    "id": "golden-temple-amritsar",
    "name": "The Golden Temple (Harmandir Sahib)",
    "nativeOrAlternateName": "ਹਰਿਮੰਦਰ ਸਾਹਿਬ (Sri Harmandir Sahib - Abode of God) / Darbar Sahib",
    "category": "Sacred Temple / Cathedral",
    "location": "Amritsar, Punjab",
    "country": "India",
    "region": "Asia",
    "era": "Sikh Era (Founded 1577; Gilded 1830 CE)",
    "yearBuilt": "Founded 1581–1604 CE; Gilded by Maharaja Ranjit Singh 1830 CE",
    "numericYear": 1604,
    "architectOrCreator": "Guru Arjan Dev (5th Sikh Guru); Foundation stone laid by Sufi Saint Mian Mir; Gilded by Maharaja Ranjit Singh",
    "architecturalStyle": "Sikh Architecture (Fusion of Indo-Islamic Mughal and Rajput architectural elements)",
    "dimensionsAndHeight": "Sarovar (Pool of Nectar) size: 154 × 150 m (505 × 492 ft); Depth: 5.1 m; Central sanctum height: 3 stories",
    "materialsUsed": "400 kg of pure 24-karat gold foil sheathing on copper plates, white marble walls with floral pietra dura inlays",
    "historyAndBackground": "The Golden Temple (Harmandir Sahib) is the holiest gurdwara and spiritual center of Sikhism worldwide. Conceived by Guru Amar Das, the fourth Sikh Guru, who excavated the holy pool (Amrit Sarovar). His successor, Guru Arjan Dev, designed the temple and invited Sufi Muslim saint Hazrat Mian Mir of Lahore to lay its foundation stone in December 1588, symbolizing interfaith harmony. Completed in 1604, Guru Arjan installed the primary Sikh scripture, the Adi Granth, with Baba Buddha as first head Granthi. In the 18th century, Afghan invader Ahmad Shah Durrani repeatedly attacked and desecrated the temple. Following the establishment of the Sikh Empire, Maharaja Ranjit Singh rebuilt the shrine in marble and coated the upper storeys in 400 kilograms of pure gold foil in 1830.",
    "architecturalMarvels": "Unlike traditional Hindu temples built on elevated plinths, the Golden Temple is built on a lower level than the surrounding grounds, symbolizing spiritual humility. It features four entrance doors facing North, South, East, and West, explicitly welcoming people of all faiths, castes, and creeds without discrimination. Reached across a marble causeway called the Guru's Bridge. The sanctum's marble panels are decorated with relief floral carvings and Pietra Dura stonework. The complex operates the world's largest free community kitchen (Langar), serving between 50,000 and 100,000 fresh, hot vegetarian meals daily to all visitors free of charge.",
    "modernStatusAndSignificance": "The preeminent spiritual sanctuary of Sikhism. Consistently ranked among the most visited religious destinations on Earth, often welcoming more daily visitors than the Taj Mahal.",
    "imageUrl": "https://images.unsplash.com/photo-1514222134-b57cbb8ce073?auto=format&fit=crop&q=80&w=1200",
    "fallbackImageUrl": "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&q=80&w=1200",
    "tags": ["Golden Temple", "Amritsar", "Punjab", "India", "Sikhism", "Harmandir Sahib", "Gold", "Langar"],
    "keyFacts": [
      "Plated in over 400 kg of pure 24-karat gold leaf by Maharaja Ranjit Singh in 1830",
      "Foundation stone was laid by Muslim Sufi saint Hazrat Mian Mir to symbolize unity",
      "Operates the world's largest free community kitchen, feeding up to 100,000 people daily",
      "Features four open doors facing all four cardinal directions to welcome all humanity"
    ],
    "unescoStatus": "Sacred Global Sikh Shrine"
  },
  {
    "id": "brihadisvara-temple",
    "name": "Brihadisvara Temple (Peruvudaiyar Kovil)",
    "nativeOrAlternateName": "பெருவுடையார் கோயில் (Big Temple of Thanjavur)",
    "category": "Sacred Temple / Cathedral",
    "location": "Thanjavur, Tamil Nadu",
    "country": "India",
    "region": "Asia",
    "era": "Chola Empire Golden Age (1003–1010 CE)",
    "yearBuilt": "1003–1010 CE (Completed in exactly 275 days of consecration year)",
    "numericYear": 1010,
    "architectOrCreator": "Emperor Rajaraja Chola I; Chief Architect Kunjara Mallan Raja Rama Perunthachan",
    "architecturalStyle": "Dravidian Architecture (High Chola Classical Stone Vimana)",
    "dimensionsAndHeight": "Vimana (Tower) height: 66 m (216 ft); Vimana base: 30 m square; Kumbam (capstone) weight: 81 tonnes",
    "materialsUsed": "Over 130,000 tonnes of solid quarried granite blocks assembled entirely without mortar",
    "historyAndBackground": "The Brihadisvara Temple, dedicated to Lord Shiva, is widely recognized as one of the greatest architectural achievements of South Indian civilization. Built by Emperor Rajaraja Chola I between 1003 and 1010 CE at the peak of the maritime Chola Empire, which dominated southern India, Sri Lanka, and Southeast Asian trade routes. Commemorating the emperor's vast military conquests and religious devotion. Built entirely of solid granite in a flat delta region where there are no natural granite deposits for over 60 kilometers. The entire temple was completed in only seven years by thousands of skilled stone carvers, sculptors, and bronze casters.",
    "architecturalMarvels": "The 66-meter Vimana tower was the tallest building in India when built and among the tallest stone structures of the medieval world. Uniquely, the central sanctum tower (Vimana) dwarfs the entrance gateway towers (gopurams). At the very summit sits a single monolithic granite Kumbam (cupola capstone) carved from an 81-tonne block of granite. To hoist this colossal stone to the 66-meter summit without modern cranes, Chola engineers constructed an earthen ramp over 6 kilometers (4 miles) long, rolling the stone up using elephants and log rollers. The entrance houses a monolithic Nandi bull statue carved from a single granite block weighing 20 tonnes. The inner sanctum contains one of the largest monolithic Shiva lingams in India (3.7 m tall).",
    "modernStatusAndSignificance": "Inscribed as a UNESCO World Heritage Site in 1987 as the primary monument of the 'Great Living Chola Temples' group. It celebrated its 1,000th year of continuous worship in 2010.",
    "imageUrl": "https://images.unsplash.com/photo-1621255850948-cfae09849221?auto=format&fit=crop&q=80&w=1200",
    "fallbackImageUrl": "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&q=80&w=1200",
    "tags": ["Brihadisvara", "Thanjavur", "India", "Chola", "Dravidian", "UNESCO", "Granite", "Shiva"],
    "keyFacts": [
      "Built from 130,000 tonnes of solid granite without using any mortar",
      "The 81-tonne single granite capstone at the summit was hauled up a 6-km earthen ramp",
      "There were no granite quarries within 60 km of the construction site",
      "Celebrated 1,000 years of unbroken daily Hindu temple rituals in 2010"
    ],
    "unescoStatus": "Inscribed 1987 (Great Living Chola Temples)"
  },
  {
    "id": "konark-sun-temple",
    "name": "Konark Sun Temple (The Black Pagoda)",
    "nativeOrAlternateName": "କୋଣାର୍କ ସୂର୍ଯ୍ୟ ମନ୍ଦିର (Konarka Surya Mandira)",
    "category": "Sacred Temple / Cathedral",
    "location": "Konark, Puri District, Odisha",
    "country": "India",
    "region": "Asia",
    "era": "Eastern Ganga Dynasty (c. 1250 CE)",
    "yearBuilt": "c. 1250 CE",
    "numericYear": 1250,
    "architectOrCreator": "King Narasimhadeva I; Master Architect Bisu Maharana",
    "architecturalStyle": "Kalinga Architecture (Deula Style)",
    "dimensionsAndHeight": "Jagamohana (Audience Hall) height: 39 m (128 ft); Original lost tower height: ~70 m (230 ft); 24 carved wheels",
    "materialsUsed": "Chlorite, khondalite stone, laterite stone, iron load-bearing lintel beams",
    "historyAndBackground": "The Konark Sun Temple is a monumental 13th-century Hindu temple dedicated to the solar deity Surya. Commissioned around 1250 CE by King Narasimhadeva I of the Eastern Ganga Dynasty to celebrate his military victories over the Turco-Afghan invaders of Bengal. European sailors navigating the Bay of Bengal called it the 'Black Pagoda' because its dark stone tower served as a prominent maritime landmark. Over the centuries, the colossal 70-meter main sanctuary tower collapsed due to soft sand soil subsidence, violent cyclonic storms, and historical raiding. In the early 20th century, British colonial conservators saved the remaining 39-meter Jagamohana (assembly hall) by filling its interior with stone and sand to prevent roof collapse.",
    "architecturalMarvels": "The entire temple is sculpted in the form of a colossal cosmic chariot for the Sun God Surya, mounted on 24 intricately carved stone wheels (each nearly 3 meters in diameter) and pulled by seven leaping horses, representing the seven days of the week and the seven colors of sunlight. The 24 wheels function as remarkably precise sundials: the spokes cast shadows that calculate the exact time of day down to the minute. The stone walls are covered in thousands of bas-reliefs depicting celestial dancers, musicians, royal court processions, mythical beasts, and famous erotic Maithuna sculptures that reflect life's spiritual and physical fullness.",
    "modernStatusAndSignificance": "Designated a UNESCO World Heritage Site in 1984. One of the stone chariot wheels is prominently featured on the reverse of the Indian 10-rupee banknote.",
    "imageUrl": "https://images.unsplash.com/photo-1606293459214-3860538fb9b2?auto=format&fit=crop&q=80&w=1200",
    "fallbackImageUrl": "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&q=80&w=1200",
    "tags": ["Konark", "Sun Temple", "Odisha", "India", "Surya", "Kalinga", "UNESCO", "Black Pagoda"],
    "keyFacts": [
      "Engineered as a colossal stone chariot with 24 giant wheels pulled by 7 stone horses",
      "The spokes of the 3-meter stone wheels function as accurate astronomical sundials",
      "European navigators called it the 'Black Pagoda' and used it as a coastal navigation beacon",
      "The iconic sundial wheel is immortalized on India's official 10-rupee currency note"
    ],
    "unescoStatus": "Inscribed 1984 (Criteria i, iii, vi)"
  },
  {
    "id": "hawa-mahal",
    "name": "Hawa Mahal (Palace of Winds)",
    "nativeOrAlternateName": "हवा महल (Palace of the Breeze)",
    "category": "Palace & Fortress",
    "location": "Jaipur, Rajasthan",
    "country": "India",
    "region": "Asia",
    "era": "Kachwaha Rajput Era (1799 CE)",
    "yearBuilt": "1799 CE",
    "numericYear": 1799,
    "architectOrCreator": "Lal Chand Ustad; Commissioned by Maharaja Sawai Pratap Singh",
    "architecturalStyle": "Fusion of Rajput Architectural Splendor and Mughal Style",
    "dimensionsAndHeight": "Height: 15 m (50 ft); 5 stories; 953 jharokhas (casement windows); Thickness at top: only a few inches",
    "materialsUsed": "Pink and red sandstone, white lime plaster borders, delicate stone filigree latticework",
    "historyAndBackground": "Hawa Mahal is one of the most famous symbols of Jaipur, the 'Pink City'. Built in 1799 by Maharaja Sawai Pratap Singh, grandson of Jaipur's founder Maharaja Sawai Jai Singh. Pratap Singh was an ardent devotee of Lord Krishna, and the five-story palace facade was intentionally designed to resemble the gemstone crown (mukut) of Krishna. Built as an extension of the City Palace to allow royal women observing the strict purdah custom (which prevented them from being seen by commoners in public) to watch daily street processions, vibrant bazaars, and royal festivities in the streets below without being observed.",
    "architecturalMarvels": "The facade features 953 small casements (jharokhas), each decorated with miniature carved sandstone domes and stone latticework. The name 'Hawa Mahal' derives from its ingenious natural air conditioning: the Venturi effect created by the hundreds of perforated openings channels desert breezes through the corridors, keeping interior chambers pleasantly cool even when outside temperatures exceed 40°C in Rajasthani summers. Remarkably, the building has no conventional staircases to connect its five floors—ramps were built instead so royal litters and palanquins could be smoothly pushed up.",
    "modernStatusAndSignificance": "Core component of the UNESCO World Heritage Site 'Jaipur City, Rajasthan' (inscribed 2019). It remains one of the most photographed architectural facades in the world.",
    "imageUrl": "https://images.unsplash.com/photo-1609137144813-7d9921338f24?auto=format&fit=crop&q=80&w=1200",
    "fallbackImageUrl": "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&q=80&w=1200",
    "tags": ["Hawa Mahal", "Jaipur", "Rajasthan", "India", "Pink City", "Rajput", "UNESCO", "Architecture"],
    "keyFacts": [
      "Features 953 intricately carved sandstone jharokhas (latticed windows)",
      "Built so royal court ladies could watch street festivals without being seen from outside",
      "Operates like an evaporative cooling wind tunnel using natural Venturi airflow",
      "Contains no staircases; ramps were constructed so royal palanquins could be carried up"
    ],
    "unescoStatus": "Inscribed 2019 (Jaipur City)"
  },
  {
    "id": "lotus-temple",
    "name": "The Lotus Temple (Bahá'í House of Worship)",
    "nativeOrAlternateName": "لوتس ٹیمپل / कमल मंदिर",
    "category": "Sacred Temple / Cathedral",
    "location": "Kalkaji, New Delhi",
    "country": "India",
    "region": "Asia",
    "era": "Modern Architecture (1980–1986 CE)",
    "yearBuilt": "1980–1986 CE",
    "numericYear": 1986,
    "architectOrCreator": "Fariborz Sahba (Iranian-Canadian Architect); Engineered by Flint & Neill",
    "architecturalStyle": "Modern Biomimetic Expressionist Architecture",
    "dimensionsAndHeight": "Height: 34.3 m (112 ft); Diameter: 70 m (230 ft); Capacity: 2,500 people; 27 petals",
    "materialsUsed": "Pure white Pentelic marble panels from Mount Pentelicus (Greece), dolomite, white silica concrete",
    "historyAndBackground": "The Lotus Temple in New Delhi is a Bahá'í House of Worship open to all humanity regardless of religion, caste, nationality, or gender. Dedicated in December 1986, it was designed by Iranian-born architect Fariborz Sahba, who chose the lotus flower—a sacred symbol of purity and spiritual awakening shared across Hinduism, Buddhism, Jainism, and Islam—to embody the Bahá'í principle of the oneness of humankind and God. In accordance with Bahá'í teachings, there are no religious pictures, statues, altars, or sermons inside; visitors of any spiritual background are invited to sit in contemplative silence or read sacred scriptures of any faith.",
    "architecturalMarvels": "The building is composed of 27 freestanding petals made of thin-shell reinforced concrete clad in pristine white Pentelic marble (the same marble quarry that supplied the ancient Parthenon in Athens). The petals are grouped into clusters of three to form nine equal sides, with nine doors opening into a soaring central hall that seats 2,500 people. Surrounding the temple are nine blue ponds and lush gardens spanning 26 acres, which not only evoke the lotus floating upon water, but also naturally cool the air entering the building through subterranean channels.",
    "modernStatusAndSignificance": "Has won numerous international architectural accolades, including the GlobArt Academy Award and the Institution of Structural Engineers award. One of the most visited buildings on Earth, having welcomed over 100 million people since its inauguration.",
    "imageUrl": "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&q=80&w=1200",
    "fallbackImageUrl": "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&q=80&w=1200",
    "tags": ["Lotus Temple", "Delhi", "India", "Bahai", "Modern", "Architecture", "Lotus"],
    "keyFacts": [
      "Composed of 27 freestanding marble petals arranged in clusters of three on 9 sides",
      "Clad in white Pentelic marble quarried from the same mountain that built the Parthenon",
      "Welcomes followers of every religion and background to pray together in silence",
      "Has welcomed over 100 million visitors since opening in December 1986"
    ],
    "unescoStatus": "Modern Landmark of Global Unity"
  },
  {
    "id": "khajuraho-monuments",
    "name": "Khajuraho Group of Monuments",
    "nativeOrAlternateName": "खजुराहो स्मारक समूह (Khajuraho Temples)",
    "category": "Sacred Temple / Cathedral",
    "location": "Chhatarpur District, Madhya Pradesh",
    "country": "India",
    "region": "Asia",
    "era": "Chandela Dynasty (c. 950–1050 CE)",
    "yearBuilt": "c. 950–1050 CE",
    "numericYear": 1000,
    "architectOrCreator": "Chandela Dynasty Kings, notably Yashovarman and Dhanga",
    "architecturalStyle": "Nagara Architectural Style (Sandhara Temples with Soaring Shikhara spires)",
    "dimensionsAndHeight": "Kandariya Mahadeva height: 31 m (102 ft); 25 surviving temples across 20 km²",
    "materialsUsed": "Fine-grained sandstone quarried from Panna, granite foundation platforms",
    "historyAndBackground": "The Khajuraho Group of Monuments is a celebrated complex of Hindu and Jain temples in central India. Built between 950 and 1050 CE by the Rajput Chandela Dynasty, who ruled the region of Bundelkhand. Historical records indicate that the complex once consisted of 85 temples spread over 20 square kilometers, of which 25 survive in excellent preservation. After the decline of the Chandela dynasty in the 13th century, the temples were swallowed by thick sal forests, which preserved their delicate sandstone sculptures from destruction until British surveyor T.S. Burt rediscovered them in 1838.",
    "architecturalMarvels": "The temples are renowned for their Nagara-style architecture, where the soaring Shikhara spires mimic the sacred mountain peaks of the Himalayas. The Kandariya Mahadeva Temple is the masterpiece of the group, covered in over 870 intricately sculpted stone figures. While famous in popular culture for their erotic mithuna carvings (which actually represent less than 10% of the sculptures), the reliefs depict the full spectrum of medieval Indian life: musicians, dancers, warriors, teachers, mythical beasts, domestic scenes, and deities, reflecting the ancient Hindu doctrine of Purushartha (the four legitimate aims of human life: Dharma, Artha, Kama, and Moksha).",
    "modernStatusAndSignificance": "Inscribed as a UNESCO World Heritage Site in 1986. Celebrated as one of the supreme high points of Indian stone sculpture and artistic expression.",
    "imageUrl": "https://images.unsplash.com/photo-1600100397608-f010e42e0e56?auto=format&fit=crop&q=80&w=1200",
    "fallbackImageUrl": "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&q=80&w=1200",
    "tags": ["Khajuraho", "India", "Chandela", "Hindu", "Jain", "Nagara", "UNESCO", "Sculpture"],
    "keyFacts": [
      "Built between 950 and 1050 CE by the Chandela kings of Bundelkhand",
      "Surviving 25 temples feature both Hindu and Jain sanctuaries side by side",
      "Kandariya Mahadeva Temple alone contains over 870 masterfully carved statues",
      "Preserved for centuries under dense forest foliage until rediscovered in 1838"
    ],
    "unescoStatus": "Inscribed 1986 (Criteria i, iii)"
  },
  {
    "id": "fatehpur-sikri",
    "name": "Fatehpur Sikri & Buland Darwaza",
    "nativeOrAlternateName": "फ़तेहपुर सीकरी (City of Victory)",
    "category": "Archaeological City",
    "location": "Agra District, Uttar Pradesh",
    "country": "India",
    "region": "Asia",
    "era": "Mughal Empire (1571–1585 CE)",
    "yearBuilt": "1571–1585 CE (Buland Darwaza added 1575–1601)",
    "numericYear": 1573,
    "architectOrCreator": "Emperor Akbar the Great",
    "architecturalStyle": "Mughal Imperial Architecture (Akbari Synthesis of Persian and Indian Styles)",
    "dimensionsAndHeight": "Buland Darwaza height: 54 m (177 ft); Citadel length: 3.2 km; Width: 1.6 km",
    "materialsUsed": "Red Sikri sandstone, white marble tomb of Salim Chishti, brass and mother-of-pearl",
    "historyAndBackground": "Fatehpur Sikri was founded in 1571 by Mughal Emperor Akbar the Great as the new imperial capital of his empire. Akbar established the city to honor the revered Sufi saint Sheikh Salim Chishti, who had correctly prophesied the birth of Akbar’s first surviving son and heir, Prince Salim (later Emperor Jahangir). Akbar lived in the city for only 14 years before abandoning it in 1585 to campaign in Punjab and due to a chronic failure of the local water supply. As a result of this sudden abandonment, the city's red sandstone palaces, courtyards, and mosques remained frozen in time as a pristine snapshot of high Mughal culture.",
    "architecturalMarvels": "The entrance to the Jama Masjid mosque is crowned by the monumental Buland Darwaza ('Gate of Magnificence'), which rises 54 meters and ranks among the highest gateway portals in the world. Built to commemorate Akbar's victory over Gujarat in 1573, it is inscribed with a famous quote attributed to Jesus: 'The world is a bridge, pass over it, but build no house upon it.' Inside the courtyard sits the tomb of Salim Chishti, a white marble jewel surrounded by pierced marble jali latticework screens where pilgrims still tie red threads for wish fulfillment. The palace contains the enigmatic Panch Mahal (a five-tiered pillared pavilion) and the Diwan-i-Khas, centering on a massive carved central lotus pillar connected by four aerial stone walkways.",
    "modernStatusAndSignificance": "Designated a UNESCO World Heritage Site in 1986. Regarded by historians as one of the best-preserved royal ghost cities in Asia.",
    "imageUrl": "https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&q=80&w=1200",
    "fallbackImageUrl": "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&q=80&w=1200",
    "tags": ["Fatehpur Sikri", "Akbar", "Mughal", "India", "Buland Darwaza", "UNESCO", "Sufi"],
    "keyFacts": [
      "Built by Emperor Akbar to honor Sufi saint Sheikh Salim Chishti",
      "Buland Darwaza is one of the highest gateway arches in the world at 54 meters",
      "Abandoned after only 14 years of use due to a shortage of fresh water",
      "Features the Diwan-i-Khas with its singular carved stone lotus pillar"
    ],
    "unescoStatus": "Inscribed 1986 (Criteria ii, iii, iv)"
  },
  {
    "id": "victoria-memorial-kolkata",
    "name": "Victoria Memorial Hall",
    "nativeOrAlternateName": "ভিক্টোরিয়া মেমোরিয়াল",
    "category": "Famous Building",
    "location": "Kolkata (Calcutta), West Bengal",
    "country": "India",
    "region": "Asia",
    "era": "British Raj (1906–1921 CE)",
    "yearBuilt": "1906–1921 CE",
    "numericYear": 1921,
    "architectOrCreator": "Sir William Emerson & Vincent Esch; Conceived by Viceroy Lord Curzon",
    "architecturalStyle": "Indo-Saracenic Revival Architecture (Fusion of British, Mughal, and Venetian motifs)",
    "dimensionsAndHeight": "Height: 56 m (184 ft); Dimensions: 103 × 69 m (338 × 228 ft); Grounds: 64 acres",
    "materialsUsed": "Makrana white marble (from the same quarries as the Taj Mahal), Belgian crystal glass, bronze",
    "historyAndBackground": "The Victoria Memorial is a monumental marble building in central Kolkata, constructed between 1906 and 1921 in memory of Queen Victoria, Empress of India. Conceived by Lord Curzon, Viceroy of India, following Victoria’s death in January 1901. Curzon envisioned 'a monumental hall that would stand as a tribute to the Queen and a museum representing the history of India under the British Crown.' Funded entirely by voluntary donations from Indian princes and the British public, the foundation stone was laid in 1906 by the Prince of Wales (later King George V), and the building was formally opened to the public in 1921 by the Prince of Wales (later Duke of Windsor).",
    "architecturalMarvels": "Designed by Sir William Emerson, President of the Royal Institute of British Architects, the building features an Indo-Saracenic design combining British neoclassical elements with Mughal domes, chhatris, and corner towers. Like the Taj Mahal, it is clad in white marble quarried from Makrana in Rajasthan. Atop the 56-meter central dome sits a famous 5-meter-tall black bronze Angel of Victory, which weighs 3 tonnes and rotates on ball bearings like a weather vane in high winds. The memorial houses 25 galleries containing rare oil paintings, historical manuscripts, weapons, and coins from three centuries of Indian history.",
    "modernStatusAndSignificance": "Designated an Institution of National Importance under the Indian Ministry of Culture. Welcomes over 3.5 million visitors each year as the primary architectural landmark of Kolkata.",
    "imageUrl": "https://images.unsplash.com/photo-1558431382-27e303142255?auto=format&fit=crop&q=80&w=1200",
    "fallbackImageUrl": "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&q=80&w=1200",
    "tags": ["Victoria Memorial", "Kolkata", "India", "Marble", "Indo-Saracenic", "British Raj", "Museum"],
    "keyFacts": [
      "Built from the same translucent Makrana white marble as the Taj Mahal",
      "The 3-tonne bronze Angel of Victory on the dome rotates freely with the wind",
      "Funded entirely by public donations without government tax revenues",
      "Houses 25 museum galleries displaying over 30,000 historical artifacts"
    ],
    "unescoStatus": "National Heritage Monument of India"
  }
]

print(f"Loaded {len(additional_asian)} additional Asian monuments.")
