#!/usr/bin/env python3
"""
Generates 55 Americas, Africa, and Oceania Monuments into:
src/data/monuments/americasAfricaOceaniaMonuments.ts
"""
import json

def item(id, name, native, cat, loc, country, region, era, yr_str, yr_num, arch, style, dim, mat, hist, marv, mod, img, tags, facts, unesco="World Heritage Landmark"):
    return {
        "id": id,
        "name": name,
        "nativeOrAlternateName": native,
        "category": cat,
        "location": loc,
        "country": country,
        "region": region,
        "era": era,
        "yearBuilt": yr_str,
        "numericYear": yr_num,
        "architectOrCreator": arch,
        "architecturalStyle": style,
        "dimensionsAndHeight": dim,
        "materialsUsed": mat,
        "historyAndBackground": hist,
        "architecturalMarvels": marv,
        "modernStatusAndSignificance": mod,
        "imageUrl": img,
        "fallbackImageUrl": "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?auto=format&fit=crop&q=80&w=1200",
        "tags": tags,
        "keyFacts": facts,
        "unescoStatus": unesco
    }

monuments = [
  # --- AMERICAS (25) ---
  # 1. Statue of Liberty
  item("statue-of-liberty", "Statue of Liberty", "Liberty Enlightening the World (La Liberté éclairant le monde)", "Monument & Tower", "Liberty Island, New York Harbor, NY", "United States", "Americas",
    "Gilded Age French-American Alliance (1875–1886 CE)", "1875–1886 CE", 1886, "Frédéric-Auguste Bartholdi & Gustave Eiffel",
    "Colossal Neoclassical Copper Repoussé Sculpture", "Height: 93 m (305 ft) from ground to torch; Statue height: 46 m; Weight: 225 tonnes",
    "Pure copper sheet skin (2.4 mm thick), puddled wrought-iron truss skeleton by Eiffel, granite pedestal",
    "The Statue of Liberty was a gift of friendship from the people of France to the United States to celebrate the centennial of the Declaration of Independence and the abolition of slavery following the American Civil War. Dedicated by President Grover Cleveland on October 28, 1886. For decades, it was the first beacon seen by over 12 million immigrants arriving by steamship at nearby Ellis Island.",
    "Gustave Eiffel engineered an internal flexible wrought-iron pylon framework that allows the statue to sway up to three inches in gale-force winds while the torch sways five inches without structural fatigue. The outer copper skin is as thin as two pennies (2.4 mm), hand-hammered using the repoussé technique. Originally shiny copper-brown, natural oxidation formed its iconic blue-green verdigris patina by 1906. Her tablet bears the Roman numerals 'JULY IV MDCCLXXVI', and broken shackles lie at her feet.",
    "Inscribed as a UNESCO World Heritage Site in 1984. The universal global symbol of freedom and democracy.",
    "https://images.unsplash.com/photo-1605130284535-11dd9eedc58a?auto=format&fit=crop&q=80&w=1200",
    ["Statue of Liberty", "New York", "USA", "Bartholdi", "Gustave Eiffel", "UNESCO", "Freedom"],
    ["Gift from the people of France to the United States dedicated on October 28, 1886", "Gustave Eiffel engineered the flexible internal iron skeleton that allows the statue to sway safely", "The green color is a natural copper patina (verdigris) that took 20 years of marine oxidation to form", "Broken chains and shackles at her feet symbolize the emancipation of enslaved people"],
    "Inscribed 1984 (Statue of Liberty)"),

  # 2. Empire State Building
  item("empire-state-building", "Empire State Building", "The Empire State Building", "Famous Building", "Midtown Manhattan, New York City", "United States", "Americas",
    "Art Deco Golden Age (1930–1931 CE)", "1930–1931 CE", 1931, "Shreve, Lamb & Harmon (Lead designer: William F. Lamb)",
    "Classic Art Deco Setback Skyscraper Architecture", "Roof height: 381 m (1,250 ft); Pinnacle height: 443.2 m (1,454 ft); 102 floors",
    "Structural steel frame (60,000 tonnes), Indiana limestone and granite facade, aluminum spandrels, nickel-bronze fittings",
    "The Empire State Building is a 102-story Art Deco skyscraper in Midtown Manhattan, New York City. Built during the Great Depression as part of an intense 'Race to the Sky' against the Chrysler Building and 40 Wall Street. Completed in an astonishing 1 year and 45 days (at a record pace of 4.5 floors per week) by 3,400 construction workers, including legendary Mohawk ironworkers.",
    "Held the title of the tallest building in the world for 40 years, from 1931 until the completion of the World Trade Center's North Tower in 1970. Its 61-meter mooring mast was originally intended as a docking station for transatlantic dirigible passenger airships. Named by the American Society of Civil Engineers as one of the Seven Wonders of the Modern World. Struck by lightning an average of 25 times per year, acting as a giant urban lightning rod.",
    "A designated National Historic Landmark. Visited by over 4 million tourists each year.",
    "https://images.unsplash.com/photo-1534430480872-3498386e7856?auto=format&fit=crop&q=80&w=1200",
    ["Empire State", "New York", "USA", "Art Deco", "Skyscraper", "Manhattan", "Icon"],
    ["Constructed in a record-breaking 1 year and 45 days during the Great Depression", "Held the undisputed title of the world's tallest building for 40 years (1931–1970)", "Its spire was originally designed as a docking station for transatlantic Zeppelin airships", "Acts as a giant lightning rod struck by lightning an average of 25 times per year"],
    "National Historic Landmark of the USA"),

  # 3. Golden Gate Bridge
  item("golden-gate-bridge", "Golden Gate Bridge", "The Golden Gate Bridge", "Bridge & Engineering", "San Francisco to Marin County, CA", "United States", "Americas",
    "Great Depression Public Works / Art Deco (1933–1937 CE)", "1933–1937 CE", 1937, "Joseph Strauss (Chief Engineer), Charles Ellis, Leon Moisseiff, Irving Morrow (Architect)",
    "Art Deco Suspension Bridge Engineering", "Total length: 2,737 m (8,981 ft); Main suspension span: 1,280 m; Tower height: 227 m (746 ft)",
    "Structural carbon steel, 129,000 km of galvanized steel wire cables, International Orange paint",
    "The Golden Gate Bridge is a suspension bridge spanning the Golden Gate strait, the one-mile-wide channel connecting San Francisco Bay and the Pacific Ocean. Opened in May 1937 under chief engineer Joseph Strauss, defying critics who claimed strong tides, 60 mph winds, and dense coastal fog made bridge construction impossible.",
    "Held the record for the world's longest suspension bridge span for 27 years until 1964. Architect Irving Morrow chose the signature 'International Orange' color because it matched warm California coastal hills and made the bridge visible through dense ocean fog. Strauss enforced unprecedented safety standards, requiring hard hats and installing an innovative safety net beneath the span, saving the lives of 19 workers who formed the 'Halfway to Hell Club'.",
    "Named one of the Wonders of the Modern World by the American Society of Civil Engineers. One of the most photographed bridges on Earth.",
    "https://images.unsplash.com/photo-1501594907352-04cda38ebc29?auto=format&fit=crop&q=80&w=1200",
    ["Golden Gate", "San Francisco", "California", "Bridge", "Art Deco", "International Orange"],
    ["Spanned the treacherous 1-mile Golden Gate strait, defying critics who called it unbuildable", "Painted in signature 'International Orange' to ensure maximum visibility through dense ocean fog", "Contains enough galvanized steel cable wire (129,000 km) to wrap around the equator three times", "An innovative safety net beneath the deck saved the lives of 19 construction workers"],
    "National Historic Civil Engineering Landmark"),

  # 4. White House
  item("white-house", "The White House", "1600 Pennsylvania Avenue", "Famous Building", "Washington, D.C.", "United States", "Americas",
    "Early American Federal / Neoclassical (1792–1800 CE; rebuilt 1817 CE)", "1792–1800 CE", 1800, "James Hoban, commissioned by George Washington",
    "Palladian Neoclassical Federal Architecture", "6 storeys; 132 rooms; 35 bathrooms; Floor area: 5,100 m² (55,000 sq ft); Grounds: 18 acres",
    "Aquia Creek Virginia sandstone ashlar, white lime-based whitewash, Georgian timber",
    "The White House is the official residence and workplace of the President of the United States. Located at 1600 Pennsylvania Avenue in Washington, D.C. Designed by Irish-born architect James Hoban, who won a national design competition. George Washington selected the site and approved the design in 1791, though John Adams was the first president to move in, on November 1, 1800.",
    "During the War of 1812, British forces burned the White House on August 24, 1814, in retaliation for the American burning of Upper Canada's parliament; First Lady Dolley Madison famously saved the full-length Lansdowne portrait of George Washington before escaping. The interior was completely gutted and rebuilt under President Harry S. Truman (1948–1952) with a modern steel frame. Contains the Oval Office, the Cabinet Room, the Situation Room, and the East Room.",
    "The executive heart of the United States government and the world's most famous residence.",
    "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&q=80&w=1200",
    ["White House", "Washington DC", "USA", "President", "James Hoban", "Oval Office"],
    ["The official residence and workplace of every US President since John Adams moved in in 1800", "Burned by British troops during the War of 1812 and painstakingly rebuilt by James Hoban", "Completely gutted and reconstructed with a steel frame under President Harry Truman in 1948–1952", "Contains 132 rooms, 35 bathrooms, 412 doors, and 28 fireplaces"],
    "National Heritage Monument"),

  # 5. United States Capitol
  item("us-capitol", "United States Capitol", "The United States Capitol", "Famous Building", "Capitol Hill, Washington, D.C.", "United States", "Americas",
    "Neoclassical American Republic (1793–1826 CE; cast-iron dome 1866 CE)", "1793–1866 CE", 1800, "William Thornton, Benjamin Henry Latrobe, Charles Bulfinch, Thomas U. Walter",
    "American Neoclassical Monumental Architecture", "Length: 229 m; Width: 107 m; Dome height: 88 m (288 ft); Cast-iron dome weight: 4,000 tonnes",
    "Aquia Creek sandstone, Georgia and Massachusetts marble, cast iron dome, bronze Statue of Freedom",
    "The United States Capitol is the seat of the legislative branch of the United States federal government, located on Capitol Hill in Washington, D.C. Houses the chambers of the United States Senate in the north wing and the House of Representatives in the south wing. The cornerstone was laid by President George Washington on September 18, 1793.",
    "The Capitol is crowned by a colossal cast-iron dome weighing 4,000 tonnes, designed by Thomas U. Walter and completed during the height of the American Civil War. President Abraham Lincoln insisted construction continue during the war, stating: 'If people see the Capitol going on, it is a sign we intend the Union shall go on.' Inside the Rotunda, Constantino Brumidi's colossal fresco 'The Apotheosis of Washington' covers the dome canopy, and the bronze Statue of Freedom crowns the peak.",
    "The focal point of American democracy, where presidential inaugurations take place on the West Front.",
    "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&q=80&w=1200",
    ["US Capitol", "Washington DC", "USA", "Congress", "Senate", "Dome", "Democracy"],
    ["The seat of the United States Congress, with cornerstone laid by George Washington in 1793", "Abraham Lincoln ordered the cast-iron dome construction to continue during the Civil War", "The Rotunda ceiling features Constantino Brumidi's massive fresco 'The Apotheosis of Washington'", "West Front steps serve as the traditional ceremonial stage for US Presidential inaugurations"],
    "National Historic Landmark"),

  # 6. Mount Rushmore
  item("mount-rushmore", "Mount Rushmore National Memorial", "Six Grandfathers (Tȟuŋkášila Šákpe) / Mount Rushmore", "Monument & Tower", "Black Hills, Keystone, South Dakota", "United States", "Americas",
    "Interwar Modern Colossal Sculpture (1927–1941 CE)", "1927–1941 CE", 1941, "Gutzon Borglum and Lincoln Borglum",
    "Colossal Granite Monolithic Mountain Carving", "Elevation: 1,745 m (5,725 ft); Face height: 18 m (60 ft); Nose length: 6 m; Eye width: 3.3 m",
    "Precambrian granite batholith of the Black Hills, dynamite blasting, pneumatic air chisels",
    "Mount Rushmore National Memorial is a colossal sculpture carved into the granite face of Mount Rushmore in the Black Hills of South Dakota. Sculptor Gutzon Borglum conceived the monument to represent the first 130 years of American history through four presidents: George Washington (birth of the nation), Thomas Jefferson (expansion through Louisiana Purchase), Theodore Roosevelt (development and conservation), and Abraham Lincoln (preservation of the Union). Built between 1927 and 1941.",
    "An astonishing 90% of the 450,000 tonnes of granite was removed using controlled micro-dynamite blasting by skilled powdermen suspended in bosun's chairs from steel cables. Despite the perilous heights and explosives, not a single worker died during the entire 14-year construction. The monument remains sacred to the Lakota Sioux nation, who knew the mountain as 'The Six Grandfathers' before the land was seized following the 1874 Black Hills gold rush.",
    "Welcomes over two million visitors annually. One of the most famous colossal monuments on Earth.",
    "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&q=80&w=1200",
    ["Mount Rushmore", "South Dakota", "USA", "Black Hills", "Presidents", "Granite", "Sculpture"],
    ["Features 18-meter-tall faces of George Washington, Thomas Jefferson, Theodore Roosevelt, and Abraham Lincoln", "90% of the 450,000 tonnes of rock was carved using precision dynamite blasting", "Remarkably, not a single worker was killed during the perilous 14 years of construction", "Originally known to the indigenous Lakota Sioux nation as 'The Six Grandfathers'"],
    "National Memorial of the USA"),

  # 7. Brooklyn Bridge
  item("brooklyn-bridge", "Brooklyn Bridge", "New York and Brooklyn Bridge", "Bridge & Engineering", "East River, New York City", "United States", "Americas",
    "Gilded Age Industrial Engineering (1869–1883 CE)", "1869–1883 CE", 1883, "John A. Roebling, Washington Roebling, Emily Warren Roebling",
    "Neo-Gothic Suspension Bridge Engineering", "Total length: 1,825 m (5,989 ft); Main suspension span: 486.3 m; Tower height: 84.3 m (277 ft)",
    "Granite and Rosendale cement towers, galvanized steel wire cables (first steel wire bridge), timber caissons",
    "The Brooklyn Bridge is a hybrid cable-stayed/suspension bridge connecting Manhattan and Brooklyn across the East River. Completed in 1883, it was the first steel-wire suspension bridge ever constructed and the longest suspension bridge in the world at the time. Conceived by German immigrant John A. Roebling, who died of tetanus after his foot was crushed at the dock. His son Washington Roebling took over as chief engineer but became paralyzed by decompression sickness ('the bends') while working in compressed-air underwater caissons.",
    "Washington's brilliant wife, Emily Warren Roebling, stepped in for over a decade: she mastered advanced civil engineering, mathematics, and cable fabrication to serve as the bridge's de facto chief engineer, communicating her husband's daily instructions to assistant engineers and contractors. The monumental neo-Gothic stone towers, featuring dual pointed arches, were taller than any building in New York except Trinity Church spire. On opening day, May 24, 1883, Emily Roebling was the first person to cross the bridge in a carriage carrying a rooster as a symbol of victory.",
    "Designated a National Historic Landmark in 1964 and an International Historic Civil Engineering Landmark. A beloved architectural symbol of New York.",
    "https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&q=80&w=1200",
    ["Brooklyn Bridge", "New York", "USA", "Suspension Bridge", "Roebling", "East River", "Historic"],
    ["The first suspension bridge in world history to utilize woven galvanized steel wire cables", "Completed under the direction of Emily Warren Roebling after her husband was paralyzed by the bends", "Upon opening in 1883, it was the longest suspension bridge in the world and New York's tallest structure", "Circus showman P.T. Barnum led 21 elephants across the bridge in 1884 to prove its strength to the public"],
    "National Historic Landmark"),

  # 8. Lincoln Memorial
  item("lincoln-memorial", "Lincoln Memorial", "Lincoln Memorial", "Monument & Tower", "National Mall, Washington, D.C.", "United States", "Americas",
    "American Beaux-Arts / Neoclassical (1914–1922 CE)", "1914–1922 CE", 1922, "Henry Bacon (Architect), Daniel Chester French (Sculptor)",
    "Classical Greek Doric Peripteral Temple Architecture", "Building width: 58 m; Depth: 39 m; Height: 30 m; Lincoln seated statue height: 5.8 m (19 ft); Weight: 175 tonnes",
    "Yule Colorado marble exterior, Georgia marble statue (28 interlocking blocks), Indiana limestone, pink Tennessee marble floor",
    "The Lincoln Memorial is a US national memorial honoring the 16th President of the United States, Abraham Lincoln. Located at the western terminus of the National Mall in Washington, D.C., overlooking the Lincoln Memorial Reflecting Pool. Dedicated on May 30, 1922, by Chief Justice William Howard Taft in the presence of Lincoln's 78-year-old surviving son, Robert Todd Lincoln.",
    "Designed in the form of a classical Greek Doric temple inspired by the Parthenon in Athens. The exterior is surrounded by 36 fluted Doric columns, representing the 36 states in the Union at the time of Lincoln's death. Inside sits Daniel Chester French's monumental statue of Abraham Lincoln seated in contemplation, carved from 28 blocks of white Georgia marble. The north wall is engraved with Lincoln's Second Inaugural Address, and the south wall bears the Gettysburg Address. Famous worldwide as the site of Martin Luther King Jr.'s 'I Have a Dream' speech on August 28, 1963, delivered from the monument's steps to 250,000 civil rights marchers.",
    "Inscribed on the National Register of Historic Places in 1966. Attracts nearly 8 million visitors annually.",
    "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&q=80&w=1200",
    ["Lincoln Memorial", "Washington DC", "USA", "Abraham Lincoln", "MLK", "I Have a Dream", "Civil Rights"],
    ["Surrounded by 36 Doric columns representing the 36 states of the Union at Lincoln's death in 1865", "Daniel Chester French carved the 19-foot statue of Lincoln from 28 blocks of Georgia white marble", "The monument steps were the site of Martin Luther King Jr.'s historic 'I Have a Dream' speech in 1963", "Engraved with the full texts of Lincoln's Gettysburg Address and Second Inaugural Address"],
    "National Memorial of the USA"),

  # 9. Gateway Arch, St. Louis
  item("gateway-arch", "The Gateway Arch", "Gateway to the West", "Monument & Tower", "Gateway Arch National Park, St. Louis, Missouri", "United States", "Americas",
    "Mid-Century Modernist Expressionism (1963–1965 CE)", "1963–1965 CE", 1965, "Eero Saarinen & Hannskarl Bandel",
    "Weighted Inverted Catenary Arch Structural Engineering", "Height & Width: exactly 192 m (630 ft); Triangular leg base width: 16.5 m; Weight: 43,226 tonnes",
    "Double-walled stainless steel exterior (grade 304), carbon steel structural interior, post-tensioned concrete base",
    "The Gateway Arch is a 630-foot (192 m) monument in St. Louis, Missouri. Designed by Finnish-American architect Eero Saarinen in 1947 as a memorial to Thomas Jefferson and the 19th-century American pioneers who expanded westward following the Lewis and Clark Expedition. Built between 1963 and 1965 on the west bank of the Mississippi River.",
    "It is the world's tallest arch and the tallest human-made monument in the Western Hemisphere. Engineered as a mathematically perfect 'weighted inverted catenary arch'—the ideal structural curve formed by a hanging chain under gravity. The arch has no internal skeleton: its strength comes entirely from its hollow double-wall stressed skin. Visitors travel to the observation deck at the apex in an ingenious tram system designed by Dick Bowser that combines elevator cables with rotating Ferris wheel pods that self-level as they climb the curve. Built with zero tolerance: when the two legs met at the top, they aligned to within a fraction of a millimeter.",
    "The centerpiece of Gateway Arch National Park. A triumph of mid-century structural mathematics and stainless steel engineering.",
    "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&q=80&w=1200",
    ["Gateway Arch", "St Louis", "Missouri", "USA", "Eero Saarinen", "Catenary Arch", "Modernist"],
    ["The tallest arch in the world and tallest monument in the Western Hemisphere at 630 feet (192 m)", "Engineered as a mathematically pure weighted inverted catenary arch without an internal frame", "Visitors ascend to the observation apex in a unique rotating Ferris-wheel capsule tram system", "Built with stainless steel that gleams across the Mississippi River at dawn and sunset"],
    "National Historic Landmark"),

  # 10. Chrysler Building
  item("chrysler-building", "Chrysler Building", "The Chrysler Building", "Famous Building", "Midtown Manhattan, New York City", "United States", "Americas",
    "Art Deco Zenith (1928–1930 CE)", "1928–1930 CE", 1930, "William Van Alen, commissioned by Walter P. Chrysler",
    "Art Deco Skyscraper Architecture", "Height: 318.9 m (1,046 ft); 77 floors; Spire height: 56 m (185 ft); Steel weight: 20,961 tonnes",
    "White and dark gray brickwork, Nirosta chrome-nickel steel ('Enduro KA-2') sunburst crown, African red granite",
    "The Chrysler Building is an Art Deco skyscraper on the East Side of Midtown Manhattan. Built between 1928 and 1930 by automobile magnate Walter P. Chrysler as the headquarters of the Chrysler Corporation. Designed by architect William Van Alen with automotive motifs: the 31st floor features radiator-cap winged helmets inspired by the 1929 Chrysler roadster, and the 61st floor corners are guarded by eight colossal stainless steel American eagles modeled on car hood ornaments.",
    "During construction, Van Alen engaged in a secret duel with his former partner Craig Severance (building 40 Wall Street) for the title of world's tallest building. When 40 Wall Street surpassed Chrysler's published height, Van Alen secretly assembled a 185-foot steel spire (the 'Vertex') inside the fire tower. On October 23, 1929, the spire was hoisted through the roof in just 90 minutes, stunning New York and snatching the world's tallest building title from Wall Street. The sunburst crown features seven radiating terraced arches clad in Nirosta stainless steel that never rusts or tarnishes.",
    "Widely voted by American architects as the most beautiful skyscraper in the world. A designated National Historic Landmark.",
    "https://images.unsplash.com/photo-1534430480872-3498386e7856?auto=format&fit=crop&q=80&w=1200",
    ["Chrysler Building", "New York", "USA", "Art Deco", "Skyscraper", "Spire", "Manhattan"],
    ["Its gleaming sunburst Art Deco crown is clad in Nirosta German stainless steel that never tarnishes", "Decorated with automotive motifs, including radiator-cap wings and steel eagle hood ornaments", "The 185-foot steel spire was secretly assembled inside the fire shaft and hoisted in 90 minutes", "Briefly held the title of the tallest building in the world before the Empire State Building opened"],
    "National Historic Landmark"),

  # 11. One World Trade Center
  item("one-world-trade-center", "One World Trade Center (Freedom Tower)", "One WTC / Freedom Tower", "Famous Building", "Lower Manhattan, New York City", "United States", "Americas",
    "21st Century Resilient High-Tech (2006–2014 CE)", "2006–2014 CE", 2014, "David Childs (Skidmore, Owings & Merrill)",
    "Contemporary Resilient Neo-Modernist Skyscraper Architecture", "Height: 541.3 m (1,776 ft); 94 floors; Base footprint: 61 × 61 m (exact footprint of original Twin Towers)",
    "Ultra-high-strength reinforced concrete core (14,000 psi), structural blast-resistant steel, low-iron insulated glass",
    "One World Trade Center is the lead building of the rebuilt World Trade Center complex in Lower Manhattan, New York City. Built on the site of the catastrophic terrorist attacks of September 11, 2001. Designed by David Childs of Skidmore, Owings & Merrill. Opened on November 3, 2014. The tallest building in the United States and the Western Hemisphere.",
    "Its total height of exactly 1,776 feet (541.3 m) is a deliberate symbolic reference to the year the United States Declaration of Independence was signed. The building's base is a square matching the exact 200 × 200 foot footprint of the original Twin Towers; as it rises, its corners are chamfered, transforming the tower into eight elongated isosceles triangles forming a perfect octagon at the midpoint and culminating in a glass square rotated 45 degrees at the parapet. Engineered with the world's strongest building core: three-foot-thick blast-resistant concrete walls protecting life-safety stairwells and elevators.",
    "The modern symbol of American resilience and rebirth, standing beside the 9/11 Memorial pools.",
    "https://images.unsplash.com/photo-1534430480872-3498386e7856?auto=format&fit=crop&q=80&w=1200",
    ["One WTC", "New York", "USA", "Freedom Tower", "1776", "Skyscraper", "Manhattan"],
    ["The tallest building in the Western Hemisphere, soaring to a symbolic height of exactly 1,776 feet", "The tower's geometry transitions smoothly from a square base to an octagon and back to a square", "Features a 3-foot-thick ultra-reinforced concrete core engineered to withstand catastrophic blasts", "Base footprint matches the exact 200 × 200 foot dimensions of the original Twin Towers"],
    "Tallest Building in the Western Hemisphere"),

  # 12. Space Needle, Seattle
  item("space-needle", "The Space Needle", "Space Needle", "Monument & Tower", "Seattle Center, Seattle, Washington", "United States", "Americas",
    "Mid-Century Space Age Modernism (1961–1962 CE)", "1961–1962 CE", 1962, "Edward E. Carlson & John Graham Jr. (Architect: Victor Steinbrueck)",
    "Googie / Space Age Modernist Observation Tower Architecture", "Height: 184 m (605 ft); Width: 42 m; Weight: 9,550 tonnes; Foundation depth: 9 m (weighs more than the tower)",
    "Structural carbon steel, earthquake-resistant trusses, rotating floor mechanism, floor-to-ceiling glass",
    "The Space Needle is an observation tower in Seattle, Washington, built as the iconic symbol for the 1962 Century 21 Exposition (the Seattle World's Fair), whose theme was the 21st-century Space Age. Conceived by Edward E. Carlson, who drew the initial design on a coffee shop napkin inspired by the Stuttgart TV Tower in Germany. Built in an astonishingly fast 400 days.",
    "Engineered to withstand 200 mph hurricane-force winds and earthquakes up to magnitude 9.0. The foundation hole was filled with 467 cement trucks of concrete over 12 continuous hours, weighing 5,850 tonnes—meaning the underground foundation weighs more than the entire steel tower above ground, placing the center of gravity just five feet above ground level! Features SkyCity, the world's first revolving restaurant with a motor of just 1.5 horsepower. In 2018, a $100 million renovation installed the 'Loupe', the world's first revolving glass floor, offering vertigo-inducing views straight down 500 feet.",
    "A designated Seattle landmark and the undisputed international symbol of the American Pacific Northwest.",
    "https://images.unsplash.com/photo-1502175353174-a7a70e73b362?auto=format&fit=crop&q=80&w=1200",
    ["Space Needle", "Seattle", "Washington", "USA", "Space Age", "Revolving Glass", "Tower"],
    ["Built in just 400 days as the futuristic centerpiece of the 1962 Seattle World's Fair", "The underground concrete foundation weighs 5,850 tonnes, more than the entire tower above ground", "Engineered to survive 200 mph winds and magnitude 9.0 earthquakes with minimal sway", "Features 'The Loupe', the world's first revolving glass floor looking 500 feet straight down"],
    "Official Landmark of Seattle"),

  # 13. Chichen Itza (El Castillo), Mexico
  item("chichen-itza", "Chichen Itza & El Castillo (Pyramid of Kukulkan)", "Chi'ch'èen Ìitsha' / El Castillo (Temple of Kukulcan)", "Ancient Wonder", "Tinúm Municipality, Yucatán", "Mexico", "Americas",
    "Post-Classic Maya-Toltec Civilization (c. 600–1200 CE)", "c. 800–1000 CE", 900, "Maya-Toltec architects and astronomers",
    "Maya-Toltec Stepped Pyramid & Archaeoastronomical Architecture", "Height: 30 m (98 ft) including temple; Base width: 55.3 m; Steps: 365 total steps",
    "Yucatán limestone ashlar blocks, lime mortar, carved serpent balustrades",
    "El Castillo (The Castle), also known as the Temple of Kukulcan, is a Mesoamerican stepped pyramid dominating the center of the archaeological site of Chichen Itza in Yucatán, Mexico. Built by the Maya civilization between the 9th and 12th centuries CE, dedicated to Kukulcan, the feathered serpent deity. Served as an immense monumental calendar carved in stone.",
    "The pyramid has four stairways, each with 91 steps; combined with the shared top temple platform, they total exactly 365 steps—one for each day of the solar year. During the spring and autumn equinoxes (March 21 and September 21), the late afternoon sun casts a series of triangular shadows along the northwest balustrade, creating the optical illusion of a 120-foot feathered rattlesnake slithering down the pyramid to join the colossal carved stone serpent heads at the base. Clapping your hands at the base of the staircase produces an acoustic echo mimicking the high-pitched chirp of the sacred Quetzal bird.",
    "Inscribed as a UNESCO World Heritage Site in 1988 and voted one of the New 7 Wonders of the World in 2007.",
    "https://images.unsplash.com/photo-1518638150340-f706e86654de?auto=format&fit=crop&q=80&w=1200",
    ["Chichen Itza", "Yucatan", "Mexico", "Maya", "El Castillo", "Kukulcan", "UNESCO", "Wonder"],
    ["The four stairways feature 91 steps each, totaling 365 steps including the summit platform", "On equinoxes, afternoon shadows create the optical illusion of a giant serpent slithering down", "Clapping at the base of the stairway produces an echo that mimics the sacred Quetzal bird call", "Voted one of the New 7 Wonders of the World in 2007 and inscribed by UNESCO in 1988"],
    "Inscribed 1988 (Pre-Hispanic City of Chichen-Itza)"),

  # 14. Teotihuacan (Pyramid of the Sun), Mexico
  item("teotihuacan-pyramid-sun", "Teotihuacan (Pyramid of the Sun)", "Teōtīhuacān (City of the Gods) / Tonatiuh Iztacual", "Ancient Wonder", "San Juan Teotihuacán, State of Mexico", "Mexico", "Americas",
    "Pre-Columbian Mesoamerican Classic (c. 100 BCE – 200 CE)", "c. 100–200 CE", 100, "Teotihuacano master builders (identity unknown)",
    "Talud-Tablero Mesoamerican Megalithic Pyramid Architecture", "Base dimensions: 220 × 230 m (720 × 760 ft); Height: 65.5 m (216 ft); Volume: 1.2 million m³",
    "Volcanic basalt rock, tezontle red volcanic slag, lime plaster, tempera mineral paints",
    "Teotihuacan, named by the Aztecs centuries later as 'The Place Where the Gods Were Born', was the largest pre-Columbian city in the Americas, flourishing between 100 BCE and 650 CE with an estimated population of 125,000. Located 40 kilometers northeast of modern Mexico City along the monumental Avenue of the Dead (Miccaotli). Abandoned mysteriously around 650–750 CE following devastating fires, its monumental pyramids were revered as sacred mythic ruins by the Aztecs.",
    "The Pyramid of the Sun is the third-largest ancient pyramid in the world by volume (after Cholula and Giza). Constructed of 1.2 million cubic meters of earth and volcanic basalt. Built directly above a 100-meter-long subterranean cloverleaf-shaped lava tube cave, believed by Teotihuacanos to be the Chicomoztoc ('Place of Seven Caves') from which human creation emerged. Aligned precisely with the setting sun on August 12 and April 30, marking the beginning of the Mesoamerican agricultural calendar.",
    "Inscribed as a UNESCO World Heritage Site in 1987. One of the most monumental archaeological landscapes in the world.",
    "https://images.unsplash.com/photo-1518638150340-f706e86654de?auto=format&fit=crop&q=80&w=1200",
    ["Teotihuacan", "Pyramid of Sun", "Mexico", "Avenue of Dead", "Aztec", "Pre-Columbian", "UNESCO"],
    ["The third-largest ancient pyramid on Earth by volume, constructed of 1.2 million m³ of stone", "Built directly over a sacred volcanic lava tube cave revered as the womb of human creation", "The city housed over 125,000 people at its zenith, making it one of the ancient world's largest cities", "Aztecs discovered the abandoned ruins centuries later and named it 'The Place Where Gods Were Born'"],
    "Inscribed 1987 (Pre-Hispanic City of Teotihuacan)"),

  # 15. Palenque Mayan Ruins, Mexico
  item("palenque-maya", "Palenque (Lakamha) & Temple of the Inscriptions", "Lakamha' (Big Water) / Palenque", "Archaeological City", "Palenque, Chiapas", "Mexico", "Americas",
    "Classic Maya Golden Age (c. 226 BCE – 799 CE; peak 615–683 CE)", "c. 600–700 CE", 683, "K'inich Janaab' Pakal (Pakal the Great)",
    "Classic Maya Tropical Limestone Architecture (Mansard roofs and corbel vaults)", "Temple of Inscriptions height: 27 m (89 ft); Palace tower: 4 storeys; Plaza area: 2.2 km²",
    "Chiapas Cretaceous limestone ashlar, lime stucco reliefs, jade mosaic funerary mask",
    "Palenque was a Maya city-state in southern Mexico that flourished in the 7th century CE. Perched in the lush jungle foothills overlooking the coastal plains of Chiapas. Famous for its patron ruler K'inich Janaab' Pakal (Pakal the Great), who ascended the throne at age 12 in 615 CE and ruled for 68 years, transforming Palenque into an architectural jewel. Swallowed by dense rainforest after its collapse in the 8th century until rediscovered in the 18th century.",
    "The Temple of the Inscriptions is celebrated in world archaeology: in 1952, Mexican archaeologist Alberto Ruz Lhuillier discovered a secret stairway descending 22 meters through the interior of the pyramid to Pakal's sealed royal burial chamber. Pakal lay inside a monolithic stone sarcophagus weighing 20 tonnes, wearing an exquisite funerary mask crafted from 200 jade mosaic tesserae. The carved sarcophagus lid, depicting Pakal's rebirth from the jaws of the underworld beneath the sacred World Tree (Ceiba), is one of the greatest masterpieces of pre-Columbian art.",
    "Inscribed as a UNESCO World Heritage Site in 1987. Considered the most aesthetically refined of all Maya cities.",
    "https://images.unsplash.com/photo-1518638150340-f706e86654de?auto=format&fit=crop&q=80&w=1200",
    ["Palenque", "Chiapas", "Mexico", "Maya", "Pakal", "Temple of Inscriptions", "Jade", "UNESCO"],
    ["Houses the royal tomb of Pakal the Great, discovered hidden deep inside the pyramid in 1952", "Pakal was buried wearing an intricate royal funerary mask crafted from over 200 jade pieces", "The carved 20-ton stone sarcophagus lid is celebrated as a pinnacle of ancient American art", "Features an advanced network of subterranean stone aqueducts channeling mountain streams"],
    "Inscribed 1987 (Pre-Hispanic City and National Park of Palenque)"),

  # 16. Templo Mayor, Mexico City
  item("templo-mayor", "Templo Mayor of Tenochtitlan", "Huēyi Teōcalli (Great Temple of Tenochtitlan)", "Archaeological City", "Zócalo, Mexico City", "Mexico", "Americas",
    "Aztec Empire Golden Age (1325–1521 CE)", "1325–1487 CE", 1487, "Aztec Huey Tlatoanis (Ahuitzotl, Moctezuma I)",
    "Aztec Dual-Pyramid Ceremonial Architecture", "Base dimensions: 100 × 80 m; Height: 60 m (197 ft); 7 building phases stacked like an onion",
    "Volcanic tezontle stone, basalt slabs, lime stucco, polychrome mineral pigments",
    "The Templo Mayor (Huēyi Teōcalli) was the main temple of Tenochtitlan, the island capital of the Aztec Empire (now Mexico City). Founded in 1325 on Lake Texcoco on the spot where the Mexica saw the prophesied sign: an eagle perched on a nopal cactus devouring a snake (now the national emblem of Mexico). Destroyed in August 1521 by Spanish conquistadors led by Hernán Cortés, who dismantled the temple and used its stones to build the Mexico City Metropolitan Cathedral next door.",
    "The temple was dedicated to two deities simultaneously, crowned by twin shrines atop the pyramid: the left shrine painted blue and white for Tlaloc (the god of rain and fertility), and the right painted red and white for Huitzilopochtli (the god of war and the sun). Expanded through seven distinct phases, with each new emperor encasing the previous temple like an onion. In February 1978, electric utility workers digging near the Zócalo unearthed the colossal 8-tonne circular stone disc of the moon goddess Coyolxauhqui, launching the systematic excavation of the Aztec imperial heart.",
    "Inscribed as a UNESCO World Heritage Site in 1987 as part of the Historic Centre of Mexico City.",
    "https://images.unsplash.com/photo-1518638150340-f706e86654de?auto=format&fit=crop&q=80&w=1200",
    ["Templo Mayor", "Mexico City", "Aztec", "Tenochtitlan", "Coyolxauhqui", "Huitzilopochtli", "UNESCO"],
    ["The spiritual and political ground zero of the Aztec Empire, founded on Lake Texcoco in 1325", "Featured twin temples on its summit: one for Tlaloc (Rain) and one for Huitzilopochtli (War)", "Expanded across seven layers, encasing earlier pyramids like the layers of an onion", "Rediscovered accidentally in 1978 when workers unearthed the colossal 8-ton Coyolxauhqui stone"],
    "Inscribed 1987 (Historic Centre of Mexico City)"),

  # 17. Metropolitan Cathedral of Mexico City
  item("mexico-city-cathedral", "Mexico City Metropolitan Cathedral", "Catedral Metropolitana de la Asunción de la Santísima Virgen María", "Sacred Temple / Cathedral", "Plaza de la Constitución (Zócalo), Mexico City", "Mexico", "Americas",
    "New Spain Viceroyalty (1573–1813 CE)", "1573–1813 CE", 1667, "Claudio de Arciniega, Manuel Tolsá",
    "Spanish Colonial Baroque, Churrigueresque & Neoclassical Architecture", "Length: 110 m; Width: 54 m; Twin bell towers height: 67 m; 16 chapels",
    "Grey Chiluca and red Tezontle volcanic stones quarried from dismantled Aztec pyramids, cedar wood, gold leaf",
    "The Metropolitan Cathedral of Mexico City is the oldest and largest cathedral in the Americas, dominating the northern edge of the grand Zócalo plaza in Mexico City. Construction spanned nearly two and a half centuries (1573–1813), incorporating elements of Renaissance, Baroque, Churrigueresque, and Neoclassical styles. Built directly atop the sacred precinct of Aztec Tenochtitlan using stones from the demolished Aztec Templo Mayor.",
    "Because it was constructed atop the soft, waterlogged lacustrine mud beds of drained Lake Texcoco, the massive cathedral sank unevenly by up to three meters into the ground over the centuries, threatening structural collapse. Between 1993 and 1998, world-renowned geotechnical engineers executed an audacious underexcavation project, drilling shafts beneath the cathedral to extract mud and level the foundations, saving the monument. Contains the Altar of the Kings (Altar de los Reyes), a 25-meter-high masterpiece of ultrabaroque gilded wood carving, and Latin America's two largest 18th-century pipe organs.",
    "Inscribed as a UNESCO World Heritage Site in 1987 as part of the Historic Centre of Mexico City.",
    "https://images.unsplash.com/photo-1518638150340-f706e86654de?auto=format&fit=crop&q=80&w=1200",
    ["Mexico City Cathedral", "Zocalo", "Mexico", "Spanish Colonial", "Baroque", "Churrigueresque", "UNESCO"],
    ["The largest and oldest cathedral in the Americas, constructed over 240 years (1573–1813)", "Built using volcanic stones salvaged from the dismantled Aztec Templo Mayor pyramids", "Engineers saved it in the 1990s by drilling beneath the foundation to reverse centuries of sinking into lake mud", "Features the Altar of the Kings, an astounding 25-meter-tall gilded wooden baroque masterpiece"],
    "Inscribed 1987 (Historic Centre of Mexico City)"),

  # 18. Machu Picchu, Peru
  item("machu-picchu", "Machu Picchu (Lost City of the Incas)", "Machu Pikchu (Old Peak)", "Archaeological City", "Urubamba Province, Cusco Region", "Peru", "Americas",
    "Inca Empire Golden Age (c. 1450–1470 CE)", "c. 1450 CE", 1450, "Inca Emperor Pachacuti (Inca Yupanqui)",
    "Classical Inca Megalithic Dry-Stone (Ashlar) Architecture", "Elevation: 2,430 m (7,970 ft); Site area: 325 km²; Over 200 stone buildings; 700 agricultural terraces",
    "White-gray granite blocks cut and polished with hammerstones, dry-stone fitted without mortar",
    "Machu Picchu is a 15th-century Inca royal citadel situated on a narrow mountain ridge between the peaks of Machu Picchu and Huayna Picchu, 2,430 meters above sea level in the Andes above the Urubamba River. Built around 1450 CE as an imperial estate and ceremonial sanctuary for Emperor Pachacuti. Abandoned a century later during the Spanish conquest of the Inca Empire. Because the Spanish conquistadors never found the citadel, it remained preserved under subtropical cloud forest until introduced to the world in 1911 by American explorer Hiram Bingham.",
    "Constructed without mortar, wheels, or iron tools using precision ashlar masonry, where polygonal granite megaliths were chiseled to fit together so tightly that a razor blade cannot pass between them. The buildings are seismically flexible: during earthquakes, the stones shake and dance in place, then settle back into their original positions without collapsing! Contains the Intihuatana stone ('Hitching Post of the Sun'), a carved granite astronomical gnomon used to predict the winter solstice. Over 700 agricultural terraces stabilized the steep slopes and prevented erosion while growing maize and potatoes.",
    "Inscribed as a UNESCO World Heritage Site in 1983 and voted one of the New 7 Wonders of the World in 2007. Peru's most revered cultural treasure.",
    "https://images.unsplash.com/photo-1526392060635-9d6019884377?auto=format&fit=crop&q=80&w=1200",
    ["Machu Picchu", "Peru", "Inca", "Andes", "Pachacuti", "New 7 Wonders", "UNESCO"],
    ["Built around 1450 atop a 2,430-meter Andean ridge as a sacred estate for Emperor Pachacuti", "Granite stones were cut so precisely without mortar that a knife blade cannot slip between them", "Engineered with seismic flexibility: stones dance during earthquakes and fall back into place", "Houses the Intihuatana astronomical stone used by Inca priests to track the winter solstice"],
    "Inscribed 1983 (Historic Sanctuary of Machu Picchu)"),

  # 19. Christ the Redeemer, Rio de Janeiro, Brazil
  item("christ-the-redeemer", "Christ the Redeemer", "Cristo Redentor", "Monument & Tower", "Corcovado Mountain, Rio de Janeiro", "Brazil", "Americas",
    "Art Deco Golden Age (1922–1931 CE)", "1922–1931 CE", 1931, "Heitor da Silva Costa (Engineer), Paul Landowski (Sculptor), Gheorghe Leonida",
    "Colossal Art Deco Reinforced Concrete & Soapstone Sculpture", "Height: 30 m (98 ft) excluding 8 m pedestal; Arm span: 28 m (92 ft); Weight: 1,145 tonnes",
    "Reinforced concrete core, mosaic cladding of 6 million Swedish soapstone triangular tiles",
    "Christ the Redeemer is a colossal Art Deco statue of Jesus Christ standing atop the 710-meter (2,329 ft) granite peak of Corcovado Mountain overlooking the city and harbor of Rio de Janeiro. Proposed in 1920 by the Catholic Circle of Rio to counter what they perceived as increasing godlessness in society. Constructed between 1922 and 1931 under Brazilian engineer Heitor da Silva Costa and French-Polish sculptor Paul Landowski.",
    "It is the largest Art Deco sculpture in the world. Engineered in reinforced concrete, then sheathed in an outer mosaic skin of six million triangular tiles made of soapstone (talc) quarried in Minas Gerais, chosen for its extreme weather resistance, malleability, and pearlescent luminosity under tropical sunlight. Local Catholic women wrote the names of their children and prayers on the backs of the soapstone tiles before gluing them in place. The arms stretch 28 meters wide in an embrace symbolizing peace and welcoming the world. Struck by lightning three to six times a year, protected by lightning rods integrated along the head and hands.",
    "Designated one of the New 7 Wonders of the World in 2007. The international symbol of Rio de Janeiro and Brazil.",
    "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&q=80&w=1200",
    ["Christ the Redeemer", "Rio de Janeiro", "Brazil", "Art Deco", "Corcovado", "Soapstone", "Wonder"],
    ["The largest Art Deco statue in the world, standing atop Corcovado mountain 710 meters above Rio", "Outer skin is covered in six million soapstone tiles on which local women wrote personal prayers", "Arms stretch 28 meters wide, welcoming the city with a message of peace and divine embrace", "Voted one of the New 7 Wonders of the World in 2007 alongside the Taj Mahal and Colosseum"],
    "New 7 Wonders of the World"),

  # 20. Nazca Lines, Peru
  item("nazca-lines", "The Nazca Lines (Geoglyphs of Nasca)", "Líneas de Nasca (Geoglifos de Nasca)", "Ancient Wonder", "Nazca Desert, Ica Region", "Peru", "Americas",
    "Nazca Culture (c. 500 BCE – 500 CE)", "c. 500 BCE – 500 CE", 100, "Nazca religious leaders and engineers",
    "Ancient Pre-Columbian Megalithic Desert Geoglyphs", "Area: 450 km²; Over 800 straight lines, 300 geometric figures, and 70 biomorphic animals; Line length: up to 48 km",
    "Desert floor ferric oxide-coated reddish pebbles scraped away to reveal white-yellow gypsum subsoil",
    "The Nazca Lines are a collection of giant geoglyphs etched into the arid plains of the Nazca Desert in southern Peru. Created by the Nazca culture between 500 BCE and 500 CE. Composed of over 10,000 lines, 300 geometric figures (trapezoids, spirals, triangles), and 70 colossal biomorphic designs depicting plants and animals—including a 93-meter monkey with a coiled tail, a 46-meter spider, a 300-meter pelican, a hummingbird, and a humanoid figure known as 'The Astronaut'.",
    "Created by scraping away the top layer of dark reddish-brown iron-oxide coated desert stones to expose the bright, light-colored gypsum and chalk subsoil underneath. Preserved for over 2,000 years because the Nazca plateau is one of the driest places on Earth, receiving less than 4 millimeters of rain per year with calm desert winds. German mathematician Maria Reiche dedicated 40 years of her life to studying and preserving the lines, proposing they functioned as a giant astronomical calendar aligning with solstices and celestial constellations to call for rainfall in a hyper-arid desert.",
    "Inscribed as a UNESCO World Heritage Site in 1994. Visible in their full glory from the air.",
    "https://images.unsplash.com/photo-1526392060635-9d6019884377?auto=format&fit=crop&q=80&w=1200",
    ["Nazca Lines", "Peru", "Geoglyphs", "Hummingbird", "Desert", "Astronomy", "UNESCO"],
    ["Etched into the desert floor over 2,000 years ago, covering an area of 450 square kilometers", "Features colossal biomorphic drawings of a hummingbird, spider, monkey, and killer whale", "Preserved for two millennia by one of the driest, windless desert microclimates on Earth", "Researched for four decades by mathematician Maria Reiche as a colossal astronomical calendar"],
    "Inscribed 1994 (Lines and Geoglyphs of Nasca and Palpa)"),

  # 21. Tikal National Park, Guatemala
  item("tikal-guatemala", "Tikal National Park (Yax Mutal)", "Yax Mutal (First Knot) / Tikal", "Archaeological City", "Petén Basin", "Guatemala", "Americas",
    "Classic Maya Golden Age (c. 600 BCE – 900 CE; peak 200–900 CE)", "c. 200–850 CE", 734, "Yik'in Chan K'awiil & Jasaw Chan K'awiil I",
    "Classic Maya Petén-Style Stepped Temple Pyramid Architecture", "Temple IV height: 65 m (213 ft); Temple I height: 47 m; Urban core: 16 km²; 3,000 stone structures",
    "Petén porous limestone ashlar blocks, flint, chert, sapodilla wood lintels, painted stucco",
    "Tikal, anciently known as Yax Mutal, was one of the most powerful military, economic, and cultural superpowers of the ancient Maya civilization. Located in the Petén rainforest of northern Guatemala. Inhabited from the 6th century BCE to the 10th century CE, with an urban population exceeding 100,000 at its peak. Fought epic centuries-long wars against its bitter rival Calakmul for hegemony across the Maya lowlands.",
    "Celebrated for its steep, soaring Petén-style pyramid temples that rise through the tropical jungle canopy. Temple I (Temple of the Great Jaguar), built in 734 CE as the funerary pyramid of King Jasaw Chan K'awiil I, rises 47 meters above the Grand Plaza. Temple IV (Temple of the Double-Headed Serpent) soars 65 meters, making it the tallest pre-Columbian structure in the Americas. Maya engineers designed an advanced rainwater catchment and reservoir system lined with sand-and-zeolite water filtration systems that sustained the city through severe dry seasons.",
    "Inscribed as a UNESCO World Heritage Site in 1979 under dual cultural and natural criteria. Served as the rebel base on the moon Yavin 4 in 'Star Wars: Episode IV - A New Hope'.",
    "https://images.unsplash.com/photo-1518638150340-f706e86654de?auto=format&fit=crop&q=80&w=1200",
    ["Tikal", "Guatemala", "Maya", "Temple of Jaguar", "Peten", "Rainforest", "UNESCO"],
    ["One of the greatest political and military superpowers of the ancient Maya civilization", "Temple IV soars 65 meters above the jungle floor, the tallest pre-Columbian temple in the Americas", "Maya engineers built advanced zeolite sand filtration systems to purify drinking water in reservoirs", "Featured in 'Star Wars: Episode IV' as the iconic Rebel Alliance base on Yavin 4"],
    "Inscribed 1979 (Tikal National Park)"),

  # 22. Tiwanaku, Bolivia
  item("tiwanaku-bolivia", "Tiwanaku (Tiahuanaco) & Gate of the Sun", "Tiwanaku (Taypiqala - Stone in the Center)", "Archaeological City", "Ingavi Province, La Paz Department", "Bolivia", "Americas",
    "Pre-Inca Tiwanaku Empire (c. 300–1000 CE)", "c. 300–800 CE", 600, "Tiwanaku imperial architects and stone sculptors",
    "Pre-Inca Monolithic Megalithic Ashlar & Tenon Architecture", "Elevation: 3,850 m (12,630 ft); Gate of the Sun weight: 10 tonnes; Akapana pyramid height: 18 m",
    "Andesite volcanic stone, red sandstone megaliths (up to 130 tonnes), cast bronze and copper-arsenic cramps",
    "Tiwanaku was the capital of a major pre-Inca Andean empire that ruled the Lake Titicaca basin and surrounding highlands across modern Bolivia, Peru, and Chile from 300 to 1000 CE. Perched at a staggering altitude of 3,850 meters (12,630 feet) in the Altiplano. Regarded by the later Incas as the sacred birthplace of humanity, where the creator god Viracocha rose from Lake Titicaca to create the sun, stars, and the first human beings.",
    "Engineered with megalithic precision: the stones of the Pumapunku platform weigh up to 130 tonnes and feature intricate right-angle recesses, drill holes, and interlocking T-shaped copper-arsenic alloy cramps used to bind masonry against earthquakes. The iconic Gate of the Sun (Puerta del Sol) is a monolithic archway carved out of a single block of volcanic andesite stone weighing 10 tonnes, featuring a carved relief of the 'Staff God' (Viracocha) shedding tears that turn into winged condors and pumas.",
    "Inscribed as a UNESCO World Heritage Site in 2000. Considered one of the foundational cradles of South American civilization.",
    "https://images.unsplash.com/photo-1526392060635-9d6019884377?auto=format&fit=crop&q=80&w=1200",
    ["Tiwanaku", "Bolivia", "Gate of Sun", "Lake Titicaca", "Viracocha", "Pre-Inca", "UNESCO"],
    ["Flourished at an altitude of 3,850 meters as the capital of an empire predating the Incas", "The Gate of the Sun is carved from a single monolithic 10-tonne block of andesite stone", "Used precision cast copper cramps to lock colossal 130-tonne megaliths against earthquakes", "Revered by the Incas as the sacred cosmic location where Viracocha created mankind"],
    "Inscribed 2000 (Tiwanaku: Spiritual and Political Centre)"),

  # 23. Moai of Easter Island / Rapa Nui, Chile
  item("moai-easter-island", "Moai of Rapa Nui (Easter Island)", "Moai Aruga (Living Faces of the Ancestors) / Rapa Nui", "Ancient Wonder", "Easter Island (Rapa Nui), Valparaíso Region", "Chile", "Americas",
    "Polynesian Rapa Nui Civilization (c. 1100–1650 CE)", "c. 1100–1600 CE", 1250, "Rapa Nui master carvers and clan guilds",
    "Polynesian Monolithic Volcanic Tuff Sculpture", "Average height: 4 m; Tallest erected (Paro): 10 m (33 ft); Unfinished giant: 21.6 m (270 tonnes); Total: 900+ moai",
    "Rano Raraku compressed volcanic lapilli tuff stone, basalt stone chisels (toki), coral and obsidian eyes",
    "Rapa Nui (Easter Island) is an isolated volcanic island in the southeastern Pacific Ocean, 3,700 kilometers west of Chile. Settled by Polynesian navigators around 1100 CE. Between 1100 and 1650 CE, island clans carved nearly 1,000 colossal monolithic stone statues called Moai to honor deceased high chiefs and deified ancestors, believing the statues projected spiritual protective energy (mana) across the tribal villages.",
    "Nearly all moai were carved at Rano Raraku, an extinct volcanic crater, using hand-held basalt stone adzes (toki). The statues feature oversized heads (occupying three-eighths of the total height) with proud, elongated noses, jutting chins, and inset white coral eyes with dark obsidian pupils. Experimental archaeology showed that clans 'walked' the statues upright over miles of rough terrain using ropes rocked rhythmically from side to side, matching Rapa Nui oral traditions that the moai 'walked' from the quarry to their coastal stone platforms (ahu).",
    "Inscribed as a UNESCO World Heritage Site in 1995 as Rapa Nui National Park. One of the most enigmatic cultural monuments in the Pacific.",
    "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&q=80&w=1200",
    ["Moai", "Easter Island", "Chile", "Rapa Nui", "Polynesian", "Volcanic Tuff", "UNESCO"],
    ["Over 900 colossal monolithic statues were carved by Polynesian settlers between 1100 and 1650 CE", "Carved at the volcanic crater of Rano Raraku and 'walked' upright over miles using ropes", "The statues represent deified ancestors projecting their protective spiritual energy (mana)", "Heads occupy three-eighths of the height and were once fitted with white coral and obsidian eyes"],
    "Inscribed 1995 (Rapa Nui National Park)"),

  # 24. CN Tower, Toronto, Canada
  item("cn-tower-toronto", "CN Tower", "Canadian National Tower", "Monument & Tower", "Downtown Toronto, Ontario", "Canada", "Americas",
    "Late 20th Century Concrete Engineering (1973–1976 CE)", "1973–1976 CE", 1976, "WZMH Architects & John Andrews (Structural engineer: Franz Knoll)",
    "Post-Tensioned Concrete Communications & Observation Tower", "Pinnacle height: 553.3 m (1,815 ft); SkyPod: 447 m; Concrete volume: 40,500 m³; Weight: 130,000 tonnes",
    "High-strength post-tensioned slip-form concrete, steel cables, glass floor panels, broadcast antenna",
    "The CN Tower is a 553.3-meter concrete communications and observation tower in Downtown Toronto, Ontario. Built by Canadian National Railway between 1973 and 1976 to solve television and radio broadcasting interference caused by the construction of tall skyscrapers in downtown Toronto. Opened to the public on June 26, 1976.",
    "Held the record as the world's tallest freestanding structure on land for 31 years until surpassed by the Burj Khalifa in 2007. Built using the continuous slip-form method: concrete was poured 24 hours a day as the climbing wooden mold ascended, completing the massive main shaft in just 26 weeks. In 1994, it opened the world's first Glass Floor, allowing visitors to stand 342 meters directly above the city street. Features the 'EdgeWalk', an adrenaline hands-free outdoor walk on a 1.5-meter ledge circling the top of the main pod at 356 meters (1,168 feet).",
    "Named one of the modern Seven Wonders of the World by the American Society of Civil Engineers in 1995. The signature icon of Toronto and Canada.",
    "https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&q=80&w=1200",
    ["CN Tower", "Toronto", "Canada", "Tower", "Tallest Freestanding", "EdgeWalk", "Engineering"],
    ["Held the undisputed record as the world's tallest freestanding structure for 31 years (1976–2007)", "Poured using continuous 24-hour slip-form concrete climbing at 6 meters per day", "Features the famous outdoor 'EdgeWalk' on a 1.5-meter ledge 356 meters above the ground", "Installed the world's first glass observation floor in 1994, capable of holding 14 hippos"],
    "Modern Civil Engineering Wonder"),

  # 25. Château Frontenac, Quebec City, Canada
  item("chateau-frontenac", "Fairmont Le Château Frontenac", "Château Frontenac", "Famous Building", "Old Quebec, Quebec City", "Canada", "Americas",
    "Châteauesque / Canadian Grand Railway Hotel (1892–1893 CE; central tower 1924 CE)", "1892–1924 CE", 1893, "Bruce Price, expanded by Maxwell & Pitts",
    "Châteauesque Style Architecture (French Renaissance Loire châteaux revival)", "Height: 79.9 m (262 ft); 18 floors; 610 guest rooms; Roof slope: steep copper hipped roofs",
    "Glenboig orange brick from Scotland, Deschambault grey limestone, green copper roof sheeting",
    "The Château Frontenac is a grand hotel located in Old Quebec, Quebec City. Perched atop Cap Diamant (Cape Diamond) overlooking the Saint Lawrence River. Commissioned in 1892 by the Canadian Pacific Railway as part of its network of luxury grand railway hotels designed to encourage wealthy tourists to travel across Canada by train. Named in honor of Louis de Buade, Count of Frontenac, the colorful 17th-century Governor General of New France.",
    "Designed by American architect Bruce Price, drawing inspiration from the Renaissance châteaux of the French Loire Valley with steep copper roofs, circular turrets, and ornate gables. Site of the historic First and Second Quebec Conferences during World War II (1943 and 1944), where British Prime Minister Winston Churchill, US President Franklin D. Roosevelt, and Canadian Prime Minister William Lyon Mackenzie King planned the D-Day landings in Normandy and atomic strategies. Officially recognized by the Guinness World Records as the 'most photographed hotel in the world'.",
    "Designated a National Historic Site of Canada in 1981 and part of the UNESCO World Heritage Historic District of Old Québec (1985).",
    "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&q=80&w=1200",
    ["Chateau Frontenac", "Quebec City", "Canada", "Chateauesque", "Grand Railway Hotel", "Churchill", "UNESCO"],
    ["Recognized by Guinness World Records as the most photographed hotel in the world", "Built by the Canadian Pacific Railway atop Cap Diamant overlooking the Saint Lawrence River", "Venue of the 1943 Quebec Conference where Churchill and Roosevelt planned the D-Day invasion", "Features iconic green oxidized copper roofs and French Loire Valley Renaissance turrets"],
    "Inscribed 1985 (Historic District of Old Québec)")
]

print(f"Americas 25 loaded: {len(monuments)}")
