#!/usr/bin/env python3
"""
Full Generator for all 60 European Monuments
Writes directly to src/data/monuments/europeanMonuments.ts
"""
import json
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from build_europe_60 import europe_data, item

more_europe = [
  # 21. Brandenburg Gate
  item("brandenburg-gate", "Brandenburg Gate", "Brandenburger Tor", "Monument & Tower", "Mitte, Berlin", "Germany",
    "Prussian Neoclassicism (1788–1791 CE)", "1788–1791 CE", 1791, "Carl Gotthard Langhans (Sculptor: Johann Gottfried Schadow)",
    "German Neoclassical Monumental Gateway Architecture", "Height: 26 m (85 ft); Width: 65.5 m; Depth: 11 m; 12 Doric columns",
    "Elbe sandstone, bronze Quadriga chariot sculpted by Schadow",
    "The Brandenburg Gate is an 18th-century neoclassical monument in Berlin, commissioned by Prussian King Frederick William II as a key entry into the city and named the 'Peace Gate'. Modeled on the Propylaea, the ceremonial gateway to the Acropolis in Athens.",
    "Crowned by the iconic bronze Quadriga: a chariot drawn by four horses driven by Victoria, the goddess of victory. In 1806, Napoleon took the Quadriga to Paris as a war trophy, returning it after his 1814 defeat. During the Cold War, the gate stood directly inside the Berlin Wall exclusion zone. On June 12, 1987, US President Ronald Reagan made his famous speech here: 'Mr. Gorbachev, tear down this wall!'. Became the joyous global symbol of German reunification in November 1989.",
    "The premier national symbol of Germany, hosting the country's main New Year's Eve festivities.",
    "https://images.unsplash.com/photo-1599940824399-b87987ceb72a?auto=format&fit=crop&q=80&w=1200",
    ["Brandenburg Gate", "Berlin", "Germany", "Quadriga", "Cold War", "Berlin Wall", "Neoclassical"],
    ["Modeled after the Propylaea gateway of the ancient Acropolis in Athens", "Napoleon looted the bronze Quadriga to Paris in 1806; it was reclaimed in 1814", "Stood isolated in the no-man's land of the Berlin Wall during the Cold War", "Site of Ronald Reagan's 1987 speech: 'Mr. Gorbachev, tear down this wall!'"],
    "National Heritage Monument"),

  # 22. Cologne Cathedral
  item("cologne-cathedral", "Cologne Cathedral", "Kölner Dom (Hohe Domkirche Sankt Petrus)", "Sacred Temple / Cathedral", "Cologne, North Rhine-Westphalia", "Germany",
    "High Gothic to 19th Century Completion (1248–1880 CE)", "1248–1880 CE", 1880, "Master Gerhard, Ernst Friedrich Zwirner, Richard Voigtel",
    "High Gothic Cathedral Architecture (Rayonnant Gothic)", "Twin spires height: 157.38 m (516 ft); Length: 144.5 m; Width: 86.2 m; Floor area: 7,914 m²",
    "Trachyte stone from Drachenfels, Obernkirchen sandstone, lead roof, stained glass",
    "Cologne Cathedral is a renowned Gothic cathedral located on the Rhine in Cologne, Germany. Built to house the Shrine of the Three Kings, containing relics of the biblical Magi brought from Milan in 1164 by Holy Roman Emperor Frederick Barbarossa. Construction began in 1248 but halted in 1473, leaving the unfinished cathedral dominated by a medieval wooden crane on the south tower for 400 years. Rekindled by German Romanticism, construction resumed in 1842 using rediscovered original medieval plans and was completed in 1880 in the presence of Emperor Wilhelm I.",
    "Upon its completion in 1880, it was the tallest building in the world for four years until surpassed by the Washington Monument. It has the largest church facade of any church on Earth (7,000 m²). Astonishingly survived 14 direct aerial bomb hits during Allied bombing in World War II, towering above the flattened ruins of Cologne.",
    "Inscribed as a UNESCO World Heritage Site in 1996. Germany's most visited architectural landmark.",
    "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&q=80&w=1200",
    ["Cologne Cathedral", "Cologne", "Germany", "Gothic", "Three Kings", "Twin Spires", "UNESCO"],
    ["Construction spanned 632 years (1248 to 1880) following original medieval parchment plans", "The tallest building in the world from 1880 to 1884, with twin spires soaring 157 meters", "Survived 14 direct bomb hits during World War II while surrounding Cologne was destroyed", "Enshrines the gold-and-silver Shrine of the Three Kings, the largest reliquary in Europe"],
    "Inscribed 1996 (Cologne Cathedral)"),

  # 23. Arc de Triomphe
  item("arc-de-triomphe", "Arc de Triomphe de l'Étoile", "Arc de Triomphe de l'Étoile", "Monument & Tower", "Place Charles de Gaulle, Paris", "France",
    "French Neoclassical Empire Style (1806–1836 CE)", "1806–1836 CE", 1836, "Jean Chalgrin, Louis-Étienne Héricart de Thury",
    "Neoclassical Triumphal Arch Architecture", "Height: 50 m (164 ft); Width: 45 m; Depth: 22 m; Weight: 100,000 tonnes",
    "Château-Landon fine-grained white limestone, sculpted high-relief marble friezes",
    "The Arc de Triomphe is one of the most famous monuments in Paris, standing at the western end of the Champs-Élysées at the center of the Place Charles de Gaulle (historically the Place de l'Étoile). Commissioned by Emperor Napoleon Bonaparte in 1806 following his decisive victory at the Battle of Austerlitz, promising his Grand Army: 'You will return home through arches of triumph.'",
    "Inspired by the Roman Arch of Titus but erected on a colossal scale, over three times larger. Features Francois Rude's monumental high-relief sculpture 'Departure of the Volunteers of 1792' (La Marseillaise). Engraved on its inner walls are the names of 660 French military generals and 158 battles. Beneath the arch lies the Tomb of the Unknown Soldier from World War I, where an eternal flame of remembrance has been rekindled every single evening at 6:30 PM since November 11, 1923.",
    "The focal point of French national military parades, including Bastille Day and the ceremonial finish of the Tour de France.",
    "https://images.unsplash.com/photo-1509299349698-dd22323b5963?auto=format&fit=crop&q=80&w=1200",
    ["Arc de Triomphe", "Paris", "France", "Napoleon", "Champs-Elysees", "Eternal Flame"],
    ["Commissioned by Napoleon in 1806 after his great triumph at the Battle of Austerlitz", "Inner stone walls are engraved with the names of 660 generals and 158 military campaigns", "The eternal flame at the Tomb of the Unknown Soldier has been relit daily since 1923", "Serves as the dramatic finish line for the annual Tour de France cycling race"],
    "National Monument of France"),

  # 24. Trevi Fountain
  item("trevi-fountain", "Trevi Fountain", "Fontana di Trevi", "Monument & Tower", "Trevi District, Rome", "Italy",
    "Late Italian Baroque (1732–1762 CE)", "1732–1762 CE", 1762, "Nicola Salvi, completed by Giuseppe Pannini",
    "Late Roman Baroque Fountain Architecture", "Height: 26.3 m (86 ft); Width: 49.15 m; Daily water flow: 80,000 m³ (2.8 million cu ft)",
    "Travertine stone quarried from Tivoli, Carrara marble statues, Roman tuff rockwork",
    "The Trevi Fountain is the largest Baroque fountain in Rome and one of the most famous fountains in the world. Stands at the terminal point of the Acqua Vergine (Aqua Virgo), an ancient Roman aqueduct built in 19 BCE by Marcus Agrippa that still supplies clean water today. Commissioned by Pope Clement XII, who held an architectural competition won by Nicola Salvi in 1732.",
    "The facade depicts the allegorical drama of the 'Taming of the Waters'. In the center, Oceanus (Titan god of water) rides a shell chariot pulled by two winged sea horses (hippocamps)—one wild and rearing, representing the stormy sea, and one calm, representing tranquil waters—guided by Tritons. Local legend holds that tossing a coin over your left shoulder with your right hand ensures you will return to Rome; tossing two brings romance, and three brings marriage. Approximately 3,000 euros are thrown into the fountain daily, all donated to the Catholic charity Caritas to feed families in need.",
    "Inscribed as a UNESCO World Heritage Site in 1980 as part of the Historic Centre of Rome. Immortalized in Federico Fellini's classic film 'La Dolce Vita'.",
    "https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&q=80&w=1200",
    ["Trevi Fountain", "Rome", "Italy", "Baroque", "Aqua Virgo", "La Dolce Vita", "UNESCO"],
    ["Supplied by the Aqua Virgo aqueduct constructed in 19 BCE, which still brings water today", "Central statue depicts Titan god Oceanus riding a shell chariot drawn by winged sea horses", "Visitors toss over €1.5 million in coins annually, all donated to feed Rome's needy families", "Immortalized in cinema history by Anita Ekberg and Marcello Mastroianni in 'La Dolce Vita'"],
    "Inscribed 1980 (Historic Centre of Rome)"),

  # 25. St. Mark's Basilica & Campanile, Venice
  item("st-marks-basilica", "St. Mark's Basilica & Campanile", "Basilica Cattedrale Patriarcale di San Marco", "Sacred Temple / Cathedral", "Piazza San Marco, Venice", "Italy",
    "Italo-Byzantine to Venetian Gothic (1063–1094 CE; campanile 1514 CE)", "1063–1094 CE", 1094, "Domenico Contarini (Doge), rebuilt 1063",
    "Italo-Byzantine Architecture with Gothic additions", "Campanile height: 98.6 m (323 ft); Interior mosaic area: 8,000 m²; 5 Greek cross domes",
    "Gold leaf glass mosaic tesserae, imported Greek and Anatolian colored marbles, porphyry, bronze",
    "St. Mark's Basilica is the patriarchal cathedral basilica of Venice, standing on the famous Piazza San Marco. Begun in 1063 to replace an earlier church built to house the relics of Saint Mark the Evangelist, stolen from Alexandria by Venetian merchants hidden under barrels of pork in 828 CE. Known as the 'Chiesa d'Oro' (Church of Gold) due to its opulence and Venetian naval dominance across the Mediterranean.",
    "The interior contains over 8,000 square meters of luminous golden glass mosaics depicting biblical scenes, shimmering under natural light. The high altar holds the Pala d'Oro, a Byzantine gold altarpiece studded with 1,927 precious jewels including rubies, sapphires, and emeralds. On the upper facade stand the bronze Horses of Saint Mark, classical Roman sculptures looted from the Hippodrome of Constantinople during the Fourth Crusade in 1204.",
    "Inscribed as a UNESCO World Heritage Site in 1987 as part of 'Venice and its Lagoon'.",
    "https://images.unsplash.com/photo-1514890547357-a9ee288728e0?auto=format&fit=crop&q=80&w=1200",
    ["St Marks", "Venice", "Italy", "Byzantine", "Gold Mosaics", "Pala dOro", "UNESCO"],
    ["Known as the 'Church of Gold' with over 8,000 square meters of gold glass mosaics", "Enshrines the relics of Saint Mark smuggled from Alexandria in 828 CE under pork barrels", "The high altar holds the Pala d'Oro, adorned with 1,927 rubies, emeralds, and sapphires", "The bronze horses on the loggia were looted from Constantinople during the 1204 Fourth Crusade"],
    "Inscribed 1987 (Venice and its Lagoon)"),

  # 26. Doge's Palace, Venice
  item("doges-palace", "Doge's Palace (Palazzo Ducale)", "Palazzo Ducale di Venezia", "Palace & Fortress", "Piazza San Marco, Venice", "Italy",
    "Venetian Gothic Maritime Empire (1340–1442 CE)", "1340–1442 CE", 1442, "Filippo Calendario, Pierpaolo dalle Masegne",
    "Venetian Gothic Architecture (Fusion of Byzantine, Gothic, and Islamic motifs)", "Length: 75 m; Facade arcades: 36 lower arches, 71 upper loggia arches; Sala del Maggior Consiglio: 53 × 25 m",
    "Verona pink marble, Istrian white limestone, gilded carved woodwork, oil canvases",
    "The Doge's Palace was the supreme seat of government, judicial administration, and official residence of the elected Doge of the Most Serene Republic of Venice for over a millennium. Construction began in 1340 in Venetian Gothic style, designed with an inverted visual weight: heavy solid pink marble walls rest atop airy, delicate open loggias and pointed arcades.",
    "The palace contains the monumental Sala del Maggior Consiglio (Great Council Hall), one of the largest unsupported rooms in Europe, where up to 2,000 Venetian patricians met. It features Tintoretto's 'Il Paradiso' (1588–1592), measuring 22 × 7 meters, one of the largest oil paintings on canvas ever created. Connected across the Rio di Palazzo canal to the New Prisons via the covered Bridge of Sighs (Ponte dei Sospiri), named by Lord Byron for the sighs of convicts viewing Venice for the last time.",
    "Inscribed as a UNESCO World Heritage Site in 1987 as part of 'Venice and its Lagoon'. Welcomes over 1.4 million visitors annually.",
    "https://images.unsplash.com/photo-1514890547357-a9ee288728e0?auto=format&fit=crop&q=80&w=1200",
    ["Doges Palace", "Venice", "Italy", "Venetian Gothic", "Bridge of Sighs", "Tintoretto", "UNESCO"],
    ["Served as the political, administrative, and judicial heart of the Venetian Republic for 1,000 years", "Built with visual inversion: heavy stone walls rest atop light, delicate open-air arcades", "Houses Tintoretto's 'Il Paradiso', one of the largest canvas oil paintings in art history", "Connected to the historic state prison by the famous covered Bridge of Sighs"],
    "Inscribed 1987 (Venice and its Lagoon)"),

  # 27. Ponte Vecchio, Florence
  item("ponte-vecchio", "Ponte Vecchio (Old Bridge)", "Ponte Vecchio", "Bridge & Engineering", "Arno River, Florence, Tuscany", "Italy",
    "Medieval Renaissance Florence (Rebuilt 1345 CE)", "1345 CE", 1345, "Taddeo Gaddi or Neri di Fioravante",
    "Medieval Segmental Stone Arch Bridge Architecture", "Total length: 84 m (276 ft); Width: 32 m; Central arch span: 30 m",
    "Pietra forte sandstone ashlar masonry, timber frames, terracotta roof tiles",
    "Ponte Vecchio is a medieval stone segmental arch bridge over the Arno River in Florence, Italy. Built in 1345 to replace a wooden bridge destroyed by a catastrophic flood in 1333. It is world-renowned for still having houses, shops, and merchants built along both sides of its span. Originally occupied by butchers and tanners who discarded animal waste directly into the river.",
    "In 1593, Grand Duke Ferdinand I evicted the butchers because of the stench and decreed that only goldsmiths and jewelers could occupy the bridge shops—a tradition that continues today. Above the shops runs the Corridoio Vasariano (Vasari Corridor), a private elevated passageway built in 1565 by Giorgio Vasari so the Medici rulers could walk between the Palazzo Vecchio and Palazzo Pitti in safety. It was the only bridge in Florence not blown up by retreating German forces in World War II, reportedly saved on the direct orders of Gerhard Wolf.",
    "Inscribed as a UNESCO World Heritage Site in 1982 as part of the Historic Centre of Florence.",
    "https://images.unsplash.com/photo-1543429776-2782fc8e1acd?auto=format&fit=crop&q=80&w=1200",
    ["Ponte Vecchio", "Florence", "Italy", "Arno", "Medici", "Vasari Corridor", "UNESCO"],
    ["The oldest stone segmental arch bridge in Europe, completed in 1345 over the Arno River", "Grand Duke Ferdinand I evicted butchers in 1593, replacing them permanently with goldsmiths", "Features the elevated Vasari Corridor enabling the Medici family to cross the city in private", "The only bridge across the Arno in Florence spared from destruction by retreating German forces in 1944"],
    "Inscribed 1982 (Historic Centre of Florence)"),

  # 28. Roman Forum
  item("roman-forum", "The Roman Forum", "Forum Romanum / Foro Romano", "Archaeological City", "Piazza Santa Maria Nova, Rome", "Italy",
    "Roman Kingdom, Republic, and Empire (c. 600 BCE – 400 CE)", "c. 500 BCE – 312 CE", -500, "Roman kings, consuls, and emperors",
    "Classical Roman Civic, Religious & Triumphal Architecture", "Valley area: 250 × 170 m (4 hectares); Contains 30 major temples, basilicas, and monuments",
    "Travertine limestone, Roman marble, tufa, Roman concrete, gilded bronze",
    "The Roman Forum was the pulsating ceremonial, legal, religious, and political center of ancient Rome for over a millennium. Situated in the valley between the Palatine and Capitoline Hills, originally an unhealthy swamp until drained in the 6th century BCE by the Cloaca Maxima sewer under King Tarquinius Priscus. Site of the Senate House (Curia Julia), the Temple of Saturn, the Arch of Septimius Severus, and the Rostra orator's platform where Mark Antony delivered Caesar's funeral oration.",
    "It contained the Temple of Vesta, where the Vestal Virgins tended the sacred eternal fire of Rome, and the Regia, the ancient residence of the Pontifex Maximus. In the center stood the Umbilicus Urbis Romae ('Navel of the City of Rome') and the Golden Milestone (Milliarium Aureum), the symbolic point from which all Roman roads across the Mediterranean radiated.",
    "Inscribed as a UNESCO World Heritage Site in 1980 as part of the Historic Centre of Rome. The ultimate archaeological landscape of classical Mediterranean statecraft.",
    "https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&q=80&w=1200",
    ["Roman Forum", "Rome", "Italy", "Senate", "Julius Caesar", "Curia", "UNESCO"],
    ["The political, legal, and commercial beating heart of the Roman Empire for over a millennium", "Site where Mark Antony delivered Julius Caesar's funeral oration in 44 BCE", "Enclosed the Temple of Vesta where Vestal Virgins guarded Rome's eternal sacred fire", "Contained the Golden Milestone from which all paved Roman roads across Europe were measured"],
    "Inscribed 1980 (Historic Centre of Rome)"),

  # 29. Pompeii Ruins
  item("pompeii-ruins", "Archaeological Areas of Pompeii", "Pompeii Ruinae", "Archaeological City", "Pompei, Campania", "Italy",
    "Classical Antiquity Roman Period (Destroyed 79 CE)", "6th Century BCE – 79 CE", 79, "Oscans, Samnites, and Roman citizens",
    "Roman Urban Planning, Villas, Atriums, and Fresco Architecture", "Excavated area: 44 hectares (110 acres); City wall perimeter: 3.2 km; Population: ~20,000",
    "Volcanic tufa blocks, Roman brick, pozzolanic mortar, fresco pigment on wet plaster, tesserae mosaics",
    "Pompeii was a prosperous Greco-Roman city in the shadow of Mount Vesuvius near the Bay of Naples. On August 24 (or October 24), 79 CE, Mount Vesuvius erupted violently, burying the entire city under six meters of volcanic ash, pumice, and superheated pyroclastic surges in less than 24 hours. Preserved beneath the oxygen-deprived volcanic blanket for 1,700 years until systematic excavations began in 1748 under King Charles III of Naples.",
    "Because the catastrophe froze the city in time, Pompeii offers an unparalleled snapshot of Roman daily life: bakeries with loaves of bread still inside stone ovens, graffiti scrawled on election walls, thermopolia (ancient fast-food snack bars) with jars in stone counters, and lavish villas decorated with vivid mythological frescoes and mosaics (like the Alexander Mosaic in the House of the Faun). Italian archaeologist Giuseppe Fiorelli invented the technique of pouring plaster into the hollow voids left by decayed human bodies in the hardened ash, capturing the poignant final death postures of victims.",
    "Inscribed as a UNESCO World Heritage Site in 1997. Welcomes over 3.5 million visitors annually.",
    "https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&q=80&w=1200",
    ["Pompeii", "Naples", "Italy", "Vesuvius", "Roman Ruins", "Archaeology", "UNESCO"],
    ["Buried under six meters of volcanic ash in 79 CE, preserving a Roman city for 1,700 years", "Plaster casts reveal the poignant final moments and physical features of victims in the ash", "Features complete ancient Roman streets, bakeries with carbonized bread, and snack bars", "Home to the Alexander Mosaic and world-renowned First to Fourth Style Roman frescoes"],
    "Inscribed 1997 (Archaeological Areas of Pompei)"),

  # 30. Hermitage Museum / Winter Palace, Russia
  item("hermitage-winter-palace", "The Winter Palace & Hermitage Museum", "Зимний дворец (Zimniy Dvorets) / Государственный Эрмитаж", "Palace & Fortress", "Palace Square, St. Petersburg", "Russia",
    "Russian Imperial Golden Age (1754–1762 CE)", "1754–1762 CE", 1762, "Francesco Bartolomeo Rastrelli, commissioned by Empress Elizabeth Petrovna",
    "Elizabethan Russian Baroque Palace Architecture", "Length: 215 m; Width: 160 m; Height: 22 m; 1,500 rooms; 1,786 doors; 1,945 windows",
    "Mint-green and white stucco facade, gilded bronze capitals, marble, porphyry, malachite",
    "The Winter Palace in Saint Petersburg was the official winter residence of the Russian Tsars of the Romanov dynasty from 1732 to 1917. Built by Italian-Russian architect Bartolomeo Rastrelli for Empress Elizabeth. Catherine the Great transformed it into a world-class cultural institution by purchasing art collections across Europe, founding the Hermitage in 1764. On October 25, 1917, the Bolshevik storming of the Winter Palace signaled the victory of the Russian Revolution.",
    "The State Hermitage Museum holds over 3 million items, including masterpieces by Leonardo da Vinci, Rembrandt, Michelangelo, and Titian. The palace features the Jordan Staircase of white Carrara marble and the Malachite Room, decorated with over two tonnes of polished green Ural malachite stone applied using Russian mosaic technique. Its facade on Palace Square is crowned by 176 neoclassical statues and vases.",
    "Inscribed as a UNESCO World Heritage Site in 1990 as part of the Historic Centre of Saint Petersburg. One of the largest art museums in the world.",
    "https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?auto=format&fit=crop&q=80&w=1200",
    ["Hermitage", "Winter Palace", "St Petersburg", "Russia", "Baroque", "Romanov", "UNESCO"],
    ["Official residence of the Russian Tsars from 1732 until the Bolshevik Revolution in 1917", "Founded in 1764 by Catherine the Great, holding over 3 million works of world art", "Features the Jordan Staircase and the Malachite Room decorated with two tons of Ural malachite", "Built by Bartolomeo Rastrelli in opulent turquoise, white, and gold Russian Baroque"],
    "Inscribed 1990 (Historic Centre of Saint Petersburg)"),

  # 31. Moscow Kremlin & Red Square
  item("moscow-kremlin", "The Moscow Kremlin & Red Square", "Московский Кремль (Moskovsky Kreml - Citadel)", "Palace & Fortress", "Central Administrative Okrug, Moscow", "Russia",
    "Medieval to Tsarist Era (1485–1495 CE walls; founded 1147 CE)", "1485–1495 CE", 1495, "Aristotele Fioravanti, Pietro Antonio Solari, Marco Ruffo (commissioned by Ivan III)",
    "Russian Medieval & Renaissance Citadel Fortress Architecture", "Wall length: 2,235 m (1.39 mi); Wall height: 5–19 m; Wall thickness: 3.5–6.5 m; 20 defensive towers",
    "Kiln-baked red brick, white limestone foundations, gold leaf cathedral domes, cast bronze",
    "The Moscow Kremlin is a historic fortified complex in the heart of Moscow, overlooking the Moskva River. Founded in 1147 by Prince Yuri Dolgorukiy. In the late 15th century, Grand Prince Ivan III ('Ivan the Great') invited master architects from Renaissance Italy (including Aristotele Fioravanti) to rebuild the fortress walls in red brick with distinctive swallow-tail battlements (Ghibelline merlons) and construct Cathedral Square.",
    "The complex encloses four historic cathedrals, including the Dormition Cathedral where all Russian Tsars were crowned. It houses the Tsar Bell (the largest bell in the world, weighing 202 tonnes) and the Tsar Cannon (the largest bombard by caliber at 890 mm). The Grand Kremlin Palace contains the official working residence of the President of the Russian Federation.",
    "Inscribed as a UNESCO World Heritage Site in 1990 in conjunction with Red Square. The monumental center of Russian statehood for over eight centuries.",
    "https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?auto=format&fit=crop&q=80&w=1200",
    ["Kremlin", "Moscow", "Russia", "Red Square", "Citadel", "Tsar Bell", "UNESCO"],
    ["Fortress walls were built in 1485–1495 by Italian Renaissance architects hired by Ivan III", "Contains Cathedral Square, where Russian Tsars and Emperors were traditionally crowned", "Houses the 202-tonne Tsar Bell, the largest bell in the world, cast in bronze in 1735", "Serves as the official working residence of the President of the Russian Federation"],
    "Inscribed 1990 (Kremlin and Red Square)"),

  # 32. Church of the Savior on Spilled Blood, St. Petersburg
  item("savior-on-blood", "Church of the Savior on Spilled Blood", "Храм Спаса на Крови (Cathedral of the Resurrection of Christ)", "Sacred Temple / Cathedral", "Griboyedov Canal, St. Petersburg", "Russia",
    "Russian Revival / Neo-Russian Style (1883–1907 CE)", "1883–1907 CE", 1907, "Alfred Parland and Archimandrite Ignaty",
    "Romantic Russian Revival Architecture (Muscovite 17th-century style)", "Height: 81 m (266 ft); Mosaic area: 7,500 m² (largest mosaic collection in Europe)",
    "Polychrome glazed ceramic tiles, enameled onion domes, Italian marble, Ural jasper, topaz, rhodonite",
    "The Church of the Savior on Spilled Blood is a cathedral in Saint Petersburg, built on the exact spot where Tsar Alexander II was assassinated on March 1, 1881, by members of the revolutionary Narodnaya Volya ('People's Will') movement who threw a dynamite bomb into his carriage. His son, Tsar Alexander III, commissioned the church as a sacred imperial memorial. Built in vivid contrast to Saint Petersburg's predominant Baroque and Neoclassical architecture, drawing inspiration from medieval Russian churches like Saint Basil's in Moscow.",
    "The interior and exterior are covered in 7,500 square meters of intricate mosaics, designed by prominent Russian artists including Viktor Vasnetsov and Mikhail Nesterov. Inside, the canopy altar enshrines the original cobblestone section of the canal embankment where the Tsar's blood was spilled, preserved under a canopy of jasper and rhodonite. During the 900-day Siege of Leningrad in World War II, the church was used as a temporary morgue and vegetable warehouse.",
    "Part of the UNESCO World Heritage Historic Centre of Saint Petersburg (1990). One of the greatest masterpieces of mosaic art on Earth.",
    "https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?auto=format&fit=crop&q=80&w=1200",
    ["Savior on Blood", "St Petersburg", "Russia", "Mosaics", "Alexander II", "Russian Revival", "UNESCO"],
    ["Built on the exact spot where Tsar Alexander II was fatally wounded by a bomb in March 1881", "Contains over 7,500 square meters of mosaics, the largest collection in any church in Europe", "Enshrines the original bloodstained cobblestones of the street beneath a canopy of Ural jasper", "Modeled directly after Saint Basil's Cathedral in Moscow with vibrant enameled onion domes"],
    "Inscribed 1990 (Historic Centre of Saint Petersburg)"),

  # 33. Catherine Palace (Amber Room), Russia
  item("catherine-palace", "Catherine Palace & The Amber Room", "Екатерининский дворец (Yekaterininsky Dvorets) / Янтарная комната", "Palace & Fortress", "Tsarskoye Selo, Pushkin, St. Petersburg", "Russia",
    "Russian Rococo Imperial Golden Age (1717–1756 CE)", "1756 CE", 1756, "Bartolomeo Rastrelli, commissioned by Empress Elizabeth Petrovna",
    "Russian Rococo Palace Architecture", "Length: 325 m (1,066 ft); Gold leaf on exterior: over 100 kg; Park area: 300 hectares",
    "Cyan-blue and white plaster facade, gilded caryatids and pilasters, six tonnes of Baltic amber panels",
    "The Catherine Palace was the rococo summer residence of the Russian tsars, located in the town of Tsarskoye Selo (Pushkin), 25 kilometers south of Saint Petersburg. Named after Catherine I, wife of Peter the Great. Transformed into an immense palace in 1752 by Empress Elizabeth, who hired court architect Bartolomeo Rastrelli to outshine Versailles. Over 100 kilograms of pure gold leaf was used to gild the exterior statues and roof urns.",
    "World-famous for housing the legendary Amber Room (Yantarnaya Komnata), celebrated in Europe as the 'Eighth Wonder of the World'. Constructed from six tonnes of carved amber panels backing gold leaf and mirrors, gifted to Peter the Great in 1716 by King Frederick William I of Prussia. Looted by Nazi troops during World War II and shipped to Königsberg Castle, where it mysteriously disappeared in 1945. Between 1979 and 2003, Russian craftsmen completely reconstructed the Amber Room using 434 amber panels funded by German and Russian donations.",
    "Part of the UNESCO World Heritage Historic Centre of Saint Petersburg (1990).",
    "https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?auto=format&fit=crop&q=80&w=1200",
    ["Catherine Palace", "Amber Room", "Tsarskoye Selo", "Russia", "Rococo", "Rastrelli", "UNESCO"],
    ["Built by Bartolomeo Rastrelli in opulent turquoise and gold for Empress Elizabeth in 1756", "The legendary Amber Room was constructed of six tonnes of carved Baltic amber panels and gold leaf", "The original room was looted by Nazi troops in 1941 and vanished during the fall of Königsberg", "Painstakingly reconstructed over 24 years using 434 new amber panels, reopening in 2003"],
    "Inscribed 1990 (Historic Centre of Saint Petersburg)"),

  # 34. Prague Castle
  item("prague-castle", "Prague Castle (Pražský Hrad)", "Pražský hrad", "Palace & Fortress", "Hradčany, Prague", "Czech Republic",
    "Bohemian Romanesque to Gothic & Modern (870 CE – 1929 CE)", "870–1929 CE", 870, "Prince Bořivoj I, Peter Parler, Josip Plečnik",
    "Bohemian Gothic, Renaissance & Mannerist Castle Architecture", "Area: 70,000 m² (750,000 sq ft); Length: 570 m; Width: 130 m (Largest ancient castle complex)",
    "Bohemian sandstone, granite, lime mortar, Bohemian crystal chandeliers, lead roofing",
    "Prague Castle is the official office of the President of the Czech Republic and former seat of power for Kings of Bohemia, Holy Roman Emperors, and presidents of Czechoslovakia. Founded in 870 CE by Prince Bořivoj of the Přemyslid dynasty. According to the Guinness Book of Records, Prague Castle is the largest ancient castle complex in the world, occupying an area of almost 70,000 square meters.",
    "Site of the famous 1618 Second Defenestration of Prague, when Protestant nobles hurled Catholic Habsburg regents out of a palace window into a dung heap, triggering the devastating Thirty Years' War. Encloses the Gothic St. Vitus Cathedral, the Old Royal Palace with Vladislav Hall (where knights held indoor jousting tournaments on horseback), St. George's Basilica, and Golden Lane (Zlatá ulička), where 16th-century royal alchemists sought the philosopher's stone and Franz Kafka later lived at No. 22.",
    "Inscribed as a UNESCO World Heritage Site in 1992 as part of the Historic Centre of Prague. The political and spiritual crown of Bohemia.",
    "https://images.unsplash.com/photo-1541849546-216549ae216d?auto=format&fit=crop&q=80&w=1200",
    ["Prague Castle", "Prague", "Czech Republic", "Bohemia", "Guinness Record", "Hradcany", "UNESCO"],
    ["Recognized by Guinness World Records as the largest ancient castle complex in the world (70,000 m²)", "The 1618 Defenestration of Prague here sparked the continent-wide Thirty Years' War", "Features the Vladislav Hall, where medieval knights held indoor jousting tournaments on horses", "Houses Golden Lane, where alchemists worked and author Franz Kafka lived at House No. 22"],
    "Inscribed 1992 (Historic Centre of Prague)"),

  # 35. Charles Bridge, Prague
  item("charles-bridge", "Charles Bridge (Karlův Most)", "Karlův most (Stone Bridge)", "Bridge & Engineering", "Vltava River, Prague", "Czech Republic",
    "Medieval Bohemian Gothic (1357–1402 CE)", "1357–1402 CE", 1402, "Peter Parler, commissioned by Holy Roman Emperor Charles IV",
    "Bohemian High Gothic Stone Arch Bridge Architecture", "Length: 516 m (1,693 ft); Width: 9.5 m; 16 sandstone arches; 30 baroque saint statues",
    "Bohemian sandstone blocks, egg-mortar legend (mortar mixed with egg whites, wine, and milk)",
    "Charles Bridge is a historic stone Gothic bridge crossing the Vltava River in Prague. Commissioned in 1357 by Holy Roman Emperor Charles IV to replace the Judith Bridge, which had collapsed in a flood in 1342. Construction was supervised by master builder Peter Parler. According to chroniclers, Charles IV laid the bridge foundation stone personally at precisely 5:31 AM on July 9, 1357 (creating an astronomical palindrome: 1357 9/7 5:31), believed by astrologers to protect the bridge from destruction.",
    "The bridge spans 516 meters on 16 graceful arches and is guarded by three fortified Gothic bridge towers. Between 1683 and 1714, 30 baroque statues and statuaries of Christian saints were erected along the balustrades, notably the bronze statue of Saint John of Nepomuk, who was drowned from the bridge in 1393 by King Wenceslaus IV; touching his bronze plaque is said to bring good luck and a guaranteed return to Prague.",
    "Inscribed as a UNESCO World Heritage Site in 1992 as part of the Historic Centre of Prague. A pedestrian thoroughfare celebrated by poets, artists, and musicians.",
    "https://images.unsplash.com/photo-1541849546-216549ae216d?auto=format&fit=crop&q=80&w=1200",
    ["Charles Bridge", "Prague", "Czech Republic", "Vltava", "Charles IV", "Baroque Statues", "UNESCO"],
    ["Foundation stone laid by Charles IV at 5:31 AM on July 9, 1357, creating an astrological palindrome", "Legend claims medieval builders mixed thousands of egg whites and milk into the mortar for strength", "Decorated with 30 baroque saint statues, including Saint John of Nepomuk who was martyred here", "Successfully withstood six centuries of catastrophic Vltava River ice floods and wars"],
    "Inscribed 1992 (Historic Centre of Prague)"),

  # 36. St. Vitus Cathedral, Prague
  item("st-vitus-cathedral", "St. Vitus Cathedral", "Katedrála svatého Víta, Václava a Vojtěcha", "Sacred Temple / Cathedral", "Prague Castle, Prague", "Czech Republic",
    "High Gothic to Modern Completion (1344–1929 CE)", "1344–1929 CE", 1929, "Matthias of Arras, Peter Parler, Kamil Hilbert",
    "French and Bohemian High Gothic Cathedral Architecture", "South tower height: 96.5 m; Nave height: 33.2 m; Length: 124 m; Width: 60 m",
    "Bohemian sandstone, lead roofing, Bohemian garnet and semi-precious stone inlays, stained glass by Alfons Mucha",
    "St. Vitus Cathedral is a Gothic cathedral located entirely within the Prague Castle complex. Founded in 1344 by King John of Bohemia and Charles IV. Built under master builders Matthias of Arras and Peter Parler. Halted during the 15th-century Hussite Wars and left half-finished for centuries until the Union for the Completion of the Cathedral finished work in 1929, marking the millennium of the death of Saint Wenceslaus.",
    "Contains the St. Wenceslaus Chapel (Svatováclavská kaple), decorated with over 1,300 polished Bohemian gemstones (jasper, amethyst, agate) and 14th-century frescoes depicting the Passion of Christ. Above the chapel sits the Crown Chamber, locked with seven separate keys held by seven state and church leaders (including the Czech President and Prime Minister), holding the Bohemian Crown Jewels and the legendary St. Wenceslaus Crown; legend holds that any usurper who wears the crown will die within a year.",
    "Inscribed as a UNESCO World Heritage Site in 1992 as part of the Historic Centre of Prague.",
    "https://images.unsplash.com/photo-1541849546-216549ae216d?auto=format&fit=crop&q=80&w=1200",
    ["St Vitus", "Prague", "Czech Republic", "Gothic", "Wenceslaus", "Crown Jewels", "UNESCO"],
    ["Took nearly 600 years to complete from 1344 to its final consecration in 1929", "St. Wenceslaus Chapel walls are encrusted with over 1,300 Bohemian precious gems and gold leaf", "The Crown Chamber requires seven separate keys held by seven Czech state leaders to unlock", "Features stunning early 20th-century Art Nouveau stained glass designed by Alfons Mucha"],
    "Inscribed 1992 (Historic Centre of Prague)"),

  # 37. Schönbrunn Palace, Vienna
  item("schonbrunn-palace", "Schönbrunn Palace", "Schloss Schönbrunn (Beautiful Spring)", "Palace & Fortress", "Hietzing, Vienna", "Austria",
    "Habsburg High Baroque Golden Age (1696–1750 CE)", "1743–1750 CE", 1750, "Johann Bernhard Fischer von Erlach & Nicolò Pacassi",
    "Austrian High Baroque and Rococo Imperial Palace Architecture", "1,441 rooms; 45 State Apartments open to public; Grounds area: 160 hectares (395 acres)",
    "Yellow ochre limestone ('Schönbrunn Yellow'), gilded stucco, Bohemian crystal chandeliers, mirror glass",
    "Schönbrunn Palace was the principal summer residence of the Habsburg monarchs in Vienna, Austria. The name Schönbrunn ('beautiful spring') derives from an artesian well used by the imperial court. Transformed in the 1740s by Empress Maria Theresa into an opulent Rococo imperial palace for her 16 children (including Marie Antoinette). Emperor Franz Joseph was born here in 1830 and died here in 1916 during the First World War.",
    "Contains 1,441 rooms, featuring the Great Gallery (Große Galerie), a 40-meter hall decorated with gilded stucco and ceiling frescoes depicting Habsburg triumphs, where the 1961 Kennedy-Khrushchev summit was held. In 1762, a six-year-old child prodigy named Wolfgang Amadeus Mozart played his first royal concert in the Hall of Mirrors, famously leaping into Empress Maria Theresa's lap to hug her. The palace park contains the Gloriette colonnade and the Tiergarten Schönbrunn, founded in 1752—the oldest continuously operating zoo in the world.",
    "Inscribed as a UNESCO World Heritage Site in 1996. Attracts over 4 million visitors annually.",
    "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&q=80&w=1200",
    ["Schonbrunn", "Vienna", "Austria", "Habsburg", "Maria Theresa", "Mozart", "UNESCO"],
    ["The 1,441-room summer palace of the Habsburg dynasty and Empress Maria Theresa", "Six-year-old child prodigy Mozart played his first royal concert here in 1762", "The grounds house the Tiergarten Schönbrunn, the oldest operating zoo in the world (founded 1752)", "Venue of the historic 1961 Cold War summit between John F. Kennedy and Nikita Khrushchev"],
    "Inscribed 1996 (Palace and Gardens of Schönbrunn)"),

  # 38. St. Stephen's Cathedral (Stephansdom), Vienna
  item("st-stephens-vienna", "St. Stephen's Cathedral (Stephansdom)", "Stephansdom (Domkirche St. Stephan zu Wien)", "Sacred Temple / Cathedral", "Stephansplatz, Innere Stadt, Vienna", "Austria",
    "Romanesque to High Gothic (1137–1511 CE)", "1137–1511 CE", 1147, "Master Wenzla, Anton Pilgram, Duke Rudolf IV ('The Founder')",
    "Gothic and Romanesque Cathedral Architecture", "South Tower ('Steffl') height: 136.4 m (447 ft); Length: 107 m; 230,000 colored glazed roof tiles",
    "Sandstone ashlar masonry, polychrome glazed roof ceramic tiles, marble altars",
    "St. Stephen's Cathedral is the mother church of the Roman Catholic Archdiocese of Vienna and the most prominent symbol of Vienna. Begun in 1137 under the Babenberg dukes and expanded into a magnificent Gothic cathedral by Habsburg Duke Rudolf IV in the 14th century. The south tower, affectionately called 'Steffl' by locals, rises 136.4 meters and served as Vienna's main observation post during the Ottoman sieges of 1529 and 1683.",
    "World-famous for its kaleidoscopic geometric roof covered in 230,000 glazed ceramic tiles forming the double-headed imperial eagle of the Habsburg monarchy and the coats of arms of Vienna and Austria. Houses the Pummerin ('Boomer'), the second-largest free-swinging church bell in Europe, cast in 1711 from 180 captured Ottoman bronze cannons. Master sculptor Anton Pilgram carved his own self-portrait peeking out from beneath the cathedral organ and the stone pulpit.",
    "Inscribed as a UNESCO World Heritage Site in 2001 as part of the Historic Centre of Vienna.",
    "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&q=80&w=1200",
    ["Stephansdom", "Vienna", "Austria", "Gothic", "Habsburg", "Pummerin", "UNESCO"],
    ["The geometric roof is clad in 230,000 glazed tiles depicting the Habsburg double-headed eagle", "The south tower ('Steffl') soars 136 meters and served as a lookout during the 1683 siege", "The famous 'Pummerin' bell was cast in 1711 from 180 captured Ottoman bronze cannons", "Sculptor Anton Pilgram carved an iconic self-portrait peeking from beneath the pulpit"],
    "Inscribed 2001 (Historic Centre of Vienna)"),

  # 39. Belém Tower, Lisbon, Portugal
  item("belem-tower", "Belém Tower (Torre de Belém)", "Torre de Belém (Torre de São Vicente)", "Palace & Fortress", "Belém, Lisbon", "Portugal",
    "Portuguese Age of Discovery Manueline Era (1514–1519 CE)", "1514–1519 CE", 1519, "Francisco de Arruda, commissioned by King Manuel I",
    "Manueline Portuguese Late Gothic Fortress Architecture", "Height: 30 m (98 ft); 4 storeys; Hexagonal bastion length: 30 m; 17 cannon ports",
    "Lioz limestone (Portuguese royal marble), carved stone nautical ropes, armillary spheres",
    "Belém Tower is a 16th-century fortified tower located in the Belém district of Lisbon. Commissioned by King Manuel I in 1514 to serve as a military defense gateway at the mouth of the Tagus River and a ceremonial departure and arrival beacon for Portuguese navigators—including Vasco da Gama and Pedro Álvares Cabral—embarking on epic voyages to discover maritime trade routes to India and Brazil.",
    "A masterpiece of the Manueline architectural style (Portuguese Late Gothic), featuring intricate stone-carved maritime symbols: twisted naval ropes, armillary spheres, crosses of the Order of Christ, and Moorish watchtower bartizans. Beneath one of the turrets sits a famous carved stone gargoyle in the shape of a rhinoceros, inspired by the live Indian rhinoceros sent by the Governor of Portuguese India to King Manuel I in 1515. Originally built on a basalt island in the middle of the Tagus, subsequent shoreline silting after the 1755 Lisbon earthquake brought the tower close to the riverbank.",
    "Inscribed as a UNESCO World Heritage Site in 1983 in conjunction with the Jerónimos Monastery. The national emblem of Portugal's Age of Discovery.",
    "https://images.unsplash.com/photo-1508672019048-805b876b67e2?auto=format&fit=crop&q=80&w=1200",
    ["Belem Tower", "Lisbon", "Portugal", "Manueline", "Age of Discovery", "Vasco da Gama", "UNESCO"],
    ["Ceremonial gateway where Portuguese navigators departed for India and the New World", "Built in 1514 in ornate Manueline style decorated with stone maritime ropes and spheres", "Features a famous stone-carved rhinoceros gargoyle inspired by an Indian rhino gift in 1515", "Shifted closer to shore after the cataclysmic 1755 Lisbon earthquake altered the Tagus River"],
    "Inscribed 1983 (Monastery of the Hieronymites and Tower of Belém)"),

  # 40. Jerónimos Monastery, Lisbon, Portugal
  item("jeronimos-monastery", "Jerónimos Monastery (Hieronymites)", "Mosteiro dos Jerónimos (Mosteiro de Santa Maria de Belém)", "Sacred Temple / Cathedral", "Belém, Lisbon", "Portugal",
    "Portuguese Age of Discovery Manueline Golden Age (1501–1601 CE)", "1501–1601 CE", 1601, "Diogo de Boitaca, João de Castilho, commissioned by King Manuel I",
    "Manueline Architecture (Portuguese Flamboyant Gothic)", "Cloister dimensions: 55 × 55 m; Church length: 70 m; Vault height: 25 m",
    "Lioz limestone (crème-colored calciclastic limestone), carved vaults",
    "The Jerónimos Monastery is a former monastery of the Order of Saint Jerome in Belém, Lisbon. Commissioned in 1501 by King Manuel I to celebrate Vasco da Gama's successful maritime discovery of the sea route to India in 1498. Funded directly by the 'Vintena da Pimenta' (a 5 percent royal tax on spices, gold, and precious gems imported from the Orient). Navigators spent their final night in prayer in the monastery's chapel before setting sail.",
    "The two-story cloister is celebrated as one of the most beautiful courtyards in world architecture, with delicate openwork arches carved with maritime motifs, exotic animals, coral branches, and nautical knots. The church of Santa Maria features an audacious single stone fan-vault ceiling that spans 30 meters without central column supports, which miraculously survived the massive 1755 Lisbon earthquake without a single crack. The monastery encloses the ornate stone tombs of explorer Vasco da Gama and Portugal's national poet Luís de Camões.",
    "Inscribed as a UNESCO World Heritage Site in 1983. In 2007, the historic Treaty of Lisbon was signed here by European Union heads of state.",
    "https://images.unsplash.com/photo-1508672019048-805b876b67e2?auto=format&fit=crop&q=80&w=1200",
    ["Jeronimos Monastery", "Lisbon", "Portugal", "Manueline", "Vasco da Gama", "Camoes", "UNESCO"],
    ["Funded by a 5% royal spice tax on pepper and cinnamon imported from the Portuguese Indies", "The two-tier stone cloister is considered the crowning masterpiece of Manueline architecture", "Miraculously survived the cataclysmic 1755 Lisbon earthquake without structural collapse", "Houses the tombs of national navigator Vasco da Gama and epic poet Luís de Camões"],
    "Inscribed 1983 (Monastery of the Hieronymites and Tower of Belém)"),

  # 41. Pena Palace, Sintra, Portugal
  item("pena-palace", "Pena Palace (Palácio da Pena)", "Palácio Nacional da Pena", "Palace & Fortress", "Sintra Mountains, Lisbon District", "Portugal",
    "Romanticism Golden Age (1840–1854 CE)", "1840–1854 CE", 1854, "Wilhelm Ludwig von Eschwege, commissioned by King Ferdinand II",
    "Romanticist Eclectic Architecture (Neo-Gothic, Neo-Manueline, Neo-Islamic, Neo-Renaissance)", "Elevation: 529 m atop Sintra peak; Park area: 200 hectares (500 acres); 500 tree species",
    "Vibrant yellow ochre, pastel red, and violet stucco facades, Lioz limestone, azulejo ceramic tiles",
    "Pena Palace is a Romanticist castle perched atop a rugged granite peak in the Sintra Mountains above Lisbon. Commissioned in 1840 by King Consort Ferdinand II (Ferdinand of Saxe-Coburg and Gotha), an artistic monarch known as the 'Artist-King'. Ferdinand transformed the ruins of a medieval Hieronymite monastery destroyed in the 1755 earthquake into an eclectic summer castle, designing it alongside German mining engineer Wilhelm Ludwig von Eschwege.",
    "The castle is a colorful fairy tale, combining bright yellow and pastel red towers with Islamic onion domes, Gothic battlements, and Renaissance drawbridges. The Triton Terrace features a fearsome high-relief stone sculpture of a mythological Triton (half-man, half-fish) emerging from a conch shell with tree branches growing from his head, symbolizing the creation of the world out of chaos. The surrounding 200-hectare Pena Park was planted with exotic trees from every continent, including North American sequoias, Australian eucalyptus, Japanese cryptomeria, and Western red cedars.",
    "Inscribed as a UNESCO World Heritage Site in 1995 as the centerpiece of the Cultural Landscape of Sintra. One of the Seven Wonders of Portugal.",
    "https://images.unsplash.com/photo-1508672019048-805b876b67e2?auto=format&fit=crop&q=80&w=1200",
    ["Pena Palace", "Sintra", "Portugal", "Romanticism", "Ferdinand II", "Fairy Tale", "UNESCO"],
    ["Perched on a 529-meter mountain peak, visible on clear days from central Lisbon", "Commissioned in 1840 by King Ferdinand II blending Neo-Gothic, Moorish, and Manueline styles", "Features the famous gargoyle of the mythological Triton emerging from a giant sea shell", "Surrounded by a 200-hectare botanical park planted with exotic flora from all five continents"],
    "Inscribed 1995 (Cultural Landscape of Sintra)"),

  # 42. Mezquita-Cathedral of Córdoba, Spain
  item("mezquita-cordoba", "Mosque-Cathedral of Córdoba", "Mezquita-Catedral de Córdoba (Great Mosque of Córdoba)", "Sacred Temple / Cathedral", "Córdoba, Andalusia", "Spain",
    "Umayyad Caliphate to Renaissance (785–1523 CE)", "785–1523 CE", 785, "Abd al-Rahman I, Al-Hakam II, Hernán Ruiz (Cathedral)",
    "Moorish Islamic Umayyad and Renaissance Christian Architecture", "Total area: 23,400 m² (one of the largest sacred halls in the world); 856 columns; Bell tower height: 54 m",
    "Jasper, onyx, marble, and granite spolia columns, two-tier alternating red brick and white limestone horseshoe arches, gold mosaic tesserae",
    "The Mosque-Cathedral of Córdoba is an architectural monument located in Córdoba, Andalusia, Spain. Originally founded in 785 CE by Abd al-Rahman I, the founder of the Umayyad Emirate of Córdoba, on the site of a Visigothic basilica. Expanded across two centuries by his successors, it served as the grand congregational mosque of Islamic Al-Andalus. Following the Christian Reconquista of Córdoba in 1236 by King Ferdinand III, the mosque was converted into a Catholic cathedral, and in the 16th century, a Renaissance cathedral choir was built directly in the center of the mosque.",
    "The hypostyle prayer hall is a forest of stone, featuring 856 columns recycled from Roman and Visigothic ruins supporting double-tiered horseshoe arches painted in alternating red brick and white stone stripes. The Mihrab (prayer niche) is an octagonal chamber framed by a horseshoe arch sheathed in Byzantine gold glass mosaics gifted by Emperor Constantine VII of Constantinople. When Holy Roman Emperor Charles V visited the site after authorizing the Renaissance nave, he famously remarked: 'You have destroyed something that was unique to this world to build what could be built anywhere.'",
    "Inscribed as a UNESCO World Heritage Site in 1984. Regarded as one of the greatest architectural accomplishments of Moorish Islamic art.",
    "https://images.unsplash.com/photo-1599833975787-5c143f373c30?auto=format&fit=crop&q=80&w=1200",
    ["Mezquita", "Cordoba", "Spain", "Umayyad", "Moorish", "Horseshoe Arches", "UNESCO"],
    ["The prayer hall is a forest of stone supported by 856 columns of jasper, onyx, and marble", "Features iconic two-tiered horseshoe arches in alternating red brick and white limestone stripes", "The Mihrab is adorned with Byzantine gold mosaics gifted by the Emperor of Constantinople", "A Renaissance Catholic cathedral was built in the 16th century right inside the ancient mosque"],
    "Inscribed 1984 (Historic Centre of Cordoba)"),

  # 43. Seville Cathedral & Giralda, Spain
  item("seville-cathedral", "Seville Cathedral & La Giralda", "Catedral de Santa María de la Sede & La Giralda", "Sacred Temple / Cathedral", "Seville, Andalusia", "Spain",
    "Almohad Caliphate to Castilian Gothic (1172–1506 CE)", "1401–1506 CE", 1506, "Alonso Martínez, Pedro Dancart, Hernán Ruiz the Younger",
    "Gothic Cathedral Architecture with Almohad Islamic Minaret", "Total floor area: 11,520 m²; Nave height: 42 m; Giralda tower height: 104.1 m",
    "Ashlar limestone from El Puerto de Santa María, carved wood, gold leaf retablo, bronze",
    "Seville Cathedral is the fourth-largest church in the world and the largest Gothic cathedral on Earth by internal volume. Constructed between 1401 and 1506 on the site of the great 12th-century Almohad mosque after the Christian reconquest of Seville. Church elders famously resolved in 1401: 'Let us build a church so great and magnificent that those who see it finished will think we were mad!'",
    "The cathedral bell tower, La Giralda, was originally the 12th-century minaret of the mosque. Instead of stairs, the Giralda features 35 gently sloping brick ramps wide enough for the muezzin to ride a horse to the top five times a day to give the call to prayer. Inside stands the Monument to Christopher Columbus, an ornate bronze sepulcher carried by four heraldic figures representing the historical kingdoms of Spain (Castile, León, Aragon, and Navarre). The High Altar retablo, carved by Pedro Dancart, is the largest altarpiece in Christendom, featuring 45 gilded relief panels depicting the life of Christ.",
    "Inscribed as a UNESCO World Heritage Site in 1987 in conjunction with the Real Alcázar. A magnificent testament to Andalusian history.",
    "https://images.unsplash.com/photo-1599833975787-5c143f373c30?auto=format&fit=crop&q=80&w=1200",
    ["Seville Cathedral", "Giralda", "Seville", "Spain", "Gothic", "Columbus", "UNESCO"],
    ["The largest Gothic cathedral in the world by internal volume, completed in 1506", "The Giralda bell tower has 35 interior ramps so the muezzin could ride a horse to the top", "Houses the monumental bronze tomb of Christopher Columbus carried by four Spanish kings", "Features the largest carved and gilded wooden altarpiece in Christendom with 45 scenes"],
    "Inscribed 1987 (Cathedral, Alcázar and Archivo de Indias in Seville)"),

  # 44. Park Güell, Barcelona, Spain
  item("park-guell", "Park Güell", "Parc Güell", "Famous Building", "Gràcia, Barcelona, Catalonia", "Spain",
    "Modernisme / Catalan Art Nouveau (1900–1914 CE)", "1900–1914 CE", 1914, "Antoni Gaudí, commissioned by Count Eusebi Güell",
    "Catalan Modernisme Biomimetic Landscape Architecture", "Park area: 17.18 hectares; Hypostyle room: 86 fluted columns; Serpentine bench length: 110 m",
    "Trencadís recycled mosaic ceramics, broken tiles, local limestone, Portland cement",
    "Park Güell is a public park system composed of gardens and architectural elements located on Carmel Hill in Barcelona. Commissioned in 1900 by wealthy industrialist Count Eusebi Güell as an upscale garden city residential housing estate for Barcelona's bourgeoisie, inspired by the English garden city movement. Only two houses were built, one of which Gaudí purchased and lived in from 1906 until 1926. In 1926, the estate was converted into a public municipal park.",
    "The park showcases Gaudí's signature 'trencadís' technique—mosaic surfaces assembled from broken, recycled ceramic tiles, dinner plates, and bottles. The entrance is flanked by two fairy-tale gingerbread pavilions with mushroom-shaped roofs. A monumental double staircase features 'El Drac', a colorful mosaic dragon salamander that has become the mascot of Barcelona. Above sits the Hypostyle Room with 86 Doric-inspired columns supporting a vast terrace bordered by a continuous 110-meter serpentine bench curved to match the human spine.",
    "Inscribed as a UNESCO World Heritage Site in 1984 as part of the 'Works of Antoni Gaudí'. Welcomes millions of visitors annually.",
    "https://images.unsplash.com/photo-1583772654844-4b45508a8a6a?auto=format&fit=crop&q=80&w=1200",
    ["Park Guell", "Barcelona", "Spain", "Antoni Gaudi", "Modernisme", "Trencadis", "UNESCO"],
    ["Originally conceived as an exclusive 60-home luxury garden suburb for wealthy Catalans", "Pioneered Gaudí's 'trencadís' mosaic art created from shattered recycled ceramic tiles and plates", "Features 'El Drac', the colorful mosaic salamander dragon guarding the grand staircase", "The 110-meter serpentine undulating stone bench is ergonomically molded to the human body"],
    "Inscribed 1984 (Works of Antoni Gaudí)"),

  # 45. Casa Batlló, Barcelona, Spain
  item("casa-batllo", "Casa Batlló (House of Bones)", "Casa Batlló (Casa dels ossos / House of the Dragon)", "Famous Building", "Passeig de Gràcia, Eixample, Barcelona", "Spain",
    "Modernisme / Catalan Art Nouveau (1904–1906 CE)", "1904–1906 CE", 1906, "Antoni Gaudí & Josep Maria Jujol",
    "Catalan Modernisme Organic Biomimetic Architecture", "Height: 32 m; 8 storeys; Floor area: 4,300 m²; Facade width: 14.5 m",
    "Montjuïc sandstone carved into bone-like pillars, iridescent ceramic glass mosaic (trencadís), glazed roof tiles",
    "Casa Batlló is a building in the center of Barcelona, remodeled between 1904 and 1906 by Antoni Gaudí for wealthy textile industrialist Josep Batlló. Located on the Passeig de Gràcia in the 'Manzana de la Discordia' ('Block of Discord'), where Barcelona's top modernist architects competed side-by-side. Batlló originally wanted to demolish the building, but Gaudí convinced him that a radical redesign would create a work of art.",
    "Known locally as 'Casa dels ossos' ('House of Bones') because the lower balconies and sandstone columns resemble human skulls and leg bones. The facade is an undulating iridescent mosaic reminiscent of Claude Monet's water lilies. The arched roof is shaped like the scaly back of a dragon, with colorful tiles changing color as the sun moves. A small tower crowned with a four-armed cross represents the sword of Saint George (Sant Jordi, patron saint of Catalonia) plunged into the dragon's back.",
    "Inscribed as a UNESCO World Heritage Site in 2005. Awarded Best Monument in Europe by Remarkable Venue Awards.",
    "https://images.unsplash.com/photo-1583772654844-4b45508a8a6a?auto=format&fit=crop&q=80&w=1200",
    ["Casa Batllo", "Barcelona", "Spain", "Antoni Gaudi", "Dragon", "House of Bones", "UNESCO"],
    ["Nicknamed the 'House of Bones' for its skeletal stone columns and skull-shaped balconies", "The arched ceramic roof represents the scaly spine of the dragon slain by Saint George", "Gaudí designed custom ergonomic brass door handles cast directly from his handprints", "The interior light well is tiled in gradated shades of blue to distribute natural sunlight evenly"],
    "Inscribed 2005 (Works of Antoni Gaudí)"),

  # 46. Palace of the Popes, Avignon, France
  item("palais-des-papes", "Palace of the Popes (Palais des Papes)", "Palais des Papes d'Avignon", "Palace & Fortress", "Avignon, Provence", "France",
    "Avignon Papacy Medieval Gothic (1335–1352 CE)", "1335–1352 CE", 1352, "Pierre Peysson, Jean de Louvres, commissioned by Popes Benedict XII and Clement VI",
    "Southern French Medieval Fortified Gothic Palace Architecture", "Total floor area: 15,000 m² (equivalent to 4 Gothic cathedrals); 12 defensive towers; Wall thickness: up to 3 m",
    "Local Urgonian limestone ashlar masonry, oak timber ceilings, Italian Renaissance frescoes by Matteo Giovannetti",
    "The Palais des Papes in Avignon is one of the largest and most important medieval Gothic buildings in Europe. During the 14th century, conflict between the French Crown and the Roman Church led seven successive popes—from Clement V in 1309 to Gregory XI in 1377—to abandon Rome and reside in Avignon, a period known as the 'Avignon Papacy' or the 'Babylonian Captivity of the Church'.",
    "The fortress is divided into the austere Palais Vieux (Old Palace) built by Pope Benedict XII and the lavish Palais Neuf (New Palace) built by Pope Clement VI. Covering 15,000 square meters, it contains 12 fortified towers and walls up to three meters thick. The private apartments of Clement VI (the Chambre du Cerf) feature secular frescoes depicting hunting scenes, fishing, and falconry painted by Italian master Matteo Giovannetti. In 1377, Gregory XI returned the papacy to Rome, sparking the Western Schism.",
    "Inscribed as a UNESCO World Heritage Site in 1995 as part of the Historic Centre of Avignon. Host of the world-famous annual Festival d'Avignon theatre festival.",
    "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&q=80&w=1200",
    ["Palace of Popes", "Avignon", "France", "Papacy", "Gothic Fortress", "Provence", "UNESCO"],
    ["The seat of Western Christianity for nearly 70 years when seven popes ruled from Avignon", "One of the largest Gothic buildings in Europe, spanning 15,000 m² across two fortified palaces", "Walls are up to 3 meters thick, built to protect the papal court from bandit mercenaries", "Pope Clement VI's study features secular medieval hunting frescoes by Matteo Giovannetti"],
    "Inscribed 1995 (Historic Centre of Avignon)"),

  # 47. Château de Chambord, France
  item("chateau-de-chambord", "Château de Chambord", "Château de Chambord", "Palace & Fortress", "Chambord, Loir-et-Cher, Loire Valley", "France",
    "French Renaissance Golden Age (1519–1547 CE)", "1519–1547 CE", 1547, "Domenico da Cortona, influenced by Leonardo da Vinci, commissioned by King Francis I",
    "French Renaissance Architecture (Italian Classical proportions fused with French Medieval castles)", "Facade width: 156 m; Height: 56 m; 426 rooms; 83 staircases; 282 fireplaces; Park area: 5,440 hectares",
    "Soft white tuffeau limestone from the Loire Valley, slate roof tiles, oak framing",
    "The Château de Chambord is the largest and most recognizable château in the Loire Valley. Built by King Francis I starting in 1519, ostensibly as a royal hunting lodge in the game-rich Sologne forest, but fundamentally designed as a colossal statement of French Renaissance power following his victory at the Battle of Marignano. Francis I hosted his great rival, Holy Roman Emperor Charles V, here in 1539 to show off the palace.",
    "Celebrated for its double-helix central staircase (escalier à double révolution), universally attributed to Leonardo da Vinci, who was living in nearby Amboise as Francis I's guest. The staircase features two entwined spiral ramps ascending a lantern tower without ever crossing: two people can ascend and descend simultaneously, seeing each other through carved window slits without ever meeting! The roofline is a skyline of 282 ornate chimneys, cupolas, gables, and turrets that resembles the skyline of a fairy-tale city.",
    "Inscribed as a UNESCO World Heritage Site in 1981. Surrounded by the largest enclosed forest park in Europe (5,440 hectares), surrounded by a 32-kilometer wall.",
    "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&q=80&w=1200",
    ["Chambord", "Loire Valley", "France", "French Renaissance", "Francis I", "Leonardo da Vinci", "UNESCO"],
    ["The largest château in the Loire Valley, featuring 426 rooms, 83 staircases, and 282 fireplaces", "Famous for its double-helix staircase designed by Leonardo da Vinci where two people never cross paths", "The whimsical roofscape features hundreds of sculpted chimneys, towers, and lantern turrets", "Enclosed within a 5,440-hectare walled forest park, the largest game reserve in Europe"],
    "Inscribed 1981 (The Loire Valley)"),

  # 48. Chartres Cathedral, France
  item("chartres-cathedral", "Chartres Cathedral", "Cathédrale Notre-Dame de Chartres", "Sacred Temple / Cathedral", "Chartres, Eure-et-Loir", "France",
    "High Gothic Golden Age (1194–1220 CE)", "1194–1220 CE", 1220, "Anonymous master masons of Chartres",
    "French High Gothic Cathedral Architecture", "Length: 130 m; Nave width: 16.4 m; Nave vault height: 37 m; South spire: 105 m; North spire: 115 m",
    "Berchères limestone ashlar, cobalt-stained glass ('Chartres blue'), lead roofing",
    "Chartres Cathedral is widely considered the highest achievement of French High Gothic architecture. Located 80 kilometers southwest of Paris. Built to house the Sancta Camisia (Sacred Tunic), the relic worn by the Virgin Mary at the birth of Jesus Christ, gifted to the cathedral in 876 CE by Holy Roman Emperor Charles the Bald. After a catastrophic fire in 1194 destroyed the Romanesque cathedral but miraculously left the sacred relic unharmed, the entire population joined in rebuilding the cathedral in just 26 years.",
    "Chartres is celebrated for having preserved almost all of its original 13th-century stained-glass windows—over 2,600 square meters across 176 windows. World-famous for 'Bleu de Chartres' (Chartres blue), an intense cobalt-oxide stained glass formula that fills the interior with celestial blue light. The stone floor features the original 1200 CE stone labyrinth, a circular pathway 12.8 meters in diameter used by medieval pilgrims for symbolic walking meditations.",
    "Inscribed as a UNESCO World Heritage Site in 1979 as a masterpiece of Gothic art. French sculptor Auguste Rodin called it 'the Acropolis of France'.",
    "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&q=80&w=1200",
    ["Chartres", "France", "High Gothic", "Cathedral", "Chartres Blue", "Stained Glass", "UNESCO"],
    ["Preserves 176 original 13th-century stained glass windows covering 2,600 m² of brilliant light", "World-renowned for 'Bleu de Chartres', an unmatched cobalt glass hue that has never faded", "Enshrines the Sancta Camisia, believed to be the tunic worn by Mary at the birth of Christ", "Features an intact 13th-century stone floor labyrinth measuring 12.8 meters in diameter"],
    "Inscribed 1979 (Chartres Cathedral)"),

  # 49. Sainte-Chapelle, Paris, France
  item("sainte-chapelle", "Sainte-Chapelle (Holy Chapel)", "Sainte-Chapelle du Palais", "Sacred Temple / Cathedral", "Île de la Cité, Paris", "France",
    "French Rayonnant High Gothic (1242–1248 CE)", "1242–1248 CE", 1248, "Pierre de Montreuil or Thomas de Cormont, commissioned by King Louis IX (Saint Louis)",
    "French Rayonnant Gothic Chapel Architecture", "Length: 36 m; Width: 17 m; Nave height: 20.5 m; Spire height: 75 m; Stained glass area: 618 m²",
    "Champagne limestone, gold leaf, polychrome painted stone, 1,113 biblical stained glass scenes",
    "Sainte-Chapelle is a royal medieval Gothic chapel located within the Palais de la Cité on the Île de la Cité in Paris. Commissioned by King Louis IX of France (Saint Louis) in 1242 to house his collection of Passion Relics—most notably the sacred Crown of Thorns worn by Jesus Christ during the crucifixion, purchased from the Latin Emperor Baldwin II of Constantinople for 135,000 livres (more than three times the entire construction cost of the chapel itself!). Completed in an astonishingly brief six years.",
    "Designed as a two-level royal reliquary: a low, darkly painted lower chapel for palace servants, and an Upper Chapel for the royal family where the stone walls are replaced by 15-meter-tall stained-glass windows. The windows comprise 15 soaring lancets containing 1,113 distinct narrative biblical panels depicting human history from Genesis to the arrival of the Crown of Thorns in Paris. The slim stone piers are so thin that the building appears to be held up purely by stained glass and light.",
    "Inscribed as a UNESCO World Heritage Site in 1991 as part of 'Paris, Banks of the Seine'. Celebrated as the ultimate jewel box of Gothic architecture.",
    "https://images.unsplash.com/photo-1543349689-9a4d426bee8e?auto=format&fit=crop&q=80&w=1200",
    ["Sainte-Chapelle", "Paris", "France", "Saint Louis", "Rayonnant Gothic", "Crown of Thorns", "UNESCO"],
    ["Built by King Louis IX in just six years to house the sacred Crown of Thorns of Jesus Christ", "The Upper Chapel features 15-meter-tall stained glass walls containing 1,113 biblical scenes", "Stone walls are replaced almost entirely by 618 square meters of glowing 13th-century glass", "The purchase price of the Crown of Thorns was three times the cost of building the entire chapel"],
    "Inscribed 1991 (Paris, Banks of the Seine)"),

  # 50. Edinburgh Castle, Scotland, UK
  item("edinburgh-castle", "Edinburgh Castle", "Caisteal Dhùn Èideann", "Palace & Fortress", "Castle Rock, Edinburgh, Scotland", "United Kingdom",
    "Medieval to Early Modern (12th–17th Century CE; founded c. 1103 CE)", "1103–1650 CE", 1103, "King David I of Scotland & subsequent Scottish monarchs",
    "Scottish Medieval Royal Fortress & Military Stronghold Architecture", "Castle rock elevation: 130 m (430 ft); Area: 35,737 m² (8.6 acres); Fortress garrison capacity: 1,000 troops",
    "Carboniferous volcanic basalt crag (Castle Rock), local Scottish sandstone ashlar, granite",
    "Edinburgh Castle is a historic fortress dominating the skyline of Edinburgh from atop an extinct volcanic plug called Castle Rock. Archaeological excavations demonstrate human habitation on the rock since the Iron Age (2nd century CE). Established as a Scottish royal castle by King David I in the 12th century, serving as a royal residence until the Union of the Crowns in 1603. It has endured 26 sieges throughout its history, making it 'the most besieged place in Great Britain'.",
    "Houses St. Margaret's Chapel, built around 1130 by King David I in honor of his mother—the oldest surviving building in Edinburgh. Contains the Honours of Scotland (the Scottish Crown Jewels: Crown, Sceptre, and Sword of State, made in 1540), the oldest crown jewels in the British Isles, alongside the Stone of Destiny (Stone of Scone), the ancient coronation seat of Scottish and British monarchs. Every day at precisely 1:00 PM (except Sundays), the One O'Clock Gun is fired from the Mill's Mount Battery.",
    "Inscribed as a UNESCO World Heritage Site in 1995 as part of the Old and New Towns of Edinburgh. The definitive national symbol of Scotland.",
    "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&q=80&w=1200",
    ["Edinburgh Castle", "Scotland", "UK", "Castle Rock", "Honours of Scotland", "Stone of Destiny", "UNESCO"],
    ["Perched atop an extinct volcanic plug that has been occupied since the Bronze Age", "Has survived 26 military sieges, making it the most besieged fortress in Great Britain", "Enshrines the Honours of Scotland and the Stone of Scone, used in royal coronations", "The One O'Clock Gun has been fired from its battery daily since 1861 to set maritime clocks"],
    "Inscribed 1995 (Old and New Towns of Edinburgh)"),

  # 51. Roman Baths, Bath, UK
  item("roman-baths-bath", "The Roman Baths", "Aquae Sulis (Waters of Sulis)", "Ancient Wonder", "Bath, Somerset", "United Kingdom",
    "Roman Britain (c. 60–70 CE; 19th-century colonnade 1897 CE)", "c. 60–70 CE", 70, "Roman provincial architects under Emperor Vespasian",
    "Roman Thermal Bath & Sanctuary Architecture", "Great Bath dimensions: 24 × 12 m; Depth: 1.6 m; Thermal spring daily flow: 1.17 million liters at 46°C (115°F)",
    "Bath oolitic limestone, lead lining sheets from Mendip Hills, Roman ceramic hypocaust box flue tiles",
    "The Roman Baths complex in Bath, Somerset, is one of the best-preserved classical Roman thermal spas in the world. Constructed around 60–70 CE around natural geothermal mineral springs sacred to the Celtic goddess Sulis, whom the Romans identified with Minerva (worshipped as Sulis Minerva). The town that grew around the baths was known as Aquae Sulis ('Waters of Sulis'). The site served as a religious sanctuary, healing hospital, and social hub for Roman Britain for over 300 years.",
    "The Great Bath is lined with 45 colossal lead sheets melted down from lead mined in the nearby Mendip Hills, filled with steaming geothermal mineral water bubbling from the ground at a constant 46°C (115°F). Archaeological excavations beneath the pump room revealed the sacred spring where Romans threw over 130 lead and pewter 'curse tablets' (defixiones) inscribed in Latin calling on Sulis Minerva to punish thieves who stole their cloaks or money. The Victorian terrace statues above depict Roman governors and emperors including Julius Caesar and Claudius.",
    "Inscribed as a UNESCO World Heritage Site in 1987 as part of the City of Bath. Attracts over one million visitors annually.",
    "https://images.unsplash.com/photo-1529655683826-aba9b3e77383?auto=format&fit=crop&q=80&w=1200",
    ["Roman Baths", "Bath", "UK", "Aquae Sulis", "Minerva", "Geothermal", "UNESCO"],
    ["Built around natural thermal springs flowing with 1.17 million liters of 46°C hot water daily", "The pool basin is lined with original 2,000-year-old lead sheets from local Mendip mines", "Over 130 ancient Roman lead 'curse tablets' requesting vengeance were recovered from the spring", "Dedicated to Sulis Minerva, uniting local Celtic and classical Roman religious worship"],
    "Inscribed 1987 (City of Bath)"),

  # 52. Westminster Abbey, London, UK
  item("westminster-abbey", "Westminster Abbey", "Collegiate Church of Saint Peter at Westminster", "Sacred Temple / Cathedral", "City of Westminster, London", "United Kingdom",
    "Anglo-Saxon to Gothic (1065 CE consecration; rebuilt 1245–1519 CE)", "1245–1519 CE", 1245, "Henry of Reyns, John of Gloucester, Robert Janyns Jr., commissioned by King Henry III",
    "English High Gothic and Perpendicular Gothic Abbey Architecture", "Length: 161.5 m; Nave height: 31 m (highest Gothic nave in UK); Henry VII Lady Chapel width: 21 m",
    "Reigate freestone, Caen limestone from Normandy, Purbeck marble polished shafts, stained glass",
    "Westminster Abbey is a royal collegiate church in the City of Westminster, London. Founded by King Edward the Confessor around 1042 and consecrated in December 1065. King Henry III tore down most of the Norman church in 1245 to rebuild it in French Gothic style as a shrine for Edward the Confessor. It has been the coronation site for every English and British monarch since William the Conqueror in 1066 (with 40 coronations held here).",
    "The Henry VII Lady Chapel (consecrated 1519) features a breathtaking fan-vaulted stone ceiling with pendant bosses described by John Leland as 'the wonder of the world'. The abbey encloses Poets' Corner, where Geoffrey Chaucer, William Shakespeare, Charles Dickens, and Jane Austen are buried or memorialized, alongside scientists Sir Isaac Newton and Stephen Hawking. In the center stands the Coronation Chair (King Edward's Chair), crafted in 1296 to encase the Stone of Scone, which has crowned every monarch for 700 years.",
    "Inscribed as a UNESCO World Heritage Site in 1987. Site of 16 royal weddings and state funerals, including Queen Elizabeth II in 2022.",
    "https://images.unsplash.com/photo-1529655683826-aba9b3e77383?auto=format&fit=crop&q=80&w=1200",
    ["Westminster Abbey", "London", "UK", "Coronation", "Poets Corner", "Isaac Newton", "UNESCO"],
    ["The coronation site of 40 British monarchs since William the Conqueror in December 1066", "Features the magnificent 1519 fan-vaulted ceiling of Henry VII's Lady Chapel", "Houses Poets' Corner and the tombs of global icons Isaac Newton, Charles Darwin, and Stephen Hawking", "Contains the 700-year-old Coronation Chair made in 1296 by order of King Edward I"],
    "Inscribed 1987 (Westminster Palace and Abbey)"),

  # 53. Giant's Causeway, Northern Ireland, UK
  item("giants-causeway", "Giant's Causeway", "Clochán an Aifir / Clochán na bhFomhórach", "Ancient Wonder", "Bushmills, County Antrim", "United Kingdom",
    "Paleogene Geological Volcanic Period (50–60 Million Years Ago)", "50–60 Million BCE", -50000000, "Nature (Volcanic columnar basalt cracking) / Irish myth: Giant Finn MacCool",
    "Columnar Basalt Polygonal Prismatic Geological Architecture", "Area: 70 hectares; Over 40,000 interlocking basalt columns; Max column height: 12 m (39 ft)",
    "Tholeiitic basalt rock, volcanic lava flows, columnar joint cooling fractures",
    "The Giant's Causeway is an area of approximately 40,000 interlocking basalt columns along the dramatic coast of County Antrim, Northern Ireland. Formed 50 to 60 million years ago during the Paleogene period, when intense subterranean volcanic activity forced molten basalt up through chalk beds. As the lava lake cooled slowly and contracted uniformly, horizontal contraction forces caused the rock to fracture in regular geometric patterns, creating thousands of vertical hexagonal, pentagonal, and octagonal stepping-stone pillars.",
    "According to Irish mythology, the causeway was built by the mythical giant Finn MacCool (Fionn mac Cumhaill) so he could walk across the North Channel to Scotland to fight his Scottish rival giant Benandonner. Features unique formations like the 'Giant's Boot', the 'Wishing Chair', the 'Organ' (a cliff of tall, pipe-like columns), and the 'Chimney Stacks'. Across the sea in Scotland, the exact same volcanic formation appears at Fingal's Cave on the Isle of Staffa.",
    "Inscribed as Northern Ireland's only UNESCO World Heritage Site in 1986. Celebrated as one of the natural geological wonders of the world.",
    "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&q=80&w=1200",
    ["Giants Causeway", "Northern Ireland", "UK", "Basalt", "Finn MacCool", "Geology", "UNESCO"],
    ["Composed of 40,000 geometric hexagonal basalt columns formed by cooling volcanic lava", "Irish legend claims the giant Finn MacCool built the causeway as a path to fight a Scottish rival", "Part of the same ancient lava flow that created Fingal's Cave across the sea in Scotland", "Northern Ireland's premier natural UNESCO World Heritage Site inscribed in 1986"],
    "Inscribed 1986 (Giant's Causeway and Causeway Coast)"),

  # 54. Meteora Monasteries, Greece
  item("meteora-monasteries", "Meteora Rock-Pinnacle Monasteries", "Μετέωρα (Meteora - Suspended in the Air)", "Sacred Temple / Cathedral", "Kalabaka, Thessaly", "Greece",
    "Late Byzantine to Post-Byzantine (14th–16th Century CE; hermit roots 11th Century)", "1344–1542 CE", 1344, "Saint Athanasios the Meteorite, Saint Joasaph, Nektarios and Theophanes",
    "Byzantine Monastic Cliff-Top Fortress Architecture", "Pinnacle heights: 300–400 m (1,000–1,300 ft) above Peneas valley; 24 original monasteries, 6 active today",
    "Natural deltaic sandstone and conglomerate monolithic stone pillars, brick, terracotta tiles, timber windlasses",
    "Meteora, meaning 'suspended in the air' or 'in the heavens above' in Greek, is a rock formation in central Greece hosting one of the most dramatically situated complexes of Eastern Orthodox monasteries in the world. In the 11th century, hermit monks lived in cliff caves. In 1344, Saint Athanasios the Meteorite established the Monastery of Great Meteoron atop a sheer 613-meter rock peak to escape Turkish raiders and bandits. During the Ottoman expansion, monks built 24 monasteries atop isolated sandstone pinnacles.",
    "Until the 1920s, the monasteries were accessible only by climbing long ladders tied together or by being hauled up in a cargo net suspended from a hand-cranked wooden windlass over a 400-meter drop. When visitors asked how often the hauling ropes were replaced, the monks famously answered: 'Only when the Lord lets them break!' Six monasteries remain active today, preserving post-Byzantine frescoes, rare manuscripts, and icon screens.",
    "Inscribed as a UNESCO World Heritage Site in 1988 under dual cultural and natural criteria. Featured in the James Bond film 'For Your Eyes Only'.",
    "https://images.unsplash.com/photo-1555993539-1732b0258235?auto=format&fit=crop&q=80&w=1200",
    ["Meteora", "Greece", "Thessaly", "Monasteries", "Byzantine", "Cliff Top", "UNESCO"],
    ["Monasteries sit atop sheer 400-meter sandstone rock pillars rising above the plain of Thessaly", "Until the 1920s, monks and visitors were hauled up in rope nets over dizzying vertical drops", "Founded by Saint Athanasios in the 14th century to escape Ottoman raiders", "Six historic Greek Orthodox monasteries remain fully active communities today"],
    "Inscribed 1988 (Meteora)"),

  # 55. Delphi Sanctuary & Theater, Greece
  item("delphi-sanctuary", "Sanctuary of Delphi & Temple of Apollo", "Δελφοί (Delphoi - Navel of the Earth)", "Archaeological City", "Mount Parnassus, Phocis", "Greece",
    "Archaic to Classical Greece (6th–4th Century BCE; founded Mycenaean era)", "c. 510–330 BCE", -510, "Spintharos, Xenodoros, Agathon (Architects)",
    "Classical Greek Doric Sanctuary, Theater & Tholos Architecture", "Sanctuary elevation: 570 m; Theater capacity: 5,000 spectators; Tholos circular diameter: 13.5 m",
    "Parnassian limestone, poros stone, Pentelic marble, bronze victory offerings",
    "Delphi was the sacred religious sanctuary of ancient Greece, situated on the southwestern slopes of Mount Parnassus overlooking the Gulf of Corinth. Revered throughout the Mediterranean as the 'Omphalos' ('Navel of the Earth')—the geographic and spiritual center of the world, determined when Zeus released two eagles from opposite ends of the earth and their paths crossed over Delphi. For over a millennium, kings, generals, and citizens consulted the Pythia (the Oracle of Delphi) before waging war or founding colonies.",
    "The Pythia, an elder peasant woman chosen for purity, sat on a bronze tripod over a chasm in the inner adyton of the Temple of Apollo, inhaling natural hydrocarbon vapors (ethylene) emerging from geological fault lines, uttering prophecies interpreted into hexameter verse by priests. The sanctuary contains the Treasury of the Athenians, the ancient Theater seating 5,000 with panoramic mountain views, and the famous circular Tholos at the Sanctuary of Athena Pronaia. Site of the quadrennial Pythian Games, a precursor to the Olympics celebrating music and athletics.",
    "Inscribed as a UNESCO World Heritage Site in 1987. The spiritual beacon of the ancient classical world.",
    "https://images.unsplash.com/photo-1555993539-1732b0258235?auto=format&fit=crop&q=80&w=1200",
    ["Delphi", "Greece", "Apollo", "Oracle", "Pythia", "Parnassus", "UNESCO"],
    ["Revered in ancient Greece as the 'Omphalos'—the sacred geographic Navel of the Earth", "The Pythia (Oracle) gave prophecies over a fissure emitting sweet-smelling geological gases", "Kings and statesmen traveled from across the Mediterranean before declaring war or laws", "Features a mountain theater with acoustic views across thousands of olive groves"],
    "Inscribed 1987 (Archaeological Site of Delphi)"),

  # 56. Knossos Palace, Crete, Greece
  item("knossos-palace", "Palace of Knossos", "Κνωσός (Knōsós - Minoan Capital)", "Ancient Wonder", "Heraklion, Crete", "Greece",
    "Minoan Bronze Age Civilization (c. 1950–1375 BCE)", "c. 1950–1450 BCE", -1950, "Minoan builders under mythical King Minos (Excavated by Sir Arthur Evans)",
    "Minoan Bronze Age Multistory Courtyard Architecture", "Palace area: 20,000 m² (5 acres); 1,300 rooms; 4 stories; Central court: 50 × 25 m",
    "Gypsum, Cretan limestone, timber beams (for seismic elasticity), terracotta pipes, wet fresco plaster",
    "The Palace of Knossos was the ceremonial and political capital of the Minoan civilization on Crete, Europe's first advanced Bronze Age society. Associated in Greek mythology with King Minos, the architect Daedalus, the cunning labyrinth, and the fearsome half-man, half-bull Minotaur fed Athenian youths until slain by Theseus with the help of Ariadne's golden thread. Excavated and controversially restored between 1900 and 1935 by British archaeologist Sir Arthur Evans.",
    "The palace was an engineering marvel: a four-story labyrinth of 1,300 interconnected halls, royal throne rooms, workshops, and granaries arranged around a central open courtyard. Minoan engineers installed advanced plumbing: terracotta water pipes, rainwater drainage channels, and the world's earliest known flushing toilets. Famous for vibrant frescoes including the 'Bull-Leaping' (Toreador) fresco, the 'Prince of the Lilies', and playful dolphins. Its downward-tapering red wooden columns were engineered upside-down to withstand regional earthquakes.",
    "The foundational cradle of European civilization and Mediterranean Bronze Age seafaring culture.",
    "https://images.unsplash.com/photo-1555993539-1732b0258235?auto=format&fit=crop&q=80&w=1200",
    ["Knossos", "Crete", "Greece", "Minoan", "Minotaur", "Labyrinth", "Bronze Age"],
    ["Europe's oldest city and the capital of the Minoan civilization, flourishing 3,500 years ago", "Legendary home of the mythical Labyrinth, King Minos, Daedalus, and the Minotaur", "Engineered with four storeys, seismic timber framing, and the world's first flush toilets", "Features famous frescoes of acrobats performing dangerous gymnastic leaps over charging bulls"],
    "Prehistoric European Monument"),

  # 57. Pont du Gard, Nîmes, France
  item("pont-du-gard", "Pont du Gard Roman Aqueduct", "Pont du Gard", "Bridge & Engineering", "Vers-Pont-du-Gard, Gard, Occitanie", "France",
    "Imperial Roman Augustan Era (c. 40–60 CE)", "c. 40–60 CE", 50, "Roman engineers under Marcus Vipsanius Agrippa & Emperor Claudius",
    "Classical Imperial Roman Three-Tier Aqueduct Bridge Architecture", "Height: 48.8 m (160 ft); Length: 275 m; 3 tiers of arches (6 lower, 11 middle, 35 upper)",
    "Shelly limestone ('Pierre de Vers') ashlar blocks weighing up to 6 tonnes, dry-stone construction without mortar",
    "The Pont du Gard is an ancient Roman aqueduct bridge that crosses the Gardon River in southern France near Nîmes. Built in the 1st century CE as part of a 50-kilometer aqueduct system to carry spring water from Uzès to the Roman colony of Nemausus (Nîmes). The entire 50-kilometer aqueduct dropped just 12.6 meters in elevation along its course—an average slope of only 25 centimeters per kilometer (1 in 4,000)—requiring mathematical surveying of extraordinary precision.",
    "The bridge is built on three tiers of arches, standing 48.8 meters high—the highest of all elevated Roman aqueducts. Constructed from 50,400 tonnes of soft yellow limestone quarried right on the riverbank, cut with millimeter accuracy and assembled completely dry without using any mortar, held together purely by precision friction and gravitational pressure. The aqueduct channel carried approximately 40,000 cubic meters (8.8 million gallons) of fresh water to Nîmes every day for baths, public fountains, and patrician gardens.",
    "Inscribed as a UNESCO World Heritage Site in 1985. A testament to classical Roman hydraulic and civil engineering.",
    "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&q=80&w=1200",
    ["Pont du Gard", "France", "Roman", "Aqueduct", "Nimes", "Engineering", "UNESCO"],
    ["The highest elevated Roman aqueduct bridge in the world, standing 48.8 meters tall", "Built from 50,400 tonnes of limestone blocks assembled entirely without mortar or cement", "Part of a 50-km water system dropping only 12.6 meters in height, carrying 40,000 m³ daily", "Preserved for 2,000 years because local lords maintained it as a toll bridge"],
    "Inscribed 1985 (Pont du Gard)"),

  # 58. Reichstag Building & Glass Dome, Berlin, Germany
  item("reichstag-berlin", "Reichstag Building & Glass Dome", "Reichstagsgebäude (Bundestag)", "Famous Building", "Platz der Republik, Mitte, Berlin", "Germany",
    "Wilhelmine Imperial to Modern Democratic Rebirth (1894 CE; Foster Dome 1999 CE)", "1894–1999 CE", 1999, "Paul Wallot (1894), Norman Foster (Glass Dome reconstruction 1999)",
    "Neo-Renaissance and High-Tech Sustainable Glass Architecture", "Length: 137 m; Width: 97 m; Height with dome: 54 m; Glass dome weight: 1,200 tonnes; Diameter: 38 m",
    "Silesian sandstone, high-transparency laminated glass, steel trusses, mirrored sun-tracking cone (360 mirrors)",
    "The Reichstag is the historic seat of the German federal parliament (the Bundestag) in Berlin. Completed in 1894 under the German Empire. On February 27, 1933, a mysterious arson fire gutted the building, an event seized upon by Adolf Hitler to suspend civil liberties and establish Nazi dictatorship. On May 2, 1945, the Red Army raised the Soviet victory banner over its smoking roof, marking the fall of Berlin. Following German reunification, parliament voted to return the capital from Bonn to Berlin, commissioning British architect Norman Foster to redesign the Reichstag.",
    "Foster placed a transparent glass dome atop the historic stone shell, symbolizing democratic transparency: citizens walk along a spiraling internal ramp directly above the heads of elected parliamentarians debating in the chamber below. At the center of the dome hangs an inverted cone lined with 360 mirrored facets that channel natural daylight deep down into the plenary chamber, eliminating artificial daytime lighting. A solar-tracking computerized sun shield moves dynamically with the sun to prevent glare and heat build-up.",
    "One of Berlin's most visited attractions and a global beacon of post-Cold War democratic renewal.",
    "https://images.unsplash.com/photo-1599940824399-b87987ceb72a?auto=format&fit=crop&q=80&w=1200",
    ["Reichstag", "Berlin", "Germany", "Bundestag", "Norman Foster", "Glass Dome", "Democracy"],
    ["The 1933 Reichstag fire was exploited by the Nazi regime to abolish German civil liberties", "Norman Foster's 1999 glass dome lets visitors walk directly above elected politicians", "A central cone with 360 mirrors reflects natural daylight down into the debating chamber", "Preserves historic charcoal graffiti left by victorious Soviet Red Army soldiers in May 1945"],
    "Seat of the German Parliament"),

  # 59. Atomium, Brussels, Belgium
  item("atomium-brussels", "The Atomium", "L'Atomium", "Monument & Tower", "Heysel Plateau, Brussels", "Belgium",
    "Postwar Atomic Age Modernism (1958 CE)", "1958 CE", 1958, "André Waterkeyn (Engineers: André & Jean Polak)",
    "Atomic Age Reticular Steel Shell Architecture", "Height: 102 m (335 ft); Sphere diameter: 18 m (59 ft); 9 connected spheres; Total weight: 2,500 tonnes",
    "High-tensile steel tubes, 9 aluminum-clad spheres (reclad in stainless steel in 2006)",
    "The Atomium is a landmark modernist building in Brussels, Belgium, originally constructed as the flagship pavilion and centerpiece for the 1958 Brussels World's Fair (Expo 58). Conceived by Belgian engineer André Waterkeyn. Represents an elementary unit cell of an iron crystal magnified 165 billion times, symbolizing the peaceful use of nuclear energy, atomic physics, and postwar technological optimism.",
    "The structure consists of nine 18-meter-diameter spheres connected by 20 steel tubes, each 3.3 meters in diameter, containing escalators and stairs. The central vertical column contains an elevator that was the fastest in Europe when built, reaching the top sphere in 23 seconds at a speed of 5 meters per second. Six of the nine spheres are accessible to the public, featuring panoramic restaurants, light shows, and museum exhibitions. The exterior was renovated in 2006 with shimmering stainless steel plates.",
    "The definitive national symbol of Belgium and one of the most distinctive mid-century modernist architectural sculptures on Earth.",
    "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&q=80&w=1200",
    ["Atomium", "Brussels", "Belgium", "Expo 58", "Atomic Age", "Modernism", "Icon"],
    ["Represents an iron crystal unit cell magnified an astounding 165 billion times", "Constructed as the flagship centerpiece of the 1958 Brussels World's Fair (Expo 58)", "Consists of nine connected steel spheres, each measuring 18 meters in diameter", "Visitors travel between spheres using interior escalator tubes and Europe's fastest 1958 elevator"],
    "National Monument of Belgium"),

  # 60. Grand Place of Brussels, Belgium
  item("grand-place-brussels", "Grand Place of Brussels (Grote Markt)", "La Grand-Place / Grote Markt", "Palace & Fortress", "City of Brussels", "Belgium",
    "Brabantine Gothic to Baroque Guild Era (1401–1699 CE)", "1401–1699 CE", 1455, "Jacob van Thienen, Jan van Ruysbroeck, Guillaume de Bruyn",
    "Brabantine Gothic and Flemish Baroque Guildhouse Architecture", "Square dimensions: 110 × 68 m (7,480 m²); Town Hall spire height: 96 m (315 ft); 39 guildhouses",
    "Belgian blue limestone, Balegem sandstone, gilded wood and stone carvings, slate roofs",
    "The Grand Place is the central historic square of Brussels, Belgium. Celebrated as one of the most harmonious architectural squares in the world. Originally a 12th-century muddy marketplace on the banks of the Senne river. Dominated by the monumental Town Hall (Hôtel de Ville), begun in 1401 in flamboyant Brabantine Gothic with an asymmetric 96-meter belfry crowned by a gilded statue of Saint Michael slaying the devil.",
    "In August 1695, during the Nine Years' War, French artillery under the command of Marshal de Villeroy bombarded Brussels for 36 hours, destroying almost all the wooden buildings on the Grand Place except for the Town Hall stone shell. In an extraordinary display of civic resilience, the wealthy merchant trade guilds (brewers, bakers, haberdashers, carpenters) rebuilt the entire square within four years in opulent Flemish Baroque style, decorating facades with gold leaf, allegorical statues, and ornate gables. Every two years in August, the square is covered in a 70 × 24 meter 'Flower Carpet' composed of one million fresh begonias.",
    "Inscribed as a UNESCO World Heritage Site in 1998, praised by French author Victor Hugo as 'the most beautiful square in the world'.",
    "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&q=80&w=1200",
    ["Grand Place", "Brussels", "Belgium", "Grote Markt", "Flemish Baroque", "Flower Carpet", "UNESCO"],
    ["Rebuilt in opulent Flemish Baroque in just four years after French bombardment in 1695", "The 96-meter Town Hall tower is crowned by a gilded statue of Archangel Michael slaying Satan", "Lined with 39 historic guildhouses decorated in gleaming gold leaf and maritime motifs", "Every two years, the cobbles are covered with a carpet of one million fresh begonia flowers"],
    "Inscribed 1998 (La Grand-Place, Brussels)")
]

all_europe = europe_data + more_europe

with open("src/data/monuments/europeanMonuments.ts", "w", encoding="utf-8") as f:
    f.write("import { WorldMonumentOrArtifact } from '../../types';\n\n")
    f.write("export const EUROPEAN_MONUMENTS: WorldMonumentOrArtifact[] = ")
    f.write(json.dumps(all_europe, ensure_ascii=False, indent=2))
    f.write(";\n")

print(f"Successfully generated all {len(all_europe)} European monuments in src/data/monuments/europeanMonuments.ts!")
