#!/usr/bin/env python3
import json
import os

os.makedirs("src/data/monuments", exist_ok=True)

def m(id, name, native, cat, loc, country, region, era, yr_str, yr_num, arch, style, dim, mat, hist, marv, mod, img, tags, facts, unesco="World Heritage Landmark"):
    return {
        "id": id,
        "name": name,
        "nativeOrAlternateName": native,
        "category": cat,
        "location": loc,
        "country": country,
        "region": region,
        "era": era,
        "yearBuilt": yr_str,
        "numericYear": yr_num,
        "architectOrCreator": arch,
        "architecturalStyle": style,
        "dimensionsAndHeight": dim,
        "materialsUsed": mat,
        "historyAndBackground": hist,
        "architecturalMarvels": marv,
        "modernStatusAndSignificance": mod,
        "imageUrl": img,
        "fallbackImageUrl": "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&q=80&w=1200",
        "tags": tags,
        "keyFacts": facts,
        "unescoStatus": unesco
    }

monuments = [
  m("taj-mahal", "Taj Mahal", "क्राउन ऑफ़ द पैलेस", "Famous Building", "Agra, Uttar Pradesh", "India", "Asia",
    "Mughal Empire (1632–1653 CE)", "1632–1653 CE", 1648, "Ustad Ahmad Lahori & Emperor Shah Jahan",
    "Mughal Architecture (Persian, Islamic, Indian fusion)", "Height: 73 m (240 ft); Dome diameter: 17.7 m; Complex area: 42 acres",
    "Translucent Makrana white marble, red sandstone, 28 types of precious gemstones",
    "The Taj Mahal is widely acknowledged as the crown jewel of Indo-Islamic art in India. It was commissioned in 1631 by Emperor Shah Jahan to house the tomb of his beloved favorite wife, Mumtaz Mahal, who died giving birth to their fourteenth child. Construction enlisted over 20,000 artisans from India, Persia, the Ottoman Empire, and Europe, alongside 1,000 elephants used to haul marble from Rajasthan. The central mausoleum was completed in 1648, while surrounding minarets and mosque were completed by 1653.",
    "Celebrated for its absolute bilateral symmetry along a central axis, with the sole exception being Shah Jahan’s tomb itself, which was added later beside Mumtaz Mahal. The four 40-meter corner minarets are tilted outward by approximately 3 degrees so that during an earthquake, they would fall outward away from the delicate marble dome. The translucent Makrana white marble shifts hue across the day—rosy pink at dawn, milky white at noon, and shimmering silver under the moon.",
    "Inscribed as a UNESCO World Heritage Site in 1983 and voted one of the New 7 Wonders of the World in 2007. Protected by the Taj Trapezium Zone restricting industrial emissions.",
    "https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&q=80&w=1200",
    ["Taj Mahal", "India", "Mughal", "UNESCO", "Wonder of the World", "Agra", "Marble"],
    ["Built by Emperor Shah Jahan in memory of his favorite empress Mumtaz Mahal", "Minarets lean outward at a 3-degree angle as an earthquake defense mechanism", "Took 22 years and over 20,000 master artisans to construct", "Shifts color throughout the day from pink at sunrise to golden under moonlight"],
    "Inscribed 1983 (Criterion i)"),

  m("great-wall-of-china", "Great Wall of China", "万里长城 (Wànlǐ Chángchéng)", "Ancient Wonder", "Northern Frontier across 15 provinces", "China", "Asia",
    "Qin to Ming Dynasties (7th c. BCE – 1644 CE)", "c. 221 BCE – 1644 CE", -221, "First unified under Emperor Qin Shi Huang; fortified by Ming emperors",
    "Ancient Chinese Military Defensive Rampart Engineering", "Total length: 21,196 km (13,171 miles); Height: 6–8 m; Width: 5–8 m",
    "Rammed earth, dressed granite blocks, kiln-fired gray bricks, sticky rice mortar",
    "The Great Wall is the longest defensive fortification in human history. Earliest sections were built by rival feudal states during the Warring States period. In 221 BCE, Qin Shi Huang unified China and ordered existing walls joined along the northern ridges to repel raids by Xiongnu nomadic confederations. Ming Dynasty builders fortified the wall with stone and brick towers after the Battle of Tumu.",
    "Ming builders mixed sticky rice soup with slaked lime, creating a mortar with amylopectin that resisted weathering for centuries. Over 25,000 watchtowers and beacon towers transmitted emergency tactical warnings thousands of miles using coded smoke by day and fire torches by night.",
    "Designated a UNESCO World Heritage Site in 1987 and voted one of the New 7 Wonders of the World in 2007. Serves as the ultimate symbol of Chinese civilizational perseverance.",
    "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?auto=format&fit=crop&q=80&w=1200",
    ["Great Wall", "China", "UNESCO", "Fortress", "Ming Dynasty", "Wonder of the World"],
    ["Total recognized length exceeds 21,196 kilometers across northern China", "Mortar used in Ming sections contained sticky rice starch for phenomenal durability", "Beacon towers used coded smoke signals by day and fire torches by night", "Contrary to myth, it is not visible from low Earth orbit without camera zoom lenses"],
    "Inscribed 1987 (Criteria i, ii, iii, iv, vi)"),

  m("angkor-wat", "Angkor Wat", "អង្គរវត្ត (City Temple)", "Sacred Temple / Cathedral", "Siem Reap Province", "Cambodia", "Asia",
    "Khmer Empire (12th Century CE)", "c. 1113–1150 CE", 1130, "King Suryavarman II",
    "Classical Khmer Architecture (Temple-Mountain & Concentric Galleries)", "Central tower height: 65 m (213 ft); Outer moat perimeter: 5 km; Area: 402 acres",
    "Over 5 million tonnes of quarried sandstone blocks, volcanic laterite foundation",
    "Angkor Wat is the largest religious monument in the world. Built during the peak of the Khmer Empire under King Suryavarman II in the early 12th century, it was dedicated to the Hindu deity Vishnu as the royal state temple and funerary mausoleum. By the late 12th century, under King Jayavarman VII, the temple gradually transformed into an active Theravada Buddhist sanctuary.",
    "A terrestrial representation of Hindu cosmology: five central lotus-bud towers represent Mount Meru, while the 190-meter-wide moat symbolizes the cosmic ocean. Uniquely faces westward toward the setting sun. Gallery walls feature over 1,200 square meters of bas-reliefs, including the Churning of the Ocean of Milk.",
    "Core of the UNESCO Angkor World Heritage Site (1992). Prominently depicted on Cambodia's national flag.",
    "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=1200",
    ["Angkor Wat", "Cambodia", "Khmer", "Hindu", "Buddhist", "UNESCO", "Temple Mountain"],
    ["Largest religious complex in the world, covering over 400 acres", "Faces westward toward the setting sun, unique among major classical Khmer temples", "The sun rises precisely over the central tower on the equinoxes", "Decorated with over 3,000 uniquely individual celestial Apsara carvings"],
    "Inscribed 1992 (Criteria i, ii, iii, iv)"),

  m("burj-khalifa", "Burj Khalifa", "برج خليفة", "Monument & Tower", "Downtown Dubai", "United Arab Emirates", "Middle East",
    "Contemporary Global Engineering (2004–2010 CE)", "2004–2010 CE", 2010, "Adrian Smith & William F. Baker (Skidmore, Owings & Merrill)",
    "Neo-futurist High-Tech Skyscraper (Y-shaped Buttressed Core)", "Height: 828 m (2,717 ft); 163 floors; Floor area: 309,473 m²",
    "Reinforced concrete core, structural steel spire, 103,000 m² of reflective glass and aluminum panels",
    "The Burj Khalifa is the tallest building and tallest freestanding structure in human history. Initiated by Dubai's ruler Sheikh Mohammed bin Rashid Al Maktoum to shift Dubai's economic center toward international tourism and commerce. Construction began in 2004 with over 12,000 workers on site daily. It opened on January 4, 2010, named in honor of UAE President Sheikh Khalifa bin Zayed Al Nahyan.",
    "Features a revolutionary buttressed core design—a hexagonal central concrete core braced by three wings in a Y-shape inspired by the desert flower Hymenocallis. This aerodynamic profile deflects high-altitude desert wind vortices as the tower steps back in 26 helical terraces. Set the world record for vertical concrete pumping at 606 meters.",
    "The defining icon of 21st-century architectural engineering, holding world records for tallest structure, highest occupied floor, and elevator with the longest travel distance.",
    "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&q=80&w=1200",
    ["Burj Khalifa", "Dubai", "UAE", "Skyscraper", "Tallest Building", "Architecture"],
    ["Tallest structure ever built by human hands at 828 meters (2,717 feet)", "Exterior is wrapped in over 26,000 hand-cut reflective glass panels", "Takes three to four months for professional abseilers to clean the entire facade", "The temperature at the tip of the spire is about 6°C cooler than at ground level"],
    "Modern Architectural Wonder"),

  m("petra-treasury", "Al-Khazneh (The Treasury) & Petra", "الخزنة", "Ancient Wonder", "Ma'an Governorate", "Jordan", "Middle East",
    "Nabataean Kingdom (1st c. BCE – 1st c. CE)", "c. 9 BCE – 40 CE", 9, "Nabataean master stonemasons under King Aretas IV",
    "Hellenistic-Nabataean Rock-Cut Architecture", "Facade height: 39.5 m (130 ft); Width: 25 m; City area: 264 km²",
    "Living rose-red and ochre iron-banded sandstone cliff faces",
    "Al-Khazneh is the most famous facade in the ancient rock-cut city of Petra, capital of the Nabataean Arab kingdom. Dominating the crossroads of ancient silk and incense routes linking Arabia, Egypt, and Rome. Carved into the cliffs of Jabal al-Madhbah under King Aretas IV. Bedouins called it 'The Treasury' believing an Egyptian pharaoh hid gold in the upper stone urn, though it was in fact an elaborate royal tomb.",
    "Carved directly into the cliff-face from the top down without scaffolding; masons cut footholds, chiseled upper pediments, and worked downward. The city thrived in an arid desert thanks to a sophisticated network of terracotta pipes, cisterns, and dams that distributed 45 million liters of spring water daily.",
    "UNESCO World Heritage Site (1985) and one of the New 7 Wonders of the World (2007). Jordan’s most iconic cultural destination.",
    "https://images.unsplash.com/photo-1579606032834-deffd1b4260f?auto=format&fit=crop&q=80&w=1200",
    ["Petra", "Jordan", "Nabataean", "Al-Khazneh", "Treasury", "UNESCO", "Wonder of the World"],
    ["Carved directly out of sandstone mountain cliffs from the top downward", "The decorative top urn bears bullet marks from treasure hunters seeking gold", "Reached through the Siq, a dramatic 1.2 km narrow canyon between 80-meter cliffs", "Supported a thriving desert population of 30,000 using advanced water engineering"],
    "Inscribed 1985 (Criteria i, iii, iv)"),

  m("forbidden-city", "The Forbidden City", "故宫 (Gùgōng)", "Palace & Fortress", "Beijing", "China", "Asia",
    "Ming & Qing Dynasties (1406–1912 CE)", "1406–1420 CE", 1420, "Yongle Emperor (Zhu Di); Master Architect Kuai Xiang",
    "Traditional Imperial Chinese Palace Architecture (Feng Shui, Dougang)", "Complex area: 72 hectares (178 acres); 980 surviving buildings; 8,886 room bays; Wall height: 10 m",
    "Phoebe zhennan logs, 'golden bricks', yellow glazed ceramic tiles, white marble terraces",
    "The Forbidden City was the imperial palace of China from 1420 to 1912, housing 24 successive emperors of the Ming and Qing dynasties. Built over 14 years by one million workers on the orders of the Yongle Emperor, who moved the capital from Nanjing to Beijing. Commoners were strictly forbidden from entering under penalty of execution.",
    "Arranged along a precise north-south meridian axis aligning with the North Star. Constructed entirely without iron nails using interlocking timber dougong brackets that flex to withstand major earthquakes. Roofs are covered in imperial yellow tiles, reserved exclusively for the sovereign.",
    "Inscribed as a UNESCO World Heritage Site in 1987 as the world's largest collection of preserved wooden structures. Today it houses the Palace Museum, displaying over 1.8 million imperial artifacts.",
    "https://images.unsplash.com/photo-1584646098378-0874589d76b1?auto=format&fit=crop&q=80&w=1200",
    ["Forbidden City", "Beijing", "China", "Imperial Palace", "Ming", "Qing", "UNESCO"],
    ["Home of 24 Chinese emperors across the Ming and Qing dynasties for 492 years", "Built with interlocking wooden mortise-and-tenon joints without a single iron nail", "Floor 'golden bricks' were fired for months in clay kilns to ring like chimes when stepped on", "Contains 980 preserved wooden buildings and exactly 8,886 rooms"],
    "Inscribed 1987 (Criteria i, ii, iii, iv)"),

  m("himeji-castle", "Himeji Castle (White Heron Castle)", "姫路城 (Himeji-jō)", "Palace & Fortress", "Himeji, Hyōgo Prefecture", "Japan", "Asia",
    "Sengoku to Edo Period (1333–1609 CE)", "1601–1609 CE", 1609, "Ikeda Terumasa, son-in-law of Shogun Tokugawa Ieyasu",
    "Japanese Feudal Hilltop Castle Architecture", "Main keep height: 46.4 m (152 ft); Altitude: 92 m; Grounds: 107 hectares",
    "Giant cypress timber pillars, cyclopean granite stone walls, fireproof white plaster",
    "Himeji Castle is Japan's finest surviving feudal fortress. Expanded after the Battle of Sekigahara (1600) by Ikeda Terumasa into a massive defensive stronghold. Nicknamed 'White Heron Castle' because its graceful curving white eaves resemble a heron in flight. Survived the Meiji samurai disarmament, WWII bombing, and the 1995 Kobe earthquake completely unscathed.",
    "Features a lethal defensive labyrinth of gates and dead-ends designed to trap attackers in firing zones under 997 shooting embrasures. Foundation walls curve outward to prevent climbing. Supported by two massive 25-meter cypress columns extending from the ground to the top floor.",
    "Japan's first UNESCO World Heritage Site (1993) and a designated National Treasure of Japan.",
    "https://images.unsplash.com/photo-1578637387939-43c525550085?auto=format&fit=crop&q=80&w=1200",
    ["Himeji Castle", "Japan", "Samurai", "White Heron", "UNESCO", "Castle"],
    ["Japan's most pristine feudal castle, surviving WWII bombing and the 1995 Kobe earthquake", "Outer plaster is infused with crushed seashell to provide fire resistance", "Incorporates 997 shooting embrasures engineered for matchlock guns and arrows", "Concentric spiral paths lead attackers away from the central keep into kill zones"],
    "Inscribed 1993 (Criteria i, iv)"),

  m("borobudur-temple", "Borobudur Temple Compounds", "Candi Borobudur", "Sacred Temple / Cathedral", "Central Java", "Indonesia", "Asia",
    "Sailendra Dynasty (c. 750–825 CE)", "c. 778–850 CE", 825, "Master Architect Gunadharma under Sailendra Kings",
    "Javanese Buddhist Stupa Mandala", "Base: 123 × 123 m (403 ft); Height: 35 m (115 ft); Volume: 55,000 m³ stone",
    "Over 2 million volcanic andesite stone blocks carved without mortar",
    "Borobudur is the largest Buddhist monument in the world. Constructed around 800 CE in Java during the Sailendra Dynasty. Following volcanic eruptions from Mount Merapi and political shifts, it was abandoned in the 14th century and swallowed by jungle and volcanic ash. Rediscovered in 1814 by British governor Thomas Stamford Raffles.",
    "Built as a giant three-dimensional stone mandala representing Buddhist cosmology: Kamadhatu, Rupadhatu, and Arupadhatu. Contains 2,672 carved relief panels and 72 perforated bell-shaped stupas, each housing a seated Buddha statue on the circular upper terraces.",
    "UNESCO World Heritage Site (1991). The sacred epicenter for global celebrations of Vesak Day in Southeast Asia.",
    "https://images.unsplash.com/photo-1596402184320-417e7178b2cd?auto=format&fit=crop&q=80&w=1200",
    ["Borobudur", "Indonesia", "Buddhist", "Java", "UNESCO", "Mandala"],
    ["World's largest Buddhist temple monument, built from 2 million volcanic stones", "Constructed entirely without mortar using interlocking tongue-and-groove joints", "Features 2,672 narrative stone relief panels and 504 Buddha statues", "Lay buried under volcanic ash for centuries until its rediscovery in 1814"],
    "Inscribed 1991 (Criteria i, ii, vi)"),

  m("fushimi-inari-taisha", "Fushimi Inari-Taisha Shrine", "伏見稲荷大社", "Sacred Temple / Cathedral", "Fushimi-ku, Kyoto", "Japan", "Asia",
    "Nara to Edo Period (711 CE – Present)", "Founded 711 CE; Main Hall rebuilt 1499 CE", 711, "Hata clan chieftain Hata no Irogu",
    "Traditional Japanese Shinto Shrine Architecture", "Mount Inari trail: 4 km (2.5 miles); Over 10,000 vermilion torii gates",
    "Japanese cypress timber, vermilion and black cinnabar lacquer, carved stone fox statues",
    "Fushimi Inari-Taisha is the head shrine for 32,000 Inari shrines throughout Japan. Founded in 711 CE by the aristocratic Hata clan to honor Inari, the Shinto kami of rice, fertility, and harvests. As Japan modernized, Inari became revered as the patron kami of business prosperity and commerce.",
    "The iconic Senbon Torii features thousands of vivid vermilion torii gates creating tunnels through sacred Mount Inari. The vermilion color repels evil forces in Shinto belief. Each gate is inscribed with the donor company or family and date of dedication. Stone foxes hold symbolic granary keys or sacred jewels in their mouths.",
    "Regularly voted the top cultural destination in Japan by global travelers.",
    "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?auto=format&fit=crop&q=80&w=1200",
    ["Fushimi Inari", "Kyoto", "Japan", "Shinto", "Torii Gates", "Shrine"],
    ["Features over 10,000 vermilion torii gates winding up sacred Mount Inari", "Dedicated to Inari, kami of agriculture, rice harvest, and business fortune", "Fox statues (kitsune) serve as messengers holding keys to harvest granaries", "Every single torii gate is funded and donated by Japanese businesses or families"],
    "Important Cultural Property of Japan"),

  m("kinkaku-ji", "Kinkaku-ji (The Golden Pavilion)", "金閣寺 (Rokuon-ji)", "Sacred Temple / Cathedral", "Kita-ku, Kyoto", "Japan", "Asia",
    "Muromachi Period (1397 CE)", "1397 CE (Rebuilt 1955)", 1397, "Shogun Ashikaga Yoshimitsu",
    "Kitayama Culture Zen Buddhist & Shinden-zukuri Fusion", "Height: 12.5 m (41 ft); 3-story pavilion; Mirror Pond: 6,600 m²",
    "Japanese cypress frame, pure gold leaf gilding, Japanese urushi lacquer, bronze phoenix",
    "Built in 1397 as a retirement villa for third Ashikaga Shogun Yoshimitsu, who converted it to a Rinzai Zen temple upon his death. The pavilion survived the Onin War. In 1950, a novice monk burned the 550-year-old pavilion down. Meticulously reconstructed in 1955 using 20 kg of pure gold leaf.",
    "Synthesizes three architectural styles across three floors: Heian aristocratic palace style on the ground, samurai warrior hall style on the middle, and Chinese Zen temple style on the top. The top two stories are gilded in pure gold leaf. Perched beside the Mirror Pond, casting a shimmering golden reflection.",
    "UNESCO World Heritage Site (1994, Historic Monuments of Ancient Kyoto).",
    "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?auto=format&fit=crop&q=80&w=1200",
    ["Kinkaku-ji", "Golden Pavilion", "Kyoto", "Japan", "Zen", "Ashikaga", "UNESCO"],
    ["Top two floors are completely gilded in pure gold leaf over natural lacquer", "Combines three distinct historical architectural styles on each of its three stories", "The roof is crowned with a solid bronze Chinese phoenix", "Designed specifically to project a pristine unbroken reflection across Mirror Pond"],
    "Inscribed 1994 (Historic Monuments of Ancient Kyoto)")
]

# Additional 50 Asian Monuments will be appended by the generator script
print(f"Base monuments loaded: {len(monuments)}")
